/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/

package org.cgiar.ccafs.marlo.ocs.ws.client;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 */
@WebService(name = "WSMarlo", targetNamespace = "http://logic.control.abw.ciat.cgiar.org/")
@XmlSeeAlso({

})
public interface WSMarlo {


  /**
   * @param agreementId
   * @return
   *         returns java.util.List<org.cgiar.ciat.abw.control.logic.TWsMarloAgreeCountry>
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getMarloAgreeCountry", targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloAgreeCountry")
  @ResponseWrapper(localName = "getMarloAgreeCountryResponse",
    targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloAgreeCountryResponse")
  public List<TWsMarloAgreeCountry>
    getMarloAgreeCountry(@WebParam(name = "agreementId", targetNamespace = "") String agreementId);

  /**
   * @param agreementId
   * @return
   *         returns java.util.List<org.cgiar.ciat.abw.control.logic.TWsMarloAgreeCrp>
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getMarloAgreeCrp", targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloAgreeCrp")
  @ResponseWrapper(localName = "getMarloAgreeCrpResponse", targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloAgreeCrpResponse")
  public List<TWsMarloAgreeCrp>
    getMarloAgreeCrp(@WebParam(name = "agreementId", targetNamespace = "") String agreementId);

  /**
   * @param agreementId
   * @return
   *         returns java.util.List<org.cgiar.ciat.abw.control.logic.FileTransfer>
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getMarloAgreeDocument", targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloAgreeDocument")
  @ResponseWrapper(localName = "getMarloAgreeDocumentResponse",
    targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloAgreeDocumentResponse")
  public List<FileTransfer>
    getMarloAgreeDocument(@WebParam(name = "agreementId", targetNamespace = "") String agreementId);

  /**
   * @param agreementId
   * @return
   *         returns java.util.List<org.cgiar.ciat.abw.control.logic.TWsMarloAgree>
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getMarloAgreements", targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloAgreements")
  @ResponseWrapper(localName = "getMarloAgreementsResponse",
    targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloAgreementsResponse")
  public List<TWsMarloAgree>
    getMarloAgreements(@WebParam(name = "agreementId", targetNamespace = "") String agreementId);

  /**
   * @param agreementId
   * @return
   *         returns java.util.List<org.cgiar.ciat.abw.control.logic.TWsMarloPla>
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getMarloPla", targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloPla")
  @ResponseWrapper(localName = "getMarloPlaResponse", targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloPlaResponse")
  public List<TWsMarloPla> getMarloPla(@WebParam(name = "agreementId", targetNamespace = "") String agreementId);

  /**
   * @param plaId
   * @return
   *         returns java.util.List<org.cgiar.ciat.abw.control.logic.TWsMarloPlaCountry>
   */
  @WebMethod
  @WebResult(targetNamespace = "")
  @RequestWrapper(localName = "getMarloPlaCountry", targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloPlaCountry")
  @ResponseWrapper(localName = "getMarloPlaCountryResponse",
    targetNamespace = "http://logic.control.abw.ciat.cgiar.org/",
    className = "org.cgiar.ciat.abw.control.logic.GetMarloPlaCountryResponse")
  public List<TWsMarloPlaCountry> getMarloPlaCountry(@WebParam(name = "plaId", targetNamespace = "") String plaId);

}
