package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 3, 2017 1:26:41 PM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * CrpIndicators generated by hbm2java
 */
public class CrpIndicator extends MarloSoftDeleteableEntity implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -6140435298426995366L;
  @Expose
  private CrpIndicatorType crpIndicatorType;
  @Expose
  private String serial;


  @Expose
  private String name;
  @Expose
  private String description;
  @Expose
  private Date dateAdded;
  private Set<CrpIndicatorReport> crpIndicatorReports = new HashSet<CrpIndicatorReport>(0);

  public CrpIndicator() {
  }

  public Set<CrpIndicatorReport> getCrpIndicatorReports() {
    return crpIndicatorReports;
  }


  public CrpIndicatorType getCrpIndicatorType() {
    return crpIndicatorType;
  }


  public Date getDateAdded() {
    return dateAdded;
  }


  public String getDescription() {
    return description;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  @Override
  public String getModificationJustification() {

    return "";
  }


  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }


  public String getName() {
    return name;
  }


  public String getSerial() {
    return serial;
  }


  public void setCrpIndicatorReports(Set<CrpIndicatorReport> crpIndicatorReportses) {
    this.crpIndicatorReports = crpIndicatorReportses;
  }


  public void setCrpIndicatorType(CrpIndicatorType crpIndicatorType) {
    this.crpIndicatorType = crpIndicatorType;
  }


  public void setDateAdded(Date dateAdded) {
    this.dateAdded = dateAdded;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public void setModifiedBy(User modifiedBy) {

  }


  public void setName(String name) {
    this.name = name;
  }


  public void setSerial(String serial) {
    this.serial = serial;
  }

  @Override
  public String toString() {
    return "CrpIndicator [id=" + this.getId() + ", crpIndicatorType=" + crpIndicatorType + ", serial=" + serial
      + ", name=" + name + ", description=" + description + "]";
  }


}

