/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * CrpSitesLeader generated by hbm2java
 */
public class CrpSitesLeader extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 1702272624319778464L;

  @Expose
  private CrpsSiteIntegration crpsSiteIntegration;

  @Expose
  private User user;

  @Expose
  private boolean regional;

  public CrpSitesLeader() {
  }

  public CrpSitesLeader(CrpsSiteIntegration crpsSitesIntegration, User user) {
    this.crpsSiteIntegration = crpsSitesIntegration;
    this.user = user;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    CrpSitesLeader other = (CrpSitesLeader) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public CrpsSiteIntegration getCrpsSiteIntegration() {
    return this.crpsSiteIntegration;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public User getUser() {
    return this.user;
  }

  public boolean isRegional() {
    return regional;
  }

  public void setCrpsSiteIntegration(CrpsSiteIntegration crpsSitesIntegration) {
    this.crpsSiteIntegration = crpsSitesIntegration;
  }

  public void setRegional(boolean regional) {
    this.regional = regional;
  }

  public void setUser(User user) {
    this.user = user;
  }

  @Override
  public String toString() {
    return "CrpSitesLeader [id=" + this.getId() + ", crpsSiteIntegration=" + crpsSiteIntegration + ", user=" + user
      + "]";
  }
}

