package org.cgiar.ccafs.marlo.data.model;
// Generated Apr 30, 2018 10:52:36 AM by Hibernate Tools 3.4.0.CR1

import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.Map;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.gson.annotations.Expose;

/**
 * ProjectExpectedStudyInfo generated by hbm2java
 */
public class FeedbackQAComment extends MarloBaseEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -7806050142645120199L;

  @Expose
  private Phase phase;
  @Expose
  private FeedbackQACommentableFields field;
  @Expose
  private long screen;
  @Expose
  private long parentId;
  @Expose
  private String comment;
  @Expose
  private String fieldValue;
  @Expose
  private Boolean status;
  @Expose
  private FeedbackQAReply reply;
  @Expose
  private User user;
  @Expose
  private Date commentDate;
  @Expose
  private Date approvalDate;

  public FeedbackQAComment() {
  }

  public FeedbackQAComment(Phase phase, FeedbackQACommentableFields field, long screen, long parentId, String comment,
    Boolean status, FeedbackQAReply reply, User user, Date commentDate) {
    super();
    this.phase = phase;
    this.field = field;
    this.screen = screen;
    this.parentId = parentId;
    this.comment = comment;
    this.status = status;
    this.reply = reply;
    this.user = user;
    this.commentDate = commentDate;
  }

  public Map<String, Object> convertToMap() {
    ObjectMapper oMapper = new ObjectMapper();
    Map<String, Object> map = oMapper.convertValue(this, Map.class);

    return map;
  }

  public Date getApprovalDate() {
    return approvalDate;
  }

  public String getComment() {
    return comment;
  }

  public Date getCommentDate() {
    return commentDate;
  }

  public FeedbackQACommentableFields getField() {
    return field;
  }

  public String getFieldValue() {
    return fieldValue;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public String getModificationJustification() {
    return "";
  }

  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }

  public long getParentId() {
    return parentId;
  }

  public Phase getPhase() {
    return phase;
  }

  public FeedbackQAReply getReply() {
    return reply;
  }

  public long getScreen() {
    return screen;
  }

  public Boolean getStatus() {
    return status;
  }

  public User getUser() {
    return user;
  }

  @Override
  public boolean isActive() {
    return true;
  }

  public void setApprovalDate(Date approvalDate) {
    this.approvalDate = approvalDate;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public void setCommentDate(Date commentDate) {
    this.commentDate = commentDate;
  }

  public void setField(FeedbackQACommentableFields field) {
    this.field = field;
  }

  public void setFieldValue(String fieldValue) {
    this.fieldValue = fieldValue;
  }

  @Override
  public void setModifiedBy(User modifiedBy) {
    // TODO Auto-generated method stub
  }

  public void setParentId(long parentId) {
    this.parentId = parentId;
  }

  public void setPhase(Phase phase) {
    this.phase = phase;
  }

  public void setReply(FeedbackQAReply reply) {
    this.reply = reply;
  }

  public void setScreen(long screen) {
    this.screen = screen;
  }

  public void setStatus(Boolean status) {
    this.status = status;
  }

  public void setUser(User user) {
    this.user = user;
  }
}

