/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated Jul 6, 2016 9:31:00 AM by Hibernate Tools 4.3.1.Final

/**
 * SectionStatus generated by hbm2java
 */
public class Nexus extends MarloBaseEntity implements java.io.Serializable {

  private static final long serialVersionUID = -7527583315860965374L;

  private Long id;

  private String name;

  public Nexus() {
  }

  @Override
  public Long getId() {
    return id;
  }

  public String getName() {
    return name;
  }

  @Override
  public void setId(Long id) {
    this.id = id;
  }

  public void setName(String name) {
    this.name = name;
  }


}

