package org.cgiar.ccafs.marlo.data.model;
// Generated Aug 22, 2016 10:31:13 AM by Hibernate Tools 4.3.1.Final

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ProjectMilestone generated by hbm2java
 */
public class PolicyMilestone extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6474276163660867919L;

	@Expose
	private CrpMilestone crpMilestone;
	@Expose
	private ProjectPolicy policy;
	@Expose
	private Phase phase;

	public ProjectPolicy getPolicy() {
		return policy;
	}

	public void setPolicy(ProjectPolicy policy) {
		this.policy = policy;
	}

	public PolicyMilestone() {
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}

		PolicyMilestone other = (PolicyMilestone) obj;
		if (this.getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!this.getId().equals(other.getId())) {
			return false;
		}
		return true;
	}

	public CrpMilestone getCrpMilestone() {
		return crpMilestone;
	}

	@Override
	public String getLogDeatil() {
		StringBuilder sb = new StringBuilder();

		sb.append("Id : ").append(this.getId());

		return sb.toString();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
		return result;
	}

	public void setCrpMilestone(CrpMilestone crpMilestone) {
		this.crpMilestone = crpMilestone;
	}

	@Override
	public String toString() {
		return "ProjectMilestone [id=" + this.getId() + ", crpMilestone=" + crpMilestone + ", policy=" + policy + "]";
	}

	public Phase getPhase() {
		return phase;
	}

	public void setPhase(Phase phase) {
		this.phase = phase;
	}
	
}
