package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 1, 2018 10:19:51 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * PowbCollaborationRegion generated by hbm2java
 */
public class PowbCollaborationRegion extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = 3393200972436392760L;
  @Expose
  private LiaisonInstitution liaisonInstitution;
  private PowbSynthesis powbSynthesis;
  @Expose
  private String effostornCountry;

  public PowbCollaborationRegion() {

  }

  public String getEffostornCountry() {
    return effostornCountry;
  }

  public LiaisonInstitution getLiaisonInstitution() {
    return liaisonInstitution;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }

  public PowbSynthesis getPowbSynthesis() {
    return powbSynthesis;
  }

  public void setEffostornCountry(String effostornCountry) {
    this.effostornCountry = effostornCountry;
  }

  public void setLiaisonInstitution(LiaisonInstitution liaisonInstitution) {
    this.liaisonInstitution = liaisonInstitution;
  }

  public void setPowbSynthesis(PowbSynthesis powbSynthesis) {
    this.powbSynthesis = powbSynthesis;
  }


}

