package org.cgiar.ccafs.marlo.data.model;
// Generated Feb 9, 2018 11:37:50 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * PowbMonitoringEvaluationLearning generated by hbm2java
 */
public class PowbMonitoringEvaluationLearning extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 6681061181269663002L;

  private PowbSynthesis powbSynthesis;

  @Expose
  private String highlight;

  private Set<PowbMonitoringEvaluationLearningExercise> powbMonitoringEvaluationLearningExercises =
    new HashSet<PowbMonitoringEvaluationLearningExercise>(0);

  private List<PowbMonitoringEvaluationLearningExercise> exercises;


  public PowbMonitoringEvaluationLearning() {
  }


  public List<PowbMonitoringEvaluationLearningExercise> getExercises() {
    return exercises;
  }


  public String getHighlight() {
    return highlight;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public Set<PowbMonitoringEvaluationLearningExercise> getPowbMonitoringEvaluationLearningExercises() {
    return powbMonitoringEvaluationLearningExercises;
  }

  public PowbSynthesis getPowbSynthesis() {
    return powbSynthesis;
  }

  public void setExercises(List<PowbMonitoringEvaluationLearningExercise> exercises) {
    this.exercises = exercises;
  }

  public void setHighlight(String highlight) {
    this.highlight = highlight;
  }

  public void setPowbMonitoringEvaluationLearningExercises(
    Set<PowbMonitoringEvaluationLearningExercise> powbMonitoringEvaluationLearningExercises) {
    this.powbMonitoringEvaluationLearningExercises = powbMonitoringEvaluationLearningExercises;
  }


  public void setPowbSynthesis(PowbSynthesis powbSynthesis) {
    this.powbSynthesis = powbSynthesis;
  }


}

