package org.cgiar.ccafs.marlo.data.model;
// Generated Jul 29, 2016 8:50:03 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;
import org.apache.commons.lang3.builder.ToStringBuilder;

/**
 * ProjectPartnerContribution generated by hbm2java
 */
public class ProjectPartnerContribution implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -4423203403135427412L;

  @Expose
  private Long id;

  @Expose
  private ProjectPartner projectPartner;
  @Expose
  private ProjectPartner projectPartnerContributor;
  @Expose
  private User createdBy;
  @Expose
  private User modifiedBy;
  @Expose
  private boolean active;
  @Expose
  private Date activeSince;
  @Expose
  private String modificationJustification;

  public ProjectPartnerContribution() {
  }

  public ProjectPartnerContribution(ProjectPartner projectPartnersByProjectPartnerId,
    ProjectPartner projectPartnersByProjectPartnerContributorId, User usersByCreatedBy, User usersByModifiedBy,
    boolean isActive, Date activeSince, String modificationJustification) {
    this.projectPartner = projectPartnersByProjectPartnerId;
    this.projectPartnerContributor = projectPartnersByProjectPartnerContributorId;
    this.createdBy = usersByCreatedBy;
    this.modifiedBy = usersByModifiedBy;
    this.active = isActive;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ProjectPartnerContribution other = (ProjectPartnerContribution) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }

  public Date getActiveSince() {
    return this.activeSince;
  }

  public User getCreatedBy() {
    return this.createdBy;
  }

  @Override
  public Long getId() {
    return this.id;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }

  public String getModificationJustification() {
    return this.modificationJustification;
  }

  @Override
  public User getModifiedBy() {
    return this.modifiedBy;
  }

  public ProjectPartner getProjectPartner() {
    return this.projectPartner;
  }

  public ProjectPartner getProjectPartnerContributor() {
    return this.projectPartnerContributor;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }

  @Override
  public boolean isActive() {
    return this.active;
  }

  public void setActive(boolean isActive) {
    this.active = isActive;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User usersByCreatedBy) {
    this.createdBy = usersByCreatedBy;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User usersByModifiedBy) {
    this.modifiedBy = usersByModifiedBy;
  }

  public void setProjectPartner(ProjectPartner projectPartnersByProjectPartnerId) {
    this.projectPartner = projectPartnersByProjectPartnerId;
  }

  public void setProjectPartnerContributor(ProjectPartner projectPartnersByProjectPartnerContributorId) {
    this.projectPartnerContributor = projectPartnersByProjectPartnerContributorId;
  }

  @Override
  public String toString() {
      return id.toString();
  }


}

