package org.cgiar.ccafs.marlo.data.model;
// Generated Sep 5, 2016 8:28:28 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ProjectCrpContribution generated by hbm2java
 */
public class ProjectCrpContribution extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 3312177201036421940L;
  @Expose
  private CrpPandr crp;
  @Expose
  private Project project;
  @Expose
  private String collaborationNature;

  @Expose
  private String explainAchieved;

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ProjectCrpContribution other = (ProjectCrpContribution) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public String getCollaborationNature() {
    return collaborationNature;
  }

  public CrpPandr getCrp() {
    return crp;
  }

  public String getExplainAchieved() {
    return explainAchieved;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public Project getProject() {
    return project;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }

  public void setCollaborationNature(String collaborationNature) {
    this.collaborationNature = collaborationNature;
  }

  public void setCrp(CrpPandr crp) {
    this.crp = crp;
  }

  public void setExplainAchieved(String explainAchieved) {
    this.explainAchieved = explainAchieved;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  @Override
  public String toString() {
    return "ProjectCrpContribution [id=" + this.getId() + ", crp=" + crp + ", project=" + project + "]";
  }


}

