package org.cgiar.ccafs.marlo.data.model;
// Generated Aug 22, 2016 10:31:13 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ProjectMilestone generated by hbm2java
 */
public class ProjectMilestone extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -6474276163660867919L;

  @Expose
  private CrpMilestone crpMilestone;
  @Expose
  private ProjectOutcome projectOutcome;
  @Expose
  private Double expectedValue;
  @Expose
  private Double progressValue;
  @Expose
  private Double settedValue;
  @Expose
  private SrfTargetUnit expectedUnit;

  @Expose
  private Long achievedValue;
  @Expose
  private String narrativeTarget;
  @Expose
  private String narrativeAchieved;
  @Expose
  private String narrativeProgress;


  @Expose
  private int year;

  public ProjectMilestone() {
  }


  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }

    ProjectMilestone other = (ProjectMilestone) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }


  public Long getAchievedValue() {
    return achievedValue;
  }


  public CrpMilestone getCrpMilestone() {
    return crpMilestone;
  }


  public SrfTargetUnit getExpectedUnit() {
    return expectedUnit;
  }


  public Double getExpectedValue() {
    return expectedValue;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }

  public String getNarrativeAchieved() {
    return narrativeAchieved;
  }


  public String getNarrativeProgress() {
    return narrativeProgress;
  }

  public String getNarrativeTarget() {
    return narrativeTarget;
  }


  public Double getProgressValue() {
    return progressValue;
  }

  public ProjectOutcome getProjectOutcome() {
    return projectOutcome;
  }


  public Double getSettedValue() {
    return settedValue;
  }


  public int getYear() {
    return year;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }


  public void setAchievedValue(Long achievedValue) {
    this.achievedValue = achievedValue;
  }


  public void setCrpMilestone(CrpMilestone crpMilestone) {
    this.crpMilestone = crpMilestone;
  }


  public void setExpectedUnit(SrfTargetUnit expectedUnit) {
    this.expectedUnit = expectedUnit;
  }


  public void setExpectedValue(Double expectedValue) {
    this.expectedValue = expectedValue;
  }


  public void setNarrativeAchieved(String narrativeAchieved) {
    this.narrativeAchieved = narrativeAchieved;
  }

  public void setNarrativeProgress(String narrativeProgress) {
    this.narrativeProgress = narrativeProgress;
  }

  public void setNarrativeTarget(String narrativeTarget) {
    this.narrativeTarget = narrativeTarget;
  }

  public void setProgressValue(Double progressValue) {
    this.progressValue = progressValue;
  }

  public void setProjectOutcome(ProjectOutcome projectOutcome) {
    this.projectOutcome = projectOutcome;
  }


  public void setSettedValue(Double settedValue) {
    this.settedValue = settedValue;
  }


  public void setYear(int year) {
    this.year = year;
  }

  @Override
  public String toString() {
    return "ProjectMilestone [id=" + this.getId() + ", crpMilestone=" + crpMilestone + ", projectOutcome="
      + projectOutcome + ", expectedValue=" + expectedValue + ", expectedUnit=" + expectedUnit + ", achievedValue="
      + achievedValue + ", narrativeTarget=" + narrativeTarget + ", year=" + year + "]";
  }

}

