package org.cgiar.ccafs.marlo.data.model;
// Generated Jun 8, 2018 3:52:45 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisExternalPartnership generated by hbm2java
 */
public class ReportSynthesisExternalPartnership extends MarloAuditableEntity
  implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -2160211894576488137L;


  private ReportSynthesis reportSynthesis;


  @Expose
  private String highlights;


  private Set<ReportSynthesisExternalPartnershipProject> reportSynthesisExternalPartnershipProjects =
    new HashSet<ReportSynthesisExternalPartnershipProject>(0);

  private List<ReportSynthesisExternalPartnershipProject> partnerships;


  private String partnershipsValue;

  private List<ProjectPartnerPartnership> partnerPartnerships;


  public ReportSynthesisExternalPartnership() {
  }


  public String getHighlights() {
    return highlights;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public List<ProjectPartnerPartnership> getPartnerPartnerships() {
    return partnerPartnerships;
  }


  /**
   * @return an array of integers.
   */
  public long[] getPartnershipIds() {

    List<ProjectPartnerPartnership> partnerPartnershipsList = this.getPartnerPartnerships();
    if (partnerPartnershipsList != null) {
      long[] ids = new long[partnerPartnershipsList.size()];
      for (int i = 0; i < ids.length; i++) {
        ids[i] = partnerPartnershipsList.get(i).getId();
      }
      return ids;
    }
    return null;
  }

  public List<ReportSynthesisExternalPartnershipProject> getPartnerships() {
    return partnerships;
  }


  public String getPartnershipsValue() {
    return partnershipsValue;
  }


  public ReportSynthesis getReportSynthesis() {
    return reportSynthesis;
  }


  public Set<ReportSynthesisExternalPartnershipProject> getReportSynthesisExternalPartnershipProjects() {
    return reportSynthesisExternalPartnershipProjects;
  }

  public void setHighlights(String highlights) {
    this.highlights = highlights;
  }

  public void setPartnerPartnerships(List<ProjectPartnerPartnership> partnerPartnerships) {
    this.partnerPartnerships = partnerPartnerships;
  }

  public void setPartnerships(List<ReportSynthesisExternalPartnershipProject> partnerships) {
    this.partnerships = partnerships;
  }

  public void setPartnershipsValue(String partnershipsValue) {
    this.partnershipsValue = partnershipsValue;
  }

  public void setReportSynthesis(ReportSynthesis reportSynthesis) {
    this.reportSynthesis = reportSynthesis;
  }


  public void setReportSynthesisExternalPartnershipProjects(
    Set<ReportSynthesisExternalPartnershipProject> reportSynthesisExternalPartnershipProjects) {
    this.reportSynthesisExternalPartnershipProjects = reportSynthesisExternalPartnershipProjects;
  }

}

