package org.cgiar.ccafs.marlo.data.model;
// Generated Feb 27, 2019 2:52:09 PM by Hibernate Tools 5.3.6.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisSrfProgressTargets generated by hbm2java
 */
public class ReportSynthesisSrfProgressTargetCases extends MarloAuditableEntity
  implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = 1867695696627239380L;

  @Expose
  private ReportSynthesisSrfProgress reportSynthesisSrfProgress;

  @Expose
  private SrfSloIndicatorTarget srfSloIndicatorTarget;


  @Expose
  private String briefSummary;


  @Expose
  private String additionalContribution;


  @Expose
  private Boolean isContributing;

  @Expose
  private Boolean isQAIncluded;

  private LiaisonInstitution liaisonInstitution;

  private List<ProgressTargetCaseGeographicCountry> countries;

  private Set<SrfSloIndicatorTarget> srfSloTargets = new HashSet<SrfSloIndicatorTarget>(0);
  private List<SrfSloIndicatorTarget> sloTargets = new ArrayList<>();
  private Set<ProgressTargetCaseGeographicScope> progressTargetCaseGeographicScopes =
    new HashSet<ProgressTargetCaseGeographicScope>(0);
  private List<ProgressTargetCaseGeographicScope> geographicScopes;

  private Set<ProgressTargetCaseGeographicRegion> progressTargetCaseGeographicRegions =
    new HashSet<ProgressTargetCaseGeographicRegion>(0);
  private List<ProgressTargetCaseGeographicRegion> geographicRegions;
  private Set<ProgressTargetCaseGeographicCountry> progressTargetCaseGeographicCountries =
    new HashSet<ProgressTargetCaseGeographicCountry>(0);
  private List<ProgressTargetCaseGeographicCountry> geographicCountries;
  private List<String> countriesIds = new ArrayList<>();
  private String countriesIdsText;

  public ReportSynthesisSrfProgressTargetCases() {
  }

  public String getAdditionalContribution() {
    return additionalContribution;
  }

  public String getBriefSummary() {
    return briefSummary;
  }


  public List<ProgressTargetCaseGeographicCountry> getCountries() {
    return countries;
  }


  public List<String> getCountriesIds() {
    return countriesIds;
  }


  public String getCountriesIdsText() {
    return countriesIdsText;
  }


  public List<ProgressTargetCaseGeographicCountry> getGeographicCountries() {
    return geographicCountries;
  }


  public List<ProgressTargetCaseGeographicRegion> getGeographicRegions() {
    return geographicRegions;
  }


  public List<ProgressTargetCaseGeographicScope> getGeographicScopes() {
    return geographicScopes;
  }


  public Boolean getIsContributing() {
    return isContributing;
  }


  public Boolean getIsQAIncluded() {
    return isQAIncluded;
  }


  public LiaisonInstitution getLiaisonInstitution() {
    return liaisonInstitution;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public Set<ProgressTargetCaseGeographicCountry> getProgressTargetCaseGeographicCountries() {
    return progressTargetCaseGeographicCountries;
  }

  public Set<ProgressTargetCaseGeographicRegion> getProgressTargetCaseGeographicRegions() {
    return progressTargetCaseGeographicRegions;
  }


  public Set<ProgressTargetCaseGeographicScope> getProgressTargetCaseGeographicScopes() {
    return progressTargetCaseGeographicScopes;
  }


  public ReportSynthesisSrfProgress getReportSynthesisSrfProgress() {
    return reportSynthesisSrfProgress;
  }

  public List<SrfSloIndicatorTarget> getSloTargets() {
    return sloTargets;
  }

  public SrfSloIndicatorTarget getSrfSloIndicatorTarget() {
    return srfSloIndicatorTarget;
  }


  public Set<SrfSloIndicatorTarget> getSrfSloTargets() {
    return srfSloTargets;
  }

  public void setAdditionalContribution(String additionalContribution) {
    this.additionalContribution = additionalContribution;
  }

  public void setBriefSummary(String briefSummary) {
    this.briefSummary = briefSummary;
  }

  public void setCountries(List<ProgressTargetCaseGeographicCountry> countries) {
    this.countries = countries;
  }

  public void setCountriesIds(List<String> countriesIds) {
    this.countriesIds = countriesIds;
  }

  public void setCountriesIdsText(String countriesIdsText) {
    this.countriesIdsText = countriesIdsText;
  }

  public void setGeographicCountries(List<ProgressTargetCaseGeographicCountry> geographicCountries) {
    this.geographicCountries = geographicCountries;
  }

  public void setGeographicRegions(List<ProgressTargetCaseGeographicRegion> geographicRegions) {
    this.geographicRegions = geographicRegions;
  }

  public void setGeographicScopes(List<ProgressTargetCaseGeographicScope> geographicScopes) {
    this.geographicScopes = geographicScopes;
  }


  public void setIsContributing(Boolean isContributing) {
    this.isContributing = isContributing;
  }

  public void setIsQAIncluded(Boolean isQAIncluded) {
    this.isQAIncluded = isQAIncluded;
  }

  public void setLiaisonInstitution(LiaisonInstitution liaisonInstitution) {
    this.liaisonInstitution = liaisonInstitution;
  }

  public void setProgressTargetCaseGeographicCountries(
    Set<ProgressTargetCaseGeographicCountry> progressTargetCaseGeographicCountries) {
    this.progressTargetCaseGeographicCountries = progressTargetCaseGeographicCountries;
  }

  public void setProgressTargetCaseGeographicRegions(
    Set<ProgressTargetCaseGeographicRegion> progressTargetCaseGeographicRegions) {
    this.progressTargetCaseGeographicRegions = progressTargetCaseGeographicRegions;
  }

  public void
    setProgressTargetCaseGeographicScopes(Set<ProgressTargetCaseGeographicScope> progressTargetCaseGeographicScopes) {
    this.progressTargetCaseGeographicScopes = progressTargetCaseGeographicScopes;
  }

  public void setReportSynthesisSrfProgress(ReportSynthesisSrfProgress reportSynthesisSrfProgress) {
    this.reportSynthesisSrfProgress = reportSynthesisSrfProgress;
  }

  public void setSloTargets(List<SrfSloIndicatorTarget> sloTargets) {
    this.sloTargets = sloTargets;
  }

  public void setSrfSloIndicatorTarget(SrfSloIndicatorTarget srfSloIndicatorTarget) {
    this.srfSloIndicatorTarget = srfSloIndicatorTarget;
  }

  public void setSrfSloTargets(Set<SrfSloIndicatorTarget> srfSloTargets) {
    this.srfSloTargets = srfSloTargets;
  }

}

