/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * SrfSloIndicator generated by hbm2java
 */
public class SrfSloIndicator extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = 3683018263832155505L;

  @Expose
  private SrfSlo srfSlo;

  @Expose
  private String title;

  @Expose
  private String description;


  private Set<SrfSloIndicatorTarget> srfSloIndicatorTargets = new HashSet<SrfSloIndicatorTarget>(0);


  public SrfSloIndicator() {
  }

  public String getDescription() {
    return this.description;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public SrfSlo getSrfSlo() {
    return this.srfSlo;
  }

  public Set<SrfSloIndicatorTarget> getSrfSloIndicatorTargets() {
    return this.srfSloIndicatorTargets;
  }


  public String getTitle() {
    return this.title;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setSrfSlo(SrfSlo srfSlos) {
    this.srfSlo = srfSlos;
  }

  public void setSrfSloIndicatorTargets(Set<SrfSloIndicatorTarget> srfSloIndicatorTargets) {
    this.srfSloIndicatorTargets = srfSloIndicatorTargets;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  @Override
  public String toString() {
    return "SrfSloIndicator [id=" + this.getId() + ", srfSlo=" + srfSlo + ", title=" + title + ", description="
      + description + "]";
  }
}

