/*
Navicat MySQL Data Transfer

Source Server         : local
Source Server Version : 50626
Source Host           : localhost:3306
Source Database       : ccafs_marlo

Target Server Type    : MYSQL
Target Server Version : 50626
File Encoding         : 65001

Date: 2016-06-10 10:04:15
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `loc_elements`
-- ----------------------------
DROP TABLE IF EXISTS `loc_elements`;
CREATE TABLE `loc_elements` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `code` varchar(45) DEFAULT NULL,
  `parent_id` bigint(20) DEFAULT NULL,
  `element_type_id` bigint(20) DEFAULT NULL,
  `geoposition_id` bigint(20) DEFAULT NULL,
  `is_site_integration` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_loc_element_loc_element_type_id_idx` (`element_type_id`) USING BTREE,
  KEY `FK_loc_elements_loc_geopositions_idx` (`geoposition_id`) USING BTREE,
  CONSTRAINT `loc_elements_ibfk_1` FOREIGN KEY (`geoposition_id`) REFERENCES `loc_geopositions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `loc_elements_ibfk_2` FOREIGN KEY (`element_type_id`) REFERENCES `loc_element_types` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=700 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of loc_elements
-- ----------------------------
INSERT INTO `loc_elements` VALUES ('1', 'East Africa', 'EA', null, '1', null, '0');
INSERT INTO `loc_elements` VALUES ('2', 'West Africa', 'WA', null, '1', null, '0');
INSERT INTO `loc_elements` VALUES ('3', 'South Asia', 'SA', null, '1', null, '0');
INSERT INTO `loc_elements` VALUES ('4', 'Latin America', 'LAM', null, '1', null, '0');
INSERT INTO `loc_elements` VALUES ('5', 'South East Asia', 'SEA', null, '1', null, '0');
INSERT INTO `loc_elements` VALUES ('6', 'Other', null, null, '1', null, '0');
INSERT INTO `loc_elements` VALUES ('7', 'Andorra', 'ad', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('8', 'United Arab Emirates', 'ae', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('9', 'Afghanistan', 'af', '3', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('10', 'Antigua and Barbuda', 'ag', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('11', 'Anguilla', 'ai', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('12', 'Albania', 'al', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('13', 'Armenia', 'am', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('14', 'Netherlands Antilles', 'an', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('15', 'Angola', 'ao', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('16', 'Antarctica', 'aq', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('17', 'Argentina', 'ar', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('18', 'American Samoa', 'as', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('19', 'Austria', 'at', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('20', 'Australia', 'au', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('21', 'Aruba', 'aw', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('22', 'Azerbaijan', 'az', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('23', 'Bosnia and Herzegovina', 'ba', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('24', 'Barbados', 'bb', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('25', 'Bangladesh', 'bd', '3', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('26', 'Belgium', 'be', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('27', 'Burkina Faso', 'bf', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('28', 'Bulgaria', 'bg', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('29', 'Bahrain', 'bh', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('30', 'Burundi', 'bi', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('31', 'Benin', 'bj', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('33', 'Bermuda', 'bm', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('35', 'Bolivia', 'bo', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('36', 'Brazil', 'br', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('37', 'Bahamas', 'bs', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('38', 'Bhutan', 'bt', '3', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('39', 'Botswana', 'bw', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('40', 'Belarus', 'by', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('41', 'Belize', 'bz', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('42', 'Canada', 'ca', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('43', 'Cocos (Keeling) Islands', 'cc', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('44', 'Democratic Republic of the Congo', 'cd', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('45', 'Central African Republic', 'cf', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('47', 'Switzerland', 'ch', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('48', 'Ivory Coast', 'ci', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('49', 'Cook Islands', 'ck', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('50', 'Chile', 'cl', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('51', 'Cameroon', 'cm', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('52', 'China', 'cn', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('53', 'Colombia', 'co', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('54', 'Costa Rica', 'cr', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('55', 'Cuba', 'cu', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('56', 'Cape Verde', 'cv', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('57', 'Christmas Island', 'cx', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('58', 'Cyprus', 'cy', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('59', 'Czech Republic', 'cz', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('60', 'Germany', 'de', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('61', 'Djibouti', 'dj', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('62', 'Denmark', 'dk', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('63', 'Dominica', 'dm', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('64', 'Dominican Republic', 'do', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('65', 'Algeria', 'dz', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('66', 'Ecuador', 'ec', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('67', 'Estonia', 'ee', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('68', 'Egypt', 'eg', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('69', 'Western Sahara', 'eh', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('70', 'Eritrea', 'er', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('71', 'Spain', 'es', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('72', 'Ethiopia', 'et', '1', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('73', 'Finland', 'fi', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('74', 'Fiji', 'fj', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('77', 'Faroe Islands', 'fo', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('78', 'France', 'fr', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('79', 'Gabon', 'ga', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('80', 'United Kingdom', 'gb', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('81', 'Grenada', 'gd', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('82', 'Georgia', 'ge', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('83', 'Ghana', 'gh', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('84', 'Gibraltar', 'gi', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('85', 'Greenland', 'gl', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('86', 'Gambia', 'gm', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('87', 'Guinea', 'gn', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('88', 'Equatorial Guinea', 'gq', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('89', 'Greece', 'gr', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('90', 'Guatemala', 'gt', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('91', 'Guam', 'gu', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('92', 'Guinea-Bissau', 'gw', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('93', 'Guyana', 'gy', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('95', 'Honduras', 'hn', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('96', 'Croatia', 'hr', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('97', 'Haiti', 'ht', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('98', 'Hungary', 'hu', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('99', 'Indonesia', 'id', '5', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('100', 'Ireland', 'ie', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('101', 'Israel', 'il', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('102', 'Isle of Man', 'im', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('103', 'India', 'in', '3', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('104', 'British Indian Ocean Territory', 'io', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('105', 'Iraq', 'iq', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('106', 'Iran', 'ir', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('107', 'Iceland', 'is', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('108', 'Italy', 'it', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('109', 'Jersey', 'je', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('110', 'Jamaica', 'jm', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('111', 'Jordan', 'jo', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('112', 'Japan', 'jp', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('113', 'Kenya', 'ke', '1', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('114', 'Kyrgyzstan', 'kg', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('115', 'Cambodia', 'kh', '5', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('116', 'Kiribati', 'ki', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('117', 'Comoros', 'km', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('118', 'Saint Kitts and Nevis', 'kn', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('121', 'Kuwait', 'kw', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('122', 'Cayman Islands', 'ky', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('123', 'Kazakhstan', 'kz', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('124', 'Laos', 'la', '5', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('125', 'Lebanon', 'lb', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('126', 'Saint Lucia', 'lc', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('127', 'Liechtenstein', 'li', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('128', 'Sri Lanka', 'lk', '3', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('129', 'Liberia', 'lr', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('130', 'Lesotho', 'ls', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('131', 'Lithuania', 'lt', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('132', 'Luxembourg', 'lu', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('133', 'Libya', 'ly', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('134', 'Morocco', 'ma', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('135', 'Monaco', 'mc', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('136', 'Moldova', 'md', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('137', 'Montenegro', 'me', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('139', 'Madagascar', 'mg', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('140', 'Marshall Islands', 'mh', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('142', 'Mali', 'ml', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('143', 'Burma', 'mm', '5', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('144', 'Mongolia', 'mn', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('146', 'Northern Mariana Islands', 'mp', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('147', 'Mauritania', 'mr', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('148', 'Montserrat', 'ms', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('149', 'Malta', 'mt', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('150', 'Mauritius', 'mu', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('151', 'Maldives', 'mv', '3', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('152', 'Malawi', 'mw', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('153', 'Mexico', 'mx', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('154', 'Malaysia', 'my', '5', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('155', 'Mozambique', 'mz', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('156', 'Namibia', 'na', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('157', 'New Caledonia', 'nc', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('158', 'Niger', 'ne', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('159', 'Nigeria', 'ng', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('160', 'Nicaragua', 'ni', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('161', 'Netherlands', 'nl', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('162', 'Norway', 'no', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('163', 'Nepal', 'np', '3', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('164', 'Nauru', 'nr', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('165', 'Niue', 'nu', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('166', 'New Zealand', 'nz', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('167', 'Oman', 'om', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('168', 'Panama', 'pa', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('169', 'Peru', 'pe', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('170', 'French Polynesia', 'pf', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('171', 'Papua New Guinea', 'pg', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('172', 'Philippines', 'ph', '5', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('173', 'Pakistan', 'pk', '3', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('174', 'Poland', 'pl', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('175', 'Saint Pierre and Miquelon', 'pm', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('177', 'Puerto Rico', 'pr', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('178', 'Portugal', 'pt', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('179', 'Palau', 'pw', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('180', 'Paraguay', 'py', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('181', 'Qatar', 'qa', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('182', 'Romania', 'ro', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('183', 'Serbia', 'rs', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('184', 'Russia', 'ru', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('185', 'Rwanda', 'rw', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('186', 'Saudi Arabia', 'sa', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('187', 'Solomon Islands', 'sb', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('188', 'Seychelles', 'sc', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('189', 'Sudan', 'sd', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('190', 'Sweden', 'se', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('191', 'Singapore', 'sg', '5', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('192', 'Saint Helena', 'sh', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('193', 'Slovenia', 'si', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('195', 'Slovakia', 'sk', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('196', 'Sierra Leone', 'sl', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('197', 'San Marino', 'sm', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('198', 'Senegal', 'sn', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('199', 'Somalia', 'so', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('200', 'Suriname', 'sr', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('201', 'Sao Tome and Principe', 'st', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('202', 'El Salvador', 'sv', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('204', 'Swaziland', 'sz', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('205', 'Turks and Caicos Islands', 'tc', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('206', 'Chad', 'td', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('207', 'Togo', 'tg', '2', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('208', 'Thailand', 'th', '5', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('209', 'Tajikistan', 'tj', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('210', 'Tokelau', 'tk', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('212', 'Turkmenistan', 'tm', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('213', 'Tunisia', 'tn', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('214', 'Tonga', 'to', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('215', 'Turkey', 'tr', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('216', 'Trinidad and Tobago', 'tt', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('217', 'Tuvalu', 'tv', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('219', 'Tanzania', 'tz', '1', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('220', 'Ukraine', 'ua', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('221', 'Uganda', 'ug', '1', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('222', 'United States', 'us', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('223', 'Uruguay', 'uy', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('224', 'Uzbekistan', 'uz', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('227', 'Venezuela', 've', '4', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('228', 'British Virgin Islands', 'vg', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('230', 'Vietnam', 'vn', '5', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('231', 'Vanuatu', 'vu', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('232', 'Wallis and Futuna', 'wf', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('233', 'Samoa', 'ws', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('234', 'Yemen', 'ye', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('235', 'Mayotte', 'yt', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('236', 'South Africa', 'za', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('237', 'Zambia', 'zm', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('238', 'Zimbabwe', 'zw', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('239', 'Nyando', 'KE01', '113', '11', '1', '0');
INSERT INTO `loc_elements` VALUES ('240', 'Makueni', 'KE02', '113', '11', '5', '0');
INSERT INTO `loc_elements` VALUES ('241', 'Albertine Rift', 'UG01', '221', '11', '9', '0');
INSERT INTO `loc_elements` VALUES ('242', 'Kagera Basin', 'UG02', '221', '11', '13', '0');
INSERT INTO `loc_elements` VALUES ('243', 'Usambara', 'TZ01', '219', '11', '17', '0');
INSERT INTO `loc_elements` VALUES ('244', 'Borana', 'ET01', '72', '11', '21', '0');
INSERT INTO `loc_elements` VALUES ('245', 'Yatenga', 'BF01', '27', '11', '25', '0');
INSERT INTO `loc_elements` VALUES ('246', 'Lawra-Jirapa', 'GH01', '83', '11', '29', '0');
INSERT INTO `loc_elements` VALUES ('247', 'Segou', 'MA01', '142', '11', '33', '0');
INSERT INTO `loc_elements` VALUES ('248', 'Kollo', 'NI01', '158', '11', '37', '0');
INSERT INTO `loc_elements` VALUES ('249', 'Kaffrine', 'SE01', '198', '11', '41', '0');
INSERT INTO `loc_elements` VALUES ('250', 'Khulna', 'BA04', '25', '11', '45', '0');
INSERT INTO `loc_elements` VALUES ('251', 'Haryana', 'IN17', '103', '11', '49', '0');
INSERT INTO `loc_elements` VALUES ('252', 'Bihar', 'IN16', '103', '11', '53', '0');
INSERT INTO `loc_elements` VALUES ('253', 'Mid-Western Terrai', 'NE03', '163', '11', '57', '0');
INSERT INTO `loc_elements` VALUES ('254', 'Banke', 'NE04', '163', '11', '61', '0');
INSERT INTO `loc_elements` VALUES ('255', 'Kanchanpur', 'NE05', '163', '11', '65', '0');
INSERT INTO `loc_elements` VALUES ('256', 'El Tuma-la Dalia', 'NIC01', '160', '11', '69', '0');
INSERT INTO `loc_elements` VALUES ('257', 'Olopa', 'GU01', '90', '11', '73', '0');
INSERT INTO `loc_elements` VALUES ('258', 'Santa Rita', 'HO01', '95', '11', '77', '0');
INSERT INTO `loc_elements` VALUES ('259', 'Ma', 'VN01', '230', '11', '81', '0');
INSERT INTO `loc_elements` VALUES ('260', 'Ekxang', 'LA01', '124', '11', '85', '0');
INSERT INTO `loc_elements` VALUES ('261', 'Rohar Sourng', 'CA01', '115', '11', '89', '0');
INSERT INTO `loc_elements` VALUES ('262', 'Chemildagey', 'KEN0101', '239', '10', '93', '0');
INSERT INTO `loc_elements` VALUES ('263', 'Tabet B', 'KEN0102', '239', '10', '94', '0');
INSERT INTO `loc_elements` VALUES ('264', 'Kapsorok', 'KEN0103', '239', '10', '95', '0');
INSERT INTO `loc_elements` VALUES ('265', 'Kamango', 'KEN0104', '239', '10', '96', '0');
INSERT INTO `loc_elements` VALUES ('266', 'Kobiero', 'KEN0105', '239', '10', '97', '0');
INSERT INTO `loc_elements` VALUES ('267', 'Kamuana', 'KEN0106', '239', '10', '98', '0');
INSERT INTO `loc_elements` VALUES ('268', 'Obinju', 'KEN0107', '239', '10', '99', '0');
INSERT INTO `loc_elements` VALUES ('269', 'Kyamogi', 'UGA0101', '241', '10', '100', '0');
INSERT INTO `loc_elements` VALUES ('270', 'Kibaire', 'UGA0102', '241', '10', '101', '0');
INSERT INTO `loc_elements` VALUES ('271', 'Nyakakonge', 'UGA0103', '241', '10', '102', '0');
INSERT INTO `loc_elements` VALUES ('272', 'Katikara', 'UGA0104', '241', '10', '103', '0');
INSERT INTO `loc_elements` VALUES ('273', 'Mparangasi', 'UGA0105', '241', '10', '104', '0');
INSERT INTO `loc_elements` VALUES ('274', 'Kiranga', 'UGA0106', '241', '10', '105', '0');
INSERT INTO `loc_elements` VALUES ('275', 'Kisinina', 'UGA0107', '241', '10', '106', '0');
INSERT INTO `loc_elements` VALUES ('276', 'Boheloi', 'TZA0101', '243', '10', '107', '0');
INSERT INTO `loc_elements` VALUES ('277', 'Mbuzii', 'TZA0102', '243', '10', '108', '0');
INSERT INTO `loc_elements` VALUES ('278', 'Kwang’wenda', 'TZA0103', '243', '10', '109', '0');
INSERT INTO `loc_elements` VALUES ('279', 'Gare', 'TZA0104', '243', '10', '110', '0');
INSERT INTO `loc_elements` VALUES ('280', 'Yamba', 'TZA0105', '243', '10', '111', '0');
INSERT INTO `loc_elements` VALUES ('281', 'Milungui', 'TZA0106', '243', '10', '112', '0');
INSERT INTO `loc_elements` VALUES ('282', 'Masange', 'TZA0107', '243', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('283', 'Tibtenga', 'BFA0101', '245', '10', '113', '0');
INSERT INTO `loc_elements` VALUES ('284', 'Ramdolla', 'BFA0102', '245', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('285', 'Doggoh', 'GHA0101', '246', '10', '114', '0');
INSERT INTO `loc_elements` VALUES ('286', 'Tongo', 'ML0101', '247', '10', '115', '0');
INSERT INTO `loc_elements` VALUES ('287', 'N\'gakoro', 'ML0102', '247', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('288', 'Kampa Zarama', 'NER0101', '248', '10', '116', '0');
INSERT INTO `loc_elements` VALUES ('289', 'Ngouye', 'SEN0101', '249', '10', '117', '0');
INSERT INTO `loc_elements` VALUES ('290', 'Toune Mosquee', 'SEN0102', '249', '10', '118', '0');
INSERT INTO `loc_elements` VALUES ('291', 'Jagannathpur', 'BGD0401', '250', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('292', 'Gabgachia', 'BGD0402', '250', '10', '119', '0');
INSERT INTO `loc_elements` VALUES ('293', 'Dumuria', 'BGD0403', '250', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('294', 'Chandipur', 'BGD0404', '250', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('295', 'Ajanthali', 'IND1701', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('296', 'Baraana', 'IND1702', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('297', 'Bastada', 'IND1703', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('298', 'Bjida Jaatan', 'IND1704', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('299', 'Chorpura', 'IND1705', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('300', 'Dadupur', 'IND1706', '251', '10', '120', '0');
INSERT INTO `loc_elements` VALUES ('301', 'Dhaha', 'IND1707', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('302', 'Gaanger', 'IND1708', '251', '10', '121', '0');
INSERT INTO `loc_elements` VALUES ('303', 'Ghide', 'IND1709', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('304', 'Kalsora', 'IND1710', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('305', 'Karkakhali', 'IND1711', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('306', 'Kartarpur', 'IND1712', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('307', 'Kutail', 'IND1713', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('308', 'Modi', 'IND1714', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('309', 'Musaipur', 'IND1715', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('310', 'Naryana', 'IND1716', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('311', 'Padhana', 'IND1717', '251', '10', '122', '0');
INSERT INTO `loc_elements` VALUES ('312', 'Pujaam', 'IND1718', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('313', 'Rawar', 'IND1719', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('314', 'Sambhali', 'IND1720', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('315', 'Sandir', 'IND1721', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('316', 'Shekhpursuhana', 'IND1722', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('317', 'Subri', 'IND1723', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('318', 'Unchasamana', 'IND1724', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('319', 'Veed Majara', 'IND1725', '251', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('320', 'Bhattha Dashi ', 'IN1601', '252', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('321', 'Raja Pakar', 'IN1602', '252', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('322', 'Mukundapur ', 'IN1603', '252', '10', '123', '0');
INSERT INTO `loc_elements` VALUES ('323', 'Bairiya  ', 'NPL0301', '253', '10', '124', '0');
INSERT INTO `loc_elements` VALUES ('324', 'Mahuwari', 'NPL0302', '253', '10', null, '0');
INSERT INTO `loc_elements` VALUES ('325', 'Rehara', 'NPL0303', '253', '10', '125', '0');
INSERT INTO `loc_elements` VALUES ('326', 'Ma', 'VNM0101', '259', '10', '126', '0');
INSERT INTO `loc_elements` VALUES ('327', 'My Loi', 'VNM0102', '259', '10', '127', '0');
INSERT INTO `loc_elements` VALUES ('328', 'Tra Hat ', 'VNM0103', '259', '10', '128', '0');
INSERT INTO `loc_elements` VALUES ('329', 'Phailom', 'LAO0101', '260', '10', '129', '0');
INSERT INTO `loc_elements` VALUES ('330', 'Ekxang', 'LAO0102', '260', '10', '130', '0');
INSERT INTO `loc_elements` VALUES ('331', ' Rohal Suong', 'KMH0101', '261', '10', '131', '0');
INSERT INTO `loc_elements` VALUES ('332', 'Trifinio region', null, null, '3', '805', '0');
INSERT INTO `loc_elements` VALUES ('337', 'Meta-Piedmonte', null, null, '3', '806', '0');
INSERT INTO `loc_elements` VALUES ('338', 'Meta-Altillanura', null, null, '3', '807', '0');
INSERT INTO `loc_elements` VALUES ('339', 'Cauca-Patia', null, null, '3', '808', '0');
INSERT INTO `loc_elements` VALUES ('343', 'Chorotega', null, null, '3', '809', '0');
INSERT INTO `loc_elements` VALUES ('344', 'Huetar Norte', null, null, '3', '810', '0');
INSERT INTO `loc_elements` VALUES ('345', 'Llanos-Piedmonte', null, null, '3', '145', '0');
INSERT INTO `loc_elements` VALUES ('346', 'Llanos-Altillanura', null, null, '3', '146', '0');
INSERT INTO `loc_elements` VALUES ('347', 'Patia', null, null, '3', '147', '0');
INSERT INTO `loc_elements` VALUES ('348', 'Plateau of Popayan', null, null, '3', '148', '0');
INSERT INTO `loc_elements` VALUES ('349', 'Chorotega', null, null, '3', '149', '0');
INSERT INTO `loc_elements` VALUES ('350', 'Huetar Norte', null, null, '3', '150', '0');
INSERT INTO `loc_elements` VALUES ('361', 'Paragominas', null, null, '4', '763', '0');
INSERT INTO `loc_elements` VALUES ('362', 'Paragominas', null, null, '4', '764', '0');
INSERT INTO `loc_elements` VALUES ('363', 'Paragominas', null, null, '4', '765', '0');
INSERT INTO `loc_elements` VALUES ('364', 'paragominas', null, null, '4', '766', '0');
INSERT INTO `loc_elements` VALUES ('370', 'Trifinio', null, null, '3', '768', '0');
INSERT INTO `loc_elements` VALUES ('371', 'NicaCentral', null, null, '3', '769', '0');
INSERT INTO `loc_elements` VALUES ('372', 'Trifinio', null, null, '3', '172', '0');
INSERT INTO `loc_elements` VALUES ('373', 'NicaCentral', null, null, '3', '173', '0');
INSERT INTO `loc_elements` VALUES ('374', 'Junin', null, null, '3', '174', '0');
INSERT INTO `loc_elements` VALUES ('375', 'Ondores', null, null, '4', '175', '0');
INSERT INTO `loc_elements` VALUES ('376', 'Upper Mantaro', null, null, '7', '176', '0');
INSERT INTO `loc_elements` VALUES ('377', 'Los Cerrillos Cauca', null, null, '3', '177', '0');
INSERT INTO `loc_elements` VALUES ('378', 'Cauca', null, null, '4', '795', '0');
INSERT INTO `loc_elements` VALUES ('380', 'Ucayali', null, null, '3', '796', '0');
INSERT INTO `loc_elements` VALUES ('385', 'Los Cerrillos Cauca', null, null, '3', '181', '0');
INSERT INTO `loc_elements` VALUES ('386', 'Puracé', null, null, '3', '182', '0');
INSERT INTO `loc_elements` VALUES ('387', 'Puno', null, null, '3', '183', '0');
INSERT INTO `loc_elements` VALUES ('388', 'Estelí, Nicaragua', null, null, '3', '184', '0');
INSERT INTO `loc_elements` VALUES ('389', 'Madriz, Nicaragua', null, null, '3', '185', '0');
INSERT INTO `loc_elements` VALUES ('390', 'Nueva Segovia, Nicaragua', null, null, '3', '186', '0');
INSERT INTO `loc_elements` VALUES ('391', 'Quiché, Guatemala', null, null, '3', '187', '0');
INSERT INTO `loc_elements` VALUES ('392', 'Sololá, Guatemala', null, null, '3', '188', '0');
INSERT INTO `loc_elements` VALUES ('393', 'Estelí, Nicaragua', null, null, '3', '189', '0');
INSERT INTO `loc_elements` VALUES ('394', 'Madriz, Nicaragua', null, null, '3', '190', '0');
INSERT INTO `loc_elements` VALUES ('395', 'Nueva Segovia, Nicaragua', null, null, '3', '191', '0');
INSERT INTO `loc_elements` VALUES ('396', 'Quiché, Guatemala', null, null, '3', '192', '0');
INSERT INTO `loc_elements` VALUES ('397', 'Sololá, Guatemala', null, null, '3', '193', '0');
INSERT INTO `loc_elements` VALUES ('398', 'Estelí, Nicaragua', null, null, '3', '826', '0');
INSERT INTO `loc_elements` VALUES ('399', 'Madriz, Nicaragua', null, null, '3', '827', '0');
INSERT INTO `loc_elements` VALUES ('400', 'Nueva Segovia, Nicaragua', null, null, '3', '828', '0');
INSERT INTO `loc_elements` VALUES ('401', 'Huehuetenango, Guatemala', null, null, '3', '829', '0');
INSERT INTO `loc_elements` VALUES ('403', 'Trifinio', null, null, '3', '770', '0');
INSERT INTO `loc_elements` VALUES ('404', 'NicaCentral', null, null, '3', '771', '0');
INSERT INTO `loc_elements` VALUES ('405', 'Tuma, La Dalia', null, null, '8', '201', '0');
INSERT INTO `loc_elements` VALUES ('406', 'Olopa, Trifinio-Guatemala', null, null, '8', '202', '0');
INSERT INTO `loc_elements` VALUES ('407', 'Santa Rita, Trifinio-Honduras', null, null, '8', '203', '0');
INSERT INTO `loc_elements` VALUES ('408', 'Cauca, Colombia', null, null, '8', '204', '0');
INSERT INTO `loc_elements` VALUES ('409', 'Cauca, Colombia', null, null, '8', '205', '0');
INSERT INTO `loc_elements` VALUES ('410', 'Junin', null, null, '3', '664', '0');
INSERT INTO `loc_elements` VALUES ('412', 'Upper Mantaro', null, null, '7', '665', '0');
INSERT INTO `loc_elements` VALUES ('413', 'Trifinio', null, null, '3', '209', '0');
INSERT INTO `loc_elements` VALUES ('414', 'NicaCentral', null, null, '3', '210', '0');
INSERT INTO `loc_elements` VALUES ('416', 'Son La', null, null, '3', '811', '0');
INSERT INTO `loc_elements` VALUES ('417', 'Guinayangan, Quezon Province, Philippines', null, null, '4', '776', '0');
INSERT INTO `loc_elements` VALUES ('419', 'Vietnam - Dien Bien, Dien Bien province', null, null, '4', '662', '0');
INSERT INTO `loc_elements` VALUES ('420', 'Cambodia - Kone Mom district, Ratanakiri province', null, null, '4', '663', '0');
INSERT INTO `loc_elements` VALUES ('440', 'Bihar, India', null, null, '3', '801', '0');
INSERT INTO `loc_elements` VALUES ('445', 'Githunguri', null, null, '4', '759', '0');
INSERT INTO `loc_elements` VALUES ('446', 'Kayatta', null, null, '4', '760', '0');
INSERT INTO `loc_elements` VALUES ('447', 'Kaptumo', null, null, '4', '761', '0');
INSERT INTO `loc_elements` VALUES ('449', 'Kutai Kartanegara', null, null, '4', '837', '0');
INSERT INTO `loc_elements` VALUES ('459', 'Nandi', null, null, '4', '762', '0');
INSERT INTO `loc_elements` VALUES ('464', 'Hanoi', null, null, '3', '812', '0');
INSERT INTO `loc_elements` VALUES ('465', 'Yen Binh', null, null, '4', '803', '0');
INSERT INTO `loc_elements` VALUES ('466', 'Ky Anh', null, null, '4', '804', '0');
INSERT INTO `loc_elements` VALUES ('472', 'Black Watershed 4, ICRISAT-Patancheru', null, null, '6', '774', '0');
INSERT INTO `loc_elements` VALUES ('473', 'ICRISAT-Patancheru Rice Field', null, null, '6', '775', '0');
INSERT INTO `loc_elements` VALUES ('475', 'Nioro du Rip', null, null, '4', '833', '0');
INSERT INTO `loc_elements` VALUES ('478', 'Cinzana', null, null, '4', '817', '0');
INSERT INTO `loc_elements` VALUES ('479', 'Kaffrine', null, null, '4', '818', '0');
INSERT INTO `loc_elements` VALUES ('480', 'Lawra', null, null, '4', '819', '0');
INSERT INTO `loc_elements` VALUES ('481', 'Jirapa', null, null, '4', '820', '0');
INSERT INTO `loc_elements` VALUES ('483', 'Bougouni', null, null, '4', '821', '0');
INSERT INTO `loc_elements` VALUES ('496', 'Sikasso Region', null, null, '3', '834', '0');
INSERT INTO `loc_elements` VALUES ('497', 'Sukumba', null, null, '8', '835', '0');
INSERT INTO `loc_elements` VALUES ('504', 'Paragominas', null, null, '4', '767', '0');
INSERT INTO `loc_elements` VALUES ('505', 'Rakai, Uganda', null, null, '4', '701', '0');
INSERT INTO `loc_elements` VALUES ('506', 'Lushoto, Tanzania', null, null, '4', '702', '0');
INSERT INTO `loc_elements` VALUES ('508', 'Nandom', null, null, '4', '822', '0');
INSERT INTO `loc_elements` VALUES ('509', 'Bambey', null, null, '4', '823', '0');
INSERT INTO `loc_elements` VALUES ('510', 'Linguère', null, null, '4', '824', '0');
INSERT INTO `loc_elements` VALUES ('531', 'Lushoto, Tanzania', null, null, '4', '703', '0');
INSERT INTO `loc_elements` VALUES ('532', 'Rakai, Uganda', null, null, '4', '704', '0');
INSERT INTO `loc_elements` VALUES ('536', 'Lushoto , Tanzania', null, null, '4', '705', '0');
INSERT INTO `loc_elements` VALUES ('537', 'Rakai, Uganda', null, null, '4', '706', '0');
INSERT INTO `loc_elements` VALUES ('538', 'Rakai, Uganda', null, null, '4', '707', '0');
INSERT INTO `loc_elements` VALUES ('539', 'Lushoto, Tanzania', null, null, '4', '708', '0');
INSERT INTO `loc_elements` VALUES ('540', 'Lushoto, Tanzania', null, null, '4', '709', '0');
INSERT INTO `loc_elements` VALUES ('541', 'Rakai, Uganda', null, null, '4', '710', '0');
INSERT INTO `loc_elements` VALUES ('542', 'Punjab', null, null, '3', '780', '0');
INSERT INTO `loc_elements` VALUES ('543', 'Ludhiana', null, null, '4', '781', '0');
INSERT INTO `loc_elements` VALUES ('544', 'Patiala', null, null, '4', '782', '0');
INSERT INTO `loc_elements` VALUES ('545', 'Haryana', null, null, '3', '783', '0');
INSERT INTO `loc_elements` VALUES ('546', 'Karnal', null, null, '4', '784', '0');
INSERT INTO `loc_elements` VALUES ('547', 'Bihar', null, null, '3', '785', '0');
INSERT INTO `loc_elements` VALUES ('548', 'Vaishali', null, null, '4', '786', '0');
INSERT INTO `loc_elements` VALUES ('549', 'Samastipur', null, null, '4', '787', '0');
INSERT INTO `loc_elements` VALUES ('550', 'Andhra Pradesh', null, null, '3', '788', '0');
INSERT INTO `loc_elements` VALUES ('551', 'Anantpur', null, null, '4', '789', '0');
INSERT INTO `loc_elements` VALUES ('552', 'Odisha', null, null, '3', '790', '0');
INSERT INTO `loc_elements` VALUES ('553', 'Puri', null, null, '4', '791', '0');
INSERT INTO `loc_elements` VALUES ('554', 'Bhadrak', null, null, '4', '792', '0');
INSERT INTO `loc_elements` VALUES ('555', 'Karnataka', null, null, '3', '793', '0');
INSERT INTO `loc_elements` VALUES ('558', 'Khulna', null, null, '4', '794', '0');
INSERT INTO `loc_elements` VALUES ('559', 'Luwero Uganda', null, null, '4', '711', '0');
INSERT INTO `loc_elements` VALUES ('560', 'Mbale Uganda', null, null, '4', '712', '0');
INSERT INTO `loc_elements` VALUES ('561', 'Lushoto, Tanzania', null, null, '4', '713', '0');
INSERT INTO `loc_elements` VALUES ('562', 'Rakai, Uganda', null, null, '4', '714', '0');
INSERT INTO `loc_elements` VALUES ('563', 'Bako', null, null, '8', '755', '0');
INSERT INTO `loc_elements` VALUES ('564', 'Melkassa', null, null, '8', '756', '0');
INSERT INTO `loc_elements` VALUES ('565', 'Gishwati', null, null, '8', '757', '0');
INSERT INTO `loc_elements` VALUES ('566', 'Bugesera', null, null, '3', '758', '0');
INSERT INTO `loc_elements` VALUES ('567', 'Rakai, Uganda', null, null, '4', '715', '0');
INSERT INTO `loc_elements` VALUES ('568', 'Lushoto, Tanzania', null, null, '4', '716', '0');
INSERT INTO `loc_elements` VALUES ('569', 'Lushoto , Tanzania', null, null, '4', '717', '0');
INSERT INTO `loc_elements` VALUES ('570', 'Rakai, Uganda', null, null, '4', '718', '0');
INSERT INTO `loc_elements` VALUES ('572', 'Pauri Garhwal', null, null, '4', '361', '0');
INSERT INTO `loc_elements` VALUES ('573', 'Rudra Prayag', null, null, '4', '362', '0');
INSERT INTO `loc_elements` VALUES ('574', 'Tehri Garhwal', null, null, '4', '363', '0');
INSERT INTO `loc_elements` VALUES ('575', 'Mandi', null, null, '4', '364', '0');
INSERT INTO `loc_elements` VALUES ('576', 'Sirmaur', null, null, '4', '365', '0');
INSERT INTO `loc_elements` VALUES ('577', 'Ladakh', null, null, '4', '366', '0');
INSERT INTO `loc_elements` VALUES ('578', 'Barmer', null, null, '4', '367', '0');
INSERT INTO `loc_elements` VALUES ('579', 'Jaisalmer', null, null, '4', '368', '0');
INSERT INTO `loc_elements` VALUES ('580', 'Jodhpur', null, null, '4', '369', '0');
INSERT INTO `loc_elements` VALUES ('581', 'Shahdol', null, null, '4', '370', '0');
INSERT INTO `loc_elements` VALUES ('582', 'Umaria', null, null, '4', '371', '0');
INSERT INTO `loc_elements` VALUES ('583', 'Koriya', null, null, '4', '372', '0');
INSERT INTO `loc_elements` VALUES ('584', 'Balrampur', null, null, '4', '373', '0');
INSERT INTO `loc_elements` VALUES ('585', 'Golaghat', null, null, '4', '374', '0');
INSERT INTO `loc_elements` VALUES ('586', 'Jorhat', null, null, '4', '375', '0');
INSERT INTO `loc_elements` VALUES ('587', 'Karbi Anglong', null, null, '4', '376', '0');
INSERT INTO `loc_elements` VALUES ('588', 'Tinsukia', null, null, '4', '377', '0');
INSERT INTO `loc_elements` VALUES ('589', 'Longleng', null, null, '4', '378', '0');
INSERT INTO `loc_elements` VALUES ('590', 'Peren', null, null, '4', '379', '0');
INSERT INTO `loc_elements` VALUES ('591', 'Mokokchung', null, null, '4', '380', '0');
INSERT INTO `loc_elements` VALUES ('592', 'Phek', null, null, '4', '381', '0');
INSERT INTO `loc_elements` VALUES ('593', 'Almora', null, null, '4', '382', '0');
INSERT INTO `loc_elements` VALUES ('594', 'Tanga/Arusha', null, null, '3', '719', '0');
INSERT INTO `loc_elements` VALUES ('595', 'Lushoto', null, null, '4', '720', '0');
INSERT INTO `loc_elements` VALUES ('596', 'Lushoto Tanzania', null, null, '4', '721', '0');
INSERT INTO `loc_elements` VALUES ('597', 'Rakai, Uganda', null, null, '4', '722', '0');
INSERT INTO `loc_elements` VALUES ('599', 'Lushoto, Tanzania', null, null, '4', '723', '0');
INSERT INTO `loc_elements` VALUES ('601', 'Cauca', 'CO01', '53', '11', '390', '0');
INSERT INTO `loc_elements` VALUES ('607', 'Maharashtra', null, null, '3', '749', '0');
INSERT INTO `loc_elements` VALUES ('608', 'Haryana', null, null, '3', '750', '0');
INSERT INTO `loc_elements` VALUES ('609', 'Madhya Pradesh', null, null, '3', '751', '0');
INSERT INTO `loc_elements` VALUES ('610', 'Bihar', null, null, '3', '752', '0');
INSERT INTO `loc_elements` VALUES ('620', 'Odisha, India', null, null, '3', '802', '0');
INSERT INTO `loc_elements` VALUES ('621', 'Luwero, Uganda', null, null, '4', '724', '0');
INSERT INTO `loc_elements` VALUES ('622', 'Kilolo, Tanzania', null, null, '4', '725', '0');
INSERT INTO `loc_elements` VALUES ('627', 'Bihar', null, null, '3', '747', '0');
INSERT INTO `loc_elements` VALUES ('628', 'Haryana', null, null, '3', '748', '0');
INSERT INTO `loc_elements` VALUES ('629', 'Chiquimula (Trifinio)', null, null, '3', '666', '0');
INSERT INTO `loc_elements` VALUES ('630', 'Phailom', 'LAO0150', null, '10', '437', '0');
INSERT INTO `loc_elements` VALUES ('631', 'Phongsali', null, null, '3', '488', '0');
INSERT INTO `loc_elements` VALUES ('632', 'Koutiala', null, null, '4', '825', '0');
INSERT INTO `loc_elements` VALUES ('633', 'Colombia: Tolima ', null, null, '4', '744', '0');
INSERT INTO `loc_elements` VALUES ('634', 'Perú: Jaen, ', null, null, '4', '745', '0');
INSERT INTO `loc_elements` VALUES ('635', 'Nicaragua: Malacatoya, Sebaco, Matagalpa y San Luis', null, null, '4', '746', '0');
INSERT INTO `loc_elements` VALUES ('636', 'Natagaima, Tolima', null, null, '4', '777', '0');
INSERT INTO `loc_elements` VALUES ('637', 'Nghe An', null, null, '3', '813', '0');
INSERT INTO `loc_elements` VALUES ('638', 'Dak Lak', null, null, '3', '814', '0');
INSERT INTO `loc_elements` VALUES ('639', 'Dong Nai', null, null, '3', '815', '0');
INSERT INTO `loc_elements` VALUES ('640', 'An Giang', null, null, '3', '816', '0');
INSERT INTO `loc_elements` VALUES ('641', 'Danli, El Paraiso, Honduras', null, null, '8', '778', '0');
INSERT INTO `loc_elements` VALUES ('642', 'Morocelí, El Paraíso, Honduras', null, null, '8', '779', '0');
INSERT INTO `loc_elements` VALUES ('643', 'Muzaffarpur', null, null, '4', '728', '0');
INSERT INTO `loc_elements` VALUES ('644', 'Sirajganj', null, null, '4', '729', '0');
INSERT INTO `loc_elements` VALUES ('645', 'Nwoya, Uganda', null, null, '4', '726', '0');
INSERT INTO `loc_elements` VALUES ('646', 'Paragominas', null, null, '4', '654', '0');
INSERT INTO `loc_elements` VALUES ('647', 'Gimbi ', null, null, '4', '676', '0');
INSERT INTO `loc_elements` VALUES ('648', 'Digga', null, null, '4', '677', '0');
INSERT INTO `loc_elements` VALUES ('649', 'Mbale, Uganda', null, null, '4', '727', '0');
INSERT INTO `loc_elements` VALUES ('650', 'Darbhanga', null, null, '4', '730', '0');
INSERT INTO `loc_elements` VALUES ('651', 'Samastipur', null, null, '4', '731', '0');
INSERT INTO `loc_elements` VALUES ('652', 'municipio de Gracias', null, null, '4', '754', '0');
INSERT INTO `loc_elements` VALUES ('653', 'Mahakam Hulu', null, null, '4', '836', '0');
INSERT INTO `loc_elements` VALUES ('654', 'Aland Islands', 'AX', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('655', 'Bouvet Island', 'BV', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('656', 'Brunei Darussalam', 'BN', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('657', 'Hong Kong, Special Administrative Region of China', 'HK', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('658', 'Macao, Special Administrative Region of China', 'MO', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('659', 'Congo (Brazzaville)', 'CG', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('660', 'Congo, Democratic Republic of the', 'CD', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('661', 'Côte d\'Ivoire', 'CI', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('662', 'Falkland Islands (Malvinas)', 'FK', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('663', 'French Guiana', 'GF', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('664', 'French Southern Territories', 'TF', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('665', 'Guadeloupe', 'GP', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('666', 'Guernsey', 'GG', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('667', 'Heard Island and Mcdonald Islands', 'HM', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('668', 'Holy See (Vatican City State)', 'VA', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('669', 'Iran, Islamic Republic of', 'IR', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('670', 'Korea, Democratic People\'s Republic of', 'KP', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('671', 'Korea, Republic of', 'KR', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('672', 'Lao PDR', 'LA', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('673', 'Latvia', 'LV', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('674', 'Macedonia, Republic of', 'MK', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('675', 'Martinique', 'MQ', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('676', 'Micronesia, Federated States of', 'FM', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('677', 'Myanmar', 'MM', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('678', 'Norfolk Island', 'NF', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('679', 'Palestinian Territory, Occupied', 'PS', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('680', 'Pitcairn', 'PN', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('681', 'Réunion', 'RE', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('682', 'Russian Federation', 'RU', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('683', 'Saint-Barthélemy', 'BL', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('684', 'Saint-Martin (French part)', 'MF', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('685', 'Saint Vincent and Grenadines', 'VC', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('686', 'South Georgia and the South Sandwich Islands', 'GS', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('687', 'South Sudan', 'SS', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('688', 'Suriname *', 'SR', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('689', 'Svalbard and Jan Mayen Islands', 'SJ', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('690', 'Syrian Arab Republic (Syria)', 'SY', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('691', 'Taiwan, Republic of China', 'TW', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('692', 'Tanzania *, United Republic of', 'TZ', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('693', 'Timor-Leste', 'TL', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('695', 'United States Minor Outlying Islands', 'UM', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('698', 'Virgin Islands, US', 'VI', '6', '2', null, '0');
INSERT INTO `loc_elements` VALUES ('699', 'Wallis and Futuna Islands', 'WF', '6', '2', null, '0');
