SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for loc_elements
-- ----------------------------
DROP TABLE IF EXISTS `loc_elements`;
CREATE TABLE `loc_elements` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` text NOT NULL,
  `iso_alpha_2` varchar(45) DEFAULT NULL,
  `iso_numeric` bigint(5) DEFAULT NULL,
  `parent_id` bigint(20) DEFAULT NULL,
  `element_type_id` bigint(20) DEFAULT NULL,
  `geoposition_id` bigint(20) DEFAULT NULL,
  `is_site_integration` tinyint(1) DEFAULT NULL,
  `crp_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_loc_element_loc_element_type_id_idx` (`element_type_id`) USING BTREE,
  KEY `FK_loc_elements_loc_geopositions_idx` (`geoposition_id`) USING BTREE,
  KEY `crp_id` (`crp_id`),
  CONSTRAINT `loc_elements_ibfk_1` FOREIGN KEY (`geoposition_id`) REFERENCES `loc_geopositions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `loc_elements_ibfk_2` FOREIGN KEY (`element_type_id`) REFERENCES `loc_element_types` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `loc_elements_ibfk_3` FOREIGN KEY (`crp_id`) REFERENCES `crps` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=554 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of loc_elements
-- ----------------------------
INSERT INTO `loc_elements` VALUES ('1', 'Eastern Africa', 'EA', '14', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('2', 'Western Africa', 'WA', '11', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('3', 'Southern Asia', 'SA', '34', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('4', 'Latin America and the Caribbean ', 'LAM', '419', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('5', 'South-Eastern Asia', 'SEA', '35', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('6', 'Other', null, null, null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('7', 'Middle Africa', 'MA', '17', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('8', 'Northern Africa', 'NA', '15', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('9', 'Southern Africa', 'SA', '18', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('10', 'Caribbean', 'CB', '29', '4', '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('11', 'Central America', 'CA', '13', '4', '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('12', 'South America', 'SA', '5', '4', '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('13', 'Northern America', 'NA', '21', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('14', 'Central Asia', 'CA', '143', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('15', 'Eastern Asia', 'EA', '30', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('16', 'Western Asia', 'WA', '145', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('17', 'Eastern Europe', 'EE', '151', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('18', 'Northern Europe', 'NE', '154', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('19', 'Southern Europe', 'SE', '39', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('20', 'Western Europe', 'WE', '155', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('21', 'Australia and New Zealand', 'AZ', '53', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('22', 'Melanesia', 'ML', '54', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('23', 'Micronesia', 'MN', '57', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('24', 'Polynesia', 'PL', '61', null, '1', null, '0', null);
INSERT INTO `loc_elements` VALUES ('25', 'Andorra', 'ad', '20', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('26', 'United Arab Emirates', 'ae', '784', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('27', 'Afghanistan', 'af', '4', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('28', 'Antigua and Barbuda', 'ag', '28', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('29', 'Anguilla', 'ai', '660', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('30', 'Albania', 'al', '8', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('31', 'Armenia', 'am', '51', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('32', 'Netherlands Antilles', 'an', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('33', 'Angola', 'ao', '24', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('34', 'Antarctica', 'aq', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('35', 'Argentina', 'ar', '32', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('36', 'American Samoa', 'as', '16', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('37', 'Austria', 'at', '40', '713', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('38', 'Australia', 'au', '36', '714', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('39', 'Aruba', 'aw', '533', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('40', 'Azerbaijan', 'az', '31', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('41', 'Bosnia and Herzegovina', 'ba', '70', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('42', 'Barbados', 'bb', '52', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('43', 'Bangladesh', 'bd', '50', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('44', 'Belgium', 'be', '56', '713', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('45', 'Burkina Faso', 'bf', '854', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('46', 'Bulgaria', 'bg', '100', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('47', 'Bahrain', 'bh', '48', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('48', 'Burundi', 'bi', '108', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('49', 'Benin', 'bj', '204', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('50', 'Bermuda', 'bm', '60', '706', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('51', 'Bolivia', 'bo', '68', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('52', 'Brazil', 'br', '76', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('53', 'Bahamas', 'bs', '44', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('54', 'Bhutan', 'bt', '64', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('55', 'Botswana', 'bw', '72', '702', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('56', 'Belarus', 'by', '112', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('57', 'Belize', 'bz', '84', '704', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('58', 'Canada', 'ca', '124', '706', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('59', 'Cocos (Keeling) Islands', 'cc', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('60', 'Democratic Republic of the Congo', 'cd', '180', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('61', 'Central African Republic', 'cf', '140', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('62', 'Switzerland', 'ch', '756', '713', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('63', 'Ivory Coast', 'ci', '384', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('64', 'Cook Islands', 'ck', '184', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('65', 'Chile', 'cl', '152', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('66', 'Cameroon', 'cm', '120', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('67', 'China', 'cn', '156', '708', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('68', 'Colombia', 'co', '170', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('69', 'Costa Rica', 'cr', '188', '704', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('70', 'Cuba', 'cu', '192', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('71', 'Cape Verde', 'cv', '132', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('72', 'Christmas Island', 'cx', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('73', 'Cyprus', 'cy', '196', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('74', 'Czech Republic', 'cz', '203', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('75', 'Germany', 'de', '276', '713', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('76', 'Djibouti', 'dj', '262', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('77', 'Denmark', 'dk', '208', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('78', 'Dominica', 'dm', '212', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('79', 'Dominican Republic', 'do', '214', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('80', 'Algeria', 'dz', '12', '701', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('81', 'Ecuador', 'ec', '218', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('82', 'Estonia', 'ee', '233', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('83', 'Egypt', 'eg', '818', '701', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('84', 'Western Sahara', 'eh', '732', '701', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('85', 'Eritrea', 'er', '232', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('86', 'Spain', 'es', '724', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('87', 'Ethiopia', 'et', '231', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('88', 'Finland', 'fi', '246', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('89', 'Fiji', 'fj', '242', '715', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('90', 'Faroe Islands', 'fo', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('91', 'France', 'fr', '250', '713', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('92', 'Gabon', 'ga', '266', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('93', 'United Kingdom', 'gb', '826', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('94', 'Grenada', 'gd', '308', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('95', 'Georgia', 'ge', '268', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('96', 'Ghana', 'gh', '288', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('97', 'Gibraltar', 'gi', '292', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('98', 'Greenland', 'gl', '304', '706', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('99', 'Gambia', 'gm', '270', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('100', 'Guinea', 'gn', '324', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('101', 'Equatorial Guinea', 'gq', '226', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('102', 'Greece', 'gr', '300', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('103', 'Guatemala', 'gt', '320', '704', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('104', 'Guam', 'gu', '316', '716', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('105', 'Guinea-Bissau', 'gw', '624', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('106', 'Guyana', 'gy', '328', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('107', 'Honduras', 'hn', '340', '704', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('108', 'Croatia', 'hr', '191', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('109', 'Haiti', 'ht', '332', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('110', 'Hungary', 'hu', '348', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('111', 'Indonesia', 'id', '360', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('112', 'Ireland', 'ie', '372', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('113', 'Israel', 'il', '376', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('114', 'Isle of Man', 'im', '833', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('115', 'India', 'in', '356', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('116', 'British Indian Ocean Territory', 'io', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('117', 'Iraq', 'iq', '368', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('118', 'Iran', 'ir', '364', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('119', 'Iceland', 'is', '352', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('120', 'Italy', 'it', '380', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('121', 'Jersey', 'je', '832', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('122', 'Jamaica', 'jm', '388', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('123', 'Jordan', 'jo', '400', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('124', 'Japan', 'jp', '392', '708', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('125', 'Kenya', 'ke', '404', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('126', 'Kyrgyzstan', 'kg', '417', '707', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('127', 'Cambodia', 'kh', '116', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('128', 'Kiribati', 'ki', '296', '716', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('129', 'Comoros', 'km', '174', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('130', 'Saint Kitts and Nevis', 'kn', '659', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('131', 'Kuwait', 'kw', '414', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('132', 'Cayman Islands', 'ky', '136', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('133', 'Kazakhstan', 'kz', '398', '707', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('134', 'Laos', 'la', '418', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('135', 'Lebanon', 'lb', '422', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('136', 'Saint Lucia', 'lc', '662', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('137', 'Liechtenstein', 'li', '438', '713', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('138', 'Sri Lanka', 'lk', '144', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('139', 'Liberia', 'lr', '430', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('140', 'Lesotho', 'ls', '426', '702', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('141', 'Lithuania', 'lt', '440', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('142', 'Luxembourg', 'lu', '442', '713', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('143', 'Libya', 'ly', '434', '701', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('144', 'Morocco', 'ma', '504', '701', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('145', 'Monaco', 'mc', '492', '713', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('146', 'Moldova', 'md', '498', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('147', 'Montenegro', 'me', '499', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('148', 'Madagascar', 'mg', '450', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('149', 'Marshall Islands', 'mh', '584', '716', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('150', 'Mali', 'ml', '466', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('151', 'Burma', 'mm', '104', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('152', 'Mongolia', 'mn', '496', '708', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('153', 'Northern Mariana Islands', 'mp', '580', '716', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('154', 'Mauritania', 'mr', '478', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('155', 'Montserrat', 'ms', '500', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('156', 'Malta', 'mt', '470', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('157', 'Mauritius', 'mu', '480', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('158', 'Maldives', 'mv', '462', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('159', 'Malawi', 'mw', '454', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('160', 'Mexico', 'mx', '484', '704', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('161', 'Malaysia', 'my', '458', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('162', 'Mozambique', 'mz', '508', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('163', 'Namibia', 'na', '516', '702', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('164', 'New Caledonia', 'nc', '540', '715', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('165', 'Niger', 'ne', '562', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('166', 'Nigeria', 'ng', '566', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('167', 'Nicaragua', 'ni', '558', '704', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('168', 'Netherlands', 'nl', '528', '713', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('169', 'Norway', 'no', '578', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('170', 'Nepal', 'np', '524', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('171', 'Nauru', 'nr', '520', '716', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('172', 'Niue', 'nu', '570', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('173', 'New Zealand', 'nz', '554', '714', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('174', 'Oman', 'om', '512', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('175', 'Panama', 'pa', '591', '704', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('176', 'Peru', 'pe', '604', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('177', 'French Polynesia', 'pf', '258', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('178', 'Papua New Guinea', 'pg', '598', '715', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('179', 'Philippines', 'ph', '608', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('180', 'Pakistan', 'pk', '586', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('181', 'Poland', 'pl', '616', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('182', 'Saint Pierre and Miquelon', 'pm', '666', '706', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('183', 'Puerto Rico', 'pr', '630', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('184', 'Portugal', 'pt', '620', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('185', 'Palau', 'pw', '585', '716', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('186', 'Paraguay', 'py', '600', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('187', 'Qatar', 'qa', '634', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('188', 'Romania', 'ro', '642', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('189', 'Serbia', 'rs', '688', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('190', 'Russia', 'ru', '643', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('191', 'Rwanda', 'rw', '646', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('192', 'Saudi Arabia', 'sa', '682', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('193', 'Solomon Islands', 'sb', '90', '715', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('194', 'Seychelles', 'sc', '690', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('195', 'Sudan', 'sd', '729', '701', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('196', 'Sweden', 'se', '752', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('197', 'Singapore', 'sg', '702', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('198', 'Saint Helena', 'sh', '654', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('199', 'Slovenia', 'si', '705', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('200', 'Slovakia', 'sk', '703', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('201', 'Sierra Leone', 'sl', '694', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('202', 'San Marino', 'sm', '674', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('203', 'Senegal', 'sn', '686', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('204', 'Somalia', 'so', '706', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('205', 'Suriname', 'sr', '740', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('206', 'Sao Tome and Principe', 'st', '678', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('207', 'El Salvador', 'sv', '222', '704', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('208', 'Swaziland', 'sz', '748', '702', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('209', 'Turks and Caicos Islands', 'tc', '796', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('210', 'Chad', 'td', '148', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('211', 'Togo', 'tg', '768', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('212', 'Thailand', 'th', '764', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('213', 'Tajikistan', 'tj', '762', '707', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('214', 'Tokelau', 'tk', '772', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('215', 'Turkmenistan', 'tm', '795', '707', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('216', 'Tunisia', 'tn', '788', '701', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('217', 'Tonga', 'to', '776', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('218', 'Turkey', 'tr', '792', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('219', 'Trinidad and Tobago', 'tt', '780', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('220', 'Tuvalu', 'tv', '798', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('221', 'Tanzania', 'tz', '834', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('222', 'Ukraine', 'ua', '804', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('223', 'Uganda', 'ug', '800', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('224', 'United States', 'us', '850', '706', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('225', 'Uruguay', 'uy', '858', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('226', 'Uzbekistan', 'uz', '860', '707', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('227', 'Venezuela', 've', '862', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('228', 'British Virgin Islands', 'vg', '92', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('229', 'Vietnam', 'vn', '704', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('230', 'Vanuatu', 'vu', '548', '715', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('231', 'Wallis and Futuna', 'wf', '876', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('232', 'Samoa', 'ws', '882', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('233', 'Yemen', 'ye', '887', '709', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('234', 'Mayotte', 'yt', '175', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('235', 'South Africa', 'za', '710', '702', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('236', 'Zambia', 'zm', '894', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('237', 'Zimbabwe', 'zw', '716', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('238', 'Nyando', 'KE01', null, '113', '11', '1', '0', null);
INSERT INTO `loc_elements` VALUES ('239', 'Makueni', 'KE02', null, '113', '11', '5', '0', null);
INSERT INTO `loc_elements` VALUES ('240', 'Albertine Rift', 'UG01', null, '221', '11', '9', '0', null);
INSERT INTO `loc_elements` VALUES ('241', 'Kagera Basin', 'UG02', null, '221', '11', '13', '0', null);
INSERT INTO `loc_elements` VALUES ('242', 'Usambara', 'TZ01', null, '219', '11', '17', '0', null);
INSERT INTO `loc_elements` VALUES ('243', 'Borana', 'ET01', null, '72', '11', '21', '0', null);
INSERT INTO `loc_elements` VALUES ('244', 'Yatenga', 'BF01', null, '27', '11', '25', '0', null);
INSERT INTO `loc_elements` VALUES ('245', 'Lawra-Jirapa', 'GH01', null, '83', '11', '29', '0', null);
INSERT INTO `loc_elements` VALUES ('246', 'Segou', 'MA01', null, '142', '11', '33', '0', null);
INSERT INTO `loc_elements` VALUES ('247', 'Kollo', 'NI01', null, '158', '11', '37', '0', null);
INSERT INTO `loc_elements` VALUES ('248', 'Kaffrine', 'SE01', null, '198', '11', '41', '0', null);
INSERT INTO `loc_elements` VALUES ('249', 'Khulna', 'BA04', null, '25', '11', '45', '0', null);
INSERT INTO `loc_elements` VALUES ('250', 'Haryana', 'IN17', null, '103', '11', '49', '0', null);
INSERT INTO `loc_elements` VALUES ('251', 'Bihar', 'IN16', null, '103', '11', '53', '0', null);
INSERT INTO `loc_elements` VALUES ('252', 'Mid-Western Terrai', 'NE03', null, '163', '11', '57', '0', null);
INSERT INTO `loc_elements` VALUES ('253', 'Banke', 'NE04', null, '163', '11', '61', '0', null);
INSERT INTO `loc_elements` VALUES ('254', 'Kanchanpur', 'NE05', null, '163', '11', '65', '0', null);
INSERT INTO `loc_elements` VALUES ('255', 'El Tuma-la Dalia', 'NIC01', null, '160', '11', '69', '0', null);
INSERT INTO `loc_elements` VALUES ('256', 'Olopa', 'GU01', null, '90', '11', '73', '0', null);
INSERT INTO `loc_elements` VALUES ('257', 'Santa Rita', 'HO01', null, '95', '11', '77', '0', null);
INSERT INTO `loc_elements` VALUES ('258', 'Ma', 'VN01', null, '230', '11', '81', '0', null);
INSERT INTO `loc_elements` VALUES ('259', 'Ekxang', 'LA01', null, '124', '11', '85', '0', null);
INSERT INTO `loc_elements` VALUES ('260', 'Rohar Sourng', 'CA01', null, '115', '11', '89', '0', null);
INSERT INTO `loc_elements` VALUES ('261', 'Chemildagey', 'KEN0101', null, '239', '10', '93', '0', null);
INSERT INTO `loc_elements` VALUES ('262', 'Tabet B', 'KEN0102', null, '239', '10', '94', '0', null);
INSERT INTO `loc_elements` VALUES ('263', 'Kapsorok', 'KEN0103', null, '239', '10', '95', '0', null);
INSERT INTO `loc_elements` VALUES ('264', 'Kamango', 'KEN0104', null, '239', '10', '96', '0', null);
INSERT INTO `loc_elements` VALUES ('265', 'Kobiero', 'KEN0105', null, '239', '10', '97', '0', null);
INSERT INTO `loc_elements` VALUES ('266', 'Kamuana', 'KEN0106', null, '239', '10', '98', '0', null);
INSERT INTO `loc_elements` VALUES ('267', 'Obinju', 'KEN0107', null, '239', '10', '99', '0', null);
INSERT INTO `loc_elements` VALUES ('268', 'Kyamogi', 'UGA0101', null, '241', '10', '100', '0', null);
INSERT INTO `loc_elements` VALUES ('269', 'Kibaire', 'UGA0102', null, '241', '10', '101', '0', null);
INSERT INTO `loc_elements` VALUES ('270', 'Nyakakonge', 'UGA0103', null, '241', '10', '102', '0', null);
INSERT INTO `loc_elements` VALUES ('271', 'Katikara', 'UGA0104', null, '241', '10', '103', '0', null);
INSERT INTO `loc_elements` VALUES ('272', 'Mparangasi', 'UGA0105', null, '241', '10', '104', '0', null);
INSERT INTO `loc_elements` VALUES ('273', 'Kiranga', 'UGA0106', null, '241', '10', '105', '0', null);
INSERT INTO `loc_elements` VALUES ('274', 'Kisinina', 'UGA0107', null, '241', '10', '106', '0', null);
INSERT INTO `loc_elements` VALUES ('275', 'Boheloi', 'TZA0101', null, '243', '10', '107', '0', null);
INSERT INTO `loc_elements` VALUES ('276', 'Mbuzii', 'TZA0102', null, '243', '10', '108', '0', null);
INSERT INTO `loc_elements` VALUES ('277', 'Kwang’wenda', 'TZA0103', null, '243', '10', '109', '0', null);
INSERT INTO `loc_elements` VALUES ('278', 'Gare', 'TZA0104', null, '243', '10', '110', '0', null);
INSERT INTO `loc_elements` VALUES ('279', 'Yamba', 'TZA0105', null, '243', '10', '111', '0', null);
INSERT INTO `loc_elements` VALUES ('280', 'Milungui', 'TZA0106', null, '243', '10', '112', '0', null);
INSERT INTO `loc_elements` VALUES ('281', 'Masange', 'TZA0107', null, '243', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('282', 'Tibtenga', 'BFA0101', null, '245', '10', '113', '0', null);
INSERT INTO `loc_elements` VALUES ('283', 'Ramdolla', 'BFA0102', null, '245', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('284', 'Doggoh', 'GHA0101', null, '246', '10', '114', '0', null);
INSERT INTO `loc_elements` VALUES ('285', 'Tongo', 'ML0101', null, '247', '10', '115', '0', null);
INSERT INTO `loc_elements` VALUES ('286', 'N\'gakoro', 'ML0102', null, '247', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('287', 'Kampa Zarama', 'NER0101', null, '248', '10', '116', '0', null);
INSERT INTO `loc_elements` VALUES ('288', 'Ngouye', 'SEN0101', null, '249', '10', '117', '0', null);
INSERT INTO `loc_elements` VALUES ('289', 'Toune Mosquee', 'SEN0102', null, '249', '10', '118', '0', null);
INSERT INTO `loc_elements` VALUES ('290', 'Jagannathpur', 'BGD0401', null, '250', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('291', 'Gabgachia', 'BGD0402', null, '250', '10', '119', '0', null);
INSERT INTO `loc_elements` VALUES ('292', 'Dumuria', 'BGD0403', null, '250', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('293', 'Chandipur', 'BGD0404', null, '250', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('294', 'Ajanthali', 'IND1701', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('295', 'Baraana', 'IND1702', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('296', 'Bastada', 'IND1703', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('297', 'Bjida Jaatan', 'IND1704', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('298', 'Chorpura', 'IND1705', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('299', 'Dadupur', 'IND1706', null, '251', '10', '120', '0', null);
INSERT INTO `loc_elements` VALUES ('300', 'Dhaha', 'IND1707', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('301', 'Gaanger', 'IND1708', null, '251', '10', '121', '0', null);
INSERT INTO `loc_elements` VALUES ('302', 'Ghide', 'IND1709', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('303', 'Kalsora', 'IND1710', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('304', 'Karkakhali', 'IND1711', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('305', 'Kartarpur', 'IND1712', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('306', 'Kutail', 'IND1713', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('307', 'Modi', 'IND1714', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('308', 'Musaipur', 'IND1715', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('309', 'Naryana', 'IND1716', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('310', 'Padhana', 'IND1717', null, '251', '10', '122', '0', null);
INSERT INTO `loc_elements` VALUES ('311', 'Pujaam', 'IND1718', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('312', 'Rawar', 'IND1719', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('313', 'Sambhali', 'IND1720', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('314', 'Sandir', 'IND1721', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('315', 'Shekhpursuhana', 'IND1722', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('316', 'Subri', 'IND1723', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('317', 'Unchasamana', 'IND1724', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('318', 'Veed Majara', 'IND1725', null, '251', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('319', 'Bhattha Dashi ', 'IN1601', null, '252', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('320', 'Raja Pakar', 'IN1602', null, '252', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('321', 'Mukundapur ', 'IN1603', null, '252', '10', '123', '0', null);
INSERT INTO `loc_elements` VALUES ('322', 'Bairiya  ', 'NPL0301', null, '253', '10', '124', '0', null);
INSERT INTO `loc_elements` VALUES ('323', 'Mahuwari', 'NPL0302', null, '253', '10', null, '0', null);
INSERT INTO `loc_elements` VALUES ('324', 'Rehara', 'NPL0303', null, '253', '10', '125', '0', null);
INSERT INTO `loc_elements` VALUES ('325', 'Ma', 'VNM0101', null, '259', '10', '126', '0', null);
INSERT INTO `loc_elements` VALUES ('326', 'My Loi', 'VNM0102', null, '259', '10', '127', '0', null);
INSERT INTO `loc_elements` VALUES ('327', 'Tra Hat ', 'VNM0103', null, '259', '10', '128', '0', null);
INSERT INTO `loc_elements` VALUES ('328', 'Phailom', 'LAO0101', null, '260', '10', '129', '0', null);
INSERT INTO `loc_elements` VALUES ('329', 'Ekxang', 'LAO0102', null, '260', '10', '130', '0', null);
INSERT INTO `loc_elements` VALUES ('330', 'Rohal Suong', 'KMH0101', null, '261', '10', '131', '0', null);
INSERT INTO `loc_elements` VALUES ('331', 'Trifinio region', null, null, null, '3', '805', '0', null);
INSERT INTO `loc_elements` VALUES ('332', 'Meta-Piedmonte', null, null, null, '3', '806', '0', null);
INSERT INTO `loc_elements` VALUES ('333', 'Meta-Altillanura', null, null, null, '3', '807', '0', null);
INSERT INTO `loc_elements` VALUES ('334', 'Cauca-Patia', null, null, null, '3', '808', '0', null);
INSERT INTO `loc_elements` VALUES ('335', 'Chorotega', null, null, null, '3', '809', '0', null);
INSERT INTO `loc_elements` VALUES ('336', 'Huetar Norte', null, null, null, '3', '810', '0', null);
INSERT INTO `loc_elements` VALUES ('337', 'Llanos-Piedmonte', null, null, null, '3', '145', '0', null);
INSERT INTO `loc_elements` VALUES ('338', 'Llanos-Altillanura', null, null, null, '3', '146', '0', null);
INSERT INTO `loc_elements` VALUES ('339', 'Patia', null, null, null, '3', '147', '0', null);
INSERT INTO `loc_elements` VALUES ('340', 'Plateau of Popayan', null, null, null, '3', '148', '0', null);
INSERT INTO `loc_elements` VALUES ('341', 'Chorotega', null, null, null, '3', '149', '0', null);
INSERT INTO `loc_elements` VALUES ('342', 'Huetar Norte', null, null, null, '3', '150', '0', null);
INSERT INTO `loc_elements` VALUES ('343', 'Paragominas', null, null, null, '4', '763', '0', null);
INSERT INTO `loc_elements` VALUES ('344', 'Paragominas', null, null, null, '4', '764', '0', null);
INSERT INTO `loc_elements` VALUES ('345', 'Paragominas', null, null, null, '4', '765', '0', null);
INSERT INTO `loc_elements` VALUES ('346', 'paragominas', null, null, null, '4', '766', '0', null);
INSERT INTO `loc_elements` VALUES ('347', 'Trifinio', null, null, null, '3', '768', '0', null);
INSERT INTO `loc_elements` VALUES ('348', 'NicaCentral', null, null, null, '3', '769', '0', null);
INSERT INTO `loc_elements` VALUES ('349', 'Trifinio', null, null, null, '3', '172', '0', null);
INSERT INTO `loc_elements` VALUES ('350', 'NicaCentral', null, null, null, '3', '173', '0', null);
INSERT INTO `loc_elements` VALUES ('351', 'Junin', null, null, null, '3', '174', '0', null);
INSERT INTO `loc_elements` VALUES ('352', 'Ondores', null, null, null, '4', '175', '0', null);
INSERT INTO `loc_elements` VALUES ('353', 'Upper Mantaro', null, null, null, '7', '176', '0', null);
INSERT INTO `loc_elements` VALUES ('354', 'Los Cerrillos Cauca', null, null, null, '3', '177', '0', null);
INSERT INTO `loc_elements` VALUES ('355', 'Cauca', null, null, null, '4', '795', '0', null);
INSERT INTO `loc_elements` VALUES ('356', 'Ucayali', null, null, null, '3', '796', '0', null);
INSERT INTO `loc_elements` VALUES ('357', 'Los Cerrillos Cauca', null, null, null, '3', '181', '0', null);
INSERT INTO `loc_elements` VALUES ('358', 'Puracé', null, null, null, '3', '182', '0', null);
INSERT INTO `loc_elements` VALUES ('359', 'Puno', null, null, null, '3', '183', '0', null);
INSERT INTO `loc_elements` VALUES ('360', 'Estelí, Nicaragua', null, null, null, '3', '184', '0', null);
INSERT INTO `loc_elements` VALUES ('361', 'Madriz, Nicaragua', null, null, null, '3', '185', '0', null);
INSERT INTO `loc_elements` VALUES ('362', 'Nueva Segovia, Nicaragua', null, null, null, '3', '186', '0', null);
INSERT INTO `loc_elements` VALUES ('363', 'Quiché, Guatemala', null, null, null, '3', '187', '0', null);
INSERT INTO `loc_elements` VALUES ('364', 'Sololá, Guatemala', null, null, null, '3', '188', '0', null);
INSERT INTO `loc_elements` VALUES ('365', 'Estelí, Nicaragua', null, null, null, '3', '189', '0', null);
INSERT INTO `loc_elements` VALUES ('366', 'Madriz, Nicaragua', null, null, null, '3', '190', '0', null);
INSERT INTO `loc_elements` VALUES ('367', 'Nueva Segovia, Nicaragua', null, null, null, '3', '191', '0', null);
INSERT INTO `loc_elements` VALUES ('368', 'Quiché, Guatemala', null, null, null, '3', '192', '0', null);
INSERT INTO `loc_elements` VALUES ('369', 'Sololá, Guatemala', null, null, null, '3', '193', '0', null);
INSERT INTO `loc_elements` VALUES ('370', 'Estelí, Nicaragua', null, null, null, '3', '826', '0', null);
INSERT INTO `loc_elements` VALUES ('371', 'Madriz, Nicaragua', null, null, null, '3', '827', '0', null);
INSERT INTO `loc_elements` VALUES ('372', 'Nueva Segovia, Nicaragua', null, null, null, '3', '828', '0', null);
INSERT INTO `loc_elements` VALUES ('373', 'Huehuetenango, Guatemala', null, null, null, '3', '829', '0', null);
INSERT INTO `loc_elements` VALUES ('374', 'Trifinio', null, null, null, '3', '770', '0', null);
INSERT INTO `loc_elements` VALUES ('375', 'NicaCentral', null, null, null, '3', '771', '0', null);
INSERT INTO `loc_elements` VALUES ('376', 'Tuma, La Dalia', null, null, null, '8', '201', '0', null);
INSERT INTO `loc_elements` VALUES ('377', 'Olopa, Trifinio-Guatemala', null, null, null, '8', '202', '0', null);
INSERT INTO `loc_elements` VALUES ('378', 'Santa Rita, Trifinio-Honduras', null, null, null, '8', '203', '0', null);
INSERT INTO `loc_elements` VALUES ('379', 'Cauca, Colombia', null, null, null, '8', '204', '0', null);
INSERT INTO `loc_elements` VALUES ('380', 'Cauca, Colombia', null, null, null, '8', '205', '0', null);
INSERT INTO `loc_elements` VALUES ('381', 'Junin', null, null, null, '3', '664', '0', null);
INSERT INTO `loc_elements` VALUES ('382', 'Upper Mantaro', null, null, null, '7', '665', '0', null);
INSERT INTO `loc_elements` VALUES ('383', 'Trifinio', null, null, null, '3', '209', '0', null);
INSERT INTO `loc_elements` VALUES ('384', 'NicaCentral', null, null, null, '3', '210', '0', null);
INSERT INTO `loc_elements` VALUES ('385', 'Son La', null, null, null, '3', '811', '0', null);
INSERT INTO `loc_elements` VALUES ('386', 'Guinayangan, Quezon Province, Philippines', null, null, null, '4', '776', '0', null);
INSERT INTO `loc_elements` VALUES ('387', 'Vietnam - Dien Bien, Dien Bien province', null, null, null, '4', '662', '0', null);
INSERT INTO `loc_elements` VALUES ('388', 'Cambodia - Kone Mom district, Ratanakiri province', null, null, null, '4', '663', '0', null);
INSERT INTO `loc_elements` VALUES ('389', 'Bihar, India', null, null, null, '3', '801', '0', null);
INSERT INTO `loc_elements` VALUES ('390', 'Githunguri', null, null, null, '4', '759', '0', null);
INSERT INTO `loc_elements` VALUES ('391', 'Kayatta', null, null, null, '4', '760', '0', null);
INSERT INTO `loc_elements` VALUES ('392', 'Kaptumo', null, null, null, '4', '761', '0', null);
INSERT INTO `loc_elements` VALUES ('393', 'Kutai Kartanegara', null, null, null, '4', '837', '0', null);
INSERT INTO `loc_elements` VALUES ('394', 'Nandi', null, null, null, '4', '762', '0', null);
INSERT INTO `loc_elements` VALUES ('395', 'Hanoi', null, null, null, '3', '812', '0', null);
INSERT INTO `loc_elements` VALUES ('396', 'Yen Binh', null, null, null, '4', '803', '0', null);
INSERT INTO `loc_elements` VALUES ('397', 'Ky Anh', null, null, null, '4', '804', '0', null);
INSERT INTO `loc_elements` VALUES ('398', 'Black Watershed 4, ICRISAT-Patancheru', null, null, null, '6', '774', '0', null);
INSERT INTO `loc_elements` VALUES ('399', 'ICRISAT-Patancheru Rice Field', null, null, null, '6', '775', '0', null);
INSERT INTO `loc_elements` VALUES ('400', 'Nioro du Rip', null, null, null, '4', '833', '0', null);
INSERT INTO `loc_elements` VALUES ('401', 'Cinzana', null, null, null, '4', '817', '0', null);
INSERT INTO `loc_elements` VALUES ('402', 'Kaffrine', null, null, null, '4', '818', '0', null);
INSERT INTO `loc_elements` VALUES ('403', 'Lawra', null, null, null, '4', '819', '0', null);
INSERT INTO `loc_elements` VALUES ('404', 'Jirapa', null, null, null, '4', '820', '0', null);
INSERT INTO `loc_elements` VALUES ('405', 'Bougouni', null, null, null, '4', '821', '0', null);
INSERT INTO `loc_elements` VALUES ('406', 'Sikasso Region', null, null, null, '3', '834', '0', null);
INSERT INTO `loc_elements` VALUES ('407', 'Sukumba', null, null, null, '8', '835', '0', null);
INSERT INTO `loc_elements` VALUES ('408', 'Paragominas', null, null, null, '4', '767', '0', null);
INSERT INTO `loc_elements` VALUES ('409', 'Rakai, Uganda', null, null, null, '4', '701', '0', null);
INSERT INTO `loc_elements` VALUES ('410', 'Lushoto, Tanzania', null, null, null, '4', '702', '0', null);
INSERT INTO `loc_elements` VALUES ('411', 'Nandom', null, null, null, '4', '822', '0', null);
INSERT INTO `loc_elements` VALUES ('412', 'Bambey', null, null, null, '4', '823', '0', null);
INSERT INTO `loc_elements` VALUES ('413', 'Linguère', null, null, null, '4', '824', '0', null);
INSERT INTO `loc_elements` VALUES ('414', 'Lushoto, Tanzania', null, null, null, '4', '703', '0', null);
INSERT INTO `loc_elements` VALUES ('415', 'Rakai, Uganda', null, null, null, '4', '704', '0', null);
INSERT INTO `loc_elements` VALUES ('416', 'Lushoto , Tanzania', null, null, null, '4', '705', '0', null);
INSERT INTO `loc_elements` VALUES ('417', 'Rakai, Uganda', null, null, null, '4', '706', '0', null);
INSERT INTO `loc_elements` VALUES ('418', 'Rakai, Uganda', null, null, null, '4', '707', '0', null);
INSERT INTO `loc_elements` VALUES ('419', 'Lushoto, Tanzania', null, null, null, '4', '708', '0', null);
INSERT INTO `loc_elements` VALUES ('420', 'Lushoto, Tanzania', null, null, null, '4', '709', '0', null);
INSERT INTO `loc_elements` VALUES ('421', 'Rakai, Uganda', null, null, null, '4', '710', '0', null);
INSERT INTO `loc_elements` VALUES ('422', 'Punjab', null, null, null, '3', '780', '0', null);
INSERT INTO `loc_elements` VALUES ('423', 'Ludhiana', null, null, null, '4', '781', '0', null);
INSERT INTO `loc_elements` VALUES ('424', 'Patiala', null, null, null, '4', '782', '0', null);
INSERT INTO `loc_elements` VALUES ('425', 'Haryana', null, null, null, '3', '783', '0', null);
INSERT INTO `loc_elements` VALUES ('426', 'Karnal', null, null, null, '4', '784', '0', null);
INSERT INTO `loc_elements` VALUES ('427', 'Bihar', null, null, null, '3', '785', '0', null);
INSERT INTO `loc_elements` VALUES ('428', 'Vaishali', null, null, null, '4', '786', '0', null);
INSERT INTO `loc_elements` VALUES ('429', 'Samastipur', null, null, null, '4', '787', '0', null);
INSERT INTO `loc_elements` VALUES ('430', 'Andhra Pradesh', null, null, null, '3', '788', '0', null);
INSERT INTO `loc_elements` VALUES ('431', 'Anantpur', null, null, null, '4', '789', '0', null);
INSERT INTO `loc_elements` VALUES ('432', 'Odisha', null, null, null, '3', '790', '0', null);
INSERT INTO `loc_elements` VALUES ('433', 'Puri', null, null, null, '4', '791', '0', null);
INSERT INTO `loc_elements` VALUES ('434', 'Bhadrak', null, null, null, '4', '792', '0', null);
INSERT INTO `loc_elements` VALUES ('435', 'Karnataka', null, null, null, '3', '793', '0', null);
INSERT INTO `loc_elements` VALUES ('436', 'Khulna', null, null, null, '4', '794', '0', null);
INSERT INTO `loc_elements` VALUES ('437', 'Luwero Uganda', null, null, null, '4', '711', '0', null);
INSERT INTO `loc_elements` VALUES ('438', 'Mbale Uganda', null, null, null, '4', '712', '0', null);
INSERT INTO `loc_elements` VALUES ('439', 'Lushoto, Tanzania', null, null, null, '4', '713', '0', null);
INSERT INTO `loc_elements` VALUES ('440', 'Rakai, Uganda', null, null, null, '4', '714', '0', null);
INSERT INTO `loc_elements` VALUES ('441', 'Bako', null, null, null, '8', '755', '0', null);
INSERT INTO `loc_elements` VALUES ('442', 'Melkassa', null, null, null, '8', '756', '0', null);
INSERT INTO `loc_elements` VALUES ('443', 'Gishwati', null, null, null, '8', '757', '0', null);
INSERT INTO `loc_elements` VALUES ('444', 'Bugesera', null, null, null, '3', '758', '0', null);
INSERT INTO `loc_elements` VALUES ('445', 'Rakai, Uganda', null, null, null, '4', '715', '0', null);
INSERT INTO `loc_elements` VALUES ('446', 'Lushoto, Tanzania', null, null, null, '4', '716', '0', null);
INSERT INTO `loc_elements` VALUES ('447', 'Lushoto , Tanzania', null, null, null, '4', '717', '0', null);
INSERT INTO `loc_elements` VALUES ('448', 'Rakai, Uganda', null, null, null, '4', '718', '0', null);
INSERT INTO `loc_elements` VALUES ('449', 'Pauri Garhwal', null, null, null, '4', '361', '0', null);
INSERT INTO `loc_elements` VALUES ('450', 'Rudra Prayag', null, null, null, '4', '362', '0', null);
INSERT INTO `loc_elements` VALUES ('451', 'Tehri Garhwal', null, null, null, '4', '363', '0', null);
INSERT INTO `loc_elements` VALUES ('452', 'Mandi', null, null, null, '4', '364', '0', null);
INSERT INTO `loc_elements` VALUES ('453', 'Sirmaur', null, null, null, '4', '365', '0', null);
INSERT INTO `loc_elements` VALUES ('454', 'Ladakh', null, null, null, '4', '366', '0', null);
INSERT INTO `loc_elements` VALUES ('455', 'Barmer', null, null, null, '4', '367', '0', null);
INSERT INTO `loc_elements` VALUES ('456', 'Jaisalmer', null, null, null, '4', '368', '0', null);
INSERT INTO `loc_elements` VALUES ('457', 'Jodhpur', null, null, null, '4', '369', '0', null);
INSERT INTO `loc_elements` VALUES ('458', 'Shahdol', null, null, null, '4', '370', '0', null);
INSERT INTO `loc_elements` VALUES ('459', 'Umaria', null, null, null, '4', '371', '0', null);
INSERT INTO `loc_elements` VALUES ('460', 'Koriya', null, null, null, '4', '372', '0', null);
INSERT INTO `loc_elements` VALUES ('461', 'Balrampur', null, null, null, '4', '373', '0', null);
INSERT INTO `loc_elements` VALUES ('462', 'Golaghat', null, null, null, '4', '374', '0', null);
INSERT INTO `loc_elements` VALUES ('463', 'Jorhat', null, null, null, '4', '375', '0', null);
INSERT INTO `loc_elements` VALUES ('464', 'Karbi Anglong', null, null, null, '4', '376', '0', null);
INSERT INTO `loc_elements` VALUES ('465', 'Tinsukia', null, null, null, '4', '377', '0', null);
INSERT INTO `loc_elements` VALUES ('466', 'Longleng', null, null, null, '4', '378', '0', null);
INSERT INTO `loc_elements` VALUES ('467', 'Peren', null, null, null, '4', '379', '0', null);
INSERT INTO `loc_elements` VALUES ('468', 'Mokokchung', null, null, null, '4', '380', '0', null);
INSERT INTO `loc_elements` VALUES ('469', 'Phek', null, null, null, '4', '381', '0', null);
INSERT INTO `loc_elements` VALUES ('470', 'Almora', null, null, null, '4', '382', '0', null);
INSERT INTO `loc_elements` VALUES ('471', 'Tanga/Arusha', null, null, null, '3', '719', '0', null);
INSERT INTO `loc_elements` VALUES ('472', 'Lushoto', null, null, null, '4', '720', '0', null);
INSERT INTO `loc_elements` VALUES ('473', 'Lushoto Tanzania', null, null, null, '4', '721', '0', null);
INSERT INTO `loc_elements` VALUES ('474', 'Rakai, Uganda', null, null, null, '4', '722', '0', null);
INSERT INTO `loc_elements` VALUES ('475', 'Lushoto, Tanzania', null, null, null, '4', '723', '0', null);
INSERT INTO `loc_elements` VALUES ('476', 'Cauca', 'CO01', null, '53', '11', '390', '0', null);
INSERT INTO `loc_elements` VALUES ('477', 'Maharashtra', null, null, null, '3', '749', '0', null);
INSERT INTO `loc_elements` VALUES ('478', 'Haryana', null, null, null, '3', '750', '0', null);
INSERT INTO `loc_elements` VALUES ('479', 'Madhya Pradesh', null, null, null, '3', '751', '0', null);
INSERT INTO `loc_elements` VALUES ('480', 'Bihar', null, null, null, '3', '752', '0', null);
INSERT INTO `loc_elements` VALUES ('481', 'Odisha, India', null, null, null, '3', '802', '0', null);
INSERT INTO `loc_elements` VALUES ('482', 'Luwero, Uganda', null, null, null, '4', '724', '0', null);
INSERT INTO `loc_elements` VALUES ('483', 'Kilolo, Tanzania', null, null, null, '4', '725', '0', null);
INSERT INTO `loc_elements` VALUES ('484', 'Bihar', null, null, null, '3', '747', '0', null);
INSERT INTO `loc_elements` VALUES ('485', 'Haryana', null, null, null, '3', '748', '0', null);
INSERT INTO `loc_elements` VALUES ('486', 'Chiquimula (Trifinio)', null, null, null, '3', '666', '0', null);
INSERT INTO `loc_elements` VALUES ('487', 'Phailom', 'LAO0150', null, null, '10', '437', '0', null);
INSERT INTO `loc_elements` VALUES ('488', 'Phongsali', null, null, null, '3', '488', '0', null);
INSERT INTO `loc_elements` VALUES ('489', 'Koutiala', null, null, null, '4', '825', '0', null);
INSERT INTO `loc_elements` VALUES ('490', 'Colombia: Tolima ', null, null, null, '4', '744', '0', null);
INSERT INTO `loc_elements` VALUES ('491', 'Perú: Jaen, ', null, null, null, '4', '745', '0', null);
INSERT INTO `loc_elements` VALUES ('492', 'Nicaragua: Malacatoya, Sebaco, Matagalpa y San Luis', null, null, null, '4', '746', '0', null);
INSERT INTO `loc_elements` VALUES ('493', 'Natagaima, Tolima', null, null, null, '4', '777', '0', null);
INSERT INTO `loc_elements` VALUES ('494', 'Nghe An', null, null, null, '3', '813', '0', null);
INSERT INTO `loc_elements` VALUES ('495', 'Dak Lak', null, null, null, '3', '814', '0', null);
INSERT INTO `loc_elements` VALUES ('496', 'Dong Nai', null, null, null, '3', '815', '0', null);
INSERT INTO `loc_elements` VALUES ('497', 'An Giang', null, null, null, '3', '816', '0', null);
INSERT INTO `loc_elements` VALUES ('498', 'Danli, El Paraiso, Honduras', null, null, null, '8', '778', '0', null);
INSERT INTO `loc_elements` VALUES ('499', 'Morocelí, El Paraíso, Honduras', null, null, null, '8', '779', '0', null);
INSERT INTO `loc_elements` VALUES ('500', 'Muzaffarpur', null, null, null, '4', '728', '0', null);
INSERT INTO `loc_elements` VALUES ('501', 'Sirajganj', null, null, null, '4', '729', '0', null);
INSERT INTO `loc_elements` VALUES ('502', 'Nwoya, Uganda', null, null, null, '4', '726', '0', null);
INSERT INTO `loc_elements` VALUES ('503', 'Paragominas', null, null, null, '4', '654', '0', null);
INSERT INTO `loc_elements` VALUES ('504', 'Gimbi ', null, null, null, '4', '676', '0', null);
INSERT INTO `loc_elements` VALUES ('505', 'Digga', null, null, null, '4', '677', '0', null);
INSERT INTO `loc_elements` VALUES ('506', 'Mbale, Uganda', null, null, null, '4', '727', '0', null);
INSERT INTO `loc_elements` VALUES ('507', 'Darbhanga', null, null, null, '4', '730', '0', null);
INSERT INTO `loc_elements` VALUES ('508', 'Samastipur', null, null, null, '4', '731', '0', null);
INSERT INTO `loc_elements` VALUES ('509', 'municipio de Gracias', null, null, null, '4', '754', '0', null);
INSERT INTO `loc_elements` VALUES ('510', 'Mahakam Hulu', null, null, null, '4', '836', '0', null);
INSERT INTO `loc_elements` VALUES ('511', 'Aland Islands', 'AX', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('512', 'Bouvet Island', 'BV', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('513', 'Brunei Darussalam', 'BN', '96', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('514', 'Hong Kong, Special Administrative Region of China', 'HK', '344', '707', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('515', 'Macao, Special Administrative Region of China', 'MO', '446', '707', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('516', 'Congo (Brazzaville)', 'CG', '178', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('517', 'Congo, Democratic Republic of the', 'CD', '180', '700', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('518', 'Côte d\'Ivoire', 'CI', '384', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('519', 'Falkland Islands (Malvinas)', 'FK', '238', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('520', 'French Guiana', 'GF', '254', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('521', 'French Southern Territories', 'TF', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('522', 'Guadeloupe', 'GP', '312', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('523', 'Guernsey', 'GG', '831', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('524', 'Heard Island and Mcdonald Islands', 'HM', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('525', 'Holy See (Vatican City State)', 'VA', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('526', 'Iran, Islamic Republic of', 'IR', '364', '3', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('527', 'Korea, Democratic People\'s Republic of', 'KP', '408', '708', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('528', 'Korea, Republic of', 'KR', '410', '708', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('529', 'Lao PDR', 'LA', '418', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('530', 'Latvia', 'LV', '428', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('531', 'Macedonia, Republic of', 'MK', '807', '712', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('532', 'Martinique', 'MQ', '474', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('533', 'Micronesia, Federated States of', 'FM', '583', '715', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('534', 'Myanmar', 'MM', '104', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('535', 'Norfolk Island', 'NF', '574', '714', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('536', 'Palestinian Territory, Occupied', 'PS', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('537', 'Pitcairn', 'PN', '612', '717', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('538', 'Réunion', 'RE', '638', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('539', 'Russian Federation', 'RU', '643', '710', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('540', 'Saint-Barthélemy', 'BL', '652', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('541', 'Saint-Martin (French part)', 'MF', '663', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('542', 'Saint Vincent and Grenadines', 'VC', '670', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('543', 'South Georgia and the South Sandwich Islands', 'GS', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('544', 'South Sudan', 'SS', '728', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('545', 'Suriname *', 'SR', '740', '705', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('546', 'Svalbard and Jan Mayen Islands', 'SJ', '744', '711', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('547', 'Syrian Arab Republic (Syria)', 'SY', '760', '2', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('548', 'Taiwan, Republic of China', 'TW', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('549', 'Tanzania *, United Republic of', 'TZ', '834', '1', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('550', 'Timor-Leste', 'TL', '626', '5', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('551', 'United States Minor Outlying Islands', 'UM', null, '6', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('552', 'Virgin Islands, US', 'VI', '850', '703', '2', null, '0', null);
INSERT INTO `loc_elements` VALUES ('553', 'Wallis and Futuna Islands', 'WF', '876', '717', '2', null, '0', null);
