INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('1', 'Bioaprendiz', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('2', 'Distance course', '1');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('3', 'Visitor/Individual training', '1');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('4', 'Visiting researcher/Ms student', '1');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('5', 'Multi-stakeholder platform', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('6', 'Open house for schools', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('7', 'Visiting researcher/Phd student', '1');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('8', 'Seminar', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('9', 'Specialized training course', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('10', 'Visiting researcher/Undergraduate student', '1');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('11', 'Visits from universities', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('12', 'Workshop', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('13', 'Distance course', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('14', 'Field trip', '1');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('15', 'Field trip', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('16', 'Train the trainers', '1');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('17', 'Train the trainers', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('18', 'Conference', '2');
INSERT INTO `capacity_development_types` (`id`, `name`, `category`) VALUES ('19', 'Sabatical year', '1');
