UPDATE `institutions` SET `name`='Agriculture & Co-operation Department' WHERE `id`='376';
UPDATE `institutions` SET `name`='Centro Internacional de Mejoramiento de Maíz y Trigo' WHERE `id`='50';
UPDATE `institutions` SET `name`='Centro Internacional de Mejoramiento de Maíz y Trigo' WHERE `id`='650';
UPDATE `institutions` SET `name`='Centro Internacional de Mejoramiento de Maíz y Trigo' WHERE `id`='680';
UPDATE `institutions` SET `name`='Centro Internacional de Mejoramiento de Maíz y Trigo' WHERE `id`='1178';
INSERT INTO `institutions` (`id`, `name`, `acronym`, `city`, `website_link`, `institution_type_id`, `country_id`, `headquarter`) VALUES ('1278', 'Centro Internacional de Agricultura Tropical', 'CIAT', 'Managua', 'https://ciat.cgiar.org/', '3', '160', '46');
UPDATE `institutions` SET `city`='Los Baños' WHERE `id`='1222';
UPDATE `institutions` SET `city`='Los Baños' WHERE `id`='5';
UPDATE `institutions` SET `city`='Los Baños' WHERE `id`='1143';
UPDATE `institutions` SET `city`='Los Baños' WHERE `id`='1220';
UPDATE `institutions` SET `acronym`='BIOVERSITY' WHERE `id`='49';
UPDATE `institutions` SET `acronym`='BIOVERSITY' WHERE `id`='1215';
UPDATE `institutions` SET `acronym`='BIOVERSITY' WHERE `id`='1220';
UPDATE `institutions` SET `name`="Joint Graduate School of Energy and Environment, King Mongkuk\'s University of Technology Thonburi" WHERE `id`='1231';
UPDATE `institutions` SET `headquarter`='325' WHERE `id`='752';
UPDATE `institutions` SET `headquarter`='325' WHERE `id`='754';
UPDATE `institutions` SET `headquarter`='325' WHERE `id`='1260';
UPDATE `institutions` SET `headquarter`='99' WHERE `id`='1099';
UPDATE `institutions` SET `headquarter`='99' WHERE `id`='1176';
UPDATE `institutions` SET `website_link`='http://www.africarice.org/' WHERE `id`='52';
UPDATE `institutions` SET `website_link`='http://www.icarda.cgiar.org/' WHERE `id`='51';
INSERT INTO `institutions` (`id`, `name`, `acronym`, `city`, `website_link`, `institution_type_id`, `country_id`) VALUES ('1279', 'International Center for Agricultural Research in the Dry Areas', 'ICARDA', 'Beirut', 'http://www.icarda.cgiar.org/', '3', '125');
UPDATE `institutions` SET `headquarter`='1279' WHERE `id`='51';
UPDATE `institutions` SET `city`='Ho Chi Minh City' WHERE `id`='1213';
UPDATE `institutions` SET `city`='Ho Chi Minh' WHERE `id`='485';
UPDATE `institutions` SET `city`='Ho Chi Minh' WHERE `id`='1213';
UPDATE `institutions` SET `city`='Ho Chi Minh' WHERE `id`='1263';
UPDATE `institutions` SET `city`='Vientiane' WHERE `id`='1116';
UPDATE `institutions` SET `name`='Wageningen University and Research Centre', `website_link`='http://www.wur.nl/en.htm' WHERE `id`='1';
UPDATE `institutions` SET `website_link`='http://www.ari-mikocheni.org/' WHERE `id`='2';
UPDATE `institutions` SET `website_link`='http://www.rab.gov.rw/home/' WHERE `id`='6';
UPDATE `institutions` SET `website_link`='http://www.naro.go.ug/' WHERE `id`='7';
UPDATE `institutions` SET `website_link`='http://www.isra.sn/' WHERE `id`='10';
UPDATE `institutions` SET `website_link`='http://www.saed.sn/' WHERE `id`='11';
UPDATE `institutions` SET `name`='Institut d’Economie Rurale', `website_link`='http://www.ier.gouv.ml/' WHERE `id`='12';
UPDATE `institutions` SET `website_link`='http://www.on-mali.org/joomla/index.php/' WHERE `id`='13';
UPDATE `institutions` SET `acronym`='UNL', `website_link`='http://www.unl.edu/' WHERE `id`='14';
UPDATE `institutions` SET `website_link`='http://www.ebi.gov.et/' WHERE `id`='15';
UPDATE `institutions` SET `website_link`='http://www.nari.org.pg/' WHERE `id`='16';
UPDATE `institutions` SET `website_link`='http://www.icar.org.in/' WHERE `id`='17';
UPDATE `institutions` SET `acronym`='ASOCUCH', `website_link`='http://www.asocuch.com.gt/' WHERE `id`='19';
UPDATE `institutions` SET `acronym`='CORRB' WHERE `id`='30';
UPDATE `institutions` SET `website_link`='http://www.narl.go.ug/' WHERE `id`='33';
UPDATE `institutions` SET `acronym`='GC' WHERE `id`='65';
UPDATE `institutions` SET `website_link`='http://www.cifor.org/' WHERE `id`='115';
UPDATE `institutions` SET `website_link`='https://www.minagricultura.gov.co' WHERE `id`='126';
UPDATE `institutions` SET `website_link`='http://www.fedearroz.com.co/' WHERE `id`='140';
UPDATE `institutions` SET `website_link`='http://www.insah.org/' WHERE `id`='196';
UPDATE `institutions` SET `website_link`='http://inran.refer.ne/' WHERE `id`='249';
UPDATE `institutions` SET `website_link`='http://www.planvivo.org/' WHERE `id`='288';
UPDATE `institutions` SET `website_link`='http://www.niapp.org.vn/' WHERE `id`='381';
UPDATE `institutions` SET `website_link`='https://www.catie.ac.cr/' WHERE `id`='455';
UPDATE `institutions` SET `website_link`='http://fes.org.in/' WHERE `id`='463';
UPDATE `institutions` SET `website_link`='http://www.jkuat.ac.ke/' WHERE `id`='469';
UPDATE `institutions` SET `website_link`='http://www.teriuniversity.ac.in/' WHERE `id`='493';
UPDATE `institutions` SET `website_link`='http://www.cccs.udsm.ac.tz/' WHERE `id`='519';
UPDATE `institutions` SET `website_link`='http://africasoils.net/' WHERE `id`='528';
UPDATE `institutions` SET `website_link`='http://www.fao.org/nr/cgrfa/' WHERE `id`='584';
UPDATE `institutions` SET `website_link`='http://globalcanopy.org/' WHERE `id`='605';
UPDATE `institutions` SET `website_link`='http://www.palmira.unal.edu.co/' WHERE `id`='609';
UPDATE `institutions` SET `website_link`='http://www.igac.gov.co/' WHERE `id`='610';
UPDATE `institutions` SET `website_link`='http://www.javeriana.edu.co/' WHERE `id`='611';
UPDATE `institutions` SET `website_link`='http://www.purdue.edu/' WHERE `id`='612';
UPDATE `institutions` SET `website_link`='http://avrdc.org/' WHERE `id`='618';
UPDATE `institutions` SET `website_link`='http://www.science.az/' WHERE `id`='617';
UPDATE `institutions` SET `website_link`='http://www.slari.gov.sl/' WHERE `id`='624';
UPDATE `institutions` SET `website_link`='https://www.heifer.org/' WHERE `id`='629';
UPDATE `institutions` SET `website_link`='http://www.agriculture.go.ug/' WHERE `id`='633';
UPDATE `institutions` SET `website_link`='http://english.xtbg.cas.cn/' WHERE `id`='642';
UPDATE `institutions` SET `website_link`='http://www.ouat.ac.in/' WHERE `id`='649';
UPDATE `institutions` SET `website_link`='http://www.lbda.co.ke/' WHERE `id`='655';
UPDATE `institutions` SET `website_link`='http://www.ipb.ac.id/' WHERE `id`='657';
UPDATE `institutions` SET `website_link`='http://kkp.academia.edu/' WHERE `id`='658';
UPDATE `institutions` SET `website_link`='http://www.bmz.de/' WHERE `id`='660';
UPDATE `institutions` SET `website_link`='https://www.regjeringen.no' WHERE `id`='661';
UPDATE `institutions` SET `website_link`='http://www.agriculture.go.tz/' WHERE `id`='677';
UPDATE `institutions` SET `website_link`='http://www.uz.ac.zw/' WHERE `id`='678';
UPDATE `institutions` SET `website_link`='https://www.futminna.edu.ng/' WHERE `id`='679';
UPDATE `institutions` SET `website_link`='http://www.bausabour.ac.in/' WHERE `id`='681';
UPDATE `institutions` SET `website_link`='http://dmr.res.in/' WHERE `id`='684';
UPDATE `institutions` SET `website_link`='http://www.cssri.org/' WHERE `id`='685';
UPDATE `institutions` SET `website_link`='http://www.tpri.or.tz/' WHERE `id`='690';
UPDATE `institutions` SET `website_link`='http://ableindia.in/' WHERE `id`='692';
UPDATE `institutions` SET `website_link`='https://www.bitmesra.ac.in/' WHERE `id`='694';
UPDATE `institutions` SET `website_link`='http://tiim.uz/' WHERE `id`='700';
UPDATE `institutions` SET `website_link`='http://www.hcmuaf.edu.vn/' WHERE `id`='703';
UPDATE `institutions` SET `website_link`='http://www.unesco-ihe.org/' WHERE `id`='704';
UPDATE `institutions` SET `website_link`='http://www.ynau.edu.cn/' WHERE `id`='705';
UPDATE `institutions` SET `website_link`='http://www.gau.ac.ir/' WHERE `id`='719';
UPDATE `institutions` SET `website_link`='http://www.agriculture.gouv.sn/' WHERE `id`='720';
UPDATE `institutions` SET `website_link`='http://www.via.ac.in/' WHERE `id`='726';
UPDATE `institutions` SET `website_link`='http://www.virginia.edu/' WHERE `id`='729';
UPDATE `institutions` SET `website_link`='http://www.cedac.org.kh/' WHERE `id`='731';
UPDATE `institutions` SET `website_link`='http://www.ed.ac.uk/' WHERE `id`='733';
UPDATE `institutions` SET `website_link`='http://www.pafasenegal.org/' WHERE `id`='741';
UPDATE `institutions` SET `website_link`='http://www.pafasp.org/' WHERE `id`='742';
UPDATE `institutions` SET `website_link`='http://www.roppa-afrique.org/' WHERE `id`='744';
UPDATE `institutions` SET `website_link`='http://www.cifor.org/' WHERE `id`='746';
UPDATE `institutions` SET `website_link`='http://www.coady.stfx.ca/' WHERE `id`='751';
UPDATE `institutions` SET `website_link`='http://www.unanleon.edu.ni/' WHERE `id`='756';
UPDATE `institutions` SET `website_link`='http://www.ucasanramon.com/' WHERE `id`='761';
UPDATE `institutions` SET `website_link`='http://www.unmsm.edu.pe/' WHERE `id`='772';
UPDATE `institutions` SET `website_link`='http://www.cifor.org/' WHERE `id`='775';
UPDATE `institutions` SET `website_link`='http://acatpa.blogspot.com.co/' WHERE `id`='776';
UPDATE `institutions` SET `website_link`='http://www.minam.gob.pe/' WHERE `id`='777';
UPDATE `institutions` SET `website_link`='http://minagri.gob.pe/' WHERE `id`='779';
UPDATE `institutions` SET `website_link`='http://www.inrat.agrinet.tn/' WHERE `id`='784';
UPDATE `institutions` SET `website_link`='http://www.bahri.edu.sd/' WHERE `id`='786';
UPDATE `institutions` SET `website_link`='http://www.arcsudan.sd/' WHERE `id`='787';
UPDATE `institutions` SET `website_link`='http://www.arari.gov.et/' WHERE `id`='796';
UPDATE `institutions` SET `website_link`='http://www.acclimatise.uk.com/' WHERE `id`='799';
UPDATE `institutions` SET `website_link`='http://www.cea.fr/' WHERE `id`='804';
UPDATE `institutions` SET `website_link`='http://www.lsce.ipsl.fr/' WHERE `id`='805';
UPDATE `institutions` SET `website_link`='http://www.ipsl.fr/' WHERE `id`='806';
UPDATE `institutions` SET `website_link`='http://www.eaap.org/' WHERE `id`='807';
UPDATE `institutions` SET `website_link`='https://www.wbf.admin.ch' WHERE `id`='808';
UPDATE `institutions` SET `website_link`='https://www.agroscope.admin.ch' WHERE `id`='809';
UPDATE `institutions` SET `website_link`='http://sziu.hu/' WHERE `id`='810';
UPDATE `institutions` SET `website_link`='https://www.teagasc.ie/' WHERE `id`='811';
UPDATE `institutions` SET `website_link`='http://www.ufrgs.br/' WHERE `id`='812';
UPDATE `institutions` SET `website_link`='http://www.upm.es/' WHERE `id`='813';
UPDATE `institutions` SET `website_link`='http://www.unimelb.edu.au/' WHERE `id`='817';
UPDATE `institutions` SET `website_link`='http://unram.ac.id/' WHERE `id`='818';
UPDATE `institutions` SET `website_link`='http://www.npc.gov.np/' WHERE `id`='825';
UPDATE `institutions` SET `website_link`='http://www.nicra-icar.in/' WHERE `id`='826';
UPDATE `institutions` SET `website_link`='http://www.cegisbd.com/' WHERE `id`='828';
UPDATE `institutions` SET `website_link`='http://ysef.gov.np/' WHERE `id`='831';
UPDATE `institutions` SET `website_link`='http://www.modmr.gov.bd/' WHERE `id`='835';
UPDATE `institutions` SET `website_link`='http://www.un-spider.org/' WHERE `id`='836';
UPDATE `institutions` SET `website_link`='http://www.senamhi.gob.bo/' WHERE `id`='850';
UPDATE `institutions` SET `website_link`='http://beta.www.hull.ac.uk/' WHERE `id`='857';
UPDATE `institutions` SET `website_link`='https://www.yesbank.in' WHERE `id`='863';
UPDATE `institutions` SET `website_link`='http://www.cambodiariceexporters.org' WHERE `id`='864';
UPDATE `institutions` SET `website_link`='http://www.oxfam.org.uk/' WHERE `id`='867';
UPDATE `institutions` SET `website_link`='https://www.uni-bonn.de/' WHERE `id`='868';
UPDATE `institutions` SET `website_link`='http://www.groots.org/members/kenya.htm' WHERE `id`='870';
UPDATE `institutions` SET `website_link`='http://www.uni-kassel.de/uni/' WHERE `id`='871';
UPDATE `institutions` SET `website_link`='http://www.minagri.gob.pe/' WHERE `id`='874';
UPDATE `institutions` SET `website_link`='http://www.acicafoc.org' WHERE `id`='875';
UPDATE `institutions` SET `website_link`='http://www.sag.gob.hn/' WHERE `id`='876';
UPDATE `institutions` SET `website_link`='http://www.nuigalway.ie/' WHERE `id`='879';
UPDATE `institutions` SET `website_link`='http://www.au.dk/' WHERE `id`='1040';
UPDATE `institutions` SET `website_link`='http://www5.usp.br/' WHERE `id`='1041';
UPDATE `institutions` SET `website_link`='http://www.cifor.org/' WHERE `id`='1042';
UPDATE `institutions` SET `website_link`='http://www.rainforest-alliance.org/' WHERE `id`='1043';
UPDATE `institutions` SET `website_link`='http://www.smn.gob.hn/' WHERE `id`='1049';
UPDATE `institutions` SET `website_link`='http://medellin.unal.edu.co/' WHERE `id`='1051';
UPDATE `institutions` SET `website_link`='http://www.uvm.edu/' WHERE `id`='1053';
UPDATE `institutions` SET `website_link`='http://www.cedeco.or.cr/' WHERE `id`='1054';
UPDATE `institutions` SET `website_link`='http://www.museu-goeldi.br/' WHERE `id`='1056';
UPDATE `institutions` SET `website_link`='http://www.arcosnetwork.org/' WHERE `id`='1062';
UPDATE `institutions` SET `website_link`='http://www.iisd.org/' WHERE `id`='1063';
UPDATE `institutions` SET `website_link`='https://esoko.com/' WHERE `id`='1061';
UPDATE `institutions` SET `website_link`='http://www.lse.ac.uk/' WHERE `id`='1064';
UPDATE `institutions` SET `website_link`='http://www.pep-net.org/' WHERE `id`='1068';
UPDATE `institutions` SET `website_link`='http://www.jaduniv.edu.in/' WHERE `id`='1080';
UPDATE `institutions` SET `website_link`='http://iirr.org/' WHERE `id`='1084';
UPDATE `institutions` SET `website_link`='http://www.iwmbd.org/' WHERE `id`='1091';
UPDATE `institutions` SET `website_link`='http://monre.gov.la/' WHERE `id`='1093';
UPDATE `institutions` SET `website_link`='http://www.barc.gov.bd/' WHERE `id`='1096';
UPDATE `institutions` SET `website_link`='http://www.brac.net/' WHERE `id`='1097';
UPDATE `institutions` SET `website_link`='http://www.baif.org.in/' WHERE `id`='1098';
UPDATE `institutions` SET `website_link`='http://practicalaction.org/' WHERE `id`='1100';
UPDATE `institutions` SET `website_link`='https://www.vetswithoutborders.ca/' WHERE `id`='1102';
UPDATE `institutions` SET `website_link`='http://cenpher.hsph.edu.vn/' WHERE `id`='1103';
UPDATE `institutions` SET `website_link`='http://www.nuol.edu.la/' WHERE `id`='1105';
UPDATE `institutions` SET `website_link`='http://xishuangbanna.ugo.cn/' WHERE `id`='1110';
UPDATE `institutions` SET `website_link`='http://www.moc.gov.kh/' WHERE `id`='1111';
UPDATE `institutions` SET `website_link`='http://www.cicp.org.kh/' WHERE `id`='1112';
UPDATE `institutions` SET `website_link`='http://www.swissre.com/' WHERE `id`='1117';
UPDATE `institutions` SET `website_link`='https://www.luke.fi/' WHERE `id`='1118';
UPDATE `institutions` SET `website_link`='http://daemeter.org/' WHERE `id`='1119';
UPDATE `institutions` SET `website_link`='http://www.aidenvironment.org/' WHERE `id`='1120';
UPDATE `institutions` SET `website_link`='http://ipsard.gov.vn/' WHERE `id`='1123';
UPDATE `institutions` SET `website_link`='http://www.farmradio.org/' WHERE `id`='1127';
UPDATE `institutions` SET `website_link`='http://www.cazri.res.in/' WHERE `id`='1129';
UPDATE `institutions` SET `website_link`='http://www.vpkas.nic.in/' WHERE `id`='1130';
UPDATE `institutions` SET `website_link`='http://www.manobi.com/' WHERE `id`='1133';
UPDATE `institutions` SET `website_link`='http://www.igau.edu.in/' WHERE `id`='1134';
UPDATE `institutions` SET `website_link`='http://www.hrg.org.in/' WHERE `id`='1136';
UPDATE `institutions` SET `website_link`='http://idfngo.org/' WHERE `id`='1139';
UPDATE `institutions` SET `website_link`='http://mvda.org.in/' WHERE `id`='1140';
UPDATE `institutions` SET `website_link`='http://www.meteo.gov.gh/' WHERE `id`='1144';
UPDATE `institutions` SET `website_link`='http://www.parliament.go.ug/' WHERE `id`='1148';
UPDATE `institutions` SET `website_link`='http://www.asu.edu/' WHERE `id`='1159';
UPDATE `institutions` SET `website_link`='http://www.eprcug.org/' WHERE `id`='1160';
UPDATE `institutions` SET `website_link`='http://www.kcl.ac.uk/' WHERE `id`='1161';
UPDATE `institutions` SET `website_link`='http://www.denr.gov.ph/' WHERE `id`='1162';
UPDATE `institutions` SET `website_link`='http://www.sustainableagritrust.co.zw/' WHERE `id`='1163';
UPDATE `institutions` SET `website_link`='http://www.tacri.org/' WHERE `id`='1165';
UPDATE `institutions` SET `website_link`='http://www.hrnstiftung.org/' WHERE `id`='1168';
UPDATE `institutions` SET `website_link`='http://www.senamhi.gob.pe/' WHERE `id`='1172';
UPDATE `institutions` SET `website_link`='https://www.indiana.edu/' WHERE `id`='1173';
UPDATE `institutions` SET `website_link`='https://www.luke.fi/' WHERE `id`='1182';
UPDATE `institutions` SET `website_link`='http://www.moh.gov.vn/' WHERE `id`='1179';
UPDATE `institutions` SET `website_link`='http://www.casrad.org.vn/' WHERE `id`='1183';
UPDATE `institutions` SET `website_link`='http://www.kdb.co.ke/' WHERE `id`='1187';
UPDATE `institutions` SET `website_link`='https://www.nmbu.no/' WHERE `id`='1188';
UPDATE `institutions` SET `website_link`='https://www.odi.org/' WHERE `id`='1189';

