INSERT INTO `parameters` ( `key`, `description`, `format`, `default_value`, `category`) VALUES ('crp_taw_api', 'Crp Taw Api Key', '1', NULL, '3');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_taw_api'), '1', '582f0d28fccdfa3ec8373342', '3', '1', CURRENT_TIMESTAMP, '1', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_taw_api'), '3', '582f0d82fccdfa3ec837336e', '3', '1', CURRENT_TIMESTAMP, '1', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_taw_api'), '4', '582f0d9cfccdfa3ec837337d', '3', '1', CURRENT_TIMESTAMP, '1', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_taw_api'), '5', '582f0db6fccdfa3ec8373386', '3', '1', CURRENT_TIMESTAMP, '1', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_taw_api'), '7', '582f0df2fccdfa3ec837347a', '3', '1', CURRENT_TIMESTAMP, '1', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_taw_api'), '21', '597740fc5dfc8255d623ed4d', '3', '1', CURRENT_TIMESTAMP, '1', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_taw_api'), '22', '5977436f5dfc8255d623ed52', '3', '1', CURRENT_TIMESTAMP, '1', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_taw_api'), '11', '59773fa85dfc8255d623ed45', '3', '1', CURRENT_TIMESTAMP, '1', '');
