/* Parameter to know if the CRP has contact points */
INSERT INTO `parameters` (`key`, `description`, `format`, `default_value`, `category`) VALUES ('crp_has_contact_point', 'Does the CRP have Contact Points?', '1', NULL, '2');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_has_contact_point'), '1', 'true', '3', '1', CURRENT_TIMESTAMP, '3', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_has_contact_point'), '3', 'false', '3', '1', CURRENT_TIMESTAMP, '3', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_has_contact_point'), '4', 'true', '3', '1', CURRENT_TIMESTAMP, '3', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_has_contact_point'), '5', 'false', '3', '1', CURRENT_TIMESTAMP, '3', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_has_contact_point'), '7', 'false', '3', '1', CURRENT_TIMESTAMP, '3', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_has_contact_point'), '11', 'true', '3', '1', CURRENT_TIMESTAMP, '3', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_has_contact_point'), '21', 'false', '3', '1', CURRENT_TIMESTAMP, '3', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_has_contact_point'), '22', 'false', '3', '1', CURRENT_TIMESTAMP, '3', '');

/* Parameter to identify contact point role */
INSERT INTO `parameters` (`key`, `description`, `format`, `default_value`, `category`) VALUES ('crp_cp_role', 'Identifier for Contact Point Role Role', '3', NULL, '1');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_cp_role'), '1', '4', '3', '1', CURRENT_TIMESTAMP, '3', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_cp_role'), '4', '82', '3', '1', CURRENT_TIMESTAMP, '3', '');
INSERT INTO `custom_parameters` (`parameter_id`, `crp_id`, `value`, `created_by`, `is_active`, `active_since`,`modified_by`, `modification_justification`) VALUES ((select id from parameters where `key`='crp_cp_role'), '11', '116', '3', '1', CURRENT_TIMESTAMP, '3', '');
