UPDATE `institutions` SET `website_link`='https://www.ifad.org/', `headquarter`='285' WHERE `id`='638';
UPDATE `institutions` SET `website_link`='https://www.ifad.org/', `headquarter`='285' WHERE `id`='639';
UPDATE `institutions` SET `website_link`='https://www.ifad.org/' WHERE `id`='285';
UPDATE `institutions` SET `headquarter`='66' WHERE `id`='1213';
UPDATE `institutions` SET `headquarter`='66' WHERE `id`='1223';
UPDATE `institutions` SET `website_link`='http://www.cimmyt.org/' WHERE `id`='50';
UPDATE `institutions` SET `website_link`='http://www.cimmyt.org/', `headquarter`='50' WHERE `id`='1178';
UPDATE `institutions` SET `headquarter`='50' WHERE `id`='650';
UPDATE `institutions` SET `headquarter`='50' WHERE `id`='680';
INSERT INTO `institutions` (`id`, `name`, `acronym`, `city`, `website_link`, `institution_type_id`, `country_id`) VALUES ('1274', 'International Plant Nutrition Institute', 'IPNI', 'Peachtree Corners', 'http://www.ipni.net/', '2', '222');
UPDATE `institutions` SET `headquarter`='1274' WHERE `id`='682';
UPDATE `institutions` SET `website_link`='http://www.ipni.net/', `headquarter`='1274' WHERE `id`='174';
UPDATE `institutions` SET `website_link`='http://irri.org/', `headquarter`='5' WHERE `id`='1170';
UPDATE `institutions` SET `website_link`='http://irri.org/', `headquarter`='5' WHERE `id`='1171';
UPDATE `institutions` SET `headquarter`='60' WHERE `id`='792';
UPDATE `institutions` SET `website_link`='http://www.iwmi.cgiar.org/', `headquarter`='172' WHERE `id`='1116';
UPDATE `institutions` SET `headquarter`='172' WHERE `id`='1214';
INSERT INTO `institutions` (`id`, `name`, `acronym`, `city`, `website_link`, `institution_type_id`, `country_id`) VALUES ('1275', 'Ministry of Agriculture', 'MoA', 'Kadukutty', 'http://www.moa.gov.bd/', '7', '103');
UPDATE `institutions` SET `headquarter`='1275' WHERE `id`='723';
UPDATE `institutions` SET `website_link`='http://www.mard.gov.vn/Pages/home.aspx' WHERE `id`='282';
UPDATE `institutions` SET `website_link`='http://www.mard.gov.vn/Pages/home.aspx', `headquarter`='282' WHERE `id`='1108';
UPDATE `institutions` SET `acronym`='MOH' WHERE `id`='566';
UPDATE `institutions` SET `city`='Hanoi', `website_link`='http://monre.gov.vn/' WHERE `id`='268';
DELETE FROM `institutions` WHERE `id`='1249';
UPDATE `institutions` SET `website_link`='www.niapp.org.vn' WHERE `id`='381';
UPDATE `institutions` SET `website_link`='https://www.sei-international.org/asia', `headquarter`='74' WHERE `id`='702';
UPDATE `institutions` SET `website_link`='http://www.sei-international.org/' WHERE `id`='74';
UPDATE `institutions` SET `name`='Universidad Privada del Valle', `acronym`='Univalle', `website_link`='http://www.univalle.edu/' WHERE `id`='202';
UPDATE `institutions` SET `name`='Universidad del Valle de Guatemala', `acronym`='UVG', `website_link`='http://www.uvg.edu.gt/' WHERE `id`='457';
UPDATE `institutions` SET `acronym`='Univalle', `website_link`='http://www.univalle.edu.co' WHERE `id`='770';
UPDATE `institutions` SET `website_link`='http://www.wascal.org/' WHERE `id`='628';
UPDATE `institutions` SET `website_link`='http://www.wascal.org/', `headquarter`='628' WHERE `id`='699';
UPDATE `institutions` SET `website_link`='http://www.worldagroforestry.org/', `headquarter`='88' WHERE `id`='1219';
UPDATE `institutions` SET `headquarter`='88' WHERE `id`='1143';
UPDATE `institutions` SET `headquarter`='88' WHERE `id`='1232';
UPDATE `institutions` SET `headquarter`='296' WHERE `id`='843';
UPDATE `institutions` SET `headquarter`='296' WHERE `id`='844';
UPDATE `institutions` SET `headquarter`='296' WHERE `id`='1106';
UPDATE `institutions` SET `website_link`='http://www.wvi.org/' WHERE `id`='752';
UPDATE `institutions` SET `website_link`='http://www.wvi.org/' WHERE `id`='754';
UPDATE `institutions` SET `website_link`='http://www.wvi.org/' WHERE `id`='325';
UPDATE `institutions` SET `website_link`='http://www.worldfishcenter.org/' WHERE `id`='1099';
UPDATE `institutions` SET `acronym`='' WHERE `id`='99';
UPDATE `institutions` SET `name`='Agricultural Research Council', `website_link`='http://www.arc.agric.za/Pages/Home.aspx' WHERE `id`='146';
UPDATE `institutions` SET `website_link`='http://www.barc.gov.in/index.html' WHERE `id`='435';
DELETE FROM `institutions` WHERE `id`='543';
UPDATE `institutions` SET `website_link`='http://csisa.org/' WHERE `id`='175';
UPDATE `institutions` SET `website_link`='http://www.dae.gov.bd', `headquarter`='1114' WHERE `id`='1154';
UPDATE `institutions` SET `city`='Mymensingh', `website_link`='http://www.bau.edu.bd/pages/faculty_list/AGEXT' WHERE `id`='732';
UPDATE `institutions` SET `name`='Department of Agricultural, Technical and Extension Services', `website_link`='http://www.agritex.gov.zw/' WHERE `id`='533';
UPDATE `institutions` SET `website_link`='https://www.giz.de/de/html/index.html' WHERE `id`='651';
UPDATE `institutions` SET `name`='ABS Capacity Development Initiative', `headquarter`='651' WHERE `id`='1090';
UPDATE `institutions` SET `website_link`='http://www.fao.org/home/en/' WHERE `id`='69';
UPDATE `institutions` SET `name`='Regional Office for Asia and the Pacific', `headquarter`='69' WHERE `id`='845';
UPDATE `institutions` SET `name`='Global Information and Early Warning System', `acronym`='GIEWS', `website_link`='http://www.fao.org/giews/en/', `headquarter`='69' WHERE `id`='846';
UPDATE `institutions` SET `name`='Food and Agriculture Organization of the United Nations', `website_link`='http://www.fao.org/chile/es/', `headquarter`='69' WHERE `id`='873';
UPDATE `institutions` SET `name`='Oficina Subregional para Mesoamérica', `acronym`='SLM', `website_link`='http://www.fao.org/americas/mesoamerica/es/', `headquarter`='69' WHERE `id`='872';
INSERT INTO `institutions` (`id`, `name`, `acronym`, `city`, `website_link`, `institution_type_id`, `country_id`) VALUES ('1276', 'Generation Challenge Programme', 'GCP', 'Texcoco', 'http://www.generationcp.org', '11', '153');
UPDATE `institutions` SET `name`='Generation Challenge Programme', `headquarter`='1276' WHERE `id`='606';
UPDATE `institutions` SET `name`='Georg-August-Universität Göttingen', `website_link`='http://www.uni-goettingen.de/' WHERE `id`='4';
UPDATE `institutions` SET `name`='Gorgan University of Agricultural Sciences & Natural Resources', `city`='Gorgan' WHERE `id`='719';
UPDATE `institutions` SET `website_link`='http://inrab.org/' WHERE `id`='3';
UPDATE `institutions` SET `name`='Institut National de la Recherche Agronomique du Niger', `website_link`='inran.refer.ne/' WHERE `id`='249';
UPDATE `institutions` SET `website_link`='http://www.inia.cl/' WHERE `id`='139';
UPDATE `institutions` SET `website_link`='http://www.inia.gob.pe/' WHERE `id`='276';
UPDATE `institutions` SET `website_link`='http://www.iniaf.gob.bo/index.php/es/' WHERE `id`='68';
UPDATE `institutions` SET `website_link`='http://www.inia.uy/' WHERE `id`='613';
UPDATE `institutions` SET `name`='Instituto Nicaragüense de Tecnología Agropecuaria' WHERE `id`='793';
UPDATE `institutions` SET `website_link`='http://inta.gob.ar/' WHERE `id`='124';
UPDATE `institutions` SET `website_link`='http://www.ku.edu.np/' WHERE `id`='179';
UPDATE `institutions` SET `website_link`='https://msu.edu/' WHERE `id`='300';
UPDATE `institutions` SET `website_link`='http://ww4.msu.ac.zw/' WHERE `id`='357';
UPDATE `institutions` SET `name`='Ministry of Agriculture', `website_link`='http://www.moa.gov.et/home', `headquarter`='1275' WHERE `id`='290';
UPDATE `institutions` SET `name`='Ministry of Agriculture', `headquarter`='1275' WHERE `id`='664';
UPDATE `institutions` SET `website_link`='http://www.sias-southasia.org/' WHERE `id`='295';
UPDATE `institutions` SET `website_link`='www.teriuniversity.ac.in' WHERE `id`='493';
UPDATE `institutions` SET `city`='Corvallis', `website_link`='http://oregonstate.edu/' WHERE `id`='378';
UPDATE `institutions` SET `website_link`='https://www.osu.edu/' WHERE `id`='232';
UPDATE `institutions` SET `name`='United Nations Environment Programme', `website_link`='' WHERE `id`='1238';
UPDATE `institutions` SET `website_link`='http://www.unep.org/' WHERE `id`='301';
UPDATE `institutions` SET `website_link`='http://web.unep.org/regions/roap', `headquarter`='301' WHERE `id`='1257';
UPDATE `institutions` SET `acronym`='UNEP-WCMC', `headquarter`='301' WHERE `id`='599';
UPDATE `institutions` SET `website_link`='http://www.unep.org/', `headquarter`='301' WHERE `id`='1238';
INSERT INTO `institutions` (`id`, `name`, `acronym`, `city`, `website_link`, `institution_type_id`, `country_id`) VALUES ('1277', 'Universidad Nacional de Colombia', 'UNAL', 'Bogota', 'http://unal.edu.co/', '1', '53');
UPDATE `institutions` SET `headquarter`='1277' WHERE `id`='1051';
UPDATE `institutions` SET `headquarter`='1277' WHERE `id`='609';
UPDATE `institutions` SET `name`='Université de Sherbrooke', `city`='Sherbrooke', `website_link`='http://www.usherbrooke.ca/' WHERE `id`='536';
UPDATE `institutions` SET `website_link`='http://www.uds.edu.gh/' WHERE `id`='530';
UPDATE `institutions` SET `website_link`='http://www.csir-water.com/' WHERE `id`='332';

