SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for deliverable_data_sharing_file
-- ----------------------------
DROP TABLE IF EXISTS `deliverable_data_sharing_file`;
CREATE TABLE `deliverable_data_sharing_file` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `deliverable_id` bigint(20) NOT NULL,
  `file` varchar(500) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `deliverable_id` (`deliverable_id`) USING BTREE,
  CONSTRAINT `deliverable_data_sharing_file_ibfk_1` FOREIGN KEY (`deliverable_id`) REFERENCES `deliverables` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=240 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of deliverable_data_sharing_file
-- ----------------------------
INSERT INTO `deliverable_data_sharing_file` VALUES ('1', '408', 'CCAFS_SEA_Report 2015.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('2', '404', 'FP3-SEA-ILRI Hanoi-November 2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('3', '408', 'Worldfish_CN-Flagship1-AQfutures4MRD_03Oct2014.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('7', '137', 'ftp://ftp.ciat.cgiar.org/DAPA/projects/BIGDATA_AEPS/REPORTES/FLAGSHIP/EvidenciaCCAFS.pdf', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('8', '1079', 'http://www.open-aeps.org', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('9', '1462', 'Pestforecast_SLR_HS_Lee.xlsx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('10', '1462', 'Systematic Literature Review of Pest Forecast project in Vietnam%28Draft_HS_Lee%29.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('11', '862', 'ACTION PLAN final -press.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('14', '141', 'CBouroncle_EGiron_ProductosAgroClim_GTM 02DIC15.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('16', '141', 'LINEA DE BASE_SC_ACF.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('20', '468', 'Gender Framework.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('22', '493', 'Indicators for verification of CSV.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('23', '494', 'case study_Haryana.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('24', '586', 'criteria and business assessment tool.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('25', '587', 'Lengthy list of CSA practices with potential for business development.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('26', '588', 'Action plan for business case development.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('27', '589', 'List of CSAPs.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('29', '1397', '1397-NonCO2GHG_JIES.PDF', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('30', '1397', '1397-Better Crops 2015-3 p18.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('31', '1397', '1397-CROP DIVERSIFICATION.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('32', '1397', '1397-SSAJ_finalPdf_revised.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('33', '1397', '1397-Journal of Integrative Agriculture- CLimate Chage (2015).PDF', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('34', '1397', '1397-Impact of Laser Leveling_Food Security 2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('35', '1397', '1397-LUP_2016_126_Original_V0 (2).pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('36', '1397', 'Climate Smart Villages in Haryana_LR_08-06-2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('37', '468', '468-Gender CCAFS PB10.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('38', '468', '468-Gender-Mehar, mittal, prasad- CC and gender-JRS feb2016.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('39', '482', '482-AGEE-S-16-00267.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('40', '575', '575-CSA Practice Brief-2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('41', '584', '584-FOSE-S-16-00028.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('42', '601', '601-Jat et al-Laser Assisted Precision Land Leveling.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('43', '601', '601-Socio-economic Factors Affecting Modern ICT.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('44', '494', 'Climate Smart Villages in Haryana_LR_08-06-2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('45', '1226', 'Metrics Workshop Report 2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('46', '404', 'WorldFishSAMPLES_Report4CCAFS.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('47', '409', 'SE Asia summary report livestock Feb 16.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('58', '769', 'http://www.ifpri.org/publication/international-model-policy-analysis-agricultural-commodities-and-trade-impact-model-0', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('59', '816', 'Mason-D\'Croz (Dec 2015) INAI - IMPACT3, a selection of projections from IPCC scenario.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('60', '816', 'Wiebe IFPRI Policy Seminar DC 10Nov15-tbs.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('61', '816', 'http://www.ifpri.org/publication/international-model-policy-analysis-agricultural-commodities-and-trade-impact-model-0', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('62', '815', 'http://globalfutures.cgiar.org/2015/06/29/global-futures-and-strategic-foresight-gfsf-program-contributes-to-lloyds-study-food-system-shock-the-insurance-impacts-of-acute-disruption-to-global-food-supply/', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('63', '815', 'http://www.ifpri.org/publication/international-model-policy-analysis-agricultural-commodities-and-trade-impact-model-0', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('64', '817', 'http://www.ifpri.org/publication/international-model-policy-analysis-agricultural-commodities-and-trade-impact-model-0', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('65', '1058', 'PACCA M&E Report_2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('66', '1058', 'PACCA CCSL Report_2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('68', '315', 'Sapkota et al. - 2015 - Tillage, residue and nitrogen management effects on methane and nitrous oxide emission from rice–wheat system of.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('70', '359', 'https://research.csiro.au/foodglobalchange/data-and-tools/household-data/', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('71', '360', 'https://research.csiro.au/foodglobalchange/data-and-tools/household-data/', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('72', '663', 'Deliverables 1&2 Baseline assessment.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('73', '664', 'Deliverables 1&2 Baseline assessment.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('74', '704', 'Stakeholder workshop 21 Oct 15 Samarinda.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('75', '693', 'Field trip report Age Kukar Oct 2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('76', '392', 'SciencePolicyInteractionsConceptualFramework_FINAL.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('77', '390', 'Senegal policy dynamics.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('78', '1210', 'Bioma_Reeport-CiFor_januari2016 now.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('79', '642', 'Tree forages poster.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('80', '644', 'http://www.irri.org', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('81', '645', 'http://www.irri.org', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('82', '1107', 'Poster_Acosta et al.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('91', '1065', 'https://cloud.iri.columbia.edu/index.php/s/GW8Tvm7DcfebZIl', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('92', '1065', 'https://cloud.iri.columbia.edu/index.php/s/Z9aFlLCgXBqIqr2', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('93', '1065', 'https://cloud.iri.columbia.edu/index.php/s/a3Hm4eOrJINO4u6', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('94', '1065', 'https://cloud.iri.columbia.edu/index.php/s/xrNUmOC04qb6Ic1', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('95', '1065', 'https://cloud.iri.columbia.edu/index.php/s/BYBa9W6T3AQLbJT', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('96', '1065', 'https://cloud.iri.columbia.edu/index.php/s/8aPv5vxV3oNKzXc', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('97', '1065', 'https://cloud.iri.columbia.edu/index.php/s/BelCUNX9iyrF7FA', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('98', '553', 'https://cloud.iri.columbia.edu/index.php/s/nhI4lrnwxK85Y67', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('99', '550', 'https://cloud.iri.columbia.edu/index.php/s/Ws18O6N7MUCWTz6', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('100', '550', 'https://cloud.iri.columbia.edu/index.php/s/UuONhW2ajBjqe2G', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('101', '550', 'https://cloud.iri.columbia.edu/index.php/s/HKkQIaobEenTeWG', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('102', '550', 'https://cloud.iri.columbia.edu/index.php/s/1Lf3mBC84a6qa5r', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('103', '550', 'https://cloud.iri.columbia.edu/index.php/s/1Lf3mBC84a6qa5r', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('104', '550', 'https://cloud.iri.columbia.edu/index.php/s/BFyVPxYES03N1cy', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('106', '1670', 'Pestforecast updates 16Nov_ILRI (1).PPTX', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('107', '1616', '2015_Pestforecast.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('108', '1604', 'Zoonotic conference.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('109', '1675', 'Analysis of policy dynamics - Ethiopia.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('110', '390', 'Analysis of policy dynamics - Ethiopia.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('111', '1676', 'ResearchBrief_59.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('112', '957', 'https://drive.google.com/drive/u/1/folders/0B0VTAnaUDXLBUEtHcWZQdFowSzg', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('113', '942', 'https://drive.google.com/drive/u/1/folders/0B0VTAnaUDXLBUEtHcWZQdFowSzg', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('115', '333', 'Resampling.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('116', '333', 'MScCCAFS+research+project_ThaizeBaroni.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('117', '333', 'Agreement AGRONET-MADR.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('118', '333', 'Conference Proceedings _OIRSA  (rough copy).pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('119', '94', 'AgMERRA - IDEAM.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('120', '141', 'informe LMA diciembre 2015 v2.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('121', '482', 'Climate stresses_CSAoptions.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('122', '469', '469 Pilots of action research on CSAPs.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('123', '589', 'Local Innovation Platform Established.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('124', '599', 'mising link- policies-ASS-Aug 2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('125', '675', 'https://www.dropbox.com/s/z6g9low0vxfe9t5/ACSAA-Malawi-Inception-Workshop-Report_Final.pdf?dl=0', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('126', '769', 'http://onlinelibrary.wiley.com/doi/10.1111/1746-692X.12088/full', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('127', '104', 'AGSY5200R1.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('130', '330', 'Informe de Ejercicio de Simulacro Sequía Chiquimula 2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('132', '364', 'Livestock NAMA Colombia.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('133', '358', 'http://iwmi.cgiar.org', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('134', '358', 'http://ibfi.iwmi.org', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('135', '327', 'TecnicalReport_EGiron_CBouroncle.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('136', '330', 'informe LMA diciembre 2015 v2_MAGA.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('137', '933', 'https://drive.google.com/drive/u/1/folders/0B0VTAnaUDXLBR2ZMN0tVOGxFR3c', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('138', '399', '30 November NAMA planning workshop.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('139', '1717', 'hhmod jun15.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('140', '1718', 'rangelands sem 0915 actual.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('141', '1719', 'toowoomba nov 2015.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('142', '697', 'Volunteer Farmer Approach_CSA.doc', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('143', '697', 'http://dx.doi.org/10.5716/WP16005.PDF', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('144', '697', 'Farmer-to-Farmer-Extension_GFRAS note.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('145', '642', 'Tree fodder nutrition database report.doc', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('147', '333', 'Working Paper Inventory of agroclimatic information services in Colombia.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('148', '1230', 'Honduras case study_SAG 2014_UCI.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('149', '94', 'WP CCAFS TRMM-CHIRPS.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('150', '416', 'http://nkoech.github.io/africacsa/', 'Externally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('151', '483', '483- Conceptual framework.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('152', '483', '483-Conceptual framework.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('156', '575', '575-Empowerment.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('157', '1757', 'kanter-gfs-conf-2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('158', '1761', 'CSA 15 Shirsath.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('159', '1762', 'medina-csa15.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('160', '1763', 'CSA 15 Rigolot.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('161', '1756', 'Waha_AdaptationDiversification_final_ES_edit.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('162', '1766', 'csiro science meeting dec15.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('163', '484', 'First International Training Workshop on Farming Systems Analysis in India.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('164', '623', 'social diff annex.zip', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('165', '1095', 'Gender PD  updated workplan 2016 17_Jan 25.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('166', '1397', 'CSVs in Bihar.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('167', '1782', 'FP4 Communication & Engagement Reporting .docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('168', '484', '484-CCAFS Foresight and targeting climate smart agricultural practices in Bihar.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('169', '485', '485-Targeting CSAPs.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('170', '485', 'Farming System Report.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('171', '679', 'Activity 678-9 -  FHH Variable Gap Identification.xlsx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('173', '680', 'Activity 680 - CSAP list - Rakai.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('174', '680', 'Activity 680 - CSAP list - Wote.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('176', '680', 'Activity 680 - PEACSA cross-site soil analysis.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('177', '1806', 'Climate-Smart Agriculture, Presentation.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('178', '1807', 'Climate-Smart Agriculture Presentation_clean.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('179', '680', 'Activity 680 - CSAP list - Lushoto.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('180', '402', 'CCAFS_report_03-03-2016.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('181', '402', 'data.zip', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('182', '1808', 'Lenaerts Lutgart_v2.pptx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('183', '326', 'Report_Potential Mitigations_V4 (002).pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('184', '1695', 'CCAFS_Transf_WG_LitReview_Coded_2015.xls', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('185', '681', 'Activity 678, 681 -  FHH Variable Gap Identification.xlsx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('186', '868', 'Rapport suivi-évaluation CSPEP 2015 final.doc', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('187', '690', 'PEACSA _Activity 2_Feb2016_Kindie.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('188', '921', 'Rapport Final Flagship Décembre 2015.doc', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('189', '921', 'Progres_report_flaship4_2015.doc', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('190', '1060', 'PACCA CCSL Report_2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('191', '921', 'DRAFT 2015 ANNUAL REPORT  FOR FS4.doc', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('192', '927', 'Rapport discordances_Feb16.doc', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('193', '708', 'PEACSA_FGD_May 25_Final.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('194', '708', 'Copy of Module 3.xlsx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('195', '708', 'Activity 699 - REVISED RAKAI PLOT LAYOUT AND TREATMENT DESCRIPTION.xlsx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('196', '708', 'Activity 699 - Wote, Rakai Randomization and field layout.xlsx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('197', '1057', 'Learning Alliance Report_2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('198', '676', 'CCAFS-Report-WBCIS.PDF', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('199', '1821', 'RBM report_2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('200', '355', 'informe taller Monteria.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('201', '866', 'Climate_Analogues Report_2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('202', '1386', 'CCAFS Climate Final Report (2015).pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('204', '683', 'Participatory Scenario Report _2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('205', '364', 'NINO Ganadería Bovina Vfinal (1).pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('206', '340', 'Reporte Caracterización Ambiental-1.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('210', '931', 'npg-22-383-2015.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('224', '1830', 'Bombardi_Clim_Dyn_SAD_2013.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('225', '1832', 'Carvalho_Jones_2013_cmip5_JCLI-D-12-00532.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('226', '1833', 'clivar.contribution_newsletter.2013.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('227', '1834', 'Heidinger_et_all_2012.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('228', '775', 'stakeholder tools banana CC adaptation.zip', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('229', '887', 'CASCAID_Gender_Materials_Pack.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('230', '889', 'CASCAID 352 April workshop report.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('231', '891', 'CASCAID 352 information flows report.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('232', '892', 'CASCAID 352 outreach.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('234', '1008', 'TAMSAT+ENACTS_presentations_Feb2016.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('235', '1234', '20150901_DraftMoA_ICRISAT-Meteo-Mali_V02_AMN+PCST_Final_En_revMeteoMali.docx', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('236', '1016', 'DBSTARS_Mali_v3.2.zip', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('237', '1018', 'STARS_RS_2015-12-24_PCST_manuscript_Export_CCAFS_P&R.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('238', '1007', 'ENACTS_Report.pdf', 'Locally');
INSERT INTO `deliverable_data_sharing_file` VALUES ('239', '1007', 'Norther_Ghana_Baseline_Report.pdf', 'Locally');
