/** Flagship 1 tiered funding sources **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 1 - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 1 - Tier 2 funds','Tier 2 funds are reltively likely to be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 1 - Tier 3 funds','Tier 3 funds are relatively insecure and there is a high probabiliy that they will not be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);

/** Flagship 2 tiered funding sources **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 2 - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 2 - Tier 2 funds','Tier 2 funds are reltively likely to be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 2 - Tier 3 funds','Tier 3 funds are relatively insecure and there is a high probabiliy that they will not be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);

/** Flagship 3 tiered funding sources **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 3 - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 3 - Tier 2 funds','Tier 2 funds are reltively likely to be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 3 - Tier 3 funds','Tier 3 funds are relatively insecure and there is a high probabiliy that they will not be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);

/** Flagship 4 tiered funding sources **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 4 - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 4 - Tier 2 funds','Tier 2 funds are reltively likely to be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 4 - Tier 3 funds','Tier 3 funds are relatively insecure and there is a high probabiliy that they will not be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);

/** Flagship 5 tiered funding sources **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 5 - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 5 - Tier 2 funds','Tier 2 funds are reltively likely to be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Flagship 5 - Tier 3 funds','Tier 3 funds are relatively insecure and there is a high probabiliy that they will not be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);

/** Communications tiered funding **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Communications - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);

/** Gender tiered funding **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Gender - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 Gender - Tier 2 funds','Tier 2 funds are reltively likely to be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);

/** MELIA tiered funding **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 MELIA - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 MELIA - Tier 2 funds','Tier 2 funds are reltively likely to be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);

/** CapDev tiered funding **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 CapDev - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 CapDev - Tier 2 funds','Tier 2 funds are reltively likely to be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);

/** MSU tiered funding **/
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 MSU - Tier 1 funds','Tier 1 funds are the most secure and likely to be distributed to the CRP.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 MSU - Tier 2 funds','Tier 2 funds are reltively likely to be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);
INSERT INTO funding_sources(`title`,`description`,`start_date`,`end_date`,`finance_code`,`grantAmount`,`contact_person_name`,`contact_person_email`,`file`,`donor`,`direct_donor`,`status`,`type`,`division_id`,`crp_id`,`global`,`w1w2`,`sync`,`extended_date`,`syn_date`,`created_by`,`active_since`,`modified_by`,`modification_justification`,`is_active`)values('W1/W2 MSU - Tier 3 funds','Tier 3 funds are relatively insecure and there is a high probabiliy that they will not be distributed to the CRP, unless there is a large shortfall in funding.','2017-01-01','2022-12-31',NULL,0.00,'Vincent Gitz','v.gitz@cgiar.org',NULL,NULL,221,2,1,NULL,11,false,false,false,NULL,NULL,3,'2017-11-21 09:44:53',3,'',1);