insert into lever_outcomes(name, parent_id, description, indicator) values('Multifunctional Landscapes', null, null, '2');
insert into lever_outcomes(name, parent_id, description, indicator) values('Climate Action', null, null, '3');
insert into lever_outcomes(name, parent_id, description, indicator) values('Biodiversity', null, null, '4');
insert into lever_outcomes(name, parent_id, description, indicator) values('Digital Inclusion', null, null, '5');
insert into lever_outcomes(name, parent_id, description, indicator) values('Crops for Nutrition and Health', null, null, '6');

insert into lever_outcomes(name, parent_id, description, indicator) values(null, 1, 'National and subnational authorities in priority countries adopt policies and build capacity to improve diet quality [including safety and diversity] of consumers. [add healthier diets?]', '1.1');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 1, 'Food environments offer greater opportunities for inclusion for women and youth in local, domestic and transnational markets [inclusion is also for access and affordability for the consumer]', '1.2');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 1, 'National and international public sector organizations, as well as civil society and private sector organizations at local, national and international level promote sustainable healthy diets', '1.3');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 1, 'Consumers in the global south are mobilized to support food environments that inclusively offer healthy, diverse and sustainable food choices to all consumers', '1.4');

insert into lever_outcomes(name, parent_id, description, indicator) values(null, 2, 'National and subnational authorities in priority countries implement policies and incentives that promote evidence-based agro-environmental solutions that enhance ecosystem services, healthy foods, and equitable livelihoods under a changing climate', '2.1');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 2, 'Land managers and development actors participate in the co-design and deployment of land uses that are more biodiverse, resilient to climate change and equitable, and reduce the environmental impact of agricultural systems in priority countries', '2.2');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 2, 'Public and private value-chain actors and investors participate in the negotiation and implementation of sustainable business models that lead to improved environmental and socio-economic outcomes in farms and landscapes', '2.3');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 2, 'Producers sustainably manage productive farms and landscapes and their efforts towards sustainable production are being rewarded through environmental, social and governance? incentives, more favorable prices, government aids, or other type of economic and financial mechanisms -- add healthy foods here' , '2.4');

insert into lever_outcomes(name, parent_id, description, indicator) values(null, 3, 'Development partners use tailored climate services in priority countries to help farmers and their institutions reduce the impact of climate risks', '3.1');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 3, 'Development agencies make smarter investments that deliver climate adaptation and mitigation based on agricultural and climate risks profiled' , '3.2');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 3, 'Newly established innovative finance partnerships support climate adaptation and mitigation efforts across a range of geographies','3.3');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 3, 'Farmers and their institutions co-develop adapted and low-emissions agricultural practices and technologies, improving livelihoods, environmental sustainability, and food and nutrition security in priority countries', '3.4');

insert into lever_outcomes(name, parent_id, description, indicator) values(null, 4, 'National programs and communities in priority countries characterize and use diverse genebank and local material and crop wild relatives to address resilience, climate change, and nutrition through integrated selection and breeding approaches', '4.1');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 4, 'Inclusive formal, intermediate, and informal seed systems deliver forages, trees, and crops adapted to local conditions to improve food security and sustainability of production systems', '4.2');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 4, 'National governments adopt policies and practice recommendations for genetic resource management', '4.3');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 4, 'Value-chain stakeholders integrate a greater diversity of crops for greater resilience and healthier diets', '4.4');

insert into lever_outcomes(name, parent_id, description, indicator) values(null, 5, 'Public and private organizations support inclusive digital services for producers and rural entrepreneurs to improve employment of women and youth and increase agricultural productivity and quality of life', '5.1');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 5, 'Agricultural innovation facilities make effective and responsive use of digital technology for two-way interaction to address the needs of users in R&D targeting and to ensure efficient delivery of innovations', '5.2');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 5, 'Food sellers, buyers, processors, traders and retailers, and food system governance bodies make effective use of digital technology to make better use of agrobiodiversity, make food systems more inclusive, and monitor and control environmental and social sustainability impacts', '5.3');

insert into lever_outcomes(name, parent_id, description, indicator) values(null, 6, 'National institutions accelerate delivery of new varieties with higher nutritional value in target countries, by integrating genotyping, phenotyping, and participatory approaches', '6.1');
insert into lever_outcomes(name, parent_id, description, indicator) values(null, 6, 'Partner countries improve capacity in the use of nutrition-sensitive lenses and appropriate gender-responsive participatory and genetic methodologies in the selection and breeding of crops', '6.2');