DROP TABLE IF EXISTS general_acronyms;
CREATE TABLE `general_acronyms` (
  `id`  bigint(20) NOT NULL AUTO_INCREMENT ,
  `acronym`  varchar(255) NOT NULL ,
  `description` TEXT NOT NULL ,
  `is_active` tinyint(1) DEFAULT NULL,
  `active_since` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by` bigint(20) DEFAULT NULL,
  `modified_by` bigint(20) DEFAULT NULL,
`modification_justification` text,
PRIMARY KEY (`id`)
);


INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('A&M','Adaptation and Mitigation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('A4NH','CGIAR Research Program on Agriculture for Nutrition and Health',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AAS','Aquatic Agricultural Systems',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AATF','African Agricultural Technology Foundation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ABARES','Department of Agriculture, Fisheries and Forestry (Australia)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ABCIC','The African Biodiversity Conservation and Innovations Centre',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ACBF','African Capacity Building Foundation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ACCRA','Africa Climate Change Resilience Alliance',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ACIAR','Australian Centre for International Agricultural Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ACMAD','African Center of Meteorological Application for Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ACPC','Africa Climate Policy Centre',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AECF','The Africa Enterprise Challenge Fund',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AEDD','Agence de l’Environment et du Developpement Durable',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AfDB','The African Development Bank',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AFOLU','Agriculture, Forestry and Land Use',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AfSIS','The Africa Soil Information Service',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AgClim','Agriculture and Climate letters',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AgMIP','Agricultural Model Intercomparison and Improvement Project',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AGN','African Group of Negotiators',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AGNES','Africa Group of Negotiators Expert Support',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AGRA','Alliance for a Green Revolution in Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AGRHYMET','Regional Centre for Training and Application of Agrometeorology and Operational Hydrology',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AgTrials','The Global Agricultural Trial Repository',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AIC','Agricultural Insurance Company of India',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ALIN','Arid Lands Information Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AMCEN','African Ministerial Conference on the Environment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AMKN','Adaptation and Mitigation Knowledge Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AMMA','African Monsoon Multidisciplinary Analysis',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ANAFE','African Network for Agriculture, Agroforestry and Natural Resources Education',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ANAMS','Senegalese National Weather Agency',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ANCAR','National Agency for Agriculture and Rural Advice (Senegal)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('APAARI','Asia-Pacific Association of Agricultural Research Institutions',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('APES','Animal, Plant and Enrivonmental Sciences at University of the Witwatersrand, Johannesburg',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('APSIM','Agricultural Systems Simulation Platform',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('APSRU','Agricultural Production Systems Research Unit (Australia)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AR4','Fourth Assessment Report of the IPCC',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AR5','Fifth Assessment Report of the IPCC',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ARD','Advanced research division',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ARDD','Agriculture and Rural Development Day, an annual event alongside the UNFCCC Conference of parties',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ARI','Advanced Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ASAP','Adaptation for Smallholder Agriculture Programme',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ASARECA','Association for Strengthening Agricultural Research in Eastern and Central Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ASEAN','Association of Southeast Asian Nations',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AU','African Union',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AV','Available',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AWARD','African Women in Agricultural Research and Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('AWD','Alternate wetting and drying',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('BARC','Bangladesh Agricultural Research Council',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('BARI','Bangladesh Agricultural Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('BCAS','Bangladesh Centre for Advanced Studies',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('BMGF','Bill and Melinda Gates Foundation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('BoT','Board of Trustees',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('BRICS','Grouping acronym that refers to the countries of Brazil,',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('C','Carbon',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CA','Central America',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CAADP','Comprehensive Africa Agriculture Development Programme',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CAAS','Chinese Academy of Agricultural Sciences',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CAC','Central American Agricultural Council’s (CAC)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CAF','Centrally Administered Funds',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CAMC','Central America and the Caribbean',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CAN','Comunidad Andina (Andean Community)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CAPRi','Program on Collective Action and Property Rights',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CARE','Christian Action Research and Education',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CARE','Cooperative for Assistance and Relief Everywhere',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CARE-ALP','CARE’s Adaptation Learning Programme for Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CARIAA','Collaborative Adaptation Research Initiative in Africa and Asia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CAS','Conservation Agriculture systems',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CASFESA','Conservation Agriculture for Smallholder Farmers in Eastern and Southern Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CB','Consortium Board',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CBA','Community Based Adaptation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CC','Climate Cange',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CCAFS','CGIAR Research Program on Climate Change, Agriculture and Food Security',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CCB','Climate, Community and Biodiversity Standards',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CCDA','Climate Change and Development in Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CCEE','CRP-Commissioned Independent External Evaluations',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CCF-E','Climate Change Forum – Ethiopia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CDM','Clean Development Mechanism',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CEO','Chief Executive Officer',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CER','Certified Emission Reductions',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CEREGE','Centre Européen de Recherche et d’Enseignement des Géosciences de l’Environnement',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CFS','Committee on Food Security',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CG Centers','Centers within the former Consultative Group on International Agricultural Research, now only known as CGIAR',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CGE','Computable General Equilibrium',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CGIAR','Consortium of International Agricultural Research Centers',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CIAT','International Center for Tropical Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CIDA','Canadian International Development Agency',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CIFOR','Center for International Forestry Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CILSS','Comité Permanent Inter-Etats de Lutte contre la Sécheresse dans le Sahel (Permanent Interstate Committee for Drought Control in the Sahel)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CIMMYT','International Maize and Wheat Improvement Center',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CIP','International Potato Center',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CIRAD','La recherche agronomique pour le développement',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CIS','Climate information services',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CLA','Coordinating Lead Author (in the IPCC assessment process)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CLIFF','Copenhagen University-initiated Climate Food and Farming Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CLIFF-GRADS','Climate Food and Farming – Global Research Alliance Development Scholarships',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ClimDev-Africa','Climate for Development in Africa Programme',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CLUA','The Climate and Land Use Alliance',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CN','Concept Note',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CNEARC','Center for Post Graduate Studies in Tropical and Subtropical Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CNEDD-Mali','Conseil National pour l''Environnement et le Développement Durable (The National Council on the Environment and Sustainable Development Mali)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CO','CGIAR Consortium Office',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CoA','Clusters of activity',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('COCOBOD','Ghana Cocoa Board',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('COMESA','Common Market for Eastern and Southern Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CONEDD','National Council on Environment and Sustainable Development (Burkina Faso, known by its French acronym)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('COP','Conference of the Parties',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CORAF','West and Central African Council for Agricultural Research and Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CORAF/WECARD','West and Central African Council for Agricultural Research and Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('COSO','Committee of Sponsoring Organizations of the Treadway Commission',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CP','Challenge Program of the CGIAR',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CP','CGIAR Center Contact Point to CCAFS',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CPWF','CGIAR Challenge Program on Water and Food',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CR4D','Climate research for development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRAFT','CCAFS Regional Agricultural Forecasting Tool',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRIDA','Central Research Institute for Dryland Agriculture, India',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP','CGIAR Research Program',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 1.1','Integrated Agricultural Production Systems for the Poor and Vulnerable in Dry Areas',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 1.2','Integrated Systems for the Humid Tropics',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 1.3','Harnessing the Development Potential of Aquatic Agricultural Systems for the Poor and Vulnerable',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 2','Policies, Institutions, and Markets to Strengthen Food Security and Incomes for the Rural Poor',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 3.1','WHEAT-Global Alliance for Improving Food Security and the Livelihoods of the Resource-poor in the Developing World',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 3.2','MAIZE - Global Alliance for Improving Food Security and the Livelihoods of the Resource-poor in the Developing World',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 3.3','Global Rice Science Partnership (GRiSP)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 3.4','Roots, Tubers and Bananas for Food Security and Income',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 3.5','Grain Legumes: enhanced food and feed security, nutritional balance, economic growth and soil health for smallholder farmers',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 3.6','Dryland cereals: Food Security and Growth for the World’s Most Vulnerable Poor',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 3.7','More Meat, Milk and Fish by and for the Poor',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 4','Agriculture for Improved Nutrition and Health',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 5','Water, Land and Ecosystems',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 6','Forests Trees and Agroforestry: Livelihoods, Landscapes and Governance',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRP 7','Climate Change, Agriculture and Food Security',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CRS','Catholic Relief Services',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CS','Climate service',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSA','Climate-smart agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSALP','Climate Smart Agriculture Learning Platform for South Asia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSAq','Climate-smart aquaculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSE','Centre de Suivi Ecologique',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSI','Consortium for Spatial Information',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSIR','Council of Scientific and Industrial Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSIRO','The Commonwealth Scientific and Industrial Research Organisation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSISA','The Cereal Systems Initiative for South Asia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSM','Cropping System Model',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CS-MAP','Climate-risk related maps and adaptation plans',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSO','Civil Society Organisations',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSP','Climate Services Partnership',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CSV','Climate-Smart Village',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CTA','Technical Centre for Agricultural and Rural Cooperation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('CU','Coordinating Unit of CCAFS',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DAC','Development Assistance Committee',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DAFF','Department of Agriculture, Fisheries and Forestry (Australia)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('Danida','Danish International Development Agency',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DATA+','Indicates actual, good quality, data generated by the research process',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('Dataverse','Public portal for full CCAFS data sets',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DDI','Data Documentation Initiative',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DDS','Data & Document Store',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DfID','Department for International Development (UK)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DIE','Deutsches Institut für Entwicklungspolitik (German Development Institute)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DIIS','Danish Institute for International Studies',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DMS','Data Management Strategy',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DNDC-ART','The DeNitrification-DeComposition Applications, Research and Training',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DPIPWE','Tasmanian Department of Primary Industries, Parks, Water and Environment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DS','Dryland System',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('D-Space (cgspace)','Online repository for CCAFS outputs',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DSSAT CSM','Decision Support System for Agrotechnology Transfer Cropping System Model',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('DWR','Directorate of Wheat Research of the Indian Council of Agricultural Research (ICAR)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('E3','Bureau for Economic Growth, Education, and the Environment USAID',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EA','East Africa – one of the CCAFS target regions',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EAC','East Africa Community',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EAFF','Eastern Africa Farmers Federation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EAIA','Ex-ante Impact Assessment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EC','European Commission',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ECI','Environmental Change Institute, Oxford University',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ECOWAS','Economic Community of West African States',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EEIG','European Economic Interest Group',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EFARD','European Forum for Agricultural Research for Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EIAR','Ethiopian Institute of Agricultural Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EiB','European Investment Bank',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EM','Evaluation Manager',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EMBRAPA','Empresa Brasileira de Pesquisa Agropecuária (The Brazilian Agricultural Research Corporation)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ENDA','Environnement et Développement du Tiers Monde',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ENR Africa','Environment and Natural Resources Africa Associates Ltd',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EPA','Economic Partnership Agreement (EPA) between the European Union and the ACP (Africa, Caribbean, and Pacific)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EPIA','Ex-post impact assessment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('Ep-IA','Ex-post impact assessment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ERP','Enterprise Resource Planning',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ESA','Eastern and Southern Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ESA','European Space Agency',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ESA WUR','Environmental Systems Analysis Group of Wageningen University',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ESSP','Earth System Science Partnership',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ETS','Emissions Trading Scheme',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('EU','European Union',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FACCE JPI','Joint Programming Initiative Agriculture, Food Security and Climate Change',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FAI','Fertiliser Association of India',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FAN','Focal Area Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FANRPAN','Food, Agriculture and Natural Resources Policy Analysis Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FAO','Food and Agriculture Organization of the United Nations',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FAOSTAT','Food and Agriculture Organization of the United Nations Statistics Department',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FARA','Forum for Agricultural Research in Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FC','Fund Council',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FCRN','Food Climate Research Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FEWSNET','Famine Early Warning Systems Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FICCI','Federation of Indian Chamber of Commerce and Industry',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FLW','Food loss and waste',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FMARD','Federal Ministry of Agriculture and Rural Development (Nigeria)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FOE','Friends of the Earth',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FP','Flagship Program',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FSIN','Food Security Information Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('FTA','CGIAR Research Program on Forests, Trees and Agroforestry',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('G20','The Group of Twenty (G-20) Finance Ministers and Central Bank Governors',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GAR','Golden Agri-Resources',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GCAN','Gender, Climate Change, and Nutrition Integration Initiative',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GCARD','Global Conference on Agricultural Research for Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GCCRP','Global Crop Monitoring Project',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GCM','Global climate model',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GCP','Generation Challenge Program',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GCTE','Global Change and Terrestrial Ecosystems Program',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GDP','Gross Domestic Product',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GEC','Global Environment Change',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GECAFS','Global Environment Change and Food Systems',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GEF','Global Environment Facility',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GenderCC','Gender and Climate Change Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GeoSAS','Geo Space Analytical Services',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GFAR','Global Forum on Agricultural Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GFCS','Global Framework for Climate Services',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GHG','Greenhouse gas',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GIA','Ghana Insurers Association',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GIB Service','Genomics and Integrated Breeding Service',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GIS','Geographic information systems',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GIZ','German Corporation for International Cooperation GmbH',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GLAM','General Large-Area Model',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GLF','Global Landscapes Forum',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GlobalHort','Global Initiative in Horticultural Sciences',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GLOBIOM','IIASA global recursively dynamic partial equilibrium model',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GPS','Global Positioning System',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GRA','Global Research Alliance on Agricultural Greenhouse Gases',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GRiSP','The Global Rice Science Partnership',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GTP','Growth and Transformation Plan',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('GxE','Genotype x Environment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('HQ','Head Quarter',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('HUMBO','Humbo Ethiopia Assisted Natural Regeneration Project',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('I4','Index Insurance Innovation Initiative',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IAASTD','International Assessment of Agricultural Knowledge, Science and Technology for Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IARI','Indian Agricultural Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICAR','Indian Council of Agricultural Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICARDA','International Center for Agricultural Research in the Dry Areas',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICASA','International Consortium for Agricultural Systems Applications',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICCCAD','International Centre for Climate Change and Development, Bangladesh',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICICI','Lombard Insurance Company',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICIPE','International Centre of Insect Physiology and Ecology',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICPAC','Intergovernmental Authority on Drought and Development Climate Prediction and Applications Centre',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICRAF','World Agroforestry Centre',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICRISAT','International Crops Research Institute for the Semi-Arid Tropics',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICSU','International Council for Science',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ICT','Information and communication technology',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IDO','Intermediate Development Outcome',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IDOs','Intermediate Development Outcomes',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IDRC','International Development Research Centre',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IDS','The Institute of Development Studies',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IEA','Independent Evaluation Arrangement',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IER','Institute for Rural Economy of Mali',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IFAD','International Fund for Agricultural Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IFC','International Finance Cooperation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IFFCO','Indian Farmers Fertiliser Cooperative Limited',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IFPRI','International Food Policy Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IFRI','International Forestry Resources and Institutions',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IFS','International Foundation for Science',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IGAD','Intergovernmental Authority on Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IGBP','International Geosphere-Biosphere Programme',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IGP','Indo-Gangetic Plains',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IHSN','International Household Survey Network',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IIAM','Agricultural Research Institute of Mozambique',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IIASA','International Institute for Applied Systems Analysis',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IIED','International Institute for Environment and Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IIPACC','Innovative Insurance Products for the Adaption to Climate Change',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IIRR','International Institute of Rural Reconstruction',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IITA','International Institute for Tropical Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IITM','Indian Institute of Tropical Meteorology',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ILRI','International Livestock Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IMD','India Meteorology Department',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IMPACT','International Model for Policy Analysis of Agricultural Commodities and Trade',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IndMozGoat','Small ruminant value chains as platforms for reducing poverty and increasing food security in dryland areas of India and Mozambique',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('INERA','L''institut de l''environnement et de recherches agricoles',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('INPE','The Brazil Government’s National Institute of Space Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('INR','Indian Rupee',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('INRA','Institut national de la recherche agronomique',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('INSAH','The Sahel Institute; focuses on scientific research in the Sahelian countries',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IP','Intellectual property',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IPAM','Instituto de Pesquisa Ambiental da Amazônia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IPBES','International Panel for Biodiversity and Environmental Services',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IPC','Integrated Phase Classification',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IPCC','Intergovernmental Panel on Climate Change',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IPG','International public good',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IPR','Intellectual property rights',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IRD','Institut de recherche pour le développement (France) / Institute of Research for Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IRI','International Research Institute for Climate and Society',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IRRI','International Rice Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ISC','Independent Steering Committee',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ISFM','Integrated Soil Fertility Management',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ISI','International Scientific Indexing',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ISP','Independent Science Panel, which advises CCAFS',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ISPC','Independent Science and Partnership Council',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ISRA','Senegalese National Agricultural Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ITPGRFA','International Treaty on Plant Genetic Resources for Food and Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ITS','Institute for the Tropics and Subtropics',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IUCN','World Conservation Union',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('IWMI','International Water Management Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('JRC','Joint Research Center',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('KARI','Kenyan Agricultural Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('KDB','Kenya Dairy Board',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('KMD','Kenya Meteorological Department',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('LA','Lead Author (in the IPCC assessment process)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('LAC','Latin America and the Caribbean',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('LAM','Latin America',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('LATC','Local Agro-Technical Commitees',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('LED','Low emission development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('LEI','The Agricultural Economics Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('LP','Learning Platform',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('LTAC','Local Technical Agroclimatic Committee',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('LTHE','Laboratoire d’étude des Transferts en Hydrologie et Environnement',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('M&E','Monitoring and evaluation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MADR','Ministry of Agriculture and Rural Development (Colombia)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MARD','Ministry of Agriculture and Rural Development (Vietnam)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MARLO','Managing Agricultural Research for Learning and Outcomes',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MDG','Millennium Development Goal',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MEL','Monitoring, evaluation and learning',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MELIA','Monitoring, evaluation, impact assessment and learning',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MENA','Middle East and North Africa region',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MICCA','Migration of Climate Change in Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MIS','Management information system',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MIT','Massachusetts Institute of Technology',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MoA','Ministry of Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MoE','Ministry of Environment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MOEF','Ministry of Environment and Forests, Govt of India',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MRV','Monitoring, reporting and verification',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('MSc','Master of Science',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NAAS','National Academy of Agricultural Sciences (India)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NAMA','Nationally Appropriate Mitigation Action',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NAP','National Adaptation Plan',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NAPA','National Adaptation Programmes of Action',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NARC','Nepal Agricultural Research Council',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NARES','National Agricultural Research Extension Systems',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NARI','International Forestry Resources and Institutions',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NARO','National Agricultural Research Organization',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NARO','National Agricultural and Food Research Organization, Japan',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NARS','National Agricultural Research Systems',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NASA-JPL','The Jet Propulsion Laboratory of the National Aeronautics and Space Administration (USA)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NBPGR','National Bureau of Plant Genetic Resources, India',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NCAR','National Center for Atmospheric Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NCCAG','National Color-Coded Agricultural Guide',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NDC','Nationally Determined Contribution',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NDRI','Nepal Development Research Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NEPAD','New Partnership for Africa''s Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NERC','National Environmental Research Council',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NGO','Non-governmental organizations',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NIC','National Insurance Commission (Ghana)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NIDM','National Institute of Disaster Management, India',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NIES','National Institute for Environmental Studies',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NMA','National Meteorology Agency (of Ethiopia)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NMHS','National Meteorological and Hydrological Services',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NMS','National meteorological services',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NR','Natural resources',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NRM','Natural Resource Management',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('NWCF','Nepal Water Conservation Foundation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ODA','Overseas Development Assistance',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('OECD','Organisation for Economic Co-operation and Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('OICR','Outcome Impact Case Report',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PABRA','Pan-Africa Bean Research Alliance',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PAFA','Le Projet d''appui aux filières agricoles (Mali)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PANOS','Global communications network of institutes, focused on international development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PAR','Participatory Action Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PBL','Netherlands Environmental Assessment Agency',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PC','Proof of concept',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PECS','Program on Ecosystem Change and Society (ICSU-UNESCO)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PES','Payments for Environmental Services',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PhD','Doctor of Philosophy',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PICSA','Participatory Integrated Climate Services for Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PIK','Potsdam Institute for Climate Impact Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PIL','Piloting',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PIM','CGIAR Research Program on Policies, Institutions and Markets',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PIRCCA','Policy Information and Response Platform on Climate Change and Rice in ASEAN and its Member Countries',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PMC','Program Management Committee',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('POWB','Plan of Work and Budget',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PRADAN','Professional Assistance for Development Action',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PRESAO','Seasonal Forecast in West Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PROLINNOVA','Promoting local innovation in ecologically-oriented agriculture and natural-resource management',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PSROI','Participatory Social Return of Investment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PSU','Project Support Unit',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('PVP','Plant Variety Protection',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('R&D','Research and development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RAP','Realising the Agricultural Potential of inland valley lowlands in Sub-Saharan Africa while maintaining their environmental services',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RCM','Regional climate model',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RCT','Resource Conserving Technologies',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('REDD+','Reducing emissions from deforestation and forest degradation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RF','Rockefeller Foundation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RG','Reference Group',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RHoMIS','Rural Household Multi-Indicator Survey',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RIO +20','United Nations Conference on Sustainable Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RLP','Regional Learning Partnership',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RMF','Results Monitoring Framework',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ROPPA','Réseau des organizations paysannes et des producteurs agricoles de l’Afrique de l’Ouest (Network of Farmers'' and Agricultural Producers'' Organisations of West Africa)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RPL','Regional Program Leader (CCAFS)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RTB','CGIAR Research Program on Roots, Tubers and Bananas',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RUFORUM','Regional Universities Forum for Capacity Building in Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('RWC','Rice Wheat Consortium',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SA(s)','South Asia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SAARC','South Asian Association for Regional Cooperation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SACAU','South African Confederation of Agricultural Unions',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SADC-PF','Southern African Development Community Parliamentary Forum',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SAF','Southern Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SAI','Sustainable Agriculture Initiative',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SAME','South America',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SAMPLES','Standard Assessment of Agricultural Mitigation Potential and Livelihoods',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SARI','Savannah Agricultural Research Institute (Ghana, West Africa)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SAsia','South Asia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SAUs','State Agricultural Universities',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SBSTA','Subsidiary Body for Scientific and Technological Advice',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SC','Science Council',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SDDR','Senegalese Ministry of Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SDG','Sustainable Development Goal',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SDMC','South Asian Disaster Management Centre',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SDPI','Sustainable Development Policy Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SE Asia','South East Asia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SEA','South East Asia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SEAM','Support for Environmental Assessment and Management',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SECTOR','Source-selective and Emission-adjusted GHG Calculator for Cropland',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SEI','Stockholm Environment Institute',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SESAN','Food and Nutrition Security Secretariat of Guatemala',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SFL','Sustainable Food Lab',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SID','Society for International Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SIMLESA','Sustainable Intensification of Maize-Legume cropping systems for food security in Eastern and Southern Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SLM','Sustainable land management',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SLO','System Level Outcome',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SMART','Specific, Measurable, Achievable, Relevant and Time-Bound',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SNV','Netherlands Development Organization',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SOC','Soil organic carbon',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SPIA','Standing Panel on Impact Assessment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SRF','CGIAR Strategic Results Framework',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SROI','Social Return on Investment',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('SSA','Sub-Saharan Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('START','Global change System for Analysis, Research and Training',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('T1','CCAFS Theme 1 – Adaptation to Progressive Climate change',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('T2','CCAFS Theme 2 – Adaptation through Managing Climate Risk',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('T3','CCAFS Theme 3 – Pro-poor Climate Change Mitigation',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('T4','CCAFS Theme 4 – Integration for Decision-Making',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('T-AGG','Technical Working Group on Agricultural Greenhouse Gases',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('TAMSAT','Tropical Applications of Meteorology using SATellite data and ground-based observations',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('TBC','To Be Confirmed',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('TBD','To Be Determined',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('TIA','Tasmanian Institute of Agricultural Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('TIST','The International Small Group Tree Planting Program',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('TL','Theme Leader (CCAFS)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ToC','Tools of Change',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ToR','Terms of Reference',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('TPEs','Target Plant Environments',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('TSBF','Tropical Soil Biology and Fertility',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('TSU','Technical Support Unit (of the IPCC)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UBC','University of British Columbia',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UCAR','University Corporation for Atmospheric Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UCR','University of California, Riverside',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UEMOA','West African Economic and Monetary Union',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UF','University of Florida',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UK','United Kingdom',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UMB Norway','The Norwegian University of Life Sciences',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UMB USA','The University of Massachusetts Boston US',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UNDP','United Nations Development Programme',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UNED','United Nations Environment and Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UNEP','United Nations Environment Programme',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UNESCO','United Nations Educational, Scientific and Cultural Organization',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UNFCCC','United Nations Framework Convention on Climate Change',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UNFF','United Nations Forum on Forests',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UNREDD','United Nations Collaborative Programme on Reducing Emissions from Deforestation and Forest Degradation in Developing Countries',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UoC','University of Copenhagen',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('USAID','United States Agency for International Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('USD','United States Dollar',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('USDA','The United States Department of Agriculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('USE','Uptake by next user',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UTAS','University of Tasmania',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('UVM','University of Vermont',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('VAM','Vulnerability Analysis and Mapping (World Food Programme)',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('VCS','Voluntary Carbon Standard, a quality standard for voluntary carbon offset industry.',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('VSLA','Village Savings and Loan Association',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('W','Window',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('W1','Portfolio window funding',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('W2','Program window funding',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('W3','Project window funding',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WA','West Africa – one of the CCAFS target regions',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WANA','West Africa and Northern Africa',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WASCAL','West African Science Service Center on Climate Change and Adapted Land Use',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WBCSD','World Business Council for Sustainable Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WCRP','World Climate Research Program',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WECARD','West and Central African Council for Agricultural Research and Development',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WEDO','Women’s Environment and Development Organization',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WEF','World Economic Forum',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WFP','World Food Programme',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WITS','University of the Witwatersrand, Johannesburg',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WLE','CGIAR Research Program on Water, Land and Ecosystems',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WMO','World Meteorological Organization',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WOCAN','Women Organizing for Change in Agriculture & Natural Resources Management',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WorldFish','CIGAR Research Center dedicated to reducing poverty and hunger by improving fisheries and aquaculture',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WSPC','Water Science and Policy Center, University of California, Riverside',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('WUR','Wageningen University and Research',1,SYSDATE(),1081);
INSERT INTO general_acronyms(ACRONYM, DESCRIPTION,IS_ACTIVE, ACTIVE_SINCE,CREATED_BY) VALUES ('ZimGoat','Increasing food security and household income through smallstock market development in Zimbabwe',1,SYSDATE(),1081);
SELECT * FROM general_acronyms;