insert into activities_titles (title, is_active) values ('1.1.1 Development of decision support tools (DSTs) to tailor adaptation interventions and innovations', 1);
insert into activities_titles (title, is_active) values ('1.1.2 Development and participatory assessment of climate information service (CIS) packages', 1);
insert into activities_titles (title, is_active) values ('1.1.3 Support planning and monitoring of investments in agricultural adaptation to climate change.', 1);
insert into activities_titles (title, is_active) values ('1.1.4 Support prioritization of best-bet CSA options for uptake at scale', 1);
insert into activities_titles (title, is_active) values ('1.1.5 Developing financing models for the rollout of prototype CSA and CIS solutions for farmers with private sector engagement', 1);
insert into activities_titles (title, is_active) values ('1.1.6 Policy consistency analysis for regional level CIS and CSA promotion', 1);
insert into activities_titles (title, is_active) values ('1.2.1 Development of ag-data hubs and decision support systems', 1);
insert into activities_titles (title, is_active) values ('1.2.2 Strengthening digital climate advisory services', 1);
insert into activities_titles (title, is_active) values ('1.3.1 Development of ag-data hubs and decision support systems', 1);
insert into activities_titles (title, is_active) values ('1.3.2 Strengthening digital climate advisory services in Eastern and Southern Africa', 1);
insert into activities_titles (title, is_active) values ('2.1.1 Enhance collaboration among Africa-wide and regional institutions.', 1);
insert into activities_titles (title, is_active) values ('2.2.1 Support strengthening of national meteorological real-time services', 1);
insert into activities_titles (title, is_active) values ('2.2.3 Build capacity of public and private sectors next users to support implementation of CSA technology packages', 1);
insert into activities_titles (title, is_active) values ('2.2.4 Develop existing or strengthen new National Frameworks for Climate Services (NFCS)', 1);
insert into activities_titles (title, is_active) values ('2.3.1 Support strengthening of national meteorological real-time services', 1);
insert into activities_titles (title, is_active) values ('2.3.2 Enhance the capacity of public institutions and private firms to provide climate service delivery models', 1);
insert into activities_titles (title, is_active) values ('2.3.3 Build capacity in three focus countries of public and private sector next users to support implementation of CSA technology packages', 1);
insert into activities_titles (title, is_active) values ('2.3.4 Develop existing or strengthen new National Frameworks for Climate Services (NFCS)', 1);
insert into activities_titles (title, is_active) values ('3.1.1 Identification of existing scalable initiatives around climate modeling, early warning systems, and CSA', 1);
insert into activities_titles (title, is_active) values ('3.1.2 Promoting dialogue among participants with the goal of securing agreement on common standards and protocols for delivery of climate advisory services at scale', 1);
insert into activities_titles (title, is_active) values ('3.1.3 Working with regional and continental networks to promote dissemination of climate research results across Africa; and Development of approaches to ensure sustainability of regional and continental initiatives', 1);
insert into activities_titles (title, is_active) values ('3.2.1 Identify and prioritize climate- and gender and social inclusion-smartness of CSA packages', 1);
insert into activities_titles (title, is_active) values ('3.2.2 Create awareness and identify scaling mechanisms for best-bet CSA options', 1);
insert into activities_titles (title, is_active) values ('3.2.4 Develop and promote climate-smart agricultural investment plans in West Africa', 1);
insert into activities_titles (title, is_active) values ('3.3.1 Identify climate- and gender and social inclusion-smartness of CSA packages', 1);
insert into activities_titles (title, is_active) values ('3.3.2 Prioritize and increase awareness of best-bet CSA options and approaches for key value chains', 1);
insert into activities_titles (title, is_active) values ('3.3.3 Integrate climate-smart options and tailored CSI advisory systems for specific value chains', 1);
insert into activities_titles (title, is_active) values ('3.3.4 Develop and promote climate-smart agricultural investment plans in East Africa', 1);