ALTER TABLE progress_target_case_geographic_region RENAME report_synthesis_srf_progress_targets_cases_regions;
ALTER TABLE progress_target_case_geographic_scope RENAME report_synthesis_srf_progress_targets_cases_geographic_scope;
ALTER TABLE report_synthesis_srf_progress_targets_cases_locations RENAME report_synthesis_srf_progress_targets_cases_countries;