CREATE TABLE helldots_comments (
  id bigint NOT NULL AUTO_INCREMENT,
  comment_id varchar(64) NOT NULL,
  page varchar(500) NOT NULL,
  page_query varchar(1000) DEFAULT NULL,
  author_user_id bigint DEFAULT NULL,
  author_name varchar(255) DEFAULT NULL,
  status varchar(20) NOT NULL,
  type varchar(20) DEFAULT NULL,
  priority varchar(10) DEFAULT NULL,
  created_at datetime NOT NULL,
  edited_at datetime DEFAULT NULL,
  resolved_at datetime DEFAULT NULL,
  schema_version int DEFAULT NULL,
  global_unit_id bigint DEFAULT NULL,
  payload json NOT NULL,
  is_active tinyint(1) NOT NULL DEFAULT '1',
  active_since timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  modified_by bigint DEFAULT NULL,
  modification_justification text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  PRIMARY KEY (id),
  UNIQUE KEY helldots_comments_UN (comment_id),
  KEY helldots_comments_page_IDX (page),
  KEY helldots_comments_status_IDX (status),
  KEY helldots_comments_author_FK (author_user_id),
  KEY helldots_comments_users_FK (created_by),
  KEY helldots_comments_users_FK_1 (modified_by),
  KEY helldots_comments_global_units_FK (global_unit_id),
  CONSTRAINT helldots_comments_author_FK FOREIGN KEY (author_user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT helldots_comments_users_FK FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT helldots_comments_users_FK_1 FOREIGN KEY (modified_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT helldots_comments_global_units_FK FOREIGN KEY (global_unit_id) REFERENCES global_units (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE helldots_screenshots (
  id bigint NOT NULL AUTO_INCREMENT,
  comment_id varchar(64) DEFAULT NULL,
  kind varchar(20) NOT NULL,
  file_name varchar(255) NOT NULL,
  relative_path varchar(500) NOT NULL,
  content_type varchar(50) NOT NULL,
  byte_size bigint DEFAULT NULL,
  is_active tinyint(1) NOT NULL DEFAULT '1',
  active_since timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint DEFAULT NULL,
  PRIMARY KEY (id),
  KEY helldots_screenshots_comment_IDX (comment_id),
  KEY helldots_screenshots_users_FK (created_by),
  CONSTRAINT helldots_screenshots_users_FK FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
