CREATE TABLE `project_milestone_disaggregated_target` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `expected_value` decimal(10,2) DEFAULT NULL,
  `achieved_value` decimal(10,2) DEFAULT NULL,
  `disaggregated_target_crp_program_outcome` bigint(20) NOT NULL,
  `project_milestone` bigint(20) NOT NULL,
  `narrative_target` text,
  `narrative_achieved` text,
  `suggested_value` decimal(10,2) DEFAULT NULL,
  `id_phase` bigint(20) DEFAULT NULL,
  `modified_by` bigint(20) DEFAULT NULL,
  `modification_justification` text,
  `created_by` bigint(20) DEFAULT NULL,
  `active_since` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `project_milestone_disaggregated_target__outcome_FK` (`disaggregated_target_crp_program_outcome`),
  KEY `project_milestone_disaggregated_target_project_milestones_FK` (`project_milestone`),
  KEY `project_milestone_disaggregated_target_modified_by` (`modified_by`),
  CONSTRAINT `project_milestone_disaggregated_target__outcome_FK` FOREIGN KEY (`disaggregated_target_crp_program_outcome`) REFERENCES `disaggregated_target_crp_program_outcome` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `project_milestone_disaggregated_target_project_milestones_FK` FOREIGN KEY (`project_milestone`) REFERENCES `project_milestones` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `project_milestone_disaggregated_target_project_milestones_ibfk` FOREIGN KEY (`modified_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `disaggregated_target_project_milestones_phase` FOREIGN KEY (`id_phase`) REFERENCES `phases` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;