CREATE TABLE `disaggregated_target_crp_program_outcome` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `crp_program_outcome_id` bigint(20) NOT NULL,
  `target_name` text,
  `target_description` text,
  `target_unit_id` bigint(20) DEFAULT NULL,
  `target_value` text,
  `bussiness_rule_id` bigint(20) DEFAULT NULL,
  `id_phase` bigint(20) DEFAULT NULL,
  `modified_by` bigint(20) DEFAULT NULL,
  `modification_justification` text,
  `created_by` bigint(20) DEFAULT NULL,
  `active_since` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `disaggregated_target_crp_program_outcome_crp_program_outcomes_FK` (`crp_program_outcome_id`),
  KEY `disaggregated_target_outcome_business_rules_FK` (`bussiness_rule_id`),
  KEY `disaggregated_target_crp_program_outcome_srf_target_units_FK` (`target_unit_id`),
  KEY `disaggregated_target_modified_by` (`modified_by`),
  CONSTRAINT `disaggregated_target_crp_program_outcome_crp_program_outcomes_FK` FOREIGN KEY (`crp_program_outcome_id`) REFERENCES `crp_program_outcomes` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `disaggregated_target_crp_program_outcome_srf_target_units_FK` FOREIGN KEY (`target_unit_id`) REFERENCES `srf_target_units` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `disaggregated_target_outcome_business_rules_FK` FOREIGN KEY (`bussiness_rule_id`) REFERENCES `disaggregated_targets_business_rules` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `disaggregated_target_ibfk` FOREIGN KEY (`modified_by`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `disaggregated_target_phase` FOREIGN KEY (`id_phase`) REFERENCES `phases` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;