/*Geograpic Scope of partnerships*/
update report_synthesis_partnerships set geographic_scope_id = 1 where id =23;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =24;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =25;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =26;
update report_synthesis_partnerships set geographic_scope_id = 3 where id =27;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =28;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =29;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =30;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =31;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =32;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =33;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =34;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =35;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =36;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =37;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =38;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =39;
update report_synthesis_partnerships set geographic_scope_id = 3 where id =40;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =41;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =42;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =43;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =44;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =45;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =46;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =47;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =48;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =49;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =50;
update report_synthesis_partnerships set geographic_scope_id = 2 where id =51;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =52;
update report_synthesis_partnerships set geographic_scope_id = 3 where id =53;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =54;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =55;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =56;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =57;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =58;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =59;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =60;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =61;
update report_synthesis_partnerships set geographic_scope_id = 3 where id =62;
update report_synthesis_partnerships set geographic_scope_id = 3 where id =63;
update report_synthesis_partnerships set geographic_scope_id = 3 where id =64;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =65;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =66;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =67;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =68;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =69;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =70;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =71;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =72;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =73;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =74;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =75;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =76;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =77;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =78;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =79;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =80;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =81;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =82;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =83;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =84;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =85;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =86;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =87;
update report_synthesis_partnerships set geographic_scope_id = 3 where id =88;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =89;

update report_synthesis_partnerships set geographic_scope_id = 1 where id =91;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =92;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =93;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =94;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =95;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =96;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =97;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =98;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =99;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =100;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =101;

update report_synthesis_partnerships set geographic_scope_id = 1 where id =103;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =104;
update report_synthesis_partnerships set geographic_scope_id = 2 where id =105;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =107;
update report_synthesis_partnerships set geographic_scope_id = 3 where id =108;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =109;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =110;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =111;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =112;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =113;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =114;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =115;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =116;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =117;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =118;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =119;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =120;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =121;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =122;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =123;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =124;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =125;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =126;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =127;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =128;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =129;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =130;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =131;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =106;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =132;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =133;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =134;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =135;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =136;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =137;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =138;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =139;
update report_synthesis_partnerships set geographic_scope_id = 2 where id =140;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =141;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =142;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =143;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =144;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =145;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =146;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =149;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =150;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =151;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =152;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =153;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =154;

update report_synthesis_partnerships set geographic_scope_id = 1 where id =155;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =147;
update report_synthesis_partnerships set geographic_scope_id = 2 where id =156;
update report_synthesis_partnerships set geographic_scope_id = 2 where id =157;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =148;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =158;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =159;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =160;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =161;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =162;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =163;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =164;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =165;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =166;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =167;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =168;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =169;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =170;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =171;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =172;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =173;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =174;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =175;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =176;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =177;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =167;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =178;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =179;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =180;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =181;
update report_synthesis_partnerships set geographic_scope_id = 2 where id =182;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =183;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =184;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =185;
update report_synthesis_partnerships set geographic_scope_id = 4 where id =186;
update report_synthesis_partnerships set geographic_scope_id = 1 where id =187;


/* Partnerships Regions */
update report_synthesis_partnerships set region_id = 18 where id =105;
update report_synthesis_partnerships set region_id = 18 where id =156;

/* Partnersips Locations*/
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (27,95) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (27,83) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (27,142) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (27,198) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (40,172) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (40,143) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (53,169) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (53,53) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (62,72) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (62,219) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (63,72) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (63,219) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (64,72) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (64,219) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (88,221) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (88,27) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,115) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,99) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,124) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,154) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,143) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,171) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,172) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,208) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,693) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (108,230) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (24,103) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (26,230) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (28,27) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (30,53) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (31,230) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (32,142) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (33,54) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (35,83) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (36,103) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (37,95) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (41,198) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (44,172) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (46,113) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (52,113) ;

insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (69,83) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (76,103) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (81,72) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (82,158) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (100,53) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (109,115) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (110,115) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (111,115) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (113,221) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (116,72) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (120,83) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (121,159) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (122,219) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (123,219) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (124,219) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (131,36) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (106,36) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (132,36) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (135,142) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (136,68) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (142,90) ;

insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (152,103) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (147,115) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (148,198) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (159,83) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (161,103) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (163,113) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (164,113) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (170,113) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (171,113) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (172,113) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (177,159) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (178,115) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (180,83) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (181,237) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (186,221) ;
insert into report_synthesis_partnerships_countries (partnership_id, loc_element_id) values (167,221) ;

/* CCAFS Policies*/
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values ('Process of developing a new international system of plant germplasm exchange, as part of implementation of the International Treaty on Plant Genetic Resources for Food and Agriculture ITPGRFA.',2121,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values ('At the national level, Bhutan, Burkina Faso, Costa Rica, Côte d’Ivoire, Guatemala, Nepal, Rwanda and Uganda adopted national policies and laws for implementing the ITPGRFA.',2119,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values (' In Madagascar and Benin, new laws were passed to enhance capacity to adapt to climate change by implementing the ITPGRFA and the Nagoya protocol.  [If this needs to be broken down further, please create a row for each - else report this as multicountry, 2 policies]',1952,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values (' Rwanda initiated a national policy framework for climate services under the UN Global Framework for Climate Services',2098,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values ('Kenya launched the Climate Smart Agriculture Strategy 2017‐2026. ',2122,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values ('Informed investments of USD 170 million in India for scaling up the Happy Seeder technology',2039,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values ('Informed investment of  USD 21.5 billion by the Indian Government to provide 2.75 million solar pumps to farmers and farmer cooperatives.  ',2103,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values ('Informed investment of  USD 2 million for a regional Climate Smart Agriculture (CSA) strategy for Central America',2164,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values ('Informed investment of USD 1.6 million for Climate Smart Agriculture (CSA) in Niger',2055,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values ('Informed investment of  USD 1.2 million for scaling up `Underground Taming of Floods for Irrigation` (UTFI) in India',2127,11);
insert into report_synthesis_policies(title, expected_study_id,id_phase)
values ('Informed investment of USD 66 million in Colombia for scaling up Climate Smart Agriculture (CSA) in Cauca, Colombia ',2136,11);
