CREATE TABLE project_innovation_complementary_solutions (
  id bigint NOT NULL AUTO_INCREMENT,
  title text,
  short_title text,
  short_description text,
  project_innovation_type_id bigint DEFAULT NULL,
  project_innovation_function_id bigint DEFAULT NULL,
  is_active tinyint(1) NOT NULL DEFAULT '1',
  active_since timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by bigint NOT NULL,
  modified_by bigint DEFAULT NULL,
  modification_justification text CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci,
  id_phase bigint DEFAULT NULL,
  project_innovation_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  KEY complementary_solution_innovation_functions_FK (project_innovation_function_id),
  KEY complementary_solution_rep_ind_innovation_types_FK (project_innovation_type_id),
  KEY complementary_solution_users_FK (created_by),
  KEY complementary_solution_users_FK_1 (modified_by),
  KEY innovation_complementary_solution_phases_FK (id_phase),
  KEY innovation_complementary_solution_innovations_FK (project_innovation_id),
  CONSTRAINT complementary_solution_innovation_functions_FK FOREIGN KEY (project_innovation_function_id) REFERENCES project_innovation_functions (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT complementary_solution_rep_ind_innovation_types_FK FOREIGN KEY (project_innovation_type_id) REFERENCES rep_ind_innovation_types (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT complementary_solution_users_FK FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT complementary_solution_users_FK_1 FOREIGN KEY (modified_by) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT innovation_complementary_solution_phases_FK FOREIGN KEY (id_phase) REFERENCES phases (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT complementary_solution_innovations_FK FOREIGN KEY (project_innovation_id) REFERENCES project_innovations (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;