--  Auto-generated SQL script #202511130841
INSERT INTO ai_report_configuration (report_title,report_description,button_label,button_link,created_by)
	VALUES ('🧾 AICCRA Report Generator','The AICCRA Report Generator automates the preparation of key narrative and tabular content required for the Annual Report submitted to the World Bank. This service consolidates information from multiple internal sources — including contributions, deliverables, and performance indicators — ensuring consistency, accuracy, and alignment with official reporting structures. It produces templated outputs such as indicator overviews, cumulative milestone tables, and sections like Challenges and Lessons Learned, significantly reducing manual work and accelerating the reporting process to support evidence-based decision-making and accountability.','Go to Report Generator','https://ia.prms.cgiar.org/web',1);
INSERT INTO ai_report_configuration (report_title,report_description,button_label,button_link,created_by)
	VALUES ('💬 AICCRA Chatbot','The AICCRA Chatbot is an interactive assistant designed to answer specific, focused questions about the programs activities, data, and progress. It provides quick, accurate, and contextualized responses drawn from AICCRAs internal knowledge base — helping users retrieve relevant information without navigating full reports or datasets. Ideal for program staff, partners, and stakeholders, the chatbot improves access to institutional knowledge and supports informed decision-making through a conversational and user-friendly interface.

','Go to AICCRA chatbot','https://lvurhov4wryn4pygqxf6tp54uq0jdpgs.lambda-url.us-east-1.on.aws/chatbot-ui',1);
INSERT INTO ai_report_configuration (report_title,report_description,button_label,button_link,created_by)
	VALUES ('🧠 Innovation Metadata Extractor','This tool analyzes innovation-related files to automatically identify and extract key metadata and information. It helps users quickly review all relevant details about an innovation and makes it easy to prepare the metadata for entry into the MARLO system, saving time and improving accuracy.','Go to Innovation Metadata Extractor','https://oxnrkcntlheycdgcnilexrwp4i0tucqz.lambda-url.us-east-1.on.aws/ui',1);
