ALTER TABLE project_innovation_info ADD beneficiaries_narrative text NULL;
ALTER TABLE project_innovation_info ADD intellectual_property_institution_id bigint(20) NULL;
ALTER TABLE project_innovation_info ADD CONSTRAINT project_innovation_info_ibfk_14 FOREIGN KEY (intellectual_property_institution_id) REFERENCES intellectual_property_rights_institutions(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE project_innovation_info ADD has_legal_restrictions tinyint(1) NULL;
ALTER TABLE project_innovation_info ADD has_asset_potential tinyint(1) NULL;
ALTER TABLE project_innovation_info ADD has_further_development tinyint(1) NULL;
ALTER TABLE project_innovation_info ADD other_intellectual_property text NULL;
ALTER TABLE project_innovation_info ADD innovation_importance text NULL;
ALTER TABLE project_innovation_info ADD readiness_scale int(10) NULL;
ALTER TABLE project_innovation_info ADD readiness_reason text NULL;
ALTER TABLE project_innovation_info ADD has_knowledge_methods_and_tools tinyint(1) NULL;
ALTER TABLE project_innovation_info ADD knowledge_tool_uses_narrative text NULL;
ALTER TABLE project_innovation_info ADD knowledge_results_narrative text NULL;
ALTER TABLE project_innovation_info ADD has_knowledge_potential tinyint(10) NULL;
ALTER TABLE project_innovation_info ADD reason_not_knowledge_potential text CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE project_innovation_info ADD has_tool_url tinyint(1) NULL;
ALTER TABLE project_innovation_info ADD reason_not_tool_url text CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
ALTER TABLE project_innovation_info ADD knowledge_collaboration text NULL;
ALTER TABLE project_innovation_info ADD are_users_determined tinyint(1) NULL;