package org.cgiar.ccafs.marlo.data.model;

/**
 * AdUser generated by hbm2java
 */
public class AdUser extends MarloAuditableEntity implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 8719516143850086224L;
  private String login;
  private String firstName;
  private String middleName;
  private String lastName;
  private String email;

  public AdUser() {
  }

  public String getEmail() {
    return this.email;
  }

  public String getFirstName() {
    return this.firstName;
  }


  public String getLastName() {
    return this.lastName;
  }

  public String getLogin() {
    return login;
  }

  public String getMiddleName() {
    return this.middleName;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public void setLogin(String login) {
    this.login = login;
  }


  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }


}

