package org.cgiar.ccafs.marlo.data.model;
// default package
// Generated May 30, 2017 3:06:49 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * CapacityDevelopment generated by hbm2java
 */
public class CapacityDevelopment implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 1L;

  @Expose
  private Long id;

  @Expose
  private CenterProject project;

  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;

  @Expose
  private CenterArea researchArea;

  @Expose
  private Crp crp;

  @Expose
  private CenterProgram researchProgram;

  @Expose
  private String title;

  @Expose
  private CapacityDevelopmentType capdevType;

  @Expose
  private int category;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;

  @Expose
  private String modificationJustification;

  @Expose
  private String ctFirstName;

  @Expose
  private String ctLastName;

  @Expose
  private String ctEmail;

  @Expose
  private Date startDate;

  @Expose
  private Date endDate;

  @Expose
  private Long duration;

  @Expose
  private String durationUnit;

  @Expose
  private Boolean global;

  @Expose
  private Boolean regional;

  @Expose
  private String sGlobal;

  @Expose
  private String sRegional;

  @Expose
  private Integer numParticipants;

  @Expose
  private Integer numMen;

  @Expose
  private Integer numWomen;

  @Expose
  private Integer numOther;

  @Expose
  private String otherDiscipline;

  @Expose
  private String disciplineSuggested;

  @Expose
  private String otherTargetGroup;

  @Expose
  private String targetGroupSuggested;

  @Expose
  private String otherPartner;

  @Expose
  private String partnerSuggested;

  private Set<CapdevLocations> capdevLocations = new HashSet<CapdevLocations>(0);
  private List<CapdevLocations> capDevCountries;
  private List<CapdevLocations> capDevRegions;
  private Set<CapdevDiscipline> capdevDiscipline = new HashSet<CapdevDiscipline>(0);
  private Set<CapdevTargetgroup> capdevTargetgroup = new HashSet<CapdevTargetgroup>(0);
  private Set<CapdevParticipant> capdevParticipant = new HashSet<CapdevParticipant>(0);
  private Set<CapdevOutputs> capdevOutputs = new HashSet<CapdevOutputs>(0);
  private Set<CapdevPartners> capdevPartners = new HashSet<CapdevPartners>(0);
  private Set<CapdevSupportingDocs> capdevSupportingDocs = new HashSet<CapdevSupportingDocs>(0);
  private Set<CenterDeliverable> deliverables = new HashSet<CenterDeliverable>(0);
  private Set<CenterSectionStatus> sectionStatuses = new HashSet<CenterSectionStatus>(0);

  public CapacityDevelopment() {
  }

  public CapacityDevelopment(CenterProject project, User modifiedBy, User createdBy, CenterArea researchArea, Crp crp,
    CenterProgram researchProgram, String title, CapacityDevelopmentType capdevType, int category, boolean active,
    Date activeSince, String modificationJustification, String ctFirstName, String ctLastName, String ctEmail,
    Date startDate, Date endDate, Long duration, String durationUnit, Boolean global, Boolean regional,
    Integer numParticipants, Integer numMen, Integer numWomen, Integer numOther, String otherDiscipline,
    String disciplineSuggested, String otherTargetGroup, String targetGroupSuggested, String otherPartner,
    String partnerSuggeste, Set<CapdevLocations> capdevLocations, Set<CapdevDiscipline> capdevDiscipline,
    Set<CapdevTargetgroup> capdevTargetgroup, Set<CapdevParticipant> capdevParticipant,
    Set<CapdevOutputs> capdevOutputs, Set<CapdevPartners> capdevPartners,
    Set<CapdevSupportingDocs> capdevSupportingDocs) {
    this.project = project;
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.researchArea = researchArea;
    this.crp = crp;
    this.researchProgram = researchProgram;
    this.title = title;
    this.capdevType = capdevType;
    this.category = category;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
    this.ctFirstName = ctFirstName;
    this.ctLastName = ctLastName;
    this.ctEmail = ctEmail;
    this.startDate = startDate;
    this.endDate = endDate;
    this.duration = duration;
    this.durationUnit = durationUnit;
    this.global = global;
    this.regional = regional;
    this.numParticipants = numParticipants;
    this.capdevLocations = capdevLocations;
    this.capdevDiscipline = capdevDiscipline;
    this.capdevTargetgroup = capdevTargetgroup;
    this.capdevParticipant = capdevParticipant;
    this.numMen = numMen;
    this.numWomen = numWomen;
    this.numOther = numOther;
    this.otherDiscipline = otherDiscipline;
    this.disciplineSuggested = disciplineSuggested;
    this.otherTargetGroup = otherTargetGroup;
    this.targetGroupSuggested = targetGroupSuggested;
    this.otherPartner = otherPartner;
    this.partnerSuggested = partnerSuggeste;
    this.capdevOutputs = capdevOutputs;
    this.capdevPartners = capdevPartners;
    this.capdevSupportingDocs = capdevSupportingDocs;
  }


  public CapacityDevelopment(String title, CapacityDevelopmentType capdevType, int category, boolean active,
    String ctFirstName, String ctLastName, String ctEmail, Date startDate) {
    this.title = title;
    this.capdevType = capdevType;
    this.category = category;
    this.active = active;
    this.ctFirstName = ctFirstName;
    this.ctLastName = ctLastName;
    this.ctEmail = ctEmail;
    this.startDate = startDate;
  }


  public Date getActiveSince() {
    return activeSince;
  }

  public List<CapdevLocations> getCapDevCountries() {
    return capDevCountries;
  }

  public Set<CapdevDiscipline> getCapdevDiscipline() {
    return capdevDiscipline;
  }


  public Set<CapdevLocations> getCapdevLocations() {
    return capdevLocations;
  }

  public Set<CapdevOutputs> getCapdevOutputs() {
    return capdevOutputs;
  }

  public Set<CapdevParticipant> getCapdevParticipant() {
    return capdevParticipant;
  }

  public Set<CapdevPartners> getCapdevPartners() {
    return capdevPartners;
  }

  public List<CapdevLocations> getCapDevRegions() {
    return capDevRegions;
  }

  public Set<CapdevSupportingDocs> getCapdevSupportingDocs() {
    return capdevSupportingDocs;
  }


  public Set<CapdevTargetgroup> getCapdevTargetgroup() {
    return capdevTargetgroup;
  }


  public CapacityDevelopmentType getCapdevType() {
    return this.capdevType;
  }


  public int getCategory() {
    return this.category;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public Crp getCrp() {
    return this.crp;
  }


  public String getCtEmail() {
    return this.ctEmail;
  }

  public String getCtFirstName() {
    return this.ctFirstName;
  }

  public String getCtLastName() {
    return this.ctLastName;
  }

  public Set<CenterDeliverable> getDeliverables() {
    return deliverables;
  }

  public String getDisciplineSuggested() {
    return disciplineSuggested;
  }

  public Long getDuration() {
    return duration;
  }

  public String getDurationUnit() {
    return durationUnit;
  }

  public Date getEndDate() {
    return this.endDate;
  }

  public String getEndDateFormat() {
    final String pattern = "yyyy-MM-dd";
    final SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
    String date = "";
    if (this.endDate != null) {
      date = simpleDateFormat.format(this.endDate);
    }
    return date;
  }

  public Boolean getGlobal() {
    return global;
  }

  @Override
  public Long getId() {
    return this.id;
  }

  @Override
  public String getLogDeatil() {
    final StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public String getModificationJustification() {
    return this.modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  public Integer getNumMen() {
    return numMen;
  }

  public Integer getNumOther() {
    return numOther;
  }

  public Integer getNumParticipants() {
    return this.numParticipants;
  }

  public Integer getNumWomen() {
    return numWomen;
  }

  public String getOtherDiscipline() {
    return otherDiscipline;
  }


  public String getOtherPartner() {
    return otherPartner;
  }


  public String getOtherTargetGroup() {
    return otherTargetGroup;
  }

  public String getPartnerSuggested() {
    return partnerSuggested;
  }


  public CenterProject getProject() {
    return this.project;
  }


  public Boolean getRegional() {
    return regional;
  }


  public CenterArea getResearchArea() {
    return this.researchArea;
  }


  public CenterProgram getResearchProgram() {
    return this.researchProgram;
  }


  public Set<CenterSectionStatus> getSectionStatuses() {
    return sectionStatuses;
  }


  public String getsGlobal() {
    return sGlobal;
  }


  public String getsRegional() {
    return sRegional;
  }


  public String getStarDateFormat() {
    final String pattern = "yyyy-MM-dd";
    final SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
    String date = "";
    if (this.startDate != null) {
      date = simpleDateFormat.format(this.startDate);
    }
    return date;
  }


  public Date getStartDate() {
    return this.startDate;
  }


  public String getTargetGroupSuggested() {
    return targetGroupSuggested;
  }


  public String getTitle() {
    return this.title;
  }


  @Override
  public boolean isActive() {
    return this.active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setCapDevCountries(List<CapdevLocations> capDevCountries) {
    this.capDevCountries = capDevCountries;
  }


  public void setCapdevDiscipline(Set<CapdevDiscipline> capdevDiscipline) {
    this.capdevDiscipline = capdevDiscipline;
  }


  public void setCapdevLocations(Set<CapdevLocations> capdevLocations) {
    this.capdevLocations = capdevLocations;
  }


  public void setCapdevOutputs(Set<CapdevOutputs> capdevOutputs) {
    this.capdevOutputs = capdevOutputs;
  }


  public void setCapdevParticipant(Set<CapdevParticipant> capdevParticipant) {
    this.capdevParticipant = capdevParticipant;
  }


  public void setCapdevPartners(Set<CapdevPartners> capdevPartners) {
    this.capdevPartners = capdevPartners;
  }


  public void setCapDevRegions(List<CapdevLocations> capDevRegions) {
    this.capDevRegions = capDevRegions;
  }


  public void setCapdevSupportingDocs(Set<CapdevSupportingDocs> capdevSupportingDocs) {
    this.capdevSupportingDocs = capdevSupportingDocs;
  }


  public void setCapdevTargetgroup(Set<CapdevTargetgroup> capdevTargetgroup) {
    this.capdevTargetgroup = capdevTargetgroup;
  }


  public void setCapdevType(CapacityDevelopmentType capdevType) {
    this.capdevType = capdevType;
  }


  public void setCategory(int category) {
    this.category = category;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }


  public void setCrp(Crp crp) {
    this.crp = crp;
  }


  public void setCtEmail(String ctEmail) {
    this.ctEmail = ctEmail;
  }


  public void setCtFirstName(String ctFirstName) {
    this.ctFirstName = ctFirstName;
  }


  public void setCtLastName(String ctLastName) {
    this.ctLastName = ctLastName;
  }


  public void setDeliverables(Set<CenterDeliverable> deliverables) {
    this.deliverables = deliverables;
  }


  public void setDisciplineSuggested(String disciplineSuggested) {
    this.disciplineSuggested = disciplineSuggested;
  }


  public void setDuration(Long duration) {
    this.duration = duration;
  }


  public void setDurationUnit(String durationUnit) {
    this.durationUnit = durationUnit;
  }


  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }


  public void setGlobal(Boolean global) {
    this.global = global;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setNumMen(Integer numMen) {
    this.numMen = numMen;
  }


  public void setNumOther(Integer numOther) {
    this.numOther = numOther;
  }


  public void setNumParticipants(Integer numParticipants) {
    this.numParticipants = numParticipants;
  }


  public void setNumWomen(Integer numWomen) {
    this.numWomen = numWomen;
  }


  public void setOtherDiscipline(String otherDiscipline) {
    this.otherDiscipline = otherDiscipline;
  }


  public void setOtherPartner(String otherPartner) {
    this.otherPartner = otherPartner;
  }


  public void setOtherTargetGroup(String otherTargetGroup) {
    this.otherTargetGroup = otherTargetGroup;
  }


  public void setPartnerSuggested(String partnerSuggested) {
    this.partnerSuggested = partnerSuggested;
  }


  public void setProject(CenterProject project) {
    this.project = project;
  }


  public void setRegional(Boolean regional) {
    this.regional = regional;
  }


  public void setResearchArea(CenterArea researchArea) {
    this.researchArea = researchArea;
  }

  public void setResearchProgram(CenterProgram researchProgram) {
    this.researchProgram = researchProgram;
  }


  public void setSectionStatuses(Set<CenterSectionStatus> sectionStatuses) {
    this.sectionStatuses = sectionStatuses;
  }


  public void setsGlobal(String sGlobal) {
    this.sGlobal = sGlobal;
  }


  public void setsRegional(String sRegional) {
    this.sRegional = sRegional;
  }


  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }


  public void setTargetGroupSuggested(String targetGroupSuggested) {
    this.targetGroupSuggested = targetGroupSuggested;
  }


  public void setTitle(String title) {
    this.title = title;
  }


}

