package org.cgiar.ccafs.marlo.data.model;
// default package
// Generated Jul 26, 2017 8:32:12 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * CapdevSupportingDocs generated by hbm2java
 */
public class CapdevSupportingDocs extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  @Expose
  private CenterDeliverableType centerDeliverableTypes;

  @Expose
  private CenterDeliverableType deliverableSubtype;

  @Expose
  private CapacityDevelopment capacityDevelopment;

  @Expose
  private String title;

  @Expose
  private Date publicationDate;

  private Set<CapdevSuppDocsDocuments> capdevSuppDocsDocuments = new HashSet<CapdevSuppDocsDocuments>(0);

  public CapdevSupportingDocs() {
  }


  public CapacityDevelopment getCapacityDevelopment() {
    return this.capacityDevelopment;
  }


  public Set<CapdevSuppDocsDocuments> getCapdevSuppDocsDocuments() {
    return capdevSuppDocsDocuments;
  }


  public CenterDeliverableType getCenterDeliverableType() {
    return this.centerDeliverableTypes;
  }

  public CenterDeliverableType getDeliverableSubtype() {
    return deliverableSubtype;
  }

  @Override
  public String getLogDeatil() {
    final StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public Date getPublicationDate() {
    return this.publicationDate;
  }

  public String getTitle() {
    return this.title;
  }


  public void setCapacityDevelopment(CapacityDevelopment capacityDevelopment) {
    this.capacityDevelopment = capacityDevelopment;
  }


  public void setCapdevSuppDocsDocuments(Set<CapdevSuppDocsDocuments> capdevSuppDocsDocuments) {
    this.capdevSuppDocsDocuments = capdevSuppDocsDocuments;
  }

  public void setCenterDeliverableType(CenterDeliverableType centerDeliverableTypes) {
    this.centerDeliverableTypes = centerDeliverableTypes;
  }

  public void setDeliverableSubtype(CenterDeliverableType deliverableSubtype) {
    this.deliverableSubtype = deliverableSubtype;
  }

  public void setPublicationDate(Date publicationDate) {
    this.publicationDate = publicationDate;
  }

  public void setTitle(String title) {
    this.title = title;
  }


}

