package org.cgiar.ccafs.marlo.data.model;

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * CapdevHighestDegree generated by hbm2java
 */
public class CapdevHighestDegree extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  @Expose
  private String name;

  @Expose
  private String description;

  @Expose
  private String acronym;


  public CapdevHighestDegree() {
  }

  public String getAcronym() {
    return this.acronym;
  }


  public String getDescription() {
    return this.description;
  }


  @Override
  public String getLogDeatil() {
    final StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public String getName() {
    return this.name;
  }


  public void setAcronym(String acronym) {
    this.acronym = acronym;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public void setName(String name) {
    this.name = name;
  }


}

