package org.cgiar.ccafs.marlo.data.model;
// default package
// Generated Jul 26, 2017 8:32:12 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * CapdevSuppDocsDocuments generated by hbm2java
 */
public class CapdevSuppDocsDocuments implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  private Long id;
  private User usersByModifiedBy;
  private User usersByCreatedBy;
  private CapdevSupportingDocs capdevSupportingDocs;
  private String link;
  private Boolean active;
  private Date activeSince;
  private String modificationJustification;

  public CapdevSuppDocsDocuments() {
  }

  public CapdevSuppDocsDocuments(User usersByModifiedBy, User usersByCreatedBy,
    CapdevSupportingDocs capdevSupportingDocs, String link, Boolean active, Date activeSince,
    String modificationJustification) {
    this.usersByModifiedBy = usersByModifiedBy;
    this.usersByCreatedBy = usersByCreatedBy;
    this.capdevSupportingDocs = capdevSupportingDocs;
    this.link = link;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  public Boolean getActive() {
    return this.active;
  }

  public Date getActiveSince() {
    return this.activeSince;
  }

  public CapdevSupportingDocs getCapdevSupportingDocs() {
    return this.capdevSupportingDocs;
  }

  public Long getId() {
    return this.id;
  }

  public String getLink() {
    return this.link;
  }

  public String getModificationJustification() {
    return this.modificationJustification;
  }

  public User getUsersByCreatedBy() {
    return this.usersByCreatedBy;
  }

  public User getUsersByModifiedBy() {
    return this.usersByModifiedBy;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCapdevSupportingDocs(CapdevSupportingDocs capdevSupportingDocs) {
    this.capdevSupportingDocs = capdevSupportingDocs;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setLink(String link) {
    this.link = link;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setUsersByCreatedBy(User usersByCreatedBy) {
    this.usersByCreatedBy = usersByCreatedBy;
  }

  public void setUsersByModifiedBy(User usersByModifiedBy) {
    this.usersByModifiedBy = usersByModifiedBy;
  }


}

