package org.cgiar.ccafs.marlo.data.model;
// default package
// Generated Jun 6, 2017 2:29:49 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * CapdevLocations generated by hbm2java
 */
public class CapdevLocations implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  private Long id;
  private LocElement locElement;
  private User usersByModifiedBy;
  private User usersByCreatedBy;
  private CapacityDevelopment capacityDevelopment;
  private boolean active;
  private Date activeSince;
  private String modificationJustification;

  public CapdevLocations() {
  }


  public CapdevLocations(boolean active, Date activeSince) {
    this.active = active;
    this.activeSince = activeSince;
  }

  public CapdevLocations(LocElement locElement, User usersByModifiedBy, User usersByCreatedBy,
    CapacityDevelopment capacityDevelopment, boolean active, Date activeSince, String modificationJustification) {
    this.locElement = locElement;
    this.usersByModifiedBy = usersByModifiedBy;
    this.usersByCreatedBy = usersByCreatedBy;
    this.capacityDevelopment = capacityDevelopment;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  public Date getActiveSince() {
    return this.activeSince;
  }

  public CapacityDevelopment getCapacityDevelopment() {
    return this.capacityDevelopment;
  }

  public Long getId() {
    return this.id;
  }

  public LocElement getLocElement() {
    return this.locElement;
  }

  public String getModificationJustification() {
    return this.modificationJustification;
  }

  public User getUsersByCreatedBy() {
    return this.usersByCreatedBy;
  }

  public User getUsersByModifiedBy() {
    return this.usersByModifiedBy;
  }

  public boolean isActive() {
    return this.active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCapacityDevelopment(CapacityDevelopment capacityDevelopment) {
    this.capacityDevelopment = capacityDevelopment;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setLocElement(LocElement locElement) {
    this.locElement = locElement;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setUsersByCreatedBy(User usersByCreatedBy) {
    this.usersByCreatedBy = usersByCreatedBy;
  }

  public void setUsersByModifiedBy(User usersByModifiedBy) {
    this.usersByModifiedBy = usersByModifiedBy;
  }


}

