package org.cgiar.ccafs.marlo.data.model;
// default package
// Generated Jul 12, 2017 2:20:41 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

/**
 * CapdevPartners generated by hbm2java
 */
public class CapdevPartners implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  private Long id;
  private User modifiedBy;
  private User createdBy;
  private Institution institutions;
  private CapacityDevelopment capacityDevelopment;
  private boolean active;
  private Date activeSince;
  private String modificationJustification;

  public CapdevPartners() {
  }


  public CapdevPartners(CapacityDevelopment capacityDevelopment, boolean active) {
    this.capacityDevelopment = capacityDevelopment;
    this.active = active;
  }

  public CapdevPartners(User modifiedBy, User createdBy, Institution institutions,
    CapacityDevelopment capacityDevelopment, boolean active, Date activeSince, String modificationJustification) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.institutions = institutions;
    this.capacityDevelopment = capacityDevelopment;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  public Date getActiveSince() {
    return this.activeSince;
  }

  public CapacityDevelopment getCapacityDevelopment() {
    return this.capacityDevelopment;
  }

  public User getCreatedBy() {
    return createdBy;
  }

  @Override
  public Long getId() {
    return this.id;
  }

  public Institution getInstitutions() {
    return this.institutions;
  }


  @Override
  public String getLogDeatil() {
    final StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public String getModificationJustification() {
    return this.modificationJustification;
  }

  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  @Override
  public boolean isActive() {
    return this.active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCapacityDevelopment(CapacityDevelopment capacityDevelopment) {
    this.capacityDevelopment = capacityDevelopment;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public void setInstitutions(Institution institutions) {
    this.institutions = institutions;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


}

