package org.cgiar.ccafs.marlo.data.model;
// Generated Dec 12, 2016 3:55:58 PM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * CasesStudies generated by hbm2java
 */
public class CaseStudy implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -2357028162240911773L;


  @Expose
  private Long id;


  @Expose
  private FileDB file;
  @Expose
  private User createdBy;
  @Expose
  private User modifiedBy;
  @Expose
  private String comment;
  @Expose
  private String title;
  @Expose
  private String outcomeStatement;
  @Expose
  private String researchOutputs;
  @Expose
  private String researchPatern;
  @Expose
  private String activities;
  @Expose
  private String nonResearchPartneres;
  @Expose
  private String outputUsers;
  @Expose
  private String evidenceOutcome;
  @Expose
  private String referencesCase;
  @Expose
  private String outputUsed;
  @Expose
  private String researchPartners;
  @Expose
  private String explainIndicatorRelation;
  @Expose
  private Integer year;
  @Expose
  private boolean active;
  @Expose
  private Date activeSince;
  @Expose
  private String modificationJustification;

  private Set<CaseStudyProject> caseStudyProjects = new HashSet<CaseStudyProject>(0);

  private List<CaseStudyProject> projects;
  private Set<SectionStatus> sectionStatuses = new HashSet<SectionStatus>(0);
  private Set<CaseStudyIndicator> caseStudyIndicators = new HashSet<CaseStudyIndicator>(0);
  private List<CaseStudyIndicator> indicators;
  private List<String> caseStudyIndicatorsIds;


  public CaseStudy() {
  }


  public CaseStudy(boolean isActive, Date activeSince) {
    this.active = isActive;
    this.activeSince = activeSince;
  }


  public CaseStudy(FileDB file, User usersByCreatedBy, User usersByModifiedBy, String comment, String title,
    String outcomeStatement, String researchOutputs, String researchPatern, String activities,
    String nonResearchPartneres, String outputUsers, String evidenceOutcome, String referencesCase, String outputUsed,
    String researchPartners, String explainIndicatorRelation, Integer year, boolean isActive, Date activeSince,
    String modificationJustification, Set<CaseStudyProject> caseStudyProjectses) {
    this.file = file;
    this.createdBy = usersByCreatedBy;
    this.modifiedBy = usersByModifiedBy;
    this.comment = comment;
    this.title = title;
    this.outcomeStatement = outcomeStatement;
    this.researchOutputs = researchOutputs;
    this.researchPatern = researchPatern;
    this.activities = activities;
    this.nonResearchPartneres = nonResearchPartneres;
    this.outputUsers = outputUsers;
    this.evidenceOutcome = evidenceOutcome;
    this.referencesCase = referencesCase;
    this.outputUsed = outputUsed;
    this.researchPartners = researchPartners;
    this.explainIndicatorRelation = explainIndicatorRelation;
    this.year = year;
    this.active = isActive;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
    this.caseStudyProjects = caseStudyProjectses;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public String getActivities() {
    return activities;
  }


  public Set<CaseStudyIndicator> getCaseStudyIndicators() {
    return caseStudyIndicators;
  }

  public List<String> getCaseStudyIndicatorsIds() {
    return caseStudyIndicatorsIds;
  }

  public Set<CaseStudyProject> getCaseStudyProjects() {
    return caseStudyProjects;
  }


  public String getComment() {
    return comment;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public String getEvidenceOutcome() {
    return evidenceOutcome;
  }


  public String getExplainIndicatorRelation() {
    return explainIndicatorRelation;
  }

  public FileDB getFile() {
    return file;
  }

  @Override
  public Long getId() {
    return id;
  }

  public List<CaseStudyIndicator> getIndicators() {
    return indicators;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }


  @Override
  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public String getNonResearchPartneres() {
    return nonResearchPartneres;
  }


  public String getOutcomeStatement() {
    return outcomeStatement;
  }


  public String getOutputUsed() {
    return outputUsed;
  }


  public String getOutputUsers() {
    return outputUsers;
  }


  public Project getOwner() {
    for (CaseStudyProject caseStudyProject : caseStudyProjects) {
      if (caseStudyProject.isCreated()) {
        return caseStudyProject.getProject();
      }
    }
    return null;
  }


  public List<CaseStudyProject> getProjects() {
    return projects;
  }


  public String getReferencesCase() {
    return referencesCase;
  }


  public String getResearchOutputs() {
    return researchOutputs;
  }


  public String getResearchPartners() {
    return researchPartners;
  }


  public String getResearchPatern() {
    return researchPatern;
  }


  public Set<SectionStatus> getSectionStatuses() {
    return sectionStatuses;
  }


  public String getTitle() {
    return title;
  }


  public Integer getYear() {
    return year;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setActivities(String activities) {
    this.activities = activities;
  }


  public void setCaseStudyIndicators(Set<CaseStudyIndicator> caseStudyIndicators) {
    this.caseStudyIndicators = caseStudyIndicators;
  }


  public void setCaseStudyIndicatorsIds(List<String> caseStudyIndicatorsIds) {
    this.caseStudyIndicatorsIds = caseStudyIndicatorsIds;
  }


  public void setCaseStudyProjects(Set<CaseStudyProject> caseStudyProjectses) {
    this.caseStudyProjects = caseStudyProjectses;
  }


  public void setComment(String comment) {
    this.comment = comment;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }


  public void setEvidenceOutcome(String evidenceOutcome) {
    this.evidenceOutcome = evidenceOutcome;
  }


  public void setExplainIndicatorRelation(String explainIndicatorRelation) {
    this.explainIndicatorRelation = explainIndicatorRelation;
  }


  public void setFile(FileDB file) {
    this.file = file;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public void setIndicators(List<CaseStudyIndicator> indicators) {
    this.indicators = indicators;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setNonResearchPartneres(String nonResearchPartneres) {
    this.nonResearchPartneres = nonResearchPartneres;
  }


  public void setOutcomeStatement(String outcomeStatement) {
    this.outcomeStatement = outcomeStatement;
  }


  public void setOutputUsed(String outputUsed) {
    this.outputUsed = outputUsed;
  }


  public void setOutputUsers(String outputUsers) {
    this.outputUsers = outputUsers;
  }


  public void setProjects(List<CaseStudyProject> projects) {
    this.projects = projects;
  }


  public void setReferencesCase(String referencesCase) {
    this.referencesCase = referencesCase;
  }


  public void setResearchOutputs(String researchOutputs) {
    this.researchOutputs = researchOutputs;
  }


  public void setResearchPartners(String researchPartners) {
    this.researchPartners = researchPartners;
  }


  public void setResearchPatern(String researchPatern) {
    this.researchPatern = researchPatern;
  }


  public void setSectionStatuses(Set<SectionStatus> sectionStatuses) {
    this.sectionStatuses = sectionStatuses;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public void setYear(Integer year) {
    this.year = year;
  }


}

