package org.cgiar.ccafs.marlo.data.model;
// Generated May 22, 2017 8:52:03 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * CenterDeliverableCrosscutingTheme generated by hbm2java
 */
public class CenterDeliverableCrosscutingTheme extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 8904040043407231409L;


  private CenterDeliverable deliverable;

  @Expose
  private Boolean climateChange;

  @Expose
  private Boolean gender;

  @Expose
  private Boolean youth;

  @Expose
  private Boolean policiesInstitutions;

  @Expose
  private Boolean capacityDevelopment;

  @Expose
  private Boolean bigData;

  @Expose
  private Boolean impactAssessment;

  @Expose
  private Boolean na;


  public CenterDeliverableCrosscutingTheme() {
  }


  public Boolean getBigData() {
    return bigData;
  }


  public Boolean getCapacityDevelopment() {
    return capacityDevelopment;
  }


  public Boolean getClimateChange() {
    return climateChange;
  }


  public CenterDeliverable getDeliverable() {
    return deliverable;
  }


  public Boolean getGender() {
    return gender;
  }


  public Boolean getImpactAssessment() {
    return impactAssessment;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public Boolean getNa() {
    return na;
  }

  public Boolean getPoliciesInstitutions() {
    return policiesInstitutions;
  }

  public Boolean getYouth() {
    return youth;
  }

  public void setBigData(Boolean bigData) {
    this.bigData = bigData;
  }

  public void setCapacityDevelopment(Boolean capacityDevelopment) {
    this.capacityDevelopment = capacityDevelopment;
  }

  public void setClimateChange(Boolean climateChange) {
    this.climateChange = climateChange;
  }

  public void setDeliverable(CenterDeliverable deliverable) {
    this.deliverable = deliverable;
  }

  public void setGender(Boolean gender) {
    this.gender = gender;
  }

  public void setImpactAssessment(Boolean impactAssessment) {
    this.impactAssessment = impactAssessment;
  }

  public void setNa(Boolean na) {
    this.na = na;
  }


  public void setPoliciesInstitutions(Boolean policiesInstitutions) {
    this.policiesInstitutions = policiesInstitutions;
  }


  public void setYouth(Boolean youth) {
    this.youth = youth;
  }


  @Override
  public String toString() {
    return "CenterDeliverableCrosscutingTheme [id=" + this.getId() + ", deliverable=" + deliverable + ", gender="
      + gender + ", youth=" + youth + ", capacityDevelopment=" + capacityDevelopment + "]";
  }


}

