package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 16, 2017 10:28:45 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.math.BigDecimal;

import com.google.gson.annotations.Expose;

/**
 * CenterMonitoringMilestone generated by hbm2java
 */
public class CenterMonitoringMilestone extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = 2895620658888008757L;

  @Expose
  private CenterMonitoringOutcome monitoringOutcome;

  @Expose
  private CenterMilestone researchMilestone;

  @Expose
  private BigDecimal achievedValue;

  @Expose
  private String narrative;

  private int year;


  public CenterMonitoringMilestone() {
  }


  public BigDecimal getAchievedValue() {
    return achievedValue;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public CenterMonitoringOutcome getMonitoringOutcome() {
    return monitoringOutcome;
  }

  public String getNarrative() {
    return narrative;
  }


  public CenterMilestone getResearchMilestone() {
    return researchMilestone;
  }

  public int getYear() {
    return year;
  }

  public void setAchievedValue(BigDecimal achievedValue) {
    this.achievedValue = achievedValue;
  }

  public void setMonitoringOutcome(CenterMonitoringOutcome monitoringOutcome) {
    this.monitoringOutcome = monitoringOutcome;
  }

  public void setNarrative(String narrative) {
    this.narrative = narrative;
  }


  public void setResearchMilestone(CenterMilestone researchMilestone) {
    this.researchMilestone = researchMilestone;
  }

  public void setYear(int year) {
    this.year = year;
  }

  @Override
  public String toString() {
    return "CenterMonitoringMilestone [id=" + this.getId() + ", monitoringOutcome=" + monitoringOutcome
      + ", achievedValue=" + achievedValue + "]";
  }

}

