package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 16, 2017 9:21:01 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * CenterMonitoringOutcome generated by hbm2java
 */
public class CenterMonitoringOutcome extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 6260380573367662563L;

  @Expose
  private CenterOutcome researchOutcome;

  @Expose
  private int year;
  @Expose
  private String statusQuo;

  @Expose
  private String ciatRole;

  @Expose
  private String whatChanged;

  private Set<CenterMonitoringMilestone> monitoringMilestones = new HashSet<CenterMonitoringMilestone>(0);

  private List<CenterMonitoringMilestone> milestones;

  private Set<CenterMonitoringOutcomeEvidence> monitorignOutcomeEvidences =
    new HashSet<CenterMonitoringOutcomeEvidence>(0);

  private List<CenterMonitoringOutcomeEvidence> evidences;


  public CenterMonitoringOutcome() {
  }


  public String getCiatRole() {
    return ciatRole;
  }

  public List<CenterMonitoringOutcomeEvidence> getEvidences() {
    return evidences;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public List<CenterMonitoringMilestone> getMilestones() {
    return milestones;
  }

  public Set<CenterMonitoringOutcomeEvidence> getMonitorignOutcomeEvidences() {
    return monitorignOutcomeEvidences;
  }

  public Set<CenterMonitoringMilestone> getMonitoringMilestones() {
    return monitoringMilestones;
  }

  public CenterOutcome getResearchOutcome() {
    return researchOutcome;
  }

  public String getStatusQuo() {
    return statusQuo;
  }

  public String getWhatChanged() {
    return whatChanged;
  }


  public int getYear() {
    return year;
  }

  public List<CenterMonitoringMilestone> monitoringMilestones() {
    return milestones;
  }


  public void setCiatRole(String ciatRole) {
    this.ciatRole = ciatRole;
  }


  public void setEvidences(List<CenterMonitoringOutcomeEvidence> evidences) {
    this.evidences = evidences;
  }

  public void setMilestones(List<CenterMonitoringMilestone> milestones) {
    this.milestones = milestones;
  }

  public void setMonitorignOutcomeEvidences(Set<CenterMonitoringOutcomeEvidence> monitorignOutcomeEvidences) {
    this.monitorignOutcomeEvidences = monitorignOutcomeEvidences;
  }

  public void setMonitoringMilestones(Set<CenterMonitoringMilestone> monitoringMilestones) {
    this.monitoringMilestones = monitoringMilestones;
  }

  public void setResearchOutcome(CenterOutcome researchOutcome) {
    this.researchOutcome = researchOutcome;
  }


  public void setStatusQuo(String statusQuo) {
    this.statusQuo = statusQuo;
  }


  public void setWhatChanged(String whatChanged) {
    this.whatChanged = whatChanged;
  }

  public void setYear(int year) {
    this.year = year;
  }

  @Override
  public String toString() {
    return "CenterMonitoringOutcome [id=" + this.getId() + ", researchOutcome=" + researchOutcome + ", year=" + year
      + "]";
  }


}

