package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 16, 2017 9:21:01 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * CenterMonitoringOutcome generated by hbm2java
 */
public class CenterMonitoringOutcome implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 6260380573367662563L;

  @Expose
  private Long id;

  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;

  @Expose
  private CenterOutcome researchOutcome;

  @Expose
  private int year;

  @Expose
  private String statusQuo;

  @Expose
  private String ciatRole;

  @Expose
  private String whatChanged;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;

  @Expose
  private String modificationJustification;

  private Set<CenterMonitoringMilestone> monitoringMilestones = new HashSet<CenterMonitoringMilestone>(0);

  private List<CenterMonitoringMilestone> milestones;

  private Set<CenterMonitoringOutcomeEvidence> monitorignOutcomeEvidences =
    new HashSet<CenterMonitoringOutcomeEvidence>(0);

  private List<CenterMonitoringOutcomeEvidence> evidences;


  public CenterMonitoringOutcome() {
  }


  public CenterMonitoringOutcome(CenterOutcome researchOutcome, int year, boolean active) {
    this.researchOutcome = researchOutcome;
    this.year = year;
    this.active = active;
  }


  public CenterMonitoringOutcome(User modifiedBy, User createdBy, CenterOutcome researchOutcome, int year,
    boolean active, Date activeSince, String modificationJustification) {
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.researchOutcome = researchOutcome;
    this.year = year;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  public Date getActiveSince() {
    return activeSince;
  }

  public String getCiatRole() {
    return ciatRole;
  }

  public User getCreatedBy() {
    return createdBy;
  }

  public List<CenterMonitoringOutcomeEvidence> getEvidences() {
    return evidences;
  }

  @Override
  public Long getId() {
    return id;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public List<CenterMonitoringMilestone> getMilestones() {
    return milestones;
  }

  @Override
  public String getModificationJustification() {
    return modificationJustification;
  }

  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  public Set<CenterMonitoringOutcomeEvidence> getMonitorignOutcomeEvidences() {
    return monitorignOutcomeEvidences;
  }

  public Set<CenterMonitoringMilestone> getMonitoringMilestones() {
    return monitoringMilestones;
  }

  public CenterOutcome getResearchOutcome() {
    return researchOutcome;
  }

  public String getStatusQuo() {
    return statusQuo;
  }

  public String getWhatChanged() {
    return whatChanged;
  }


  public int getYear() {
    return year;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public List<CenterMonitoringMilestone> monitoringMilestones() {
    return milestones;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setCiatRole(String ciatRole) {
    this.ciatRole = ciatRole;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setEvidences(List<CenterMonitoringOutcomeEvidence> evidences) {
    this.evidences = evidences;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setMilestones(List<CenterMonitoringMilestone> milestones) {
    this.milestones = milestones;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setMonitorignOutcomeEvidences(Set<CenterMonitoringOutcomeEvidence> monitorignOutcomeEvidences) {
    this.monitorignOutcomeEvidences = monitorignOutcomeEvidences;
  }

  public void setMonitoringMilestones(Set<CenterMonitoringMilestone> monitoringMilestones) {
    this.monitoringMilestones = monitoringMilestones;
  }

  public void setResearchOutcome(CenterOutcome researchOutcome) {
    this.researchOutcome = researchOutcome;
  }


  public void setStatusQuo(String statusQuo) {
    this.statusQuo = statusQuo;
  }


  public void setWhatChanged(String whatChanged) {
    this.whatChanged = whatChanged;
  }

  public void setYear(int year) {
    this.year = year;
  }


}

