package org.cgiar.ccafs.marlo.data.model;
// Generated Feb 28, 2017 11:23:33 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * CenterFundingSourceType generated by hbm2java
 */
public class CenterFundingSourceType extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 3947855061444655147L;

  @Expose
  private String name;

  private Set<CenterProjectFundingSource> projectFundingSources = new HashSet<CenterProjectFundingSource>(0);

  public CenterFundingSourceType() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    CenterFundingSourceType other = (CenterFundingSourceType) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public String getName() {
    return name;
  }

  public Set<CenterProjectFundingSource> getProjectFundingSources() {
    return projectFundingSources;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }


  public void setName(String name) {
    this.name = name;
  }

  public void setProjectFundingSources(Set<CenterProjectFundingSource> projectFundingSources) {
    this.projectFundingSources = projectFundingSources;
  }


  @Override
  public String toString() {
    return "CenterFundingSourceType [id=" + this.getId() + ", name=" + name + "]";
  }

}

