/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;

import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final

/**
 * CrpProgram generated by hbm2java
 */
public class CenterProgram extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -7720585854691931655L;

  @Expose
  private CenterArea researchArea;


  @Expose
  private String name;

  @Expose
  private String acronym;


  private CenterAllTypes programType;

  private Set<CenterLeader> researchLeaders = new HashSet<CenterLeader>(0);


  private Set<CenterTopic> researchTopics = new HashSet<CenterTopic>(0);

  private Set<CenterImpact> researchImpacts = new HashSet<CenterImpact>(0);


  private Set<CenterSectionStatus> sectionStatuses = new HashSet<CenterSectionStatus>(0);

  private Set<CenterProject> projects = new HashSet<CenterProject>(0);


  private Set<CenterSubmission> submissions = new HashSet<CenterSubmission>(0);

  private List<CenterImpact> impacts;


  private List<CenterTopic> topics;

  private List<CenterLeader> leaders;


  @Expose
  private String color;

  @Expose
  private String impactColor;

  private Set<CenterOutput> centerOutputs = new HashSet<CenterOutput>(0);

  public CenterProgram() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    CenterProgram other = (CenterProgram) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public String getAcronym() {
    return this.acronym;
  }

  public Set<CenterOutput> getCenterOutputs() {
    return centerOutputs;
  }

  public String getColor() {
    return color;
  }

  public String getComposedName() {
    return this.acronym + ": " + this.name;
  }

  public String getImpactColor() {
    return impactColor;
  }

  public List<CenterImpact> getImpacts() {
    return impacts;
  }

  public List<CenterLeader> getLeaders() {
    return leaders;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public String getName() {
    return this.name;
  }

  /**
   * @return the programType
   */
  public CenterAllTypes getProgramType() {
    return programType;
  }

  public Set<CenterProject> getProjects() {
    return projects;
  }


  /**
   * @return the researchArea
   */
  public CenterArea getResearchArea() {
    return researchArea;
  }

  public Set<CenterImpact> getResearchImpacts() {
    return researchImpacts;
  }

  /**
   * @return the researchLeaders
   */
  public Set<CenterLeader> getResearchLeaders() {
    return researchLeaders;
  }

  public Set<CenterTopic> getResearchTopics() {
    return researchTopics;
  }

  public Set<CenterSectionStatus> getSectionStatuses() {
    return sectionStatuses;
  }

  public Set<CenterSubmission> getSubmissions() {
    return submissions;
  }

  public List<CenterTopic> getTopics() {
    return topics;
  }

  public void setAcronym(String acronym) {
    this.acronym = acronym;
  }

  public void setCenterOutputs(Set<CenterOutput> centerOutputs) {
    this.centerOutputs = centerOutputs;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public void setImpactColor(String impactColor) {
    this.impactColor = impactColor;
  }


  public void setImpacts(List<CenterImpact> impacts) {
    this.impacts = impacts;
  }


  public void setLeaders(List<CenterLeader> leaders) {
    this.leaders = leaders;
  }

  public void setName(String name) {
    this.name = name;
  }


  /**
   * @param programType the programType to set
   */
  public void setProgramType(CenterAllTypes programType) {
    this.programType = programType;
  }


  public void setProjects(Set<CenterProject> projects) {
    this.projects = projects;
  }


  /**
   * @param researchArea the researchArea to set
   */
  public void setResearchArea(CenterArea researchArea) {
    this.researchArea = researchArea;
  }

  public void setResearchImpacts(Set<CenterImpact> researchImpacts) {
    this.researchImpacts = researchImpacts;
  }


  /**
   * @param researchLeaders the researchLeaders to set
   */
  public void setResearchLeaders(Set<CenterLeader> researchLeaders) {
    this.researchLeaders = researchLeaders;
  }


  public void setResearchTopics(Set<CenterTopic> researchTopics) {
    this.researchTopics = researchTopics;
  }

  public void setSectionStatuses(Set<CenterSectionStatus> sectionStatuses) {
    this.sectionStatuses = sectionStatuses;
  }


  public void setSubmissions(Set<CenterSubmission> submissions) {
    this.submissions = submissions;
  }

  public void setTopics(List<CenterTopic> topics) {
    this.topics = topics;
  }

  @Override
  public String toString() {
    return "CenterProgram [id=" + this.getId() + ", name=" + name + ", programType=" + programType + "]";
  }


}
