package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 13, 2017 1:43:12 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * CenterDeliverableType generated by hbm2java
 */
public class CenterDeliverableType extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -5820694928440158435L;

  @Expose
  private String name;

  @Expose
  private String description;

  @Expose
  private CenterDeliverableType deliverableType;

  private Set<CenterDeliverable> deliverables = new HashSet<CenterDeliverable>(0);

  private Set<CenterDeliverableType> centerDeliverableTypes = new HashSet<CenterDeliverableType>(0);

  public CenterDeliverableType() {
  }

  public Set<CenterDeliverableType> getCenterDeliverableTypes() {
    return centerDeliverableTypes;
  }

  public Set<CenterDeliverable> getDeliverables() {
    return deliverables;
  }


  public CenterDeliverableType getDeliverableType() {
    return deliverableType;
  }


  public String getDescription() {
    return description;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public String getName() {
    return name;
  }


  public void setCenterDeliverableTypes(Set<CenterDeliverableType> centerDeliverableTypes) {
    this.centerDeliverableTypes = centerDeliverableTypes;
  }

  public void setDeliverables(Set<CenterDeliverable> deliverables) {
    this.deliverables = deliverables;
  }

  public void setDeliverableType(CenterDeliverableType deliverableType) {
    this.deliverableType = deliverableType;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public String toString() {
    return "CenterDeliverableType [id=" + this.getId() + ", name=" + name + "]";
  }


}

