package org.cgiar.ccafs.marlo.data.model;
// Generated Feb 15, 2017 8:49:31 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * CenterProjectOutput generated by hbm2java
 */
public class CenterProjectOutput extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -1224397423357742951L;

  @Expose
  private CenterProject project;


  @Expose
  private CenterOutput researchOutput;

  public CenterProjectOutput() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    CenterProjectOutput other = (CenterProjectOutput) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public CenterProject getProject() {
    return project;
  }


  public CenterOutput getResearchOutput() {
    return researchOutput;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }

  public void setProject(CenterProject project) {
    this.project = project;
  }


  public void setResearchOutput(CenterOutput researchOutput) {
    this.researchOutput = researchOutput;
  }


  @Override
  public String toString() {
    return "CenterProjectOutput [id=" + this.getId() + ", project=" + project + ", researchOutput=" + researchOutput
      + "]";
  }


}

