package org.cgiar.ccafs.marlo.data.model;
// Generated May 22, 2017 8:52:03 AM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * CenterDeliverableOutput generated by hbm2java
 */
public class CenterDeliverableOutput extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = -2940234556389524742L;

  @Expose
  private CenterDeliverable deliverable;

  @Expose
  private CenterOutput researchOutput;


  public CenterDeliverableOutput() {
  }


  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    CenterDeliverableOutput other = (CenterDeliverableOutput) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public CenterDeliverable getDeliverable() {
    return deliverable;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public CenterOutput getResearchOutput() {
    return researchOutput;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }


  public void setDeliverable(CenterDeliverable deliverable) {
    this.deliverable = deliverable;
  }


  public void setResearchOutput(CenterOutput researchOutput) {
    this.researchOutput = researchOutput;
  }


  @Override
  public String toString() {
    return "CenterDeliverableOutput [id=" + this.getId() + ", deliverable=" + deliverable + "]";
  }


}

