package org.cgiar.ccafs.marlo.data.model;
// Generated Sep 25, 2017 11:50:22 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * CenterProjectFundingSource generated by hbm2java
 */
public class CenterProjectFundingSource implements java.io.Serializable {


  private static final long serialVersionUID = 5708773221894420200L;


  @Expose
  private Long id;

  @Expose
  private User modifiedBy;


  @Expose
  private User createdBy;

  @Expose
  private CenterFundingSyncType centerFundingSyncType;

  @Expose
  private CenterFundingSourceType centerFundingSourceType;

  @Expose
  private GlobalUnit crp;


  @Expose
  private CenterProject centerProject;

  @Expose
  private String code;

  @Expose
  private String title;

  @Expose
  private String description;

  @Expose
  private Date startDate;

  @Expose
  private Date endDate;

  @Expose
  private Date extensionDate;

  @Expose
  private String originalDonor;

  @Expose
  private String directDonor;

  @Expose
  private Double totalAmount;

  @Expose
  private boolean sync;

  @Expose
  private Date syncDate;

  @Expose
  private boolean autoFill;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;

  @Expose
  private String modificationJustification;

  public CenterProjectFundingSource() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    CenterProjectFundingSource other = (CenterProjectFundingSource) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }

  public Date getActiveSince() {
    return activeSince;
  }

  public CenterFundingSourceType getCenterFundingSourceType() {
    return centerFundingSourceType;
  }

  public CenterFundingSyncType getCenterFundingSyncType() {
    return centerFundingSyncType;
  }

  public CenterProject getCenterProject() {
    return centerProject;
  }

  public String getCode() {
    return code;
  }

  public User getCreatedBy() {
    return createdBy;
  }

  public GlobalUnit getCrp() {
    return crp;
  }

  public String getDescription() {
    return description;
  }


  public String getDirectDonor() {
    return directDonor;
  }


  public Date getEndDate() {
    return endDate;
  }


  public Date getExtensionDate() {
    return extensionDate;
  }


  public Long getId() {
    return id;
  }


  public String getModificationJustification() {
    return modificationJustification;
  }


  public User getModifiedBy() {
    return modifiedBy;
  }


  public String getOriginalDonor() {
    return originalDonor;
  }


  public Date getStartDate() {
    return startDate;
  }


  public Date getSyncDate() {
    return syncDate;
  }


  public String getTitle() {
    return title;
  }


  public Double getTotalAmount() {
    return totalAmount;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }


  public boolean isActive() {
    return active;
  }


  public boolean isAutoFill() {
    return autoFill;
  }


  public boolean isSync() {
    return sync;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setAutoFill(boolean autoFill) {
    this.autoFill = autoFill;
  }


  public void setCenterFundingSourceType(CenterFundingSourceType centerFundingSourceType) {
    this.centerFundingSourceType = centerFundingSourceType;
  }

  public void setCenterFundingSyncType(CenterFundingSyncType centerFundingSyncType) {
    this.centerFundingSyncType = centerFundingSyncType;
  }

  public void setCenterProject(CenterProject centerProject) {
    this.centerProject = centerProject;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setCrp(GlobalUnit crp) {
    this.crp = crp;
  }


  public void setDescription(String description) {
    this.description = description;
  }

  public void setDirectDonor(String directDonor) {
    this.directDonor = directDonor;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  public void setExtensionDate(Date extensionDate) {
    this.extensionDate = extensionDate;
  }


  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setOriginalDonor(String originalDonor) {
    this.originalDonor = originalDonor;
  }

  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  public void setSync(boolean sync) {
    this.sync = sync;
  }

  public void setSyncDate(Date syncDate) {
    this.syncDate = syncDate;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public void setTotalAmount(Double totalAmount) {
    this.totalAmount = totalAmount;
  }


}

