/*****************************************************************
 * This file is part of CCAFS Planning and Reporting Platform.
 * CCAFS P&R is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * CCAFS P&R is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with CCAFS P&R. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/

package org.cgiar.ccafs.marlo.data.model;
// Generated May 17, 2016 9:53:46 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Crps generated by hbm2java
 */
public class Crp implements java.io.Serializable {


  private static final long serialVersionUID = 6299077992797380051L;
  private Long id;
  private String name;
  private Set<CrpUser> crpUserses = new HashSet<CrpUser>(0);
  private Set<Role> roleses = new HashSet<Role>(0);
  private Set<CrpParameter> crpParameterses = new HashSet<CrpParameter>(0);

  public Crp() {
  }


  public Crp(String name) {
    this.name = name;
  }

  public Crp(String name, Set<CrpUser> crpUserses, Set<Role> roleses, Set<CrpParameter> crpParameterses) {
    this.name = name;
    this.crpUserses = crpUserses;
    this.roleses = roleses;
    this.crpParameterses = crpParameterses;
  }

  public Set<CrpParameter> getCrpParameterses() {
    return this.crpParameterses;
  }

  public Set<CrpUser> getCrpUserses() {
    return this.crpUserses;
  }

  public Long getId() {
    return this.id;
  }

  public String getName() {
    return this.name;
  }

  public Set<Role> getRoleses() {
    return this.roleses;
  }

  public void setCrpParameterses(Set<CrpParameter> crpParameterses) {
    this.crpParameterses = crpParameterses;
  }

  public void setCrpUserses(Set<CrpUser> crpUserses) {
    this.crpUserses = crpUserses;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setRoleses(Set<Role> roleses) {
    this.roleses = roleses;
  }


}

