/*****************************************************************
 * This file is part of CCAFS Planning and Reporting Platform.
 * CCAFS P&R is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * CCAFS P&R is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with CCAFS P&R. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final


/**
 * CrpClusterOfActivity generated by hbm2java
 */
public class CrpClusterOfActivity implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = -6392709700346014366L;
  private String id;
  private CrpProgram crpProgram;
  private String description;

  public CrpClusterOfActivity() {
  }

  public CrpClusterOfActivity(String id, CrpProgram crpProgram, String description) {
    this.id = id;
    this.crpProgram = crpProgram;
    this.description = description;
  }

  public CrpProgram getCrpProgram() {
    return this.crpProgram;
  }

  public String getDescription() {
    return this.description;
  }

  public String getId() {
    return this.id;
  }

  public void setCrpProgram(CrpProgram crpProgram) {
    this.crpProgram = crpProgram;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setId(String id) {
    this.id = id;
  }


}

