/*
 * This file is part of Managing Agricultural Research for Learning & *CCAFS P&R is free software:you can redistribute
 * it and/or
 * modify*it under the terms of the GNU General Public License as published by*the Free Software Foundation,either
 * version 3 of the License,or*at your option)any later version.*CCAFS P&R is distributed in the hope that it will be
 * useful,*but WITHOUT ANY WARRANTY;without even the implied warranty of*MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.See the*GNU General Public License for more details.*You should have received a copy of the GNU General
 * Public License*along with CCAFS P&R.If not,see<http:// www.gnu.org/licenses/>.
 *****************************************************************/

package org.cgiar.ccafs.marlo.data.model;
// Generated Jun 23, 2016 11:32:10 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * CrpClusterActivityLeader generated by hbm2java
 */
public class CrpClusterActivityLeader implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -5736083093255018407L;


  @Expose
  private Long id;


  @Expose
  private CrpClusterOfActivity crpClusterOfActivity;
  @Expose
  private User modifiedBy;
  @Expose
  private User user;
  @Expose
  private User createdBy;
  @Expose
  private boolean active;
  @Expose
  private Date activeSince;
  @Expose
  private String modificationJustification;

  public CrpClusterActivityLeader() {
  }

  public CrpClusterActivityLeader(CrpClusterOfActivity crpClusterOfActivities, User usersByModifiedBy,
    User usersByUserId, boolean isActive, Date activeSince, String modificationJustification) {
    this.crpClusterOfActivity = crpClusterOfActivities;
    this.modifiedBy = usersByModifiedBy;
    this.user = usersByUserId;
    this.active = isActive;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  public CrpClusterActivityLeader(CrpClusterOfActivity crpClusterOfActivities, User usersByModifiedBy,
    User usersByUserId, User usersByCreatedBy, boolean isActive, Date activeSince, String modificationJustification) {
    this.crpClusterOfActivity = crpClusterOfActivities;
    this.modifiedBy = usersByModifiedBy;
    this.user = usersByUserId;
    this.createdBy = usersByCreatedBy;
    this.active = isActive;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    CrpClusterActivityLeader other = (CrpClusterActivityLeader) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }


  public Date getActiveSince() {
    return this.activeSince;
  }

  public User getCreatedBy() {
    return this.createdBy;
  }

  public CrpClusterOfActivity getCrpClusterOfActivity() {
    return this.crpClusterOfActivity;
  }

  @Override
  public Long getId() {
    return this.id;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public String getModificationJustification() {
    return this.modificationJustification;
  }

  @Override
  public User getModifiedBy() {
    return this.modifiedBy;
  }

  public User getUser() {
    return this.user;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }

  @Override
  public boolean isActive() {
    return this.active;
  }


  public void setActive(boolean isActive) {
    this.active = isActive;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User usersByCreatedBy) {
    this.createdBy = usersByCreatedBy;
  }

  public void setCrpClusterOfActivity(CrpClusterOfActivity crpClusterOfActivities) {
    this.crpClusterOfActivity = crpClusterOfActivities;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User usersByModifiedBy) {
    this.modifiedBy = usersByModifiedBy;
  }

  public void setUser(User usersByUserId) {
    this.user = usersByUserId;
  }


  @Override
  public String toString() {
    return "CrpClusterActivityLeader [id=" + id + ", crpClusterOfActivity=" + crpClusterOfActivity + ", user=" + user
      + "]";
  }


}

