/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final

import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * CrpClusterOfActivity generated by hbm2java
 */
public class CrpClusterOfActivity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -6392709700346014366L;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;

  private List<ProjectClusterActivity> clusterActivities;

  @Expose
  private User createdBy;

  private Set<CrpClusterActivityLeader> crpClusterActivityLeaders = new HashSet<CrpClusterActivityLeader>(0);

  private Set<CrpClusterKeyOutput> crpClusterKeyOutputs = new HashSet<CrpClusterKeyOutput>(0);

  @Expose
  private CrpProgram crpProgram;

  @Expose
  private String description;


  @Expose
  private Long id;

  @Expose
  private Phase phase;

  @Expose
  private String identifier;


  private List<CrpClusterKeyOutput> keyOutputs;

  private List<CrpClusterActivityLeader> leaders;

  @Expose
  private String modificationJustification;

  @Expose
  private User modifiedBy;

  private Set<ProjectClusterActivity> projectClusterActivities = new HashSet<ProjectClusterActivity>(0);

  public CrpClusterOfActivity() {
  }

  public CrpClusterOfActivity(Long id, CrpProgram crpProgram, String description) {
    this.id = id;
    this.crpProgram = crpProgram;
    this.description = description;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    CrpClusterOfActivity other = (CrpClusterOfActivity) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }

  public Date getActiveSince() {
    return activeSince;
  }

  public List<ProjectClusterActivity> getClusterActivities() {
    return clusterActivities;
  }

  public String getComposedName() {
    if (this.getIdentifier() != null && !this.getIdentifier().isEmpty()) {
      return this.getIdentifier() + " : " + this.description;
    } else {
      return description;
    }
  }

  public User getCreatedBy() {
    return createdBy;
  }


  public Set<CrpClusterActivityLeader> getCrpClusterActivityLeaders() {
    return crpClusterActivityLeaders;
  }


  public Set<CrpClusterKeyOutput> getCrpClusterKeyOutputs() {
    return crpClusterKeyOutputs;
  }


  public CrpProgram getCrpProgram() {
    return this.crpProgram;
  }


  public String getDescription() {
    return description;
  }


  @Override
  public Long getId() {
    return this.id;
  }

  public String getIdentifier() {
    return identifier;
  }

  public List<CrpClusterKeyOutput> getKeyOutputs() {
    return keyOutputs;
  }

  public List<CrpClusterActivityLeader> getLeaders() {
    return leaders;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  public Phase getPhase() {
    return phase;
  }


  public Set<ProjectClusterActivity> getProjectClusterActivities() {
    return projectClusterActivities;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }

  @Override
  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setClusterActivities(List<ProjectClusterActivity> clusterActivities) {
    this.clusterActivities = clusterActivities;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setCrpClusterActivityLeaders(Set<CrpClusterActivityLeader> crpClusterActivityLeaders) {
    this.crpClusterActivityLeaders = crpClusterActivityLeaders;
  }

  public void setCrpClusterKeyOutputs(Set<CrpClusterKeyOutput> crpClusterKeyOutputs) {
    this.crpClusterKeyOutputs = crpClusterKeyOutputs;
  }

  public void setCrpProgram(CrpProgram crpProgram) {
    this.crpProgram = crpProgram;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public void setKeyOutputs(List<CrpClusterKeyOutput> keyOutputs) {
    this.keyOutputs = keyOutputs;
  }

  public void setLeaders(List<CrpClusterActivityLeader> leaders) {
    this.leaders = leaders;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setPhase(Phase phase) {
    this.phase = phase;
  }

  public void setProjectClusterActivities(Set<ProjectClusterActivity> projectClusterActivities) {
    this.projectClusterActivities = projectClusterActivities;
  }

  @Override
  public String toString() {
    return id.toString();
  }


}

