package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 3, 2017 1:26:41 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CrpIndicators generated by hbm2java
 */
public class CrpIndicator implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = -6140435298426995366L;
  private Long id;
  private CrpIndicatorType crpIndicatorType;
  private String serial;
  private String name;
  private String description;
  private boolean active;
  private Date dateAdded;
  private Set<CrpIndicatorReport> crpIndicatorReports = new HashSet<CrpIndicatorReport>(0);

  public CrpIndicator() {
  }


  public CrpIndicator(CrpIndicatorType crpIndicatorType, String serial, String name, String description,
    boolean isActive, Date dateAdded) {
    this.crpIndicatorType = crpIndicatorType;
    this.serial = serial;
    this.name = name;
    this.description = description;
    this.active = isActive;
    this.dateAdded = dateAdded;
  }

  public CrpIndicator(CrpIndicatorType crpIndicatorType, String serial, String name, String description,
    boolean isActive, Date dateAdded, Set<CrpIndicatorReport> crpIndicatorReportses) {
    this.crpIndicatorType = crpIndicatorType;
    this.serial = serial;
    this.name = name;
    this.description = description;
    this.active = isActive;
    this.dateAdded = dateAdded;
    this.crpIndicatorReports = crpIndicatorReportses;
  }


  public Set<CrpIndicatorReport> getCrpIndicatorReports() {
    return crpIndicatorReports;
  }


  public CrpIndicatorType getCrpIndicatorType() {
    return crpIndicatorType;
  }


  public Date getDateAdded() {
    return dateAdded;
  }


  public String getDescription() {
    return description;
  }


  public Long getId() {
    return id;
  }


  public String getName() {
    return name;
  }


  public String getSerial() {
    return serial;
  }


  public boolean isActive() {
    return active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setCrpIndicatorReports(Set<CrpIndicatorReport> crpIndicatorReportses) {
    this.crpIndicatorReports = crpIndicatorReportses;
  }


  public void setCrpIndicatorType(CrpIndicatorType crpIndicatorType) {
    this.crpIndicatorType = crpIndicatorType;
  }


  public void setDateAdded(Date dateAdded) {
    this.dateAdded = dateAdded;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public void setName(String name) {
    this.name = name;
  }


  public void setSerial(String serial) {
    this.serial = serial;
  }


}

