/*****************************************************************
 * This file is part of CCAFS Planning and Reporting Platform.
 * CCAFS P&R is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * CCAFS P&R is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with CCAFS P&R. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final


import java.math.BigDecimal;

/**
 * CrpMilestone generated by hbm2java
 */
public class CrpMilestone implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 4398175741401855358L;
  private Long id;
  private CrpProgramOutcome crpProgramOutcomes;
  private SrfTargetUnit srfTargetUnits;
  private String title;
  private int year;
  private BigDecimal value;

  public CrpMilestone() {
  }

  public CrpMilestone(CrpProgramOutcome crpProgramOutcomes, SrfTargetUnit srfTargetUnits, String title, int year,
    BigDecimal value) {
    this.crpProgramOutcomes = crpProgramOutcomes;
    this.srfTargetUnits = srfTargetUnits;
    this.title = title;
    this.year = year;
    this.value = value;
  }

  public CrpProgramOutcome getCrpProgramOutcomes() {
    return this.crpProgramOutcomes;
  }

  public Long getId() {
    return this.id;
  }

  public SrfTargetUnit getSrfTargetUnits() {
    return this.srfTargetUnits;
  }

  public String getTitle() {
    return this.title;
  }

  public BigDecimal getValue() {
    return this.value;
  }

  public int getYear() {
    return this.year;
  }

  public void setCrpProgramOutcomes(CrpProgramOutcome crpProgramOutcomes) {
    this.crpProgramOutcomes = crpProgramOutcomes;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setSrfTargetUnits(SrfTargetUnit srfTargetUnits) {
    this.srfTargetUnits = srfTargetUnits;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }

  public void setYear(int year) {
    this.year = year;
  }


}

