/*****************************************************************
 * This file is part of CCAFS Planning and Reporting Platform.
 * CCAFS P&R is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * CCAFS P&R is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with CCAFS P&R. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CrpProgramOutcome generated by hbm2java
 */
public class CrpProgramOutcome implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 3014520962149158601L;
  private Long id;
  private CrpProgram crpProgram;
  private SrfTargetUnit srfTargetUnit;
  private String description;
  private int year;
  private BigDecimal value;
  private Set<CrpOutcomeSubIdo> crpOutcomeSubIdos = new HashSet<CrpOutcomeSubIdo>(0);
  private Set<CrpMilestone> crpMilestones = new HashSet<CrpMilestone>(0);
  private boolean active;

  public CrpProgramOutcome() {
  }

  public CrpProgramOutcome(CrpProgram crpProgram, SrfTargetUnit srfTargetUnit, String description, int year,
    BigDecimal value) {
    this.crpProgram = crpProgram;
    this.srfTargetUnit = srfTargetUnit;
    this.description = description;
    this.year = year;
    this.value = value;
  }

  public CrpProgramOutcome(CrpProgram crpProgram, SrfTargetUnit srfTargetUnit, String description, int year,
    BigDecimal value, Set<CrpOutcomeSubIdo> crpOutcomeSubIdos, Set<CrpMilestone> crpMilestones) {
    this.crpProgram = crpProgram;
    this.srfTargetUnit = srfTargetUnit;
    this.description = description;
    this.year = year;
    this.value = value;
    this.crpOutcomeSubIdos = crpOutcomeSubIdos;
    this.crpMilestones = crpMilestones;
  }


  public Set<CrpMilestone> getCrpMilestones() {
    return this.crpMilestones;
  }

  public Set<CrpOutcomeSubIdo> getCrpOutcomeSubIdos() {
    return this.crpOutcomeSubIdos;
  }

  public CrpProgram getCrpProgram() {
    return this.crpProgram;
  }

  public String getDescription() {
    return this.description;
  }

  public Long getId() {
    return this.id;
  }

  public SrfTargetUnit getSrfTargetUnit() {
    return this.srfTargetUnit;
  }

  public BigDecimal getValue() {
    return this.value;
  }

  public int getYear() {
    return this.year;
  }

  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setCrpMilestones(Set<CrpMilestone> crpMilestones) {
    this.crpMilestones = crpMilestones;
  }

  public void setCrpOutcomeSubIdos(Set<CrpOutcomeSubIdo> crpOutcomeSubIdos) {
    this.crpOutcomeSubIdos = crpOutcomeSubIdos;
  }

  public void setCrpProgram(CrpProgram crpProgram) {
    this.crpProgram = crpProgram;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setSrfTargetUnit(SrfTargetUnit srfTargetUnit) {
    this.srfTargetUnit = srfTargetUnit;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }

  public void setYear(int year) {
    this.year = year;
  }


}

