package org.cgiar.ccafs.marlo.data.model;
// Generated May 17, 2017 3:36:29 PM by Hibernate Tools 4.3.1.Final

/**
 * CustomParameter generated by hbm2java
 */
public class CustomParameter extends MarloAuditableEntity implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 9127311887995427567L;

  private GlobalUnit crp;


  private Parameter parameter;

  private String value;

  public CustomParameter() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }

    CustomParameter other = (CustomParameter) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public GlobalUnit getCrp() {
    return crp;
  }


  public Parameter getParameter() {
    return parameter;
  }


  public String getValue() {
    return value;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }


  public void setCrp(GlobalUnit crp) {
    this.crp = crp;
  }


  public void setParameter(Parameter parameter) {
    this.parameter = parameter;
  }


  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public String toString() {
    return "CustomParameter [id=" + this.getId() + ", crp=" + crp + ", parameter=" + parameter + ", value=" + value
      + "]";
  }


}

