package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 26, 2017 10:34:59 AM by Hibernate Tools 4.3.1.Final

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * DeliverableCrps generated by hbm2java
 */
public class DeliverableCrp implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = 3934374948729277454L;
  @Expose
  private Long id;
  @Expose
  private CrpProgram crpProgram;
  @Expose
  private Crp crp;
  private Deliverable deliverable;

  public DeliverableCrp() {
  }

  public DeliverableCrp(CrpProgram crpProgram, Crp crp, Deliverable deliverable) {
    this.crpProgram = crpProgram;
    this.crp = crp;
    this.deliverable = deliverable;
  }

  public Crp getCrp() {
    return crp;
  }

  public CrpProgram getCrpProgram() {
    return crpProgram;
  }

  public Deliverable getDeliverable() {
    return deliverable;
  }

  @Override
  public Long getId() {
    return id;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  @Override
  public String getModificationJustification() {

    return "";
  }


  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }


  @Override
  public boolean isActive() {

    return true;
  }


  public void setCrp(Crp crp) {
    this.crp = crp;
  }


  public void setCrpProgram(CrpProgram crpProgram) {
    this.crpProgram = crpProgram;
  }


  public void setDeliverable(Deliverable deliverable) {
    this.deliverable = deliverable;
  }


  public void setId(Long id) {
    this.id = id;
  }


}

