package org.cgiar.ccafs.marlo.data.model;
// Generated Nov 16, 2016 3:04:23 PM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * DeliverableGenderLevel generated by hbm2java
 */
public class DeliverableGenderLevel extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -7968176539522071626L;

  @Expose
  private Deliverable deliverable;
  @Expose
  private long genderLevel;

  private String nameGenderLevel;

  private String descriptionGenderLevel;

  @Expose
  private Phase phase;

  public DeliverableGenderLevel() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    DeliverableGenderLevel other = (DeliverableGenderLevel) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public Deliverable getDeliverable() {
    return deliverable;
  }

  public String getDescriptionGenderLevel() {
    return descriptionGenderLevel;
  }


  public long getGenderLevel() {
    return genderLevel;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }


  public String getNameGenderLevel() {
    return nameGenderLevel;
  }


  public Phase getPhase() {
    return phase;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }

  public void setDeliverable(Deliverable deliverable) {
    this.deliverable = deliverable;
  }


  public void setDescriptionGenderLevel(String descriptionGenderLevel) {
    this.descriptionGenderLevel = descriptionGenderLevel;
  }


  public void setGenderLevel(long genderLevel) {
    this.genderLevel = genderLevel;
  }

  public void setNameGenderLevel(String nameGenderLevel) {
    this.nameGenderLevel = nameGenderLevel;
  }

  public void setPhase(Phase phase) {
    this.phase = phase;
  }

  @Override
  public String toString() {
    return "DeliverableGenderLevel [id=" + this.getId() + ", deliverable=" + deliverable + ", genderLevel="
      + genderLevel + ", nameGenderLevel=" + nameGenderLevel + ", descriptionGenderLevel=" + descriptionGenderLevel
      + "]";
  }


}

