package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 26, 2017 3:46:03 PM by Hibernate Tools 4.3.1.Final

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * DeliverableUsers generated by hbm2java
 */
public class DeliverableUser implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = 3729938233742430974L;
  @Expose
  private Long id;

  private Deliverable deliverable;
  @Expose
  private String firstName;
  @Expose
  private String lastName;
  @Expose
  private String elementId;

  public DeliverableUser() {
  }

  public DeliverableUser(Deliverable deliverable, String firstName, String lastName, String elementId) {
    this.deliverable = deliverable;
    this.firstName = firstName;
    this.lastName = lastName;
    this.elementId = elementId;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    DeliverableUser other = (DeliverableUser) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }


  public Deliverable getDeliverable() {
    return this.deliverable;
  }

  public String getElementId() {
    return this.elementId;
  }

  public String getFirstName() {
    return this.firstName;
  }


  @Override
  public Long getId() {
    return this.id;
  }

  public String getLastName() {
    return this.lastName;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public String getModificationJustification() {

    return "";
  }

  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }

  @Override
  public boolean isActive() {

    return true;
  }

  public void setDeliverable(Deliverable deliverable) {
    this.deliverable = deliverable;
  }

  public void setElementId(String elementId) {
    this.elementId = elementId;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


}

