package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 26, 2017 3:46:03 PM by Hibernate Tools 4.3.1.Final


/**
 * DeliverableUsers generated by hbm2java
 */
public class DeliverableUser implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 3729938233742430974L;
  private Long id;
  private Deliverable deliverable;
  private String firstName;
  private String lastName;
  private String elementId;

  public DeliverableUser() {
  }

  public DeliverableUser(Deliverable deliverable, String firstName, String lastName, String elementId) {
    this.deliverable = deliverable;
    this.firstName = firstName;
    this.lastName = lastName;
    this.elementId = elementId;
  }

  public Deliverable getDeliverable() {
    return this.deliverable;
  }

  public String getElementId() {
    return this.elementId;
  }

  public String getFirstName() {
    return this.firstName;
  }

  public Long getId() {
    return this.id;
  }

  public String getLastName() {
    return this.lastName;
  }

  public void setDeliverable(Deliverable deliverable) {
    this.deliverable = deliverable;
  }

  public void setElementId(String elementId) {
    this.elementId = elementId;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


}

