package org.cgiar.ccafs.marlo.data.model;

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

// Generated Jan 6, 2017 8:46:55 AM by Hibernate Tools 4.3.1.Final


/**
 * FundingSourceInstitutions generated by hbm2java
 */
public class FundingSourceInstitution implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -3682242088869157772L;
  @Expose
  private Long id;

  private FundingSource fundingSource;
  @Expose
  private Institution institution;


  public FundingSourceInstitution() {
  }

  public FundingSourceInstitution(FundingSource fundingSource, Institution institution) {
    this.fundingSource = fundingSource;
    this.institution = institution;
  }

  public FundingSource getFundingSource() {
    return this.fundingSource;
  }

  @Override
  public Long getId() {
    return this.id;
  }

  public Institution getInstitution() {
    return this.institution;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public String getModificationJustification() {
    // TODO Auto-generated method stub
    return "";
  }

  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }

  @Override
  public boolean isActive() {

    return true;
  }

  public void setFundingSource(FundingSource fundingSource) {
    this.fundingSource = fundingSource;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setInstitution(Institution institution) {
    this.institution = institution;
  }


}

