package org.cgiar.ccafs.marlo.data.model;
// Generated Oct 27, 2016 4:50:23 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * FundingSourceBudget generated by hbm2java
 */
public class FundingSourceBudget extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = 4796280320095062122L;

  @Expose
  private FundingSource fundingSource;

  @Expose
  private Double budget;

  @Expose
  private Integer year;

  @Expose
  private Phase phase;

  public FundingSourceBudget() {
  }

  public Double getBudget() {
    return budget;
  }

  public FundingSource getFundingSource() {
    return fundingSource;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public Phase getPhase() {
    return phase;
  }

  public Integer getYear() {
    return year;
  }

  public void setBudget(Double budget) {
    this.budget = budget;
  }

  public void setFundingSource(FundingSource fundingSource) {
    this.fundingSource = fundingSource;
  }

  public void setPhase(Phase phase) {
    this.phase = phase;
  }

  public void setYear(Integer year) {
    this.year = year;
  }


  @Override
  public String toString() {
    return "FundingSourceBudget [id=" + this.getId() + ", fundingSource=" + fundingSource + ", budget=" + budget
      + ", year=" + year + "]";
  }


}

