package org.cgiar.ccafs.marlo.data.model;
// Generated Oct 31, 2017 2:36:54 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * GlobalUnitProject generated by hbm2java
 */
public class GlobalUnitProject implements java.io.Serializable {


  private static final long serialVersionUID = -6398960131105092299L;

  @Expose
  private Long id;
  @Expose
  private User modifiedBy;

  @Expose
  private User createdBy;

  @Expose
  private GlobalUnit globalUnit;

  @Expose
  private Project project;

  @Expose
  private boolean active;

  @Expose
  private boolean origin;

  @Expose
  private Date activeSince;
  @Expose
  private String modificationJustification;


  public GlobalUnitProject() {
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public GlobalUnit getGlobalUnit() {
    return globalUnit;
  }


  public Long getId() {
    return id;
  }


  public String getModificationJustification() {
    return modificationJustification;
  }


  public User getModifiedBy() {
    return modifiedBy;
  }


  public Project getProject() {
    return project;
  }


  public boolean isActive() {
    return active;
  }

  public boolean isOrigin() {
    return origin;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setGlobalUnit(GlobalUnit globalUnit) {
    this.globalUnit = globalUnit;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setOrigin(boolean origin) {
    this.origin = origin;
  }

  public void setProject(Project project) {
    this.project = project;
  }


}

