package org.cgiar.ccafs.marlo.data.model;
// Generated Oct 31, 2017 2:36:54 PM by Hibernate Tools 3.4.0.CR1


import com.google.gson.annotations.Expose;

/**
 * GlobalUnitProject generated by hbm2java
 */
public class GlobalUnitProject extends MarloAuditableEntity implements java.io.Serializable {


  private static final long serialVersionUID = -6398960131105092299L;

  @Expose
  private GlobalUnit globalUnit;

  @Expose
  private Project project;

  @Expose
  private boolean origin;

  public GlobalUnitProject() {
  }

  public GlobalUnit getGlobalUnit() {
    return globalUnit;
  }

  public Project getProject() {
    return project;
  }

  public boolean isOrigin() {
    return origin;
  }

  public void setGlobalUnit(GlobalUnit globalUnit) {
    this.globalUnit = globalUnit;
  }

  public void setOrigin(boolean origin) {
    this.origin = origin;
  }

  public void setProject(Project project) {
    this.project = project;
  }


}

