package org.cgiar.ccafs.marlo.data.model;
// Generated Feb 7, 2017 2:38:52 PM by Hibernate Tools 3.4.0.CR1

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * IpLiaisonUser generated by hbm2java
 */
public class IpLiaisonUser implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = -2967440811079090410L;

  @Expose
  private Long id;
  @Expose
  private User user;
  @Expose
  private IpLiaisonInstitution ipLiaisonInstitution;


  public IpLiaisonUser() {
  }


  public IpLiaisonUser(User user, IpLiaisonInstitution ipLiaisonInstitution) {
    this.user = user;
    this.ipLiaisonInstitution = ipLiaisonInstitution;
  }


  @Override
  public Long getId() {
    return id;
  }

  public IpLiaisonInstitution getIpLiaisonInstitution() {
    return ipLiaisonInstitution;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }

  @Override
  public String getModificationJustification() {
    return "";
  }

  @Override
  public User getModifiedBy() {
    User user = new User();
    user.setId(new Long(3));
    return user;
  }

  public User getUser() {
    return user;
  }

  @Override
  public boolean isActive() {
    return true;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public void setIpLiaisonInstitution(IpLiaisonInstitution ipLiaisonInstitution) {
    this.ipLiaisonInstitution = ipLiaisonInstitution;
  }


  public void setUser(User user) {
    this.user = user;
  }


  @Override
  public String toString() {
    return "IpLiaisonUser [id=" + id + ", user=" + user + ", ipLiaisonInstitution=" + ipLiaisonInstitution + "]";
  }


}

