package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 3, 2017 1:26:41 PM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * IpProgramTypes generated by hbm2java
 */
public class IpProgramType extends MarloBaseEntity implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -6975829091875870124L;
  @Expose
  private String name;
  private Set<IpProgram> ipPrograms = new HashSet<IpProgram>(0);

  public IpProgramType() {
  }

  public Set<IpProgram> getIpPrograms() {
    return this.ipPrograms;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public String getModificationJustification() {

    return "";
  }

  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }

  public String getName() {
    return this.name;
  }

  @Override
  public boolean isActive() {

    return true;
  }


  public void setIpPrograms(Set<IpProgram> ipProgramses) {
    this.ipPrograms = ipProgramses;
  }


  @Override
  public void setModifiedBy(User modifiedBy) {

  }


  public void setName(String name) {
    this.name = name;
  }

  @Override
  public String toString() {
    return "IpProgramType [id=" + this.getId() + ", name=" + name + "]";
  }


}

