/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/

package org.cgiar.ccafs.marlo.data.model;


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * LiaisonInstitution generated by hbm2java
 */
public class LiaisonInstitution extends MarloSoftDeleteableEntity implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -1466921023839583918L;


  @Expose
  private CrpProgram crpProgram;


  @Expose
  private Institution institution;


  @Expose
  private String name;
  @Expose
  private String acronym;
  @Expose
  private GlobalUnit crp;
  private Set<LiaisonUser> liaisonUsers = new HashSet<LiaisonUser>(0);

  private Set<ProjectInfo> projects = new HashSet<ProjectInfo>(0);

  private Set<ProjectInfo> centerProjects = new HashSet<ProjectInfo>(0);
  private Set<PowbSynthesis> powbSynthesis = new HashSet<PowbSynthesis>(0);
  private Set<PowbFinancialPlannedBudget> powbFinancialPlannedBudget = new HashSet<PowbFinancialPlannedBudget>(0);
  private double w1;
  private double w3;

  public LiaisonInstitution() {
  }

  public String getAcronym() {
    return this.acronym;
  }


  public Set<ProjectInfo> getCenterProjects() {
    return centerProjects;
  }


  public String getComposedName() {
    if (this.getAcronym() != null) {
      if (this.getAcronym().length() != 0) {

        return this.getAcronym() + " - " + this.getName();


      }
    }

    return this.getName();

  }


  public GlobalUnit getCrp() {
    return crp;
  }


  public CrpProgram getCrpProgram() {
    return crpProgram;
  }


  public Institution getInstitution() {
    return institution;
  }


  public Set<LiaisonUser> getLiaisonUsers() {
    return liaisonUsers;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }

  @Override
  public String getModificationJustification() {

    return "";
  }

  @Override
  public User getModifiedBy() {
    User user = new User();
    user.setId(new Long(3));
    return user;
  }


  public String getName() {
    return this.name;
  }


  public Set<PowbFinancialPlannedBudget> getPowbFinancialPlannedBudget() {
    return powbFinancialPlannedBudget;
  }

  public Set<PowbSynthesis> getPowbSynthesis() {
    return powbSynthesis;
  }

  public Set<ProjectInfo> getProjects() {
    return projects;
  }


  public double getW1() {
    return w1;
  }

  public double getW3() {
    return w3;
  }


  public void setAcronym(String acronym) {
    this.acronym = acronym;
  }

  public void setCenterProjects(Set<ProjectInfo> centerProjects) {
    this.centerProjects = centerProjects;
  }

  public void setCrp(GlobalUnit crp) {
    this.crp = crp;
  }

  public void setCrpProgram(CrpProgram crpProgram) {
    this.crpProgram = crpProgram;
  }

  public void setInstitution(Institution institution) {
    this.institution = institution;
  }

  public void setLiaisonUsers(Set<LiaisonUser> liaisonUserses) {
    this.liaisonUsers = liaisonUserses;
  }


  @Override
  public void setModifiedBy(User modifiedBy) {

  }

  public void setName(String name) {
    this.name = name;
  }

  public void setPowbFinancialPlannedBudget(Set<PowbFinancialPlannedBudget> powbFinancialPlannedBudget) {
    this.powbFinancialPlannedBudget = powbFinancialPlannedBudget;
  }

  public void setPowbSynthesis(Set<PowbSynthesis> powbSynthesis) {
    this.powbSynthesis = powbSynthesis;
  }

  public void setProjects(Set<ProjectInfo> projects) {
    this.projects = projects;
  }


  public void setW1(double w1) {
    this.w1 = w1;
  }


  public void setW3(double w3) {
    this.w3 = w3;
  }


  @Override
  public String toString() {
    return "LiaisonInstitution [id=" + this.getId() + ", crpProgram=" + crpProgram + ", institution=" + institution
      + ", name=" + name + ", acronym=" + acronym + ", crp=" + crp + "]";
  }

}

