package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * LocGeoposition generated by hbm2java
 */
public class LocGeoposition extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -8360072728437813608L;

  private LocGeoposition locGeoposition;


  @Expose
  private Double latitude;


  @Expose
  private Double longitude;

  private Set<LocElement> locElements = new HashSet<LocElement>(0);

  private Set<LocGeoposition> locGeopositions = new HashSet<LocGeoposition>(0);

  public LocGeoposition() {
  }

  public Double getLatitude() {
    return this.latitude;
  }

  public Set<LocElement> getLocElements() {
    return this.locElements;
  }

  public LocGeoposition getLocGeoposition() {
    return this.locGeoposition;
  }

  public Set<LocGeoposition> getLocGeopositions() {
    return this.locGeopositions;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public Double getLongitude() {
    return this.longitude;
  }

  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }

  public void setLocElements(Set<LocElement> locElements) {
    this.locElements = locElements;
  }

  public void setLocGeoposition(LocGeoposition locGeoposition) {
    this.locGeoposition = locGeoposition;
  }

  public void setLocGeopositions(Set<LocGeoposition> locGeopositions) {
    this.locGeopositions = locGeopositions;
  }

  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }

  @Override
  public String toString() {
    return "LocGeoposition [id=" + this.getId() + ", locGeoposition=" + locGeoposition + ", latitude=" + latitude
      + ", longitude=" + longitude + "]";
  }
}

