package org.cgiar.ccafs.marlo.data.model;
// Generated Feb 26, 2018 2:20:26 PM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * PowbCollaborationGlobalUnit generated by hbm2java
 */
public class PowbCollaborationGlobalUnit implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = 371262147439030983L;


  @Expose
  private Long id;


  @Expose
  private GlobalUnit globalUnit;
  private PowbSynthesis powbSynthesis;
  @Expose
  private User createdBy;
  @Expose
  private User modifiedBy;
  @Expose
  private String flagship;
  @Expose
  private String collaborationType;
  @Expose
  private String brief;
  @Expose
  private boolean active;
  @Expose
  private Date activeSince;
  @Expose
  private String modificationJustification;

  public PowbCollaborationGlobalUnit() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }

    PowbCollaborationGlobalUnit other = (PowbCollaborationGlobalUnit) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public String getBrief() {
    return brief;
  }


  public String getCollaborationType() {
    return collaborationType;
  }

  public String getCollaborationTypeName() {
    if (collaborationType == null) {
      return "";
    }
    switch (collaborationType) {
      case "1":
        return "Contribution to";

      case "2":

        return "Service needed from";
      case "3":

        return "Both";

      default:
        return "";

    }

  }

  public User getCreatedBy() {
    return createdBy;
  }


  public String getFlagship() {
    return flagship;
  }


  public GlobalUnit getGlobalUnit() {
    return globalUnit;
  }


  @Override
  public Long getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  @Override
  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public PowbSynthesis getPowbSynthesis() {
    return powbSynthesis;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setBrief(String brief) {
    this.brief = brief;
  }


  public void setCollaborationType(String collaborationType) {
    this.collaborationType = collaborationType;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }


  public void setFlagship(String flagship) {
    this.flagship = flagship;
  }


  public void setGlobalUnit(GlobalUnit globalUnit) {
    this.globalUnit = globalUnit;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setPowbSynthesis(PowbSynthesis powbSynthesis) {
    this.powbSynthesis = powbSynthesis;
  }


}

