package org.cgiar.ccafs.marlo.data.model;
// Generated Dec 5, 2016 8:43:30 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ProjectHighligths generated by hbm2java
 */
public class ProjectHighlight implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -5813880172771852517L;
  @Expose
  private Long id;
  @Expose
  private FileDB file;
  @Expose
  private Project project;
  @Expose
  private User modifiedBy;
  @Expose
  private User createdBy;
  @Expose
  private String title;
  @Expose
  private String author;
  @Expose
  private Date startDate;
  @Expose
  private Date endDate;
  @Expose
  private String description;
  @Expose
  private String results;
  @Expose
  private boolean global;
  @Expose
  private String publisher;
  @Expose
  private String objectives;
  @Expose
  private String partners;
  @Expose
  private String links;
  @Expose
  private String keywords;
  @Expose
  private String subject;
  @Expose
  private Long year;
  @Expose
  private boolean active;
  @Expose
  private Long status;
  @Expose
  private Date activeSince;
  @Expose
  private String modificationJustification;
  private Set<ProjectHighlightType> projectHighligthsTypes = new HashSet<ProjectHighlightType>(0);
  private Set<ProjectHighlightCountry> projectHighlightCountries = new HashSet<ProjectHighlightCountry>(0);
  private List<ProjectHighlightType> types;
  private List<Long> countriesIds = new ArrayList<>();
  private List<ProjectHighligthsTypeEnum> TypesIds = new ArrayList<>();

  private Set<SectionStatus> sectionStatuses = new HashSet<SectionStatus>(0);


  private String typesidsText;


  private String countriesIdsText;


  private List<String> typesids = new ArrayList<>();

  private List<ProjectHighlightCountry> countries;


  public ProjectHighlight() {
  }


  public ProjectHighlight(FileDB file, Project project, User usersByModifiedBy, User usersByCreatedBy, String title,
    String author, Date startDate, Date endDate, String description, String results, boolean isGlobal, String publisher,
    String objectives, String partners, String links, String keywords, String subject, Long year, boolean isActive,
    Long status, Date activeSince, String modificationJustification) {
    this.file = file;
    this.project = project;
    this.modifiedBy = usersByModifiedBy;
    this.createdBy = usersByCreatedBy;
    this.title = title;
    this.author = author;
    this.startDate = startDate;
    this.endDate = endDate;
    this.description = description;
    this.results = results;
    this.global = isGlobal;
    this.publisher = publisher;
    this.objectives = objectives;
    this.partners = partners;
    this.links = links;
    this.keywords = keywords;
    this.subject = subject;
    this.year = year;
    this.active = isActive;
    this.status = status;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public String getAuthor() {
    return author;
  }

  public List<ProjectHighlightCountry> getCountries() {
    return countries;
  }


  public List<Long> getCountriesIds() {
    return countriesIds;
  }


  public String getCountriesIdsText() {
    return countriesIdsText;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public String getDescription() {
    return description;
  }

  public Date getEndDate() {
    return endDate;
  }


  public FileDB getFile() {
    return file;
  }


  @Override
  public Long getId() {
    return id;
  }


  public String getKeywords() {
    return keywords;
  }


  public String getLinks() {
    return links;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  @Override
  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public String getObjectives() {
    return objectives;
  }


  public String getPartners() {
    return partners;
  }


  public Project getProject() {
    return project;
  }


  public Set<ProjectHighlightCountry> getProjectHighligthCountries() {
    return projectHighlightCountries;
  }


  public Set<ProjectHighlightType> getProjectHighligthsTypes() {
    return projectHighligthsTypes;
  }


  public String getPublisher() {
    return publisher;
  }


  public String getResults() {
    return results;
  }


  public Set<SectionStatus> getSectionStatuses() {
    return sectionStatuses;
  }


  public Date getStartDate() {
    return startDate;
  }


  public Long getStatus() {
    return status;
  }


  public String getSubject() {
    return subject;
  }


  public String getTitle() {
    return title;
  }


  public List<ProjectHighlightType> getTypes() {
    return types;
  }


  public List<String> getTypesids() {
    return typesids;
  }


  public List<ProjectHighligthsTypeEnum> getTypesIds() {
    return TypesIds;
  }


  public String getTypesidsText() {
    return typesidsText;
  }


  public Long getYear() {
    return year;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public boolean isGlobal() {
    return global;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setAuthor(String author) {
    this.author = author;
  }


  public void setCountries(List<ProjectHighlightCountry> countries) {
    this.countries = countries;
  }


  public void setCountriesIds(List<Long> countriesIds) {
    this.countriesIds = countriesIds;
  }


  public void setCountriesIdsText(String countriesIdsText) {
    this.countriesIdsText = countriesIdsText;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }


  public void setFile(FileDB file) {
    this.file = file;
  }


  public void setGlobal(boolean global) {
    this.global = global;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }


  public void setLinks(String links) {
    this.links = links;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setObjectives(String objectives) {
    this.objectives = objectives;
  }


  public void setPartners(String partners) {
    this.partners = partners;
  }


  public void setProject(Project project) {
    this.project = project;
  }


  public void setProjectHighligthCountries(Set<ProjectHighlightCountry> projectHighlightCountries) {
    this.projectHighlightCountries = projectHighlightCountries;
  }


  public void setProjectHighligthsTypes(Set<ProjectHighlightType> projectHighligthsTypes) {
    this.projectHighligthsTypes = projectHighligthsTypes;
  }


  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }


  public void setResults(String results) {
    this.results = results;
  }


  public void setSectionStatuses(Set<SectionStatus> sectionStatuses) {
    this.sectionStatuses = sectionStatuses;
  }


  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }


  public void setStatus(Long status) {
    this.status = status;
  }


  public void setSubject(String subject) {
    this.subject = subject;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public void setTypes(List<ProjectHighlightType> types) {
    this.types = types;
  }


  public void setTypesids(List<String> typesids) {
    this.typesids = typesids;
  }


  public void setTypesIds(List<ProjectHighligthsTypeEnum> typesIds) {
    TypesIds = typesIds;
  }


  public void setTypesidsText(String typesidsText) {
    this.typesidsText = typesidsText;
  }


  public void setYear(Long year) {
    this.year = year;
  }


}

