package org.cgiar.ccafs.marlo.data.model;
// Generated Jul 29, 2016 8:50:03 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ProjectPartner generated by hbm2java
 */
public class ProjectPartner implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -8386210768059621143L;
  @Expose
  private Long id;
  @Expose
  private Institution institution;
  @Expose
  private Project project;
  @Expose
  private User createdBy;

  @Expose
  private User modifiedBy;


  @Expose
  private boolean active;


  @Expose
  private Date activeSince;
  @Expose
  private String modificationJustification;
  private Set<ProjectPartnerContribution> projectPartnerContributions = new HashSet<ProjectPartnerContribution>(0);
  private Set<ProjectPartnerContribution> projectPartnerContributors = new HashSet<ProjectPartnerContribution>(0);
  private Set<ProjectPartnerOverall> projectPartnerOveralls = new HashSet<ProjectPartnerOverall>(0);
  private Set<ProjectPartnerPerson> projectPartnerPersons = new HashSet<ProjectPartnerPerson>(0);

  public ProjectPartner() {
  }

  public ProjectPartner(Institution institution, Project project, User usersByCreatedBy, User usersByModifiedBy,
    boolean isActive, Date activeSince, String modificationJustification) {
    this.institution = institution;
    this.project = project;
    this.createdBy = usersByCreatedBy;
    this.modifiedBy = usersByModifiedBy;
    this.active = isActive;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  public ProjectPartner(Institution institution, Project project, User usersByCreatedBy, User usersByModifiedBy,
    boolean isActive, Date activeSince, String modificationJustification,
    Set<ProjectPartnerContribution> projectPartnerContributionsesForProjectPartnerId,
    Set<ProjectPartnerContribution> projectPartnerContributionsesForProjectPartnerContributorId,
    Set<ProjectPartnerOverall> projectPartnerOveralls, Set<ProjectPartnerPerson> projectPartnerPersonses) {
    this.institution = institution;
    this.project = project;
    this.createdBy = usersByCreatedBy;
    this.modifiedBy = usersByModifiedBy;
    this.active = isActive;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
    this.projectPartnerContributions = projectPartnerContributionsesForProjectPartnerId;
    this.projectPartnerContributors = projectPartnerContributionsesForProjectPartnerContributorId;
    this.projectPartnerOveralls = projectPartnerOveralls;
    this.projectPartnerPersons = projectPartnerPersonses;
  }


  public Date getActiveSince() {
    return this.activeSince;
  }

  public User getCreatedBy() {
    return this.createdBy;
  }

  @Override
  public Long getId() {
    return this.id;
  }

  public Institution getInstitution() {
    return this.institution;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }

  public String getModificationJustification() {
    return this.modificationJustification;
  }

  @Override
  public User getModifiedBy() {
    return this.modifiedBy;
  }

  public Project getProject() {
    return project;
  }

  public Set<ProjectPartnerContribution> getProjectPartnerContributions() {
    return this.projectPartnerContributions;
  }

  public Set<ProjectPartnerContribution> getProjectPartnerContributors() {
    return this.projectPartnerContributors;
  }

  public Set<ProjectPartnerOverall> getProjectPartnerOveralls() {
    return this.projectPartnerOveralls;
  }

  public Set<ProjectPartnerPerson> getProjectPartnerPersons() {
    return this.projectPartnerPersons;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User usersByCreatedBy) {
    this.createdBy = usersByCreatedBy;
  }

  public void setId(Long id) {
    this.id = id;
  }


  public void setInstitution(Institution institution) {
    this.institution = institution;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User usersByModifiedBy) {
    this.modifiedBy = usersByModifiedBy;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public void
    setProjectPartnerContributions(Set<ProjectPartnerContribution> projectPartnerContributionsesForProjectPartnerId) {
    this.projectPartnerContributions = projectPartnerContributionsesForProjectPartnerId;
  }

  public void setProjectPartnerContributors(
    Set<ProjectPartnerContribution> projectPartnerContributionsesForProjectPartnerContributorId) {
    this.projectPartnerContributors = projectPartnerContributionsesForProjectPartnerContributorId;
  }

  public void setProjectPartnerOveralls(Set<ProjectPartnerOverall> projectPartnerOveralls) {
    this.projectPartnerOveralls = projectPartnerOveralls;
  }

  public void setProjectPartnerPersons(Set<ProjectPartnerPerson> projectPartnerPersonses) {
    this.projectPartnerPersons = projectPartnerPersonses;
  }


}

