package org.cgiar.ccafs.marlo.data.model;
// Generated Dec 5, 2016 1:23:27 PM by Hibernate Tools 4.3.1.Final

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ProjectHighligthsTypes generated by hbm2java
 */
public class ProjectHighligthType implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -4160886976093977707L;
  @Expose
  private Integer id;

  private ProjectHighligth projectHighligth;
  @Expose
  private int idType;

  public ProjectHighligthType() {
  }

  public ProjectHighligthType(ProjectHighligth projectHighligth, int idType) {
    this.projectHighligth = projectHighligth;
    this.idType = idType;
  }

  @Override
  public Integer getId() {
    return id;
  }


  public int getIdType() {
    return idType;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }


  @Override
  public String getModificationJustification() {

    return "";
  }


  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }


  public ProjectHighligth getProjectHighligth() {
    return projectHighligth;
  }

  @Override
  public boolean isActive() {

    return true;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public void setIdType(int idType) {
    this.idType = idType;
  }


  public void setProjectHighligth(ProjectHighligth projectHighligth) {
    this.projectHighligth = projectHighligth;
  }

}

