package org.cgiar.ccafs.marlo.data.model;
// Generated Sep 6, 2016 2:19:19 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * ProjectBilateralCofinancing generated by hbm2java
 */
public class ProjectBilateralCofinancing implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = -5725787908570331052L;
  private Long id;
  private Institution institution;
  private LiaisonInstitution liaisonInstitution;
  private LiaisonUser liaisonUser;
  private User createdBy;
  private User modifiedBy;
  private String title;
  private Date startDate;
  private Date endDate;
  private Integer agreement;
  private boolean active;
  private Date activeSince;
  private String modificationJustification;

  public Date getActiveSince() {
    return activeSince;
  }

  public Integer getAgreement() {
    return agreement;
  }

  public User getCreatedBy() {
    return createdBy;
  }

  public Date getEndDate() {
    return endDate;
  }

  public Long getId() {
    return id;
  }

  public Institution getInstitution() {
    return institution;
  }

  public LiaisonInstitution getLiaisonInstitution() {
    return liaisonInstitution;
  }

  public LiaisonUser getLiaisonUser() {
    return liaisonUser;
  }

  public String getModificationJustification() {
    return modificationJustification;
  }

  public User getModifiedBy() {
    return modifiedBy;
  }

  public Date getStartDate() {
    return startDate;
  }

  public String getTitle() {
    return title;
  }

  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setAgreement(Integer agreement) {
    this.agreement = agreement;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setInstitution(Institution institution) {
    this.institution = institution;
  }

  public void setLiaisonInstitution(LiaisonInstitution liaisonInstitution) {
    this.liaisonInstitution = liaisonInstitution;
  }

  public void setLiaisonUser(LiaisonUser liaisonUser) {
    this.liaisonUser = liaisonUser;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  public void setTitle(String title) {
    this.title = title;
  }


}

