package org.cgiar.ccafs.marlo.data.model;
// Generated May 5, 2017 11:44:22 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ProjectPartnerLocation generated by hbm2java
 */
public class ProjectPartnerLocation extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -5187968028247593389L;
  @Expose
  private InstitutionLocation institutionLocation;
  private ProjectPartner projectPartner;

  public ProjectPartnerLocation() {
  }

  public InstitutionLocation getInstitutionLocation() {
    return institutionLocation;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }

  public ProjectPartner getProjectPartner() {
    return projectPartner;
  }


  public void setInstitutionLocation(InstitutionLocation institutionLocation) {
    this.institutionLocation = institutionLocation;
  }


  public void setProjectPartner(ProjectPartner projectPartner) {
    this.projectPartner = projectPartner;
  }


  @Override
  public String toString() {
    return "ProjectPartnerLocation [id=" + this.getId() + ", institutionLocation=" + institutionLocation
      + ", projectPartner=" + projectPartner + "]";
  }


}

