package org.cgiar.ccafs.marlo.data.model;
// Generated Dec 5, 2016 8:43:30 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import com.google.gson.annotations.Expose;

/**
 * ProjectHighligths generated by hbm2java
 */
public class ProjectHighlight extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -5813880172771852517L;


  @Expose
  private Project project;

  private ProjectHighlightInfo projectHighlightInfo;

  private Set<ProjectHighlightInfo> projectHighlightInfos = new HashSet<ProjectHighlightInfo>(0);
  private Set<ProjectHighlightType> projectHighligthsTypes = new HashSet<ProjectHighlightType>(0);
  private Set<ProjectHighlightCountry> projectHighlightCountries = new HashSet<ProjectHighlightCountry>(0);
  private List<ProjectHighlightType> types;
  private List<Long> countriesIds = new ArrayList<>();
  private List<ProjectHighligthsTypeEnum> TypesIds = new ArrayList<>();
  private Set<SectionStatus> sectionStatuses = new HashSet<SectionStatus>(0);

  private String typesidsText;


  private String countriesIdsText;


  private List<String> typesids = new ArrayList<>();


  private List<ProjectHighlightCountry> countries;


  public ProjectHighlight() {
  }


  public List<ProjectHighlightCountry> getCountries() {
    return countries;
  }


  public List<Long> getCountriesIds() {
    return countriesIds;
  }


  public String getCountriesIdsText() {
    return countriesIdsText;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }


  public Project getProject() {
    return project;
  }


  public Set<ProjectHighlightCountry> getProjectHighlightCountries() {
    return projectHighlightCountries;
  }


  public ProjectHighlightInfo getProjectHighlightInfo() {
    return projectHighlightInfo;
  }


  public ProjectHighlightInfo getProjectHighlightInfo(Phase phase) {
    if (this.getProjectHighlightInfo() != null) {
      return this.getProjectHighlightInfo();
    } else {
      List<ProjectHighlightInfo> infos =
        projectHighlightInfos.stream().filter(c -> c != null && c.getPhase() != null && c.getPhase().getId() != null
          && c.getPhase().getId().longValue() == phase.getId()).collect(Collectors.toList());
      if (!infos.isEmpty()) {
        this.setProjectHighlightInfo(infos.get(0));
        return this.getProjectHighlightInfo();
      } else {
        return null;
      }
    }


  }


  public Set<ProjectHighlightInfo> getProjectHighlightInfos() {
    return projectHighlightInfos;
  }


  public Set<ProjectHighlightType> getProjectHighligthsTypes() {
    return projectHighligthsTypes;
  }


  public Set<SectionStatus> getSectionStatuses() {
    return sectionStatuses;
  }


  public List<ProjectHighlightType> getTypes() {
    return types;
  }


  public List<String> getTypesids() {
    return typesids;
  }


  public List<ProjectHighligthsTypeEnum> getTypesIds() {
    return TypesIds;
  }


  public String getTypesidsText() {
    return typesidsText;
  }


  public void setCountries(List<ProjectHighlightCountry> countries) {
    this.countries = countries;
  }

  public void setCountriesIds(List<Long> countriesIds) {
    this.countriesIds = countriesIds;
  }

  public void setCountriesIdsText(String countriesIdsText) {
    this.countriesIdsText = countriesIdsText;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public void setProjectHighlightCountries(Set<ProjectHighlightCountry> projectHighlightCountries) {
    this.projectHighlightCountries = projectHighlightCountries;
  }

  public void setProjectHighlightInfo(ProjectHighlightInfo projectHighlightInfo) {
    this.projectHighlightInfo = projectHighlightInfo;
  }

  public void setProjectHighlightInfos(Set<ProjectHighlightInfo> projectHighlightInfos) {
    this.projectHighlightInfos = projectHighlightInfos;
  }

  public void setProjectHighligthsTypes(Set<ProjectHighlightType> projectHighligthsTypes) {
    this.projectHighligthsTypes = projectHighligthsTypes;
  }


  public void setSectionStatuses(Set<SectionStatus> sectionStatuses) {
    this.sectionStatuses = sectionStatuses;
  }


  public void setTypes(List<ProjectHighlightType> types) {
    this.types = types;
  }


  public void setTypesids(List<String> typesids) {
    this.typesids = typesids;
  }

  public void setTypesIds(List<ProjectHighligthsTypeEnum> typesIds) {
    TypesIds = typesIds;
  }

  public void setTypesidsText(String typesidsText) {
    this.typesidsText = typesidsText;
  }


}
