package org.cgiar.ccafs.marlo.data.model;
// Generated Aug 25, 2016 11:50:53 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * ProjectNextuser generated by hbm2java
 */
public class ProjectNextuser implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = -6144197606440114685L;
  private Long id;
  private ProjectOutcome projectOutcome;
  private User createdBy;
  private User modifiedBy;
  private String nextUser;
  private String knowledge;
  private String strategies;
  private boolean active;
  private Date activeSince;
  private String modificationJustification;

  public ProjectNextuser() {
  }


  public ProjectNextuser(ProjectOutcome projectOutcome, User usersByModifiedBy, boolean isActive, Date activeSince,
    String modificationJustification) {
    this.projectOutcome = projectOutcome;
    this.modifiedBy = usersByModifiedBy;
    this.active = isActive;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }

  public ProjectNextuser(ProjectOutcome projectOutcome, User usersByCreatedBy, User usersByModifiedBy, String nextUser,
    String knowledge, String strategies, boolean isActive, Date activeSince, String modificationJustification) {
    this.projectOutcome = projectOutcome;
    this.createdBy = usersByCreatedBy;
    this.modifiedBy = usersByModifiedBy;
    this.nextUser = nextUser;
    this.knowledge = knowledge;
    this.strategies = strategies;
    this.active = isActive;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public Long getId() {
    return id;
  }


  public String getKnowledge() {
    return knowledge;
  }


  public String getModificationJustification() {
    return modificationJustification;
  }


  public User getModifiedBy() {
    return modifiedBy;
  }


  public String getNextUser() {
    return nextUser;
  }


  public ProjectOutcome getProjectOutcome() {
    return projectOutcome;
  }


  public String getStrategies() {
    return strategies;
  }


  public boolean isActive() {
    return active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public void setKnowledge(String knowledge) {
    this.knowledge = knowledge;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setNextUser(String nextUser) {
    this.nextUser = nextUser;
  }


  public void setProjectOutcome(ProjectOutcome projectOutcome) {
    this.projectOutcome = projectOutcome;
  }


  public void setStrategies(String strategies) {
    this.strategies = strategies;
  }


}

