package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 10, 2017 9:25:38 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * ProjectOutcomesPandr generated by hbm2java
 */
public class ProjectOutcomePandr implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = 2933949570134738952L;
  @Expose
  private Long id;
  private Project project;
  @Expose
  private User createdBy;
  @Expose
  private User modifiedBy;
  @Expose
  private int year;
  @Expose
  private String statement;
  @Expose
  private String anualProgress;
  @Expose
  private String comunication;
  @Expose
  private FileDB file;
  @Expose
  private boolean active;
  @Expose
  private Date activeSince;
  @Expose
  private String modificationJustification;

  public ProjectOutcomePandr() {
  }


  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ProjectOutcomePandr other = (ProjectOutcomePandr) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!id.equals(other.id)) {
      return false;
    }
    return true;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public String getAnualProgress() {
    return anualProgress;
  }


  public String getComunication() {
    return comunication;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public FileDB getFile() {
    return file;
  }


  @Override
  public Long getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }


  @Override
  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public Project getProject() {
    return project;
  }


  public String getStatement() {
    return statement;
  }


  public int getYear() {
    return year;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setAnualProgress(String anualProgress) {
    this.anualProgress = anualProgress;
  }


  public void setComunication(String comunication) {
    this.comunication = comunication;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }


  public void setFile(FileDB file) {
    this.file = file;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setProject(Project project) {
    this.project = project;
  }


  public void setStatement(String statement) {
    this.statement = statement;
  }


  public void setYear(int year) {
    this.year = year;
  }


  @Override
  public String toString() {
    return "ProjectOutcomePandr [id=" + id + ", project=" + project + ", year=" + year + ", statement=" + statement
      + ", file=" + file + "]";
  }


}

