package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 18, 2018 4:07:48 PM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * ProjectOutcomeIndicator generated by hbm2java
 */
public class ProjectOutcomeIndicator implements java.io.Serializable, IAuditLog {


  /**
   * 
   */
  private static final long serialVersionUID = -790617950598935170L;
  @Expose
  private Long id;
  @Expose
  private CrpProgramOutcomeIndicator crpProgramOutcomeIndicator;
  @Expose
  private ProjectOutcome projectOutcome;
  @Expose
  private User modifiedBy;
  @Expose
  private User createdBy;
  @Expose
  private Double value;
  @Expose
  private String narrative;
  @Expose
  private boolean active;
  @Expose
  private Date activeSince;
  @Expose
  private String modificationJustification;

  public ProjectOutcomeIndicator() {
  }


  public ProjectOutcomeIndicator(Long id, CrpProgramOutcomeIndicator crpProgramOutcomeIndicator,
    ProjectOutcome projectOutcome, User modifiedBy, User createdBy, Double value, String narrative, boolean active,
    Date activeSince, String modificationJustification) {
    super();
    this.id = id;
    this.crpProgramOutcomeIndicator = crpProgramOutcomeIndicator;
    this.projectOutcome = projectOutcome;
    this.modifiedBy = modifiedBy;
    this.createdBy = createdBy;
    this.value = value;
    this.narrative = narrative;
    this.active = active;
    this.activeSince = activeSince;
    this.modificationJustification = modificationJustification;
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  public CrpProgramOutcomeIndicator getCrpProgramOutcomeIndicator() {
    return crpProgramOutcomeIndicator;
  }


  @Override
  public Long getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();

    sb.append("Id : ").append(this.getId());


    return sb.toString();
  }


  @Override
  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public String getNarrative() {
    return narrative;
  }


  public ProjectOutcome getProjectOutcome() {
    return projectOutcome;
  }


  public Double getValue() {
    return value;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }


  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }


  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }


  public void setCrpProgramOutcomeIndicator(CrpProgramOutcomeIndicator crpProgramOutcomeIndicator) {
    this.crpProgramOutcomeIndicator = crpProgramOutcomeIndicator;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public void setNarrative(String narrative) {
    this.narrative = narrative;
  }


  public void setProjectOutcome(ProjectOutcome projectOutcome) {
    this.projectOutcome = projectOutcome;
  }


  public void setValue(Double value) {
    this.value = value;
  }


}

