package org.cgiar.ccafs.marlo.data.model;
// Generated Apr 18, 2018 3:39:52 PM by Hibernate Tools 3.4.0.CR1

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ProjectInnovationInfo generated by hbm2java
 */
public class ProjectInnovationInfo implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = 6466188559245022941L;

  @Expose
  private Long id;

  @Expose
  private ProjectInnovation projectInnovation;

  @Expose
  private RepIndPhaseResearchPartnership repIndPhaseResearchPartnership;

  @Expose
  private RepIndStageInnovation repIndStageInnovation;

  @Expose
  private Phase phase;

  @Expose
  private RepIndRegion repIndRegion;

  @Expose
  private RepIndInnovationType repIndInnovationType;

  @Expose
  private RepIndGeographicScope repIndGeographicScope;

  @Expose
  private RepIndGenderYouthFocusLevel genderFocusLevel;

  @Expose
  private RepIndGenderYouthFocusLevel youthFocusLevel;

  @Expose
  private String title;

  @Expose
  private String narrative;

  @Expose
  private String novel;

  @Expose
  private String evidenceLink;

  @Expose
  private String genderExplaniation;

  @Expose
  private String youthExplaniation;


  public ProjectInnovationInfo() {
  }


  public String getEvidenceLink() {
    return evidenceLink;
  }


  public String getGenderExplaniation() {
    return genderExplaniation;
  }


  public RepIndGenderYouthFocusLevel getGenderFocusLevel() {
    return genderFocusLevel;
  }


  @Override
  public Long getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  @Override
  public String getModificationJustification() {
    return "";
  }


  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }


  public String getNarrative() {
    return narrative;
  }


  public String getNovel() {
    return novel;
  }


  public Phase getPhase() {
    return phase;
  }


  public ProjectInnovation getProjectInnovation() {
    return projectInnovation;
  }


  public RepIndGeographicScope getRepIndGeographicScope() {
    return repIndGeographicScope;
  }


  public RepIndInnovationType getRepIndInnovationType() {
    return repIndInnovationType;
  }


  public RepIndPhaseResearchPartnership getRepIndPhaseResearchPartnership() {
    return repIndPhaseResearchPartnership;
  }


  public RepIndRegion getRepIndRegion() {
    return repIndRegion;
  }

  public RepIndStageInnovation getRepIndStageInnovation() {
    return repIndStageInnovation;
  }

  public String getTitle() {
    return title;
  }

  public String getYouthExplaniation() {
    return youthExplaniation;
  }

  public RepIndGenderYouthFocusLevel getYouthFocusLevel() {
    return youthFocusLevel;
  }

  @Override
  public boolean isActive() {
    return true;
  }

  public void setEvidenceLink(String evidenceLink) {
    this.evidenceLink = evidenceLink;
  }

  public void setGenderExplaniation(String genderExplaniation) {
    this.genderExplaniation = genderExplaniation;
  }

  public void setGenderFocusLevel(RepIndGenderYouthFocusLevel genderFocusLevel) {
    this.genderFocusLevel = genderFocusLevel;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setNarrative(String narrative) {
    this.narrative = narrative;
  }

  public void setNovel(String novel) {
    this.novel = novel;
  }

  public void setPhase(Phase phase) {
    this.phase = phase;
  }

  public void setProjectInnovation(ProjectInnovation projectInnovation) {
    this.projectInnovation = projectInnovation;
  }

  public void setRepIndGeographicScope(RepIndGeographicScope repIndGeographicScope) {
    this.repIndGeographicScope = repIndGeographicScope;
  }

  public void setRepIndInnovationType(RepIndInnovationType repIndInnovationType) {
    this.repIndInnovationType = repIndInnovationType;
  }

  public void setRepIndPhaseResearchPartnership(RepIndPhaseResearchPartnership repIndPhaseResearchPartnership) {
    this.repIndPhaseResearchPartnership = repIndPhaseResearchPartnership;
  }

  public void setRepIndRegion(RepIndRegion repIndRegion) {
    this.repIndRegion = repIndRegion;
  }


  public void setRepIndStageInnovation(RepIndStageInnovation repIndStageInnovation) {
    this.repIndStageInnovation = repIndStageInnovation;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public void setYouthExplaniation(String youthExplaniation) {
    this.youthExplaniation = youthExplaniation;
  }


  public void setYouthFocusLevel(RepIndGenderYouthFocusLevel youthFocusLevel) {
    this.youthFocusLevel = youthFocusLevel;
  }


}

