package org.cgiar.ccafs.marlo.data.model;
// Generated Jan 3, 2017 1:26:41 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * ProjectOtherContributions generated by hbm2java
 */
public class ProjectOtherContribution implements java.io.Serializable {


  private Long id;
  private Project project;
  private User createdBy;

  private User modifiedBy;

  private String contribution;

  private String additionalContribution;

  private String crpContributionsNature;

  private String region;

  private String flagship;

  private String indicators;

  private String description;

  private String target;

  private boolean active;

  private Date activeSince;

  private String modificationJustification;

  public Date getActiveSince() {
    return activeSince;
  }

  public String getAdditionalContribution() {
    return additionalContribution;
  }

  public String getContribution() {
    return contribution;
  }

  public User getCreatedBy() {
    return createdBy;
  }

  public String getCrpContributionsNature() {
    return crpContributionsNature;
  }

  public String getDescription() {
    return description;
  }

  public String getFlagship() {
    return flagship;
  }

  public Long getId() {
    return id;
  }

  public String getIndicators() {
    return indicators;
  }

  public String getModificationJustification() {
    return modificationJustification;
  }

  public User getModifiedBy() {
    return modifiedBy;
  }

  public Project getProject() {
    return project;
  }

  public String getRegion() {
    return region;
  }

  public String getTarget() {
    return target;
  }

  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setAdditionalContribution(String additionalContribution) {
    this.additionalContribution = additionalContribution;
  }

  public void setContribution(String contribution) {
    this.contribution = contribution;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setCrpContributionsNature(String crpContributionsNature) {
    this.crpContributionsNature = crpContributionsNature;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setFlagship(String flagship) {
    this.flagship = flagship;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setIndicators(String indicators) {
    this.indicators = indicators;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public void setTarget(String target) {
    this.target = target;
  }


}

