package org.cgiar.ccafs.marlo.data.model;
// Generated Oct 18, 2018 8:38:07 AM by Hibernate Tools 3.4.0.CR1

import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ProjectExpectedStudyRegion generated by hbm2java
 */
public class ProjectExpectedStudyRegion extends MarloBaseEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -1623218508399338578L;

  @Expose
  private Phase phase;
  @Expose
  private ProjectExpectedStudy projectExpectedStudy;
  @Expose
  private RepIndRegion repIndRegion;

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ProjectExpectedStudyRegion other = (ProjectExpectedStudyRegion) obj;
    if (repIndRegion == null) {
      if (other.repIndRegion != null) {
        return false;
      }
    } else if (!repIndRegion.getId().equals(other.repIndRegion.getId())) {
      return false;
    }
    return true;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  @Override
  public String getModificationJustification() {
    return "";
  }

  @Override
  public User getModifiedBy() {
    User u = new User();
    u.setId(new Long(3));
    return u;
  }

  public Phase getPhase() {
    return phase;
  }

  public ProjectExpectedStudy getProjectExpectedStudy() {
    return projectExpectedStudy;
  }

  public RepIndRegion getRepIndRegion() {
    return repIndRegion;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((repIndRegion == null) ? 0 : repIndRegion.hashCode());
    return result;
  }


  @Override
  public boolean isActive() {
    return true;
  }

  @Override
  public void setModifiedBy(User modifiedBy) {

  }

  public void setPhase(Phase phase) {
    this.phase = phase;
  }

  public void setProjectExpectedStudy(ProjectExpectedStudy projectExpectedStudy) {
    this.projectExpectedStudy = projectExpectedStudy;
  }

  public void setRepIndRegion(RepIndRegion repIndRegion) {
    this.repIndRegion = repIndRegion;
  }

}

