package org.cgiar.ccafs.marlo.data.model;
// Generated May 25, 2018 3:00:57 PM by Hibernate Tools 3.4.0.CR1

import com.google.gson.annotations.Expose;

/**
 * RepIndContributionOfCrp generated by hbm2java
 */
public class RepIndContributionOfCrp extends MarloBaseEntity implements java.io.Serializable {


  private static final long serialVersionUID = 4765371192138929815L;

  @Expose
  private String name;

  public RepIndContributionOfCrp() {
  }

  public RepIndContributionOfCrp(String name) {
    this.name = name;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }


}

