package org.cgiar.ccafs.marlo.data.model;
// Generated May 24, 2018 5:28:55 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisFinancialSummaryBudget generated by hbm2java
 */
public class ReportSynthesisFinancialSummaryBudget extends MarloAuditableEntity
  implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -6823153846500574248L;

  @Expose
  private ReportSynthesisFinancialSummary reportSynthesisFinancialSummary;

  @Expose
  private LiaisonInstitution liaisonInstitution;

  @Expose
  private PowbExpenditureAreas expenditureArea;

  @Expose
  private Double w1Planned;

  @Expose
  private Double w3Planned;

  @Expose
  private Double bilateralPlanned;

  @Expose
  private Double w1Actual;

  @Expose
  private Double w3Actual;

  @Expose
  private Double bilateralActual;

  // AR2018
  @Expose
  private String comments;


  public ReportSynthesisFinancialSummaryBudget() {
  }


  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ReportSynthesisFinancialSummaryBudget other = (ReportSynthesisFinancialSummaryBudget) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public Double getBilateralActual() {
    return bilateralActual;
  }

  public Double getBilateralPlanned() {
    return bilateralPlanned;
  }

  public String getComments() {
    return comments;
  }


  public PowbExpenditureAreas getExpenditureArea() {
    return expenditureArea;
  }

  public LiaisonInstitution getLiaisonInstitution() {
    return liaisonInstitution;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public ReportSynthesisFinancialSummary getReportSynthesisFinancialSummary() {
    return reportSynthesisFinancialSummary;
  }

  public Double getW1Actual() {
    return w1Actual;
  }


  public Double getW1Planned() {
    return w1Planned;
  }


  public Double getW3Actual() {
    return w3Actual;
  }


  public Double getW3Planned() {
    return w3Planned;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }


  public void setBilateralActual(Double bilateralActual) {
    this.bilateralActual = bilateralActual;
  }

  public void setBilateralPlanned(Double bilateralPlanned) {
    this.bilateralPlanned = bilateralPlanned;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }

  public void setExpenditureArea(PowbExpenditureAreas expenditureArea) {
    this.expenditureArea = expenditureArea;
  }

  public void setLiaisonInstitution(LiaisonInstitution liaisonInstitution) {
    this.liaisonInstitution = liaisonInstitution;
  }

  public void setReportSynthesisFinancialSummary(ReportSynthesisFinancialSummary reportSynthesisFinancialSummary) {
    this.reportSynthesisFinancialSummary = reportSynthesisFinancialSummary;
  }

  public void setW1Actual(Double w1Actual) {
    this.w1Actual = w1Actual;
  }

  public void setW1Planned(Double w1Planned) {
    this.w1Planned = w1Planned;
  }

  public void setW3Actual(Double w3Actual) {
    this.w3Actual = w3Actual;
  }


  public void setW3Planned(Double w3Planned) {
    this.w3Planned = w3Planned;
  }


}

