package org.cgiar.ccafs.marlo.data.model;
// Generated Jun 8, 2018 3:52:45 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisExternalPartnership generated by hbm2java
 */
public class ReportSynthesisExternalPartnership extends MarloAuditableEntity
  implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -2160211894576488137L;


  private ReportSynthesis reportSynthesis;

  @Expose
  private String highlights;


  private Set<ReportSynthesisExternalPartnershipProject> reportSynthesisExternalPartnershipProjects =
    new HashSet<ReportSynthesisExternalPartnershipProject>(0);


  private List<ReportSynthesisExternalPartnershipProject> partnerships;


  public ReportSynthesisExternalPartnership() {
  }

  public String getHighlights() {
    return highlights;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public List<ReportSynthesisExternalPartnershipProject> getPartnerships() {
    return partnerships;
  }


  public ReportSynthesis getReportSynthesis() {
    return reportSynthesis;
  }

  public Set<ReportSynthesisExternalPartnershipProject> getReportSynthesisExternalPartnershipProjects() {
    return reportSynthesisExternalPartnershipProjects;
  }

  public void setHighlights(String highlights) {
    this.highlights = highlights;
  }

  public void setPartnerships(List<ReportSynthesisExternalPartnershipProject> partnerships) {
    this.partnerships = partnerships;
  }

  public void setReportSynthesis(ReportSynthesis reportSynthesis) {
    this.reportSynthesis = reportSynthesis;
  }

  public void setReportSynthesisExternalPartnershipProjects(
    Set<ReportSynthesisExternalPartnershipProject> reportSynthesisExternalPartnershipProjects) {
    this.reportSynthesisExternalPartnershipProjects = reportSynthesisExternalPartnershipProjects;
  }


}

