package org.cgiar.ccafs.marlo.data.model;
// Generated May 24, 2018 5:28:55 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisRisk generated by hbm2java
 */
public class ReportSynthesisIntellectualAsset extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = -6717027571806801113L;

  private ReportSynthesis reportSynthesis;

  @Expose
  private String managed;
  @Expose
  private String patents;
  @Expose
  private String criticalIssues;


  public ReportSynthesisIntellectualAsset() {
  }


  public String getCriticalIssues() {
    return criticalIssues;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public String getManaged() {
    return managed;
  }


  public String getPatents() {
    return patents;
  }


  public ReportSynthesis getReportSynthesis() {
    return reportSynthesis;
  }


  public void setCriticalIssues(String criticalIssues) {
    this.criticalIssues = criticalIssues;
  }


  public void setManaged(String managed) {
    this.managed = managed;
  }

  public void setPatents(String patents) {
    this.patents = patents;
  }

  public void setReportSynthesis(ReportSynthesis reportSynthesis) {
    this.reportSynthesis = reportSynthesis;
  }


}

