package org.cgiar.ccafs.marlo.data.model;
// Generated May 24, 2018 5:28:55 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisFundingUseSummary generated by hbm2java
 */
public class ReportSynthesisFundingUseSummary extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 8425440202212439581L;

  private ReportSynthesis reportSynthesis;

  @Expose
  private String mainArea;

  private Set<ReportSynthesisFundingUseExpendituryArea> reportSynthesisFundingUseExpendituryAreas =
    new HashSet<ReportSynthesisFundingUseExpendituryArea>(0);

  private List<ReportSynthesisFundingUseExpendituryArea> expenditureAreas;

  /** AR2018 Fields **/
  @Expose
  private String interestingPoints;

  public ReportSynthesisFundingUseSummary() {
  }


  public List<ReportSynthesisFundingUseExpendituryArea> getExpenditureAreas() {
    return expenditureAreas;
  }


  public String getInterestingPoints() {
    return interestingPoints;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public String getMainArea() {
    return mainArea;
  }


  public ReportSynthesis getReportSynthesis() {
    return reportSynthesis;
  }


  public Set<ReportSynthesisFundingUseExpendituryArea> getReportSynthesisFundingUseExpendituryAreas() {
    return reportSynthesisFundingUseExpendituryAreas;
  }


  public void setExpenditureAreas(List<ReportSynthesisFundingUseExpendituryArea> expenditureAreas) {
    this.expenditureAreas = expenditureAreas;
  }


  public void setInterestingPoints(String interestingPoints) {
    this.interestingPoints = interestingPoints;
  }


  public void setMainArea(String mainArea) {
    this.mainArea = mainArea;
  }


  public void setReportSynthesis(ReportSynthesis reportSynthesis) {
    this.reportSynthesis = reportSynthesis;
  }


  public void setReportSynthesisFundingUseExpendituryAreas(
    Set<ReportSynthesisFundingUseExpendituryArea> reportSynthesisFundingUseExpendituryAreas) {
    this.reportSynthesisFundingUseExpendituryAreas = reportSynthesisFundingUseExpendituryAreas;
  }


  @Override
  public String toString() {
    return "ReportSynthesisFundingUseSummary [Id=" + this.getId() + ", reportSynthesis=" + reportSynthesis
      + ", interestingPoints=" + interestingPoints + ", mainArea=" + mainArea + ", isActive()=" + this.isActive() + "]";
  }


}

