package org.cgiar.ccafs.marlo.data.model;
// Generated Jun 20, 2018 1:50:25 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisMelia generated by hbm2java
 */
public class ReportSynthesisMelia extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = 3900014561509985583L;


  private ReportSynthesis reportSynthesis;


  @Expose
  private String summary;


  private Set<ReportSynthesisMeliaStudy> reportSynthesisMeliaStudies = new HashSet<ReportSynthesisMeliaStudy>(0);


  private Set<ReportSynthesisMeliaEvaluation> reportSynthesisMeliaEvaluations =
    new HashSet<ReportSynthesisMeliaEvaluation>(0);


  private List<ReportSynthesisMeliaStudy> plannedStudies;


  private String plannedStudiesValue;


  private List<ProjectExpectedStudy> expectedStudies;


  private List<ReportSynthesisMeliaEvaluation> evaluations;


  public ReportSynthesisMelia() {
  }


  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ReportSynthesisMelia other = (ReportSynthesisMelia) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }


  public List<ReportSynthesisMeliaEvaluation> getEvaluations() {
    return evaluations;
  }

  public List<ProjectExpectedStudy> getExpectedStudies() {
    return expectedStudies;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public List<ReportSynthesisMeliaStudy> getPlannedStudies() {
    return plannedStudies;
  }


  public String getPlannedStudiesValue() {
    return plannedStudiesValue;
  }


  public ReportSynthesis getReportSynthesis() {
    return reportSynthesis;
  }


  public Set<ReportSynthesisMeliaEvaluation> getReportSynthesisMeliaEvaluations() {
    return reportSynthesisMeliaEvaluations;
  }


  public Set<ReportSynthesisMeliaStudy> getReportSynthesisMeliaStudies() {
    return reportSynthesisMeliaStudies;
  }

  /**
   * @return an array of integers.
   */
  public long[] getStudiesIds() {

    List<ProjectExpectedStudy> expectedStudies = this.getExpectedStudies();
    if (expectedStudies != null) {
      long[] ids = new long[expectedStudies.size()];
      for (int i = 0; i < ids.length; i++) {
        ids[i] = expectedStudies.get(i).getId();
      }
      return ids;
    }
    return null;
  }

  public String getSummary() {
    return summary;
  }

  public void setEvaluations(List<ReportSynthesisMeliaEvaluation> evaluations) {
    this.evaluations = evaluations;
  }

  public void setExpectedStudies(List<ProjectExpectedStudy> expectedStudies) {
    this.expectedStudies = expectedStudies;
  }

  public void setPlannedStudies(List<ReportSynthesisMeliaStudy> plannedStudies) {
    this.plannedStudies = plannedStudies;
  }

  public void setPlannedStudiesValue(String plannedStudiesValue) {
    this.plannedStudiesValue = plannedStudiesValue;
  }

  public void setReportSynthesis(ReportSynthesis reportSynthesis) {
    this.reportSynthesis = reportSynthesis;
  }

  public void setReportSynthesisMeliaEvaluations(Set<ReportSynthesisMeliaEvaluation> reportSynthesisMeliaEvaluations) {
    this.reportSynthesisMeliaEvaluations = reportSynthesisMeliaEvaluations;
  }


  public void setReportSynthesisMeliaStudies(Set<ReportSynthesisMeliaStudy> reportSynthesisMeliaStudies) {
    this.reportSynthesisMeliaStudies = reportSynthesisMeliaStudies;
  }


  public void setSummary(String summary) {
    this.summary = summary;
  }


}

