package org.cgiar.ccafs.marlo.data.model;
// Generated Mar 7, 2019 7:42:16 AM by Hibernate Tools 5.3.6.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisKeyPartnerships generated by hbm2java
 */
public class ReportSynthesisKeyPartnership extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -5667515346500430493L;

  private ReportSynthesis reportSynthesis;


  @Expose
  private String summary;

  @Expose
  private String summaryCgiar;


  private Set<ReportSynthesisKeyPartnershipExternal> reportSynthesisKeyPartnershipExternals =
    new HashSet<ReportSynthesisKeyPartnershipExternal>(0);


  private List<ReportSynthesisKeyPartnershipExternal> partnerships;

  private Set<ReportSynthesisKeyPartnershipCollaboration> reportSynthesisKeyPartnershipCollaborations =
    new HashSet<ReportSynthesisKeyPartnershipCollaboration>(0);

  private List<ReportSynthesisKeyPartnershipCollaboration> collaborations;

  private Set<ReportSynthesisKeyPartnershipPmu> reportSynthesisKeyPartnershipPmus =
    new HashSet<ReportSynthesisKeyPartnershipPmu>(0);

  private List<ReportSynthesisKeyPartnershipPmu> plannedExternalPartnerships;

  private String plannedExternalPartnershipsValue;

  private List<ReportSynthesisKeyPartnershipExternal> selectedExternalPartnerships;

  public ReportSynthesisKeyPartnership() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ReportSynthesisKeyPartnership other = (ReportSynthesisKeyPartnership) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public List<ReportSynthesisKeyPartnershipCollaboration> getCollaborations() {
    return collaborations;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  /**
   * @return an array of integers.
   */
  public long[] getPartnershipIds() {

    List<ReportSynthesisKeyPartnershipExternal> externalPartnerships = this.getSelectedExternalPartnerships();
    if (externalPartnerships != null) {
      long[] ids = new long[externalPartnerships.size()];
      for (int i = 0; i < ids.length; i++) {
        ids[i] = externalPartnerships.get(i).getId();
      }
      return ids;
    }
    return null;
  }


  public List<ReportSynthesisKeyPartnershipExternal> getPartnerships() {
    return partnerships;
  }


  public List<ReportSynthesisKeyPartnershipPmu> getPlannedExternalPartnerships() {
    return plannedExternalPartnerships;
  }

  public String getPlannedExternalPartnershipsValue() {
    return plannedExternalPartnershipsValue;
  }


  public ReportSynthesis getReportSynthesis() {
    return reportSynthesis;
  }


  public Set<ReportSynthesisKeyPartnershipCollaboration> getReportSynthesisKeyPartnershipCollaborations() {
    return reportSynthesisKeyPartnershipCollaborations;
  }


  public Set<ReportSynthesisKeyPartnershipExternal> getReportSynthesisKeyPartnershipExternals() {
    return reportSynthesisKeyPartnershipExternals;
  }


  public Set<ReportSynthesisKeyPartnershipPmu> getReportSynthesisKeyPartnershipPmus() {
    return reportSynthesisKeyPartnershipPmus;
  }


  public List<ReportSynthesisKeyPartnershipExternal> getSelectedExternalPartnerships() {
    return selectedExternalPartnerships;
  }


  public String getSummary() {
    return summary;
  }


  public String getSummaryCgiar() {
    return summaryCgiar;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }


  public void setCollaborations(List<ReportSynthesisKeyPartnershipCollaboration> collaborations) {
    this.collaborations = collaborations;
  }


  public void setPartnerships(List<ReportSynthesisKeyPartnershipExternal> partnerships) {
    this.partnerships = partnerships;
  }


  public void setPlannedExternalPartnerships(List<ReportSynthesisKeyPartnershipPmu> plannedExternalPartnerships) {
    this.plannedExternalPartnerships = plannedExternalPartnerships;
  }


  public void setPlannedExternalPartnershipsValue(String plannedExternalPartnershipsValue) {
    this.plannedExternalPartnershipsValue = plannedExternalPartnershipsValue;
  }

  public void setReportSynthesis(ReportSynthesis reportSynthesis) {
    this.reportSynthesis = reportSynthesis;
  }


  public void setReportSynthesisKeyPartnershipCollaborations(
    Set<ReportSynthesisKeyPartnershipCollaboration> reportSynthesisKeyPartnershipCollaborations) {
    this.reportSynthesisKeyPartnershipCollaborations = reportSynthesisKeyPartnershipCollaborations;
  }

  public void setReportSynthesisKeyPartnershipExternals(
    Set<ReportSynthesisKeyPartnershipExternal> reportSynthesisKeyPartnershipExternals) {
    this.reportSynthesisKeyPartnershipExternals = reportSynthesisKeyPartnershipExternals;
  }


  public void
    setReportSynthesisKeyPartnershipPmus(Set<ReportSynthesisKeyPartnershipPmu> reportSynthesisKeyPartnershipPmus) {
    this.reportSynthesisKeyPartnershipPmus = reportSynthesisKeyPartnershipPmus;
  }


  public void
    setSelectedExternalPartnerships(List<ReportSynthesisKeyPartnershipExternal> selectedExternalPartnerships) {
    this.selectedExternalPartnerships = selectedExternalPartnerships;
  }


  public void setSummary(String summary) {
    this.summary = summary;
  }

  public void setSummaryCgiar(String summaryCgiar) {
    this.summaryCgiar = summaryCgiar;
  }

}

