package org.cgiar.ccafs.marlo.data.model;
// Generated May 24, 2018 5:28:55 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisFinancialSummary generated by hbm2java
 */
public class ReportSynthesisFinancialSummary implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -7347316405464342743L;

  @Expose
  private Long id;

  @Expose
  private User modifiedBy;

  private ReportSynthesis reportSynthesis;

  @Expose
  private User createdBy;

  @Expose
  private String narrative;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;

  @Expose
  private String modificationJustification;


  private Set<ReportSynthesisFinancialSummaryBudget> reportSynthesisFinancialSummaryBudgets =
    new HashSet<ReportSynthesisFinancialSummaryBudget>(0);


  public ReportSynthesisFinancialSummary() {
  }


  public Date getActiveSince() {
    return activeSince;
  }


  public User getCreatedBy() {
    return createdBy;
  }


  @Override
  public Long getId() {
    return id;
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  @Override
  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }


  public String getNarrative() {
    return narrative;
  }


  public ReportSynthesis getReportSynthesis() {
    return reportSynthesis;
  }

  public Set<ReportSynthesisFinancialSummaryBudget> getReportSynthesisFinancialSummaryBudgets() {
    return reportSynthesisFinancialSummaryBudgets;
  }

  @Override
  public boolean isActive() {
    return active;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }

  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setNarrative(String narrative) {
    this.narrative = narrative;
  }

  public void setReportSynthesis(ReportSynthesis reportSynthesis) {
    this.reportSynthesis = reportSynthesis;
  }


  public void setReportSynthesisFinancialSummaryBudgets(
    Set<ReportSynthesisFinancialSummaryBudget> reportSynthesisFinancialSummaryBudgets) {
    this.reportSynthesisFinancialSummaryBudgets = reportSynthesisFinancialSummaryBudgets;
  }


}

