package org.cgiar.ccafs.marlo.data.model;
// Generated May 21, 2018 2:10:20 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisCrpProgressTarget generated by hbm2java
 */
public class ReportSynthesisCrpProgressTarget extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = 5487850972206681944L;

  @Expose
  private SrfSloIndicatorTarget srfSloIndicatorTarget;

  @Expose
  private ReportSynthesisCrpProgress reportSynthesisCrpProgress;

  @Expose
  private String birefSummary;

  @Expose
  private String additionalContribution;

  public ReportSynthesisCrpProgressTarget() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    ReportSynthesisCrpProgressTarget other = (ReportSynthesisCrpProgressTarget) obj;
    if (this.getId() == null) {
      if (other.getId() != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public String getAdditionalContribution() {
    return additionalContribution;
  }


  public String getBirefSummary() {
    return birefSummary;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public ReportSynthesisCrpProgress getReportSynthesisCrpProgress() {
    return reportSynthesisCrpProgress;
  }


  public SrfSloIndicatorTarget getSrfSloIndicatorTarget() {
    return srfSloIndicatorTarget;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
    return result;
  }

  public void setAdditionalContribution(String additionalContribution) {
    this.additionalContribution = additionalContribution;
  }

  public void setBirefSummary(String birefSummary) {
    this.birefSummary = birefSummary;
  }

  public void setReportSynthesisCrpProgress(ReportSynthesisCrpProgress reportSynthesisCrpProgress) {
    this.reportSynthesisCrpProgress = reportSynthesisCrpProgress;
  }


  public void setSrfSloIndicatorTarget(SrfSloIndicatorTarget srfSloIndicatorTarget) {
    this.srfSloIndicatorTarget = srfSloIndicatorTarget;
  }

  @Override
  public String toString() {
    return "ReportSynthesisCrpProgressTarget [id=" + this.getId() + "]";
  }


}

