package org.cgiar.ccafs.marlo.data.model;
// Generated Feb 27, 2019 2:52:09 PM by Hibernate Tools 5.3.6.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * ReportSynthesisSrfProgress generated by hbm2java
 */
public class ReportSynthesisSrfProgress extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = -1236491371016469596L;

  private ReportSynthesis reportSynthesis;

  @Expose
  private String summary;


  private Set<ReportSynthesisSrfProgressTarget> reportSynthesisSrfProgressTargets =
    new HashSet<ReportSynthesisSrfProgressTarget>(0);


  private List<ReportSynthesisSrfProgressTarget> sloTargets;

  public ReportSynthesisSrfProgress() {
  }


  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  public ReportSynthesis getReportSynthesis() {
    return reportSynthesis;
  }


  public Set<ReportSynthesisSrfProgressTarget> getReportSynthesisSrfProgressTargets() {
    return reportSynthesisSrfProgressTargets;
  }


  public List<ReportSynthesisSrfProgressTarget> getSloTargets() {
    return sloTargets;
  }


  public String getSummary() {
    return summary;
  }


  public void setReportSynthesis(ReportSynthesis reportSynthesis) {
    this.reportSynthesis = reportSynthesis;
  }


  public void
    setReportSynthesisSrfProgressTargets(Set<ReportSynthesisSrfProgressTarget> reportSynthesisSrfProgressTargets) {
    this.reportSynthesisSrfProgressTargets = reportSynthesisSrfProgressTargets;
  }


  public void setSloTargets(List<ReportSynthesisSrfProgressTarget> sloTargets) {
    this.sloTargets = sloTargets;
  }


  public void setSummary(String summary) {
    this.summary = summary;
  }


}

