/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated Jul 6, 2016 9:31:00 AM by Hibernate Tools 4.3.1.Final

/**
 * SectionStatus generated by hbm2java
 */
public class SectionStatus extends MarloBaseEntity implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = -7527583315860965374L;

  private CrpProgram crpProgram;


  private String sectionName;

  private String missingFields;


  private String cycle;

  private Integer year;


  private Project project;

  private FundingSource fundingSource;


  private Deliverable deliverable;

  private ProjectOutcome projectOutcome;


  private CaseStudy caseStudy;

  private ProjectHighlight projectHighlight;


  private IpProgram ipProgram;

  private IpLiaisonInstitution ipLiaisonInstitution;


  private PowbSynthesis powbSynthesis;

  private ProjectInnovation projectInnovation;


  private ProjectExpectedStudy projectExpectedStudy;


  private ReportSynthesis reportSynthesis;

  public SectionStatus() {
  }

  public CaseStudy getCaseStudy() {
    return caseStudy;
  }


  public CrpProgram getCrpProgram() {
    return this.crpProgram;
  }

  public String getCycle() {
    return this.cycle;
  }


  public Deliverable getDeliverable() {
    return deliverable;
  }

  public FundingSource getFundingSource() {
    return fundingSource;
  }

  public IpLiaisonInstitution getIpLiaisonInstitution() {
    return ipLiaisonInstitution;
  }

  public IpProgram getIpProgram() {
    return ipProgram;
  }

  public String getMissingFields() {
    return this.missingFields;
  }

  public PowbSynthesis getPowbSynthesis() {
    return powbSynthesis;
  }

  public Project getProject() {
    return project;
  }

  public ProjectExpectedStudy getProjectExpectedStudy() {
    return projectExpectedStudy;
  }

  public ProjectHighlight getProjectHighlight() {
    return projectHighlight;
  }

  public ProjectInnovation getProjectInnovation() {
    return projectInnovation;
  }

  public ProjectOutcome getProjectOutcome() {
    return projectOutcome;
  }

  public ReportSynthesis getReportSynthesis() {
    return reportSynthesis;
  }

  public String getSectionName() {
    return this.sectionName;
  }

  public Integer getYear() {
    return this.year;
  }

  public void setCaseStudy(CaseStudy caseStudy) {
    this.caseStudy = caseStudy;
  }

  public void setCrpProgram(CrpProgram crpProgram) {
    this.crpProgram = crpProgram;
  }

  public void setCycle(String cycle) {
    this.cycle = cycle;
  }


  public void setDeliverable(Deliverable deliverable) {
    this.deliverable = deliverable;
  }


  public void setFundingSource(FundingSource fundingSource) {
    this.fundingSource = fundingSource;
  }

  public void setIpLiaisonInstitution(IpLiaisonInstitution ipLiaisonInstitution) {
    this.ipLiaisonInstitution = ipLiaisonInstitution;
  }

  public void setIpProgram(IpProgram ipProgram) {
    this.ipProgram = ipProgram;
  }

  public void setMissingFields(String missingFields) {
    this.missingFields = missingFields;
  }


  public void setPowbSynthesis(PowbSynthesis powbSynthesis) {
    this.powbSynthesis = powbSynthesis;
  }


  public void setProject(Project project) {
    this.project = project;
  }


  public void setProjectExpectedStudy(ProjectExpectedStudy projectExpectedStudy) {
    this.projectExpectedStudy = projectExpectedStudy;
  }

  public void setProjectHighlight(ProjectHighlight projectHighlight) {
    this.projectHighlight = projectHighlight;
  }


  public void setProjectInnovation(ProjectInnovation projectInnovation) {
    this.projectInnovation = projectInnovation;
  }

  public void setProjectOutcome(ProjectOutcome projectOutcome) {
    this.projectOutcome = projectOutcome;
  }


  public void setReportSynthesis(ReportSynthesis reportSynthesis) {
    this.reportSynthesis = reportSynthesis;
  }

  public void setSectionName(String sectionName) {
    this.sectionName = sectionName;
  }

  public void setYear(Integer year) {
    this.year = year;
  }

  @Override
  public String toString() {
    return "SectionStatus [id=" + this.getId() + ", crpProgram=" + crpProgram + ", sectionName=" + sectionName
      + ", missingFields=" + missingFields + ", cycle=" + cycle + ", year=" + year + ", project=" + project
      + ", fundingSource=" + fundingSource + ", deliverable=" + deliverable + ", projectOutcome=" + projectOutcome
      + ", caseStudy=" + caseStudy + ", projectHighlight=" + projectHighlight + ", ipProgram=" + ipProgram
      + ", ipLiaisonInstitution=" + ipLiaisonInstitution + "]";
  }
}

