/*****************************************************************
 * This file is part of CCAFS Planning and Reporting Platform.
 * CCAFS P&R is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * CCAFS P&R is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with CCAFS P&R. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * SrfSloIndicator generated by hbm2java
 */
public class SrfSloIndicator implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 3683018263832155505L;
  private Long id;
  private SrfSlo srfSlo;
  private String title;
  private String description;
  private Set<SrfSloIndicatorTarget> srfSloIndicatorTargets = new HashSet<SrfSloIndicatorTarget>(0);

  public SrfSloIndicator() {
  }


  public SrfSloIndicator(SrfSlo srfSlos, String title, String description) {
    this.srfSlo = srfSlos;
    this.title = title;
    this.description = description;
  }

  public SrfSloIndicator(SrfSlo srfSlos, String title, String description,
    Set<SrfSloIndicatorTarget> srfSloIndicatorTargets) {
    this.srfSlo = srfSlos;
    this.title = title;
    this.description = description;
    this.srfSloIndicatorTargets = srfSloIndicatorTargets;
  }

  public String getDescription() {
    return this.description;
  }

  public Long getId() {
    return this.id;
  }

  public Set<SrfSloIndicatorTarget> getSrfSloIndicatorTargets() {
    return this.srfSloIndicatorTargets;
  }

  public SrfSlo getSrfSlo() {
    return this.srfSlo;
  }

  public String getTitle() {
    return this.title;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setSrfSloIndicatorTargets(Set<SrfSloIndicatorTarget> srfSloIndicatorTargets) {
    this.srfSloIndicatorTargets = srfSloIndicatorTargets;
  }

  public void setSrfSlo(SrfSlo srfSlos) {
    this.srfSlo = srfSlos;
  }

  public void setTitle(String title) {
    this.title = title;
  }


}

