/*****************************************************************
 * This file is part of CCAFS Planning and Reporting Platform.
 * CCAFS P&R is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * CCAFS P&R is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with CCAFS P&R. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final


/**
 * SrfSloIdo generated by hbm2java
 */
public class SrfSloIdo implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = 7970017895961827691L;
  private Long id;
  private SrfIdo srfIdo;
  private SrfSlo srfSlo;

  public SrfSloIdo() {
  }

  public SrfSloIdo(SrfIdo srfIdos, SrfSlo srfSlos) {
    this.srfIdo = srfIdos;
    this.srfSlo = srfSlos;
  }

  public Long getId() {
    return this.id;
  }

  public SrfIdo getSrfIdo() {
    return this.srfIdo;
  }

  public SrfSlo getSrfSlo() {
    return this.srfSlo;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setSrfIdo(SrfIdo srfIdos) {
    this.srfIdo = srfIdos;
  }

  public void setSrfSlo(SrfSlo srfSlos) {
    this.srfSlo = srfSlos;
  }


}

