/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final

import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * SrfSubIdo generated by hbm2java
 */
public class SrfSubIdo extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

	private static final long serialVersionUID = -6590673724952913143L;

	@Expose
	private SrfIdo srfIdo;

	@Expose
	private String description;

	private String smoCode;

	private Set<CrpOutcomeSubIdo> crpOutcomeSubIdos = new HashSet<CrpOutcomeSubIdo>(0);

	private Set<CrpSubIdosContribution> crpSubIdosContributions = new HashSet<CrpSubIdosContribution>(0);

	private Set<CenterImpact> centerImpacts = new HashSet<CenterImpact>(0);

	public SrfSubIdo() {
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}

		SrfSubIdo other = (SrfSubIdo) obj;
		if (this.getId() == null) {
			if (other.getId() != null) {
				return false;
			}
		} else if (!this.getId().equals(other.getId())) {
			return false;
		}
		return true;
	}

	public Set<CenterImpact> getCenterImpacts() {
		return this.centerImpacts;
	}

	public Set<CrpOutcomeSubIdo> getCrpOutcomeSubIdos() {
		return this.crpOutcomeSubIdos;
	}

	public Set<CrpSubIdosContribution> getCrpSubIdosContributions() {
		return this.crpSubIdosContributions;
	}

	public String getDescription() {
		return this.description;
	}

	@Override
	public String getLogDeatil() {
		StringBuilder sb = new StringBuilder();
		sb.append("Id : ").append(this.getId());
		return sb.toString();
	}

	public String getSmoCode() {
		return this.smoCode;
	}

	public SrfIdo getSrfIdo() {
		return this.srfIdo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((this.getId() == null) ? 0 : this.getId().hashCode());
		return result;
	}

	public void setCenterImpacts(Set<CenterImpact> centerImpacts) {
		this.centerImpacts = centerImpacts;
	}

	public void setCrpOutcomeSubIdos(Set<CrpOutcomeSubIdo> crpOutcomeSubIdos) {
		this.crpOutcomeSubIdos = crpOutcomeSubIdos;
	}

	public void setCrpSubIdosContributions(Set<CrpSubIdosContribution> crpSubIdosContributions) {
		this.crpSubIdosContributions = crpSubIdosContributions;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setSmoCode(String smoCode) {
		this.smoCode = smoCode;
	}

	public void setSrfIdo(SrfIdo srfIdos) {
		this.srfIdo = srfIdos;
	}

	@Override
	public String toString() {
		return "SrfSubIdo [id=" + this.getId() + ", smoCode=" + this.smoCode + ", srfIdo=" + this.srfIdo
				+ ", description=" + this.description + "]";
	}
}
