/*****************************************************************
 * This file is part of Managing Agricultural Research for Learning &
 * Outcomes Platform (MARLO).
 * MARLO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * MARLO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with MARLO. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.math.BigDecimal;

import com.google.gson.annotations.Expose;

/**
 * SrfSloIndicatorTarget generated by hbm2java
 */
public class SrfSloIndicatorTarget extends MarloAuditableEntity implements java.io.Serializable, IAuditLog {

  private static final long serialVersionUID = -6059800120149718264L;

  @Expose
  private SrfSloIndicator srfSloIndicator;

  @Expose
  private SrfTargetUnit srfTargetUnit;

  @Expose
  private BigDecimal value;

  @Expose
  private int year;

  public SrfSloIndicatorTarget() {
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }

  public SrfSloIndicator getSrfSloIndicator() {
    return this.srfSloIndicator;
  }

  public SrfTargetUnit getSrfTargetUnit() {
    return this.srfTargetUnit;
  }

  public BigDecimal getValue() {
    return this.value;
  }

  public int getYear() {
    return this.year;
  }

  public void setSrfSloIndicator(SrfSloIndicator srfSloIndicators) {
    this.srfSloIndicator = srfSloIndicators;
  }

  public void setSrfTargetUnit(SrfTargetUnit srfTargetUnits) {
    this.srfTargetUnit = srfTargetUnits;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }

  public void setYear(int year) {
    this.year = year;
  }

  @Override
  public String toString() {
    return "SrfSloIndicatorTarget [id=" + this.getId() + ", srfSloIndicator=" + srfSloIndicator + ", srfTargetUnit="
      + srfTargetUnit + ", value=" + value + ", year=" + year + "]";
  }

}

