package org.cgiar.ccafs.marlo.data.model;
// Generated May 21, 2018 2:10:20 PM by Hibernate Tools 3.4.0.CR1


import org.cgiar.ccafs.marlo.data.IAuditLog;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * SrfSloIndicatorTarget generated by hbm2java
 */
public class SrfSloIndicatorTarget implements java.io.Serializable, IAuditLog {


  private static final long serialVersionUID = -8975527941728871240L;


  @Expose
  private Long id;


  @Expose
  private User modifiedBy;


  @Expose
  private User createdBy;


  @Expose
  private SrfSloIndicator srfSloIndicator;


  @Expose
  private String narrative;


  @Expose
  private BigDecimal value;


  @Expose
  private int year;


  @Expose
  private SrfTargetUnit srfTargetUnit;

  @Expose
  private boolean active;

  @Expose
  private Date activeSince;

  @Expose
  private String modificationJustification;

  private Set<ReportSynthesisCrpProgressTarget> reportSynthesisCrpProgressTargets =
    new HashSet<ReportSynthesisCrpProgressTarget>(0);

  public SrfSloIndicatorTarget() {
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (this.getClass() != obj.getClass()) {
      return false;
    }
    SrfSloIndicatorTarget other = (SrfSloIndicatorTarget) obj;
    if (id == null) {
      if (other.id != null) {
        return false;
      }
    } else if (!this.getId().equals(other.getId())) {
      return false;
    }
    return true;
  }

  public Date getActiveSince() {
    return activeSince;
  }

  public String getComposedName() {
    return "SLO " + this.getSrfSloIndicator().getSrfSlo().getId() + " Target - " + narrative;
  }

  public User getCreatedBy() {
    return createdBy;
  }

  @Override
  public Long getId() {
    return id;
  }

  @Override
  public String getLogDeatil() {
    StringBuilder sb = new StringBuilder();
    sb.append("Id : ").append(this.getId());
    return sb.toString();
  }


  @Override
  public String getModificationJustification() {
    return modificationJustification;
  }


  @Override
  public User getModifiedBy() {
    return modifiedBy;
  }

  public String getNarrative() {
    return narrative;
  }


  public Set<ReportSynthesisCrpProgressTarget> getReportSynthesisCrpProgressTargets() {
    return reportSynthesisCrpProgressTargets;
  }


  public SrfSloIndicator getSrfSloIndicator() {
    return srfSloIndicator;
  }


  public SrfTargetUnit getSrfTargetUnit() {
    return srfTargetUnit;
  }


  public BigDecimal getValue() {
    return value;
  }


  public int getYear() {
    return year;
  }


  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    return result;
  }


  @Override
  public boolean isActive() {
    return active;
  }


  public void setActive(boolean active) {
    this.active = active;
  }

  public void setActiveSince(Date activeSince) {
    this.activeSince = activeSince;
  }

  public void setCreatedBy(User createdBy) {
    this.createdBy = createdBy;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setModificationJustification(String modificationJustification) {
    this.modificationJustification = modificationJustification;
  }


  public void setModifiedBy(User modifiedBy) {
    this.modifiedBy = modifiedBy;
  }

  public void setNarrative(String narrative) {
    this.narrative = narrative;
  }

  public void
    setReportSynthesisCrpProgressTargets(Set<ReportSynthesisCrpProgressTarget> reportSynthesisCrpProgressTargets) {
    this.reportSynthesisCrpProgressTargets = reportSynthesisCrpProgressTargets;
  }

  public void setSrfSloIndicator(SrfSloIndicator srfSloIndicator) {
    this.srfSloIndicator = srfSloIndicator;
  }

  public void setSrfTargetUnit(SrfTargetUnit srfTargetUnit) {
    this.srfTargetUnit = srfTargetUnit;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }


  public void setYear(int year) {
    this.year = year;
  }


}

