/*****************************************************************
 * This file is part of CCAFS Planning and Reporting Platform.
 * CCAFS P&R is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * at your option) any later version.
 * CCAFS P&R is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with CCAFS P&R. If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************/
package org.cgiar.ccafs.marlo.data.model;
// Generated May 26, 2016 9:42:28 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * SrfTargetUnit generated by hbm2java
 */
public class SrfTargetUnit implements java.io.Serializable {


  /**
   * 
   */
  private static final long serialVersionUID = -5929916550523608124L;
  private Long id;
  private String name;
  private String acronym;
  private Set<CrpMilestone> crpMilestones = new HashSet<CrpMilestone>(0);
  private Set<SrfSloIndicatorTarget> srfSloIndicatorTargets = new HashSet<SrfSloIndicatorTarget>(0);
  private Set<CrpProgramOutcome> crpProgramOutcomes = new HashSet<CrpProgramOutcome>(0);
  private boolean active;

  public SrfTargetUnit() {
  }

  public SrfTargetUnit(String name, String acronym) {
    this.name = name;
    this.acronym = acronym;
  }

  public SrfTargetUnit(String name, String acronym, Set<CrpMilestone> crpMilestones,
    Set<SrfSloIndicatorTarget> srfSloIndicatorTargets, Set<CrpProgramOutcome> crpProgramOutcomes) {
    this.name = name;
    this.acronym = acronym;
    this.crpMilestones = crpMilestones;
    this.srfSloIndicatorTargets = srfSloIndicatorTargets;
    this.crpProgramOutcomes = crpProgramOutcomes;
  }


  public String getAcronym() {
    return this.acronym;
  }

  public Set<CrpMilestone> getCrpMilestones() {
    return this.crpMilestones;
  }

  public Set<CrpProgramOutcome> getCrpProgramOutcomes() {
    return this.crpProgramOutcomes;
  }

  public Long getId() {
    return this.id;
  }

  public String getName() {
    return this.name;
  }

  public Set<SrfSloIndicatorTarget> getSrfSloIndicatorTargets() {
    return this.srfSloIndicatorTargets;
  }

  public boolean isActive() {
    return active;
  }

  public void setAcronym(String acronym) {
    this.acronym = acronym;
  }

  public void setActive(boolean active) {
    this.active = active;
  }

  public void setCrpMilestones(Set<CrpMilestone> crpMilestones) {
    this.crpMilestones = crpMilestones;
  }

  public void setCrpProgramOutcomes(Set<CrpProgramOutcome> crpProgramOutcomes) {
    this.crpProgramOutcomes = crpProgramOutcomes;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setSrfSloIndicatorTargets(Set<SrfSloIndicatorTarget> srfSloIndicatorTargets) {
    this.srfSloIndicatorTargets = srfSloIndicatorTargets;
  }


}

