SET FOREIGN_KEY_CHECKS=0;
BEGIN;
insert into permissions (id,permission,description,type) values (1,'*','Full privileges on all the platform','0');
insert into permissions (id,permission,description,type) values (2,'project:*','Can update all the planning section contents','0');
insert into permissions (id,permission,description,type) values (3,'project:projectsList:*','Can use all the functions in the projects list section in planning round.','0');
insert into permissions (id,permission,description,type) values (4,'project:projectsList:addCoreProject','Can use the "add core project" button in the projects list section in planning round.','0');
insert into permissions (id,permission,description,type) values (5,'project:projectsList:addBilateralProject','Can use the "add bilateral project" button in the projects list section in planning round.','0');
insert into permissions (id,permission,description,type) values (7,'project:{0}:manage:deleteProject','Can use the "Delete project" button in any section in planning round.','1');
insert into permissions (id,permission,description,type) values (8,'project:{0}:description:*','Can update the whole planning project description information section','1');
insert into permissions (id,permission,description,type) values (9,'project:{0}:description:update','Can update the planning project information section','1');
insert into permissions (id,permission,description,type) values (10,'project:{0}:description:managementLiaison','Can update the management liaison of a project in the planning section','1');
insert into permissions (id,permission,description,type) values (11,'project:{0}:description:startDate','Can update the start date of a project in the planning section','1');
insert into permissions (id,permission,description,type) values (12,'project:{0}:description:endDate','Can update the end date of a project in the planning section','1');
insert into permissions (id,permission,description,type) values (13,'project:{0}:description:workplan','Can update the project status in reporting section','1');
insert into permissions (id,permission,description,type) values (14,'project:{0}:description:bilateralContract','Can upload a bilateral contract proposal for a project in the planning section','1');
insert into permissions (id,permission,description,type) values (15,'project:{0}:description:flagships','Can update the flagships linked to a project in the planning section','1');
insert into permissions (id,permission,description,type) values (16,'project:{0}:description:regions','Can update the end date of a project in the planning section','1');
insert into permissions (id,permission,description,type) values (19,'project:{0}:partners:update','Can update some content in project partners section in planning round.','1');
insert into permissions (id,permission,description,type) values (20,'project:{0}:locations:*','Can update everything in project locations in planning round.','1');
insert into permissions (id,permission,description,type) values (21,'project:{0}:outcomes:*','Can update everything in project outcomes in planning round.','1');
insert into permissions (id,permission,description,type) values (22,'project:{0}:otherContributions:*','Can update the other contributions section in the planning round.','1');
insert into permissions (id,permission,description,type) values (23,'project:{0}:outputs:*','Can update the Overview by MOGs (outputs) section in the planning round.','1');
insert into permissions (id,permission,description,type) values (24,'project:{0}:activities:*','Can update the activities section in the planning round.','1');
insert into permissions (id,permission,description,type) values (25,'project:{0}:budget:update','Can update the planning project budget section in planning round','1');
insert into permissions (id,permission,description,type) values (44,'project:{0}:ccafsOutcomes:*','Can update everything in the CCAFS outcomes section in the planning round.','1');
insert into permissions (id,permission,description,type) values (47,'project:{0}:deliverablesList:*','Can update the Deliverables List section in the planning round.','1');
insert into permissions (id,permission,description,type) values (49,'project:{0}:deliverable:*','Can update the Deliverable section in the planning round.','1');
insert into permissions (id,permission,description,type) values (51,'project:{0}:budgetByMog:*','Can update everything in project budget by mog section in planning round.','1');
insert into permissions (id,permission,description,type) values (52,'project:{0}:budget:annualW1w2','Can update the W1/W2 budget in the project budget section in planning round','1');
insert into permissions (id,permission,description,type) values (53,'project:{0}:budget:annualBilateral','Can update the W3/Bilateral budget in the project budget section in planning round','1');
insert into permissions (id,permission,description,type) values (62,'summaries:*','Can update all the summaries section contents','0');
insert into permissions (id,permission,description,type) values (63,'summaries:board:*','Can use all the functions in the summaries board','0');
insert into permissions (id,permission,description,type) values (64,'project:{0}:partners:ppa','Can update the PPA partners in planning round.','1');
insert into permissions (id,permission,description,type) values (67,'project:{0}:partner:leader:update','Can update the planning project partners leader','1');
insert into permissions (id,permission,description,type) values (68,'project:{0}:partner:cordinator:update','Can update the planning project partners cordinator','1');
insert into permissions (id,permission,description,type) values (69,'project:{0}:description:*','Can update all the reporting section in project description.','1');
insert into permissions (id,permission,description,type) values (70,'project:{0}:description:status','Can update all the reporting section in project description','1');
insert into permissions (id,permission,description,type) values (71,'project:{0}:description:summary','Can update only the fields about the project status in reporting section.','1');
insert into permissions (id,permission,description,type) values (72,'project:{0}:description:title','Can update the project title in planning section','1');
insert into permissions (id,permission,description,type) values (73,'project:{0}:description:annualReportDonor','Can upload the report to the donor (bilateral project) in reporting round.','1');
insert into permissions (id,permission,description,type) values (74,'project:{0}:description:bilateralContract','Can update the bilateral contract in reporting round.','1');
insert into permissions (id,permission,description,type) values (75,'project:{0}:description:endDate','Can update the field end date in reporting round.','1');
insert into permissions (id,permission,description,type) values (76,'project:{0}:description:flagships','Can update the flagships selections in reporting round.','1');
insert into permissions (id,permission,description,type) values (77,'project:{0}:description:managementLiaison','Can update the ML in reporting round.','1');
insert into permissions (id,permission,description,type) values (78,'project:{0}:description:regions','Can update the regions selections in reporting round.','1');
insert into permissions (id,permission,description,type) values (79,'project:{0}:description:startDate','Can update the field start date in reporting round.','1');
insert into permissions (id,permission,description,type) values (80,'project:{0}:description:statusDescription','Can update the project status in reporting round.','1');
insert into permissions (id,permission,description,type) values (81,'project:{0}:description:summary','Can update the project summary in reporting round.','1');
insert into permissions (id,permission,description,type) values (82,'project:{0}:description:title','Can update the project title in reporting round','1');
insert into permissions (id,permission,description,type) values (83,'project:{0}:description:update','Can update the project description section in reporting round.','1');
insert into permissions (id,permission,description,type) values (84,'project:{0}:description:workplan','Can upload the workplan (ccafs projects) in reporting round.','1');
insert into permissions (id,permission,description,type) values (85,'project:{0}:partners:*','Can update everything on the partners section in planning round.','1');
insert into permissions (id,permission,description,type) values (86,'project:{0}:partners:coordinator','Can update the project coordinator (PC) in planning round.','1');
insert into permissions (id,permission,description,type) values (87,'project:{0}:partners:leader','Can update the project leader (PL) in planning round.','1');
insert into permissions (id,permission,description,type) values (88,'project:{0}:partners:*','Can update everything on the partners section in reporting round.','1');
insert into permissions (id,permission,description,type) values (89,'project:{0}:partners:coordinator','Can update the project coordinator (PC) in reporting round.','1');
insert into permissions (id,permission,description,type) values (90,'project:{0}:partners:leader','Can update the project leader (PL) in reporting round.','1');
insert into permissions (id,permission,description,type) values (91,'project:{0}:partners:ppa','Can udpate the PPA partners in reporting round.','1');
insert into permissions (id,permission,description,type) values (92,'project:{0}:partners:update','Can update some content in project partners section in reporting round.','1');
insert into permissions (id,permission,description,type) values (93,'project:{0}:locations:*','Can update everything in project locations in reporting round.','1');
insert into permissions (id,permission,description,type) values (94,'project:{0}:outcomes:*','Can update everything in project outcomes in reporting round.','1');
insert into permissions (id,permission,description,type) values (95,'project:{0}:manage:submitProject','Can use the "Submit project" button in any section in planning round.','1');
insert into permissions (id,permission,description,type) values (96,'project:projectsList:*','Can use all the functions in the projects list section in reporting round.','0');
insert into permissions (id,permission,description,type) values (97,'project:projectsList:addBilateralProject','Can use the "add bilateral project" button in the projects list section in reporting round.','0');
insert into permissions (id,permission,description,type) values (98,'project:projectsList:addCoreProject','Can use the "add core project" button in the projects list section in reporting round.','0');
insert into permissions (id,permission,description,type) values (99,'project:{0}:manage:deleteProject','Can use the "Delete project" button in any section in reporting round.','1');
insert into permissions (id,permission,description,type) values (100,'project:{0}:manage:submitProject','Can use the "Submit project" button in any section in reporting round.','1');
insert into permissions (id,permission,description,type) values (101,'project:{0}:ccafsOutcomes:*','Can update everything in the CCAFS outcomes section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (102,'project:{0}:otherContributions:*','Can update the other contributions section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (103,'project:{0}:caseStudies:*','Can update the Outcomes Case Studies section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (104,'project:{0}:outputs:*','Can update the Overview by MOGs (outputs) section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (105,'project:{0}:deliverable:*','Can update the Deliverable section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (106,'project:{0}:deliverablesList:*','Can update the Deliverables List section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (107,'project:{0}:nextUsers:*','Can update the Next users section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (108,'project:{0}:highlight:*','Can update the Project Highlight section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (109,'project:{0}:highlights:*','Can update the Project Highlights List section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (110,'project:{0}:activities:*','Can update the Project Activities section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (111,'project:{0}:leverages:*','Can update the Leverages section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (112,'project:{0}:caseStudies:*','Can update the Outcomes Case Studies section in the planning round.','1');
insert into permissions (id,permission,description,type) values (113,'project:{0}:outcomes:update','Can update project outcomes in planning round','1');
insert into permissions (id,permission,description,type) values (114,'project:{0}:outcomes:statement','Can update project statement in project outcomes in planning round.','1');
insert into permissions (id,permission,description,type) values (115,'project:{0}:outcomes:annualProgress','Can update annual progress in project outcomes in planning round.','1');
insert into permissions (id,permission,description,type) values (116,'project:{0}:outcomes:communicationEngagement','Can update communication engagement in project outcomes in planning round.','1');
insert into permissions (id,permission,description,type) values (117,'project:{0}:outcomes:uploadSummary','Can upload a summary file in project outcomes in planning round.','1');
insert into permissions (id,permission,description,type) values (118,'project:{0}:outcomes:update','Can update project outcomes in reporting round','1');
insert into permissions (id,permission,description,type) values (119,'project:{0}:outcomes:statement','Can update project statement in project outcomes in reporting round.','1');
insert into permissions (id,permission,description,type) values (120,'project:{0}:outcomes:annualProgress','Can update annual progress in project outcomes in reporting round.','1');
insert into permissions (id,permission,description,type) values (121,'project:{0}:outcomes:communicationEngagement','Can update communication engagement in project outcomes in reporting round.','1');
insert into permissions (id,permission,description,type) values (122,'project:{0}:outcomes:uploadSummary','Can upload a summary file in project outcomes in reporting round.','1');
insert into permissions (id,permission,description,type) values (123,'project:{0}:ccafsOutcomes:update','Can make changes in the ccafs outcomes section in planning round.','1');
insert into permissions (id,permission,description,type) values (124,'project:{0}:ccafsOutcomes:target','Can update the target value in ccafs outcomes section in plannnig round.','1');
insert into permissions (id,permission,description,type) values (125,'project:{0}:ccafsOutcomes:achieved','Can update the target achieved in ccafs outcomes section in planning round.','1');
insert into permissions (id,permission,description,type) values (126,'project:{0}:ccafsOutcomes:description','Can update the expected annual contribution in ccafs outcomes section in planning round.','1');
insert into permissions (id,permission,description,type) values (127,'project:{0}:ccafsOutcomes:narrativeTargets','Can update the annual contribution achieved in ccafs outcomes section in planning round.','1');
insert into permissions (id,permission,description,type) values (128,'project:{0}:ccafsOutcomes:gender','Can update the expected gender contribution in ccafs outcomes section in planning round.','1');
insert into permissions (id,permission,description,type) values (129,'project:{0}:ccafsOutcomes:narrativeGender','Can update the gender contribution achieved in ccafs outcomes section in planning round.','1');
insert into permissions (id,permission,description,type) values (130,'project:{0}:ccafsOutcomes:update','Can make changes in the ccafs outcomes section in reporting round.','1');
insert into permissions (id,permission,description,type) values (131,'project:{0}:ccafsOutcomes:target','Can update the target value in ccafs outcomes section in reporting round.','1');
insert into permissions (id,permission,description,type) values (132,'project:{0}:ccafsOutcomes:achieved','Can update the target achieved in ccafs outcomes section in reporting round.','1');
insert into permissions (id,permission,description,type) values (133,'project:{0}:ccafsOutcomes:description','Can update the expected annual contribution in ccafs outcomes section in reporting round.','1');
insert into permissions (id,permission,description,type) values (134,'project:{0}:ccafsOutcomes:narrativeTargets','Can update the annual contribution achieved in ccafs outcomes section in reporting round.','1');
insert into permissions (id,permission,description,type) values (135,'project:{0}:ccafsOutcomes:gender','Can update the expected gender contribution in ccafs outcomes section in reporting round.','1');
insert into permissions (id,permission,description,type) values (136,'project:{0}:ccafsOutcomes:narrativeGender','Can update the gender contribution achieved in ccafs outcomes section in reporting round.','1');
insert into permissions (id,permission,description,type) values (137,'project:{0}:otherContributions:update','Can make changes in the other contributions section in planning round.','1');
insert into permissions (id,permission,description,type) values (138,'project:{0}:otherContributions:contribution','Can update how is contributing in other contributuions section in planning round.','1');
insert into permissions (id,permission,description,type) values (139,'project:{0}:otherContributions:otherContributionIndicator','Can update the indicator in other contributions section un planning round.','1');
insert into permissions (id,permission,description,type) values (140,'project:{0}:otherContributions:otherContributionDescription','Can update the description of the contribution to the indicator in other contributions section in planning round.','1');
insert into permissions (id,permission,description,type) values (141,'project:{0}:otherContributions:otherContributionTarget','Can update the target in other contributions section in planning round.','1');
insert into permissions (id,permission,description,type) values (142,'project:{0}:otherContributions:additionalContribution','Can update the contribuition to another center activity in other contributions section in planning round.','1');
insert into permissions (id,permission,description,type) values (143,'project:{0}:otherContributions:natureCollaboration','Can update the nature collaboration in other contributions section in planning round.','1');
insert into permissions (id,permission,description,type) values (144,'project:{0}:otherContributions:explainAchieved','Can update the ahieved outcome in other contributions section in planning round.','1');
insert into permissions (id,permission,description,type) values (145,'project:{0}:otherContributions:addCRPContribution','Can add new CRP in other contributions section in planning round.','1');
insert into permissions (id,permission,description,type) values (146,'project:{0}:otherContributions:update','Can make changes in the other contributions section in reporting round.','1');
insert into permissions (id,permission,description,type) values (147,'project:{0}:otherContributions:contribution','Can update how is contributing in other contributuions section in reporting round.','1');
insert into permissions (id,permission,description,type) values (148,'project:{0}:otherContributions:otherContributionIndicator','Can update the indicator in other contributions section un reporting round.','1');
insert into permissions (id,permission,description,type) values (149,'project:{0}:otherContributions:otherContributionDescription','Can update the description of the contribution to the indicator in other contributions section in reporting round.','1');
insert into permissions (id,permission,description,type) values (150,'project:{0}:otherContributions:otherContributionTarget','Can update the target in other contributions section in reporting round.','1');
insert into permissions (id,permission,description,type) values (151,'project:{0}:otherContributions:additionalContribution','Can update the contribuition to another center activity in other contributions section in reporting round.','1');
insert into permissions (id,permission,description,type) values (152,'project:{0}:otherContributions:natureCollaboration','Can update the nature collaboration in other contributions section in reporting round.','1');
insert into permissions (id,permission,description,type) values (153,'project:{0}:otherContributions:explainAchieved','Can update the ahieved outcome in other contributions section in reporting round.','1');
insert into permissions (id,permission,description,type) values (154,'project:{0}:otherContributions:addCRPContribution','Can add new CRP in other contributions section in reporting round.','1');
insert into permissions (id,permission,description,type) values (155,'project:{0}:outputs:update','Can make changes in the overview by mogs section in the planning round.','1');
insert into permissions (id,permission,description,type) values (156,'project:{0}:outputs:expectedAnnualContribution','Can update the expected annual contribution in overview by mogs section in planning round.','1');
insert into permissions (id,permission,description,type) values (157,'project:{0}:outputs:socialInclusionDimmension','Can update the expected gender contribution in overview by mogs section in the planning round.','1');
insert into permissions (id,permission,description,type) values (158,'project:{0}:outputs:briefSummary','Can update the actual contribution in overview by mogs section in the planning round.','1');
insert into permissions (id,permission,description,type) values (159,'project:{0}:outputs:summaryGender','Can update the actual gender contribution in the overview by mogs section in the planning round.','1');
insert into permissions (id,permission,description,type) values (160,'project:{0}:outputs:update','Can make changes in the overview by mogs section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (161,'project:{0}:outputs:expectedAnnualContribution','Can update the expected annual contribution in overview by mogs section in reporting round.','1');
insert into permissions (id,permission,description,type) values (162,'project:{0}:outputs:socialInclusionDimmension','Can update the expected gender contribution in overview by mogs section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (163,'project:{0}:outputs:briefSummary','Can update the actual contribution in overview by mogs section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (164,'project:{0}:outputs:summaryGender','Can update the actual gender contribution in the overview by mogs section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (165,'project:{0}:deliverablesList:update','Can make changes in the deliverables list section in planning round.','1');
insert into permissions (id,permission,description,type) values (166,'project:{0}:deliverablesList:addDeliverable','Can add new deliverables in the deliverables list section in planning round.','1');
insert into permissions (id,permission,description,type) values (167,'project:{0}:deliverablesList:removeOldDeliverables','Can remove deliverables in the deliverables list section in planning round.','1');
insert into permissions (id,permission,description,type) values (168,'project:{0}:deliverablesList:update','Can make changes in the deliverables list section in reporting round.','1');
insert into permissions (id,permission,description,type) values (169,'project:{0}:deliverablesList:addDeliverable','Can add new deliverables in the deliverables list section in reporting round.','1');
insert into permissions (id,permission,description,type) values (170,'project:{0}:deliverablesList:removeOldDeliverables','Can remove deliverables in the deliverables list section in reporting round.','1');
insert into permissions (id,permission,description,type) values (171,'project:{0}:deliverable:update','Can make changes in a particular deliverable in the planning round.','1');
insert into permissions (id,permission,description,type) values (172,'project:{0}:deliverable:main','Can make changes in the main fields (title, start date) for a particular deliverable in planning round.','1');
insert into permissions (id,permission,description,type) values (173,'project:{0}:deliverable:other','Can make changes in the rest of the fields that are not part of "main" permission in planning round.','1');
insert into permissions (id,permission,description,type) values (174,'project:{0}:deliverable:update','Can make changes in a particular deliverable in the reporting round.','1');
insert into permissions (id,permission,description,type) values (175,'project:{0}:deliverable:main','Can make changes in the main fields (title, start date) for a particular deliverable in reporting round.','1');
insert into permissions (id,permission,description,type) values (176,'project:{0}:deliverable:other','Can make changes in the rest of the fields that are not part of "main" permission in reporting round.','1');
insert into permissions (id,permission,description,type) values (177,'project:{0}:nextUsers:*','Can update the Next users section in the planning round.','1');
insert into permissions (id,permission,description,type) values (178,'project:{0}:highlights:*','Can update the Project Highlights List section in the planning round.','1');
insert into permissions (id,permission,description,type) values (179,'project:{0}:highlights:update','Can make changes in the Project Highlights List section in the planning round.','1');
insert into permissions (id,permission,description,type) values (180,'project:{0}:highlights:addHighlight','Can add new Project Highlights in the planning round.','1');
insert into permissions (id,permission,description,type) values (181,'project:{0}:highlights:removeHighlight','Can remove Project Highlights in the planning round.','1');
insert into permissions (id,permission,description,type) values (182,'project:{0}:highlights:update','Can make changes in the Project Highlights List section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (183,'project:{0}:highlights:addHighlight','Can add new Project Highlights in the reporting round.','1');
insert into permissions (id,permission,description,type) values (184,'project:{0}:highlights:removeHighlight','Can remove Project Highlights in the reporting round.','1');
insert into permissions (id,permission,description,type) values (185,'project:{0}:highlight:*','Can update the Project Highlight section in the planning round.','1');
insert into permissions (id,permission,description,type) values (186,'project:{0}:activities:update','Can make changes in the activities section in the planning round.','1');
insert into permissions (id,permission,description,type) values (187,'project:{0}:activities:title','Can update the title of the activities section in the planning round.','1');
insert into permissions (id,permission,description,type) values (188,'project:{0}:activities:description','Can update the description of the activities section in the planning round.','1');
insert into permissions (id,permission,description,type) values (189,'project:{0}:activities:startDate','Can update the start date of the activities section in the planning round.','1');
insert into permissions (id,permission,description,type) values (190,'project:{0}:activities:endDate','Can update the end date of the activities section in the planning round.','1');
insert into permissions (id,permission,description,type) values (191,'project:{0}:activities:activityStatus','Can update the status of the activities section in the planning round.','1');
insert into permissions (id,permission,description,type) values (192,'project:{0}:activities:activityProgress','Can update the status justification of the activities section in the planning round.','1');
insert into permissions (id,permission,description,type) values (193,'project:{0}:activities:leader','Can update the leader of the activities section in the planning round.','1');
insert into permissions (id,permission,description,type) values (194,'project:{0}:activities:addActivity','Can add new activities in the planning round.','1');
insert into permissions (id,permission,description,type) values (195,'project:{0}:activities:update','Can make changes in the activities section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (196,'project:{0}:activities:title','Can update the title of the  activities section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (197,'project:{0}:activities:description','Can update the description of the activities section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (198,'project:{0}:activities:startDate','Can update the start date of the activities section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (199,'project:{0}:activities:endDate','Can update the end date of the activities section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (200,'project:{0}:activities:activityStatus','Can update the status of the activities section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (201,'project:{0}:activities:activityProgress','Can update the status justification of the activities section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (202,'project:{0}:activities:leader','Can update the leader of the activities section in the reporting round.','1');
insert into permissions (id,permission,description,type) values (203,'project:{0}:activities:addActivity','Can add new activities in the reporting round.','1');
insert into permissions (id,permission,description,type) values (204,'project:{0}:budget:*','Can update everything on project budgets in planning round','1');
insert into permissions (id,permission,description,type) values (205,'project:{0}:budget:*','Can update everything on project budgets in reporting round','1');
insert into permissions (id,permission,description,type) values (206,'project:{0}:budget:update','Can update the planning project budget section in reporting round','1');
insert into permissions (id,permission,description,type) values (207,'project:{0}:budget:annualBilateral','Can update the W3/Bilateral budget in the project budget section in reporting round','1');
insert into permissions (id,permission,description,type) values (208,'project:{0}:budget:annualW1w2:update','Can update the W1/W2 budget in the project budget section in reporting round','1');
insert into permissions (id,permission,description,type) values (209,'project:{0}:budgetByMog:*','Can update everything in project budget by mog section in reporting round.','1');
insert into permissions (id,permission,description,type) values (210,'project:{0}:leverages:*','Can update the Leverages section in the planning round.','1');
insert into permissions (id,permission,description,type) values (211,'project:synthesis:crpIndicators:*','Can update everything on CRP Indicatoris in reporting round.','0');
insert into permissions (id,permission,description,type) values (212,'project:synthesis:outcomeSynthesis:*','Can edit everything on Outcome Synthesis in reporting round.','0');
insert into permissions (id,permission,description,type) values (213,'project:synthesis:outcomeSynthesis:update','Can edit on Outcome Synthesis in reporting round.','0');
insert into permissions (id,permission,description,type) values (214,'project:synthesis:outcomeSynthesis:rplSynthesis','Can edit on Regional Synthesis in reporting round.','0');
insert into permissions (id,permission,description,type) values (215,'project:synthesis:outcomeSynthesis:fplSynthesis','Can edit on Flagship Synthesis in reporting round.','0');
insert into permissions (id,permission,description,type) values (216,'project:synthesis:synthesisByMog:*','Can edit everything on Synthesis by MOG in reporting round.','0');
insert into permissions (id,permission,description,type) values (217,'project:synthesis:synthesisByMog:update','Can edit on Synthesis by MOG in reporting round.','0');
insert into permissions (id,permission,description,type) values (218,'project:{0}:evaluation:*','Can update project Evaluation','1');
insert into permissions (id,permission,description,type) values (219,'project:projectsEvaluation:*','Can update Evaluation projects section','0');
insert into permissions (id,permission,description,type) values (220,'project:{0}:evaluation:update','Can update project Evaluation','1');
insert into permissions (id,permission,description,type) values (221,'project:{0}:evaluation:accessPL','Can view Project Leaders evaluations','1');
insert into permissions (id,permission,description,type) values (222,'project:{0}:evaluation:accessRPL','Can view Regional Program evaluations','1');
insert into permissions (id,permission,description,type) values (223,'project:{0}:evaluation:accessFPL','Can view Flagship Program evaluations','1');
insert into permissions (id,permission,description,type) values (224,'project:{0}:evaluation:accessEE','Can view External evaluator evaluations','1');
insert into permissions (id,permission,description,type) values (225,'project:{0}:evaluation:accessCU','Can view Coordination Unit evaluations','1');
insert into permissions (id,permission,description,type) values (226,'project:{0}:evaluation:accessPD','Can view Program Director evaluations','1');
COMMIT;