[#ftl]
[#-- Editable parameter --]
[#if logged]
  [@s.param name='edit' value="true" /]
[/#if]
[#-- Phase ID parameter --]
[#if actualPhase??]
  [@s.param name='phaseID' value=actualPhase.id /]
[/#if]