INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (1,'ResearchProgram', 'climate');
INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (2,'ResearchProgram', 'ecosystem');
INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (3,'ResearchProgram', 'markets');
INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (4,'ResearchLeader', 'Program Coordination');
INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (5,'ResearchLeader', 'Research Area Leader');
INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (6,'ResearchLeader', 'Research Program Leader');
INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (7,'ResearchObjective', 'Strategic Objective');
INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (8,'ResearchObjective', 'Research Area Objective');
INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (9,'ResearchPartner', 'Internal Partner');
INSERT INTO `all_types` (`id`,`class_name`, `type_name`) VALUES (10,'ResearchPartner', 'External Partner');